### ISSUE TITLE
Vec3b obj = img.at<Vec3b>(i, j);replacement in javacpp?

### ISSUE THREAD

**Issue by xwaeaewcrhomesysplug** [bytedeco/javacpp-presets#1004]
I wanted to access and view a pixel values.Say RGB,should have array or something.
The opencv java port does in fact has a get function.The javacpp,open_cv.ones does not.
Is it mistake or function moved to some other place?

In short,
org.bytedeco.opencv.opencv_core.Mat inimg){
		int apxch=inimg.get(0,0).length;...
		compile error because no such thing.
		
but
(org.opencv.core.Mat inimg{
		int apxch=inimg.get(0,0).length;
		compile ok.
		
so what is the alternative for,(get/at)

**Comment by saudet** [comment]
We can use an Indexer for that: http://bytedeco.org/news/2014/12/23/third-release/
