### ISSUE TITLE
about Mat::get(row,col)

### ISSUE THREAD

**Issue by 4714407** [bytedeco/javacpp-presets#1010]
public double[] get(int row, int col) on org.opencv.core.Mat
What is the method on the corresponding class org.bytedeco.opencv.opencv_core.Mat

**Comment by saudet** [comment]
We can use an Indexer for that: http://bytedeco.org/news/2014/12/23/third-release/

**Comment by 4714407** [comment]
mat.createIndexer().getDouble(0,0)
thank you very much
