### ISSUE TITLE
mkl-platform-redist dylib's UnsatisfiedLinkError macOS

### ISSUE THREAD

**Issue by burbma** [bytedeco/javacpp-presets#1013]
I've included `mkl-platform-redist 2020.3-1.5.4` via maven and then attempt to load the `org.bytedeco.mkl.global.mkl_rt` class. I've set `org.bytedeco.javacpp.logger.debug`to `true` and get the following:

```
Debug: Loading class org.bytedeco.javacpp.presets.javacpp
Debug: Loading class org.bytedeco.javacpp.Loader
Debug: Loading /Users/burbma/.javacpp/cache/javacpp-1.5.4-macosx-x86_64.jar/org/bytedeco/javacpp/macosx-x86_64/libjnijavacpp.dylib
Debug: Loading class org.bytedeco.javacpp.presets.javacpp
Debug: Loading class org.bytedeco.javacpp.Pointer
Debug: Loading class org.bytedeco.javacpp.presets.javacpp
Debug: Loading class org.bytedeco.mkl.global.mkl_rt
Debug: Loading /Users/burbma/.javacpp/cache/mkl-2020.3-1.5.4-macosx-x86_64-redist.jar/org/bytedeco/mkl/macosx-x86_64/libmkl_core.dylib
Debug: Loading /Users/burbma/.javacpp/cache/mkl-2020.3-1.5.4-macosx-x86_64-redist.jar/org/bytedeco/mkl/macosx-x86_64/libiomp5.dylib
Debug: Loading library libiomp5md
Debug: Failed to load for libiomp5md: java.lang.UnsatisfiedLinkError: no libiomp5md in java.library.path: [/Users/burbma/Library/Java/Extensions, /Library/Jav
a/Extensions, /Network/Library/Java/Extensions, /System/Library/Java/Extensions, /usr/lib/java, .]
...more of the same for other dylib's
```

I'm wondering if I've missed some step? I don't have mkl installed on my system as I'm under the impression I shouldn't need it with this `mkl-platform-redist`. I'm confused why it can't find `libiomp5md` if it's already located it for loading in `~/.javacpp/cache/.../libiomp5.dylib`.

```
macOS 10.15.7

openjdk version "11.0.9.1" 2020-11-04
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.9.1+1)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.9.1+1, mixed mode)
```

**Comment by saudet** [comment]
The library is named like that on Windows, so that's why it tries to find it... Anyway, you can ignore that "error". It won't prevent it from working correctly.

**Comment by burbma** [comment]
Ah ok thanks. I'm trying to track down another issue and so I had debug logs on and thought this might be the root cause. I'll dig more and you may hear back from me again with another question, feel free to redirect me if there is a more appropriate venue. Thank you!

**Comment by burbma** [comment]
I'm fairly confident at this point that the issue is not with bytedeco.
