### ISSUE TITLE
[cpython]What is the best way to use pip?

### ISSUE THREAD

**Issue by yukoba** [bytedeco/javacpp-presets#1015]
As far as I tried, I can install Python packages by this.

```Java
Py_Main(5, new PointerPointer<>(
        new CharPointer(""),
        new CharPointer("-m"),
        new CharPointer("pip"),
        new CharPointer("install"),
        new CharPointer("PackageNameToInstall")
));
```
and
```Java
Py_AddPath("Lib/site-packages");
```

But this requires external Python. Pip calls external Python.
What is the best way to use pip from javacpp-presets/cpython?

**Comment by saudet** [comment]
This way works fine:
```java
        // Extract to JavaCPP's cache CPython and obtain the path to the executable file
        String python = Loader.load(org.bytedeco.cpython.python.class);

        // Install in JavaCPP's cache GluonNLP and MXNet to download and import BERT model
        new ProcessBuilder(python, "-m", "pip", "install", "gluonnlp", "mxnet", "pytest").inheritIO().start().waitFor();
```
https://github.com/bytedeco/javacpp-presets/blob/master/tvm/samples/DeployBERT.java

**Comment by yukoba** [comment]
Thank you! It worked. 
Could you please write that here? https://github.com/bytedeco/javacpp-presets/blob/master/cpython/README.md

**Comment by saudet** [comment]
What about creating a new sample for that?
It would be great if you could contribute one to put here:
https://github.com/bytedeco/javacpp-presets/tree/master/cpython/samples

**Comment by yukoba** [comment]
> What about creating a new sample for that?

I wrote a wrapper of javacpp-presets/cpython. Do you want to include it? I wrote it by Scala, but it is easy to port to Java. You can use it like this.

```Scala
    Pip.install("pandas")
```

```Scala
    Python.exec(
      """import pandas as pd
        |
        |df = pd.DataFrame({
        |  "a": [1, 2],
        |  "b": [3, 4],
        |})
        |s = df.to_string()
        |""".stripMargin)
    println(Python.get[String]("s"))
```

```Scala
    Python.set("f", (a: Long, b: Long, c: Double) => a + b + c)
    Python.exec("v = f(1, 2, 3.0)")
    assert(Python.get[Double]("v") == 6.0)
```

**Comment by saudet** [comment]
Yes, that would be great as well. We keep adding helpers like that to the `helper` package. Global functions can go here:
https://github.com/bytedeco/javacpp-presets/blob/master/cpython/src/main/java/org/bytedeco/cpython/helper/python.java

**Comment by saudet** [comment]
But your classes seem more high-level, so we should probably create another package for that... If you'd like to keep writing those in Scala, we could simply create a new repository for that on https://github.com/bytedeco/ and you can manage that project however you like. How does that sound?

**Comment by saudet** [comment]
> > create a new repository for that on https://github.com/bytedeco/
> 
> Please create a new one.

I've invited you to become a member of the organization. Once you accept, you will be able to create new repositories as well as move existing ones to this organization: https://docs.github.com/en/github/administering-a-repository/transferring-a-repository

**Comment by saudet** [comment]
Looks good! We could have a shorter name for this though.
I'm thinking maybe something like "JavaEPy"... ?
https://github.com/bytedeco/javacpp-embedded-python

**Comment by yukoba** [comment]
I think I have implemented all that I need. I confirmed I could use it with CARLA Simulator and OpenAI Gym Python API.

> We could have a shorter name for this though. I'm thinking maybe something like "JavaEPy"... ?

Can I add one more character? JavaWzPy. This is an abbreviation of "Let's use Java with Python libraries."

**Comment by saudet** [comment]
I'm not sure what "Wz" stands for, most English speakers are probably not going to know either. What about something more simple like "JavaCPy" as in "Java -> CPython" or "Java see Python". :)  The name of the module and repository should be all lowercase "javacpy", but that looks alright as well.

**Comment by yukoba** [comment]
I use for "with" = "wz". I think nobody in the world is using this.

I am Japanese, and I live in Tokyo. For me, it is difficult to distinguish the pronunciation between "with" and "whizz". Are "th" and "z" quite different for you?

There are so many projects that use "Java" and "Py" in their name, I wanted to add something uncommon, but maybe it is Japanese English.

**Comment by saudet** [comment]
English speakers would probably associate that with "wiz" (same as "wizard") more than anything else, which isn't bad actually, like "Java Wiz Python", the Python for Java Wizards or something. Sounds OK :)

**Comment by yukoba** [comment]
How about jwpy = Java With Python? It is shorter. There is a project called jep = Java Embedded Python, so I cannot insert Embedded here.

**Comment by saudet** [comment]
What about "x" instead? It means something like "+" in Japanese, and it's also used that way by programmers where, for example, CXX stands for C++. I find that acronyms like JEP, JXP, or JxPy are a bit too short, JavaXPy maybe?

**Comment by supergrecko** [comment]
I would suggest py4j but that already exists. It's an extension library so
maybe we could have a naming scheme like javax/kotlinx does?
javacppx-python maybe?
