### ISSUE TITLE
Tesseract/Leptonica is utilizing the AutoCloseable on Pointer sufficient to deallocate resources properly?

### ISSUE THREAD

**Issue by Geckulon** [bytedeco/javacpp-presets#1018]
I see that I can use TessBaseAPI and PIX in a try-with-resources approach since the Pointer implements AutoCloseable, but will that be sufficient compared to TessBaseAPI's _End_ or PIX's _pixDestroy_ native methods?

**Comment by saudet** [comment]
The close() method will only do something when a Deallocator gets registered like the ones here in the helper packages:
https://github.com/bytedeco/javacpp-presets/blob/master/leptonica/src/main/java/org/bytedeco/leptonica/AbstractPIX.java
In the case of Tesseract, TessBaseAPI is a C++ class, so a Deallocator gets registered automatically, and close() will call the destructor.
