### ISSUE TITLE
Linux ARM64 this jar does not work , can you help how to support .

### ISSUE THREAD

**Issue by santosa-malika** [bytedeco/javacpp-presets#1019]
when we run Linux ARM64 , its gives error ND4J missing dependency , so plz help on this issue 

![image](https://user-images.githubusercontent.com/70142978/111585589-8b581c00-87e5-11eb-86a3-3818b4f8fda2.png)

**Comment by saudet** [comment]
You'll need to use the snapshots to get support for linux-arm64:
https://deeplearning4j.konduit.ai/config/config-snapshots
