### ISSUE TITLE
can't import org.bytedeco.javacpp.opencv_core and opencv_face

### ISSUE THREAD

**Issue by masa126** [bytedeco/javacpp-presets#1025]
Hi,
In this January, I didn't have any problems to import org.bytedeco.javacpp.opencv_core and opencv_face.
Now I can't import opencv_core and opencv_face.
These symbols are unresolved.
I specify the dependency in my build.gradle as follows;
    implementation 'org.bytedeco:javacv:1.5.5'
    implementation group: 'org.bytedeco.javacpp-presets', name: 'opencv', version: '4.0.1-1.4.4', classifier: 'android-arm'
Will you tell me the way to resolve this issue?

Thanks,

**Comment by saudet** [comment]
You'll need to use the same version for all the artifacts of OpenCV.
In the case of JavaCV 1.5.5, that would be 4.5.1-1.5.5:
https://github.com/bytedeco/javacv/blob/1.5.5/pom.xml#L78

**Comment by masa126** [comment]
@saudet,
Thank you for your quick response.
I changed the depenecy as you sugested; 
    implementation 'org.bytedeco:javacv:1.5.5'
    implementation 'org.bytedeco:javacpp:1.5.5'
    implementation 'org.bytedeco:javacpp-presets:1.5.5'
    implementation 'org.bytedeco:javacpp-platform:1.5.5'
    implementation group: 'org.bytedeco.javacpp', name: 'opencv', version: '4.5.1-1.5.5', classifier: 'android-arm'

But Android Studio 4.1 shows the error
 "Could not resolve org.bytedeco.javacpp:opencv:4.5.1-1.5.5"
So, "import org.bytedeco.javacpp.opencv_core;" and "import org.bytedeco.javacpp.opencv_face;" are not resolved.

**Comment by supergrecko** [comment]
Those artifacts have been moved under `org.bytedeco` groupId, so the dependency is `org.bytedeco:opencv:4.5.1-1.5.5`

**Comment by masa126** [comment]
Sorry to disturb you again.
Changed to 
    implementation group: 'org.bytedeco', name: 'opencv', version: '4.5.1-1.5.5', classifier: 'android-arm'
But Studio shows an error 
"with OS independent path 'META-INF/native-image/android-arm64/jnijavacpp/jni-config.json'."
Still these two statments are marked in red.
 import org.bytedeco.opencv_core;
 import org.bytedeco.opencv_face;

**Comment by masa126** [comment]
"opencv_face and opencv_core" are not  in the package "org.bytedeco"

**Comment by masa126** [comment]
Please let me know the packacge in which  "opencv_face.FaceRecognizer" is stored.

**Comment by saudet** [comment]
> implementation group: 'org.bytedeco', name: 'opencv', version: '4.5.1-1.5.5', classifier: 'android-arm'
> But Studio shows an error
> "with OS independent path 'META-INF/native-image/android-arm64/jnijavacpp/jni-config.json'."

We can exclude those files from the build. They are not needed by Android.

> Please let me know the packacge in which "opencv_face.FaceRecognizer" is stored.

It is there: http://bytedeco.org/javacpp-presets/opencv/apidocs/org/bytedeco/opencv/opencv_face/FaceRecognizer.html

**Comment by masa126** [comment]
@Samuel,
Thank you for your help.
I uploaded my repo
 https://github.com/masa126/face-recognition-for-android-haar
and its original 
 https://github.com/chamecall/face-recognition-for-android
In my repo, "import org.bytedeco.opencv.opencv_face;" is not resolved.
Studio doesn't show FaceRecognizer class in the package of org.bytedeco.opencv.opencv_face.
![AndroidStudio_MainActivity](https://user-images.githubusercontent.com/50834087/112440968-448e9700-8d8e-11eb-8f4f-c0339f0e6627.png)

**Comment by saudet** [comment]
To import a full package, you'll need to append `.*`.
Please take the time to go through the Java tutorial:
https://docs.oracle.com/javase/tutorial/java/package/usepkgs.html

**Comment by masa126** [comment]
@saudet,
Thank you for your kind advices.
Based on your suggestion and the manual of your javacpp package in the below
http://bytedeco.org/javacpp-presets/opencv/apidocs/index.html?org/bytedeco/opencv/opencv_core/package-summary.html
I set the dependency
    implementation group: 'org.bytedeco', name: 'javacpp', version: '1.5.3', classifier: 'android-arm64'
but these error of **opencv_core** and **opencv_face** are not resolved.

Based on the javaccp package descriptions, these two packages might be imported.
When I set "import org.bytedeco.opencv.**global.**opencv_face", the error of opencv_face was resolved, 
but "opencv_face**.FaceRecognizer**" is not resolved.
It is very strange for your javacpp package.

**Comment by saudet** [comment]
We need to provide the fully qualified name like this:
```java
import org.bytedeco.opencv.opencv_face.FaceRecognizer;
```
