### ISSUE TITLE
opencv loader not working in unix

### ISSUE THREAD

**Issue by xwaeaewcrhomesysplug** [bytedeco/javacpp-presets#1034]
as seen in picture it says it fails to load that static lib,
But It actually already exist there.The path is also properly configured.
![Screenshot from 2021-04-16 13-05-13](https://user-images.githubusercontent.com/67897598/115206602-b8c21d80-a135-11eb-9689-9cd75518d1d0.png)

**Comment by xwaeaewcrhomesysplug** [comment]
javacpp-1.5.5-linux-x86_64.jar
15/04/2021  23:10        13,730,521 openblas-0.3.13-1.5.5-linux-x86_64.jar
15/04/2021  23:27           170,560 openblas-0.3.13-1.5.5.jar
16/04/2021  00:22        26,013,002 opencv-4.5.1-1.5.5-linux-x86_64.jar
10/01/2021  00:20         1,633,725 opencv.jar

**Comment by xwaeaewcrhomesysplug** [comment]
also had the javacpp java classes unpacked.Should be perfect.

**Comment by saudet** [comment]
Make sure that Loader.load(opencv_java.class) has been called as documented here:
https://github.com/bytedeco/javacpp-presets/tree/master/opencv#documentation

**Comment by xwaeaewcrhomesysplug** [comment]
Exception in thread "Thread-0" java.lang.UnsatisfiedLinkError: no jniopencv_core in java.library.path: /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2447)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:809)
	at java.base/java.lang.System.loadLibrary(System.java:1893)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1683)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1300)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1123)
	at org.bytedeco.opencv.global.opencv_core.<clinit>(opencv_core.java:16)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:468)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1190)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1139)
	at Testcrop.prestart(Testcrop.java:5)
	at Cropgui$Prepjavacppopencv.run(Cropgui.java:123)
	at java.base/java.lang.Thread.run(Thread.java:832)
	
	public static void prestart(){
		org.bytedeco.javacpp.Loader.load(org.bytedeco.opencv.opencv_java.class);
	}
	
	Sadly it is exactly the loader that caused the error.Tested in windows the whole application works perfectly.from setup to final image output.

**Comment by saudet** [comment]
Please set the "org.bytedeco.javacpp.logger.debug" system property to "true" to get more information about loading issues like that.

**Comment by xwaeaewcrhomesysplug** [comment]
sorry i do not think i can find the class file it doesn;t seems to be in javacpp.jar or any javacpp-os.jar any idea where to find that class.I cannot compile and test.

**Comment by saudet** [comment]
It's not a class file, it's a system property. We can set those, for example, by calling System.setProperty().

**Comment by xwaeaewcrhomesysplug** [comment]
ok here is the log>
Debug: Loading library cudart
Debug: Failed to load for cudart@.11.0: java.lang.UnsatisfiedLinkError: no cudart in java.library.path: /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
Debug: Loading library cublasLt
Debug: Failed to load for cublasLt@.11: java.lang.UnsatisfiedLinkError: no cublasLt in java.library.path: /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
Debug: Loading library cublas
Debug: Failed to load for cublas@.11: java.lang.UnsatisfiedLinkError: no cublas in java.library.path: /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
Debug: Loading library cufft
Debug: Failed to load for cufft@.10: java.lang.UnsatisfiedLinkError: no cufft in java.library.path: /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
Debug: Loading library cudnn
Debug: Failed to load for cudnn@.8: java.lang.UnsatisfiedLinkError: no cudnn in java.library.path: /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
Debug: Loading library nppc
Debug: Failed to load for nppc@.11: java.lang.UnsatisfiedLinkError: no nppc in java.library.path: /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
Debug: Loading library nppial
Debug: Failed to load for nppial@.11: java.lang.UnsatisfiedLinkError: no nppial in java.library.path: /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
Debug: Loading library nppicc
Debug: Failed to load for nppicc@.11: java.lang.UnsatisfiedLinkError: no nppicc in java.library.path: /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
Debug: Loading library nppicom
Debug: Failed to load for nppicom@.11: java.lang.UnsatisfiedLinkError: no nppicom in java.library.path: /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
Debug: Loading library nppidei
Debug: Failed to load for nppidei@.11: java.lang.UnsatisfiedLinkError: no nppidei in java.library.path: /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
Debug: Loading library nppif
Debug: Failed to load for nppif@.11: java.lang.UnsatisfiedLinkError: no nppif in java.library.path: /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
Debug: Loading library nppig
Debug: Failed to load for nppig@.11: java.lang.UnsatisfiedLinkError: no nppig in java.library.path: /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
Debug: Loading library nppim
Debug: Failed to load for nppim@.11: java.lang.UnsatisfiedLinkError: no nppim in java.library.path: /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
Debug: Loading library nppist
Debug: Failed to load for nppist@.11: java.lang.UnsatisfiedLinkError: no nppist in java.library.path: /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
Debug: Loading library nppisu
Debug: Failed to load for nppisu@.11: java.lang.UnsatisfiedLinkError: no nppisu in java.library.path: /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
Debug: Loading library nppitc
Debug: Failed to load for nppitc@.11: java.lang.UnsatisfiedLinkError: no nppitc in java.library.path: /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
Debug: Loading library npps
Debug: Failed to load for npps@.11: java.lang.UnsatisfiedLinkError: no npps in java.library.path: /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
Debug: Loading library cudnn_ops_infer
Debug: Failed to load for cudnn_ops_infer@.8: java.lang.UnsatisfiedLinkError: no cudnn_ops_infer in java.library.path: /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
Debug: Loading library cudnn_ops_train
Debug: Failed to load for cudnn_ops_train@.8: java.lang.UnsatisfiedLinkError: no cudnn_ops_train in java.library.path: /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
Debug: Loading library cudnn_adv_infer
Debug: Failed to load for cudnn_adv_infer@.8: java.lang.UnsatisfiedLinkError: no cudnn_adv_infer in java.library.path: /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
Debug: Loading library cudnn_adv_train
Debug: Failed to load for cudnn_adv_train@.8: java.lang.UnsatisfiedLinkError: no cudnn_adv_train in java.library.path: /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
Debug: Loading library cudnn_cnn_infer
Debug: Failed to load for cudnn_cnn_infer@.8: java.lang.UnsatisfiedLinkError: no cudnn_cnn_infer in java.library.path: /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
Debug: Loading library cudnn_cnn_train
Debug: Failed to load for cudnn_cnn_train@.8: java.lang.UnsatisfiedLinkError: no cudnn_cnn_train in java.library.path: /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
Debug: Loading library gfortran
Debug: Failed to load for gfortran@.3: java.lang.UnsatisfiedLinkError: no gfortran in java.library.path: /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
Debug: Loading library opencv_cudev
Debug: Failed to load for opencv_cudev@.4.4: java.lang.UnsatisfiedLinkError: no opencv_cudev in java.library.path: /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
Debug: Loading library opencv_core
Debug: Failed to load for opencv_core@.4.4: java.lang.UnsatisfiedLinkError: no opencv_core in java.library.path: /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
Debug: Loading library opencv_imgproc
Debug: Failed to load for opencv_imgproc@.4.4: java.lang.UnsatisfiedLinkError: no opencv_imgproc in java.library.path: /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib

**Comment by xwaeaewcrhomesysplug** [comment]
i think i need cuda is it?and the opencv imgproc also need to be in the sys path or something?

**Comment by saudet** [comment]
It says it's missing `opencv_core` and `opencv_imgproc`. You'll need to add those for it to work. If you do not wish to use the ones that come with the JAR files, it can load them from system too, yes.

**Comment by xwaeaewcrhomesysplug** [comment]
sorry,it is working.The version is not matching for my unix setup.the opencv is 1.4.5,4.5... while the javacpp and other binary is 1.5.5 so yeah.thx the set value to debug worked in setting.i will use it in future.thank you~
