### ISSUE TITLE
Is libsrt enabled in FFmpeg?

### ISSUE THREAD

**Issue by eneskuluk** [bytedeco/javacpp-presets#1035]
As asked in title, does ffmpeg support libsrt or not? I wasn't able to get a SRT stream and got `protocol not found` error when i tried to so.
Tried both usual and gpl builds. 
When I checked [cppbuild.sh](https://github.com/bytedeco/javacpp-presets/blob/master/ffmpeg/cppbuild.sh#L11), I couldn't see something similar to  --enable-libsrt.

**Comment by bradh** [comment]
As it happens, I've been working on this over the weekend. The PR is #1036

**Comment by eneskuluk** [comment]
Thanks you for your effort! I didn't have any chance to try yet but I will as soon as possible.

**Comment by eneskuluk** [comment]
@bradh Thanks! It did resolve the issue. Now the code can ingest the SRT streams.

**Comment by saudet** [comment]
Awesome! The PR has been merged, so we can now also get it from the snapshots: http://bytedeco.org/builds/

**Comment by bradh** [comment]
Is there anything more required? Or can this issue be closed?

**Comment by eneskuluk** [comment]
I haven't done extensive testing yet but I haven't found an issue as far as I use. I think it can be closed. If something unexpected arises, I can comment on this issue or can create another issue.

**Comment by bradh** [comment]
@saudet Ready for closure.

**Comment by saudet** [comment]
No worries, the "help wanted" label has been removed. :) I tend to close issues after a release including the fix, as a kind of review of the changelog.

**Comment by bradh** [comment]
OK. Will note the convention for the future.
