### ISSUE TITLE
cant compile ffmpeg

### ISSUE THREAD

**Issue by jduke32** [bytedeco/javacpp-presets#104]
i got error on bash when i tried on visual studio cmd :
```
#        [[ $ENABLE =~ "--enable-gpl" ]] && X11GRAB="--enable-x11grab" || X11GRAB=
../cppbuild.sh: line 7: conditional binary operator expected
../cppbuild.sh: line 266: conditional binary operator expected
../cppbuild.sh: line 181: conditional binary operator expected
```

**Comment by jduke32** [comment]
265    windows-x86_64)
266         if [[ !($DISABLE =~ "--disable-everything") ]]; then

../cppbuild.sh: line 266: conditional binary operator expected

**Comment by saudet** [comment]
Are you following the instructions from the following page?
https://github.com/bytedeco/javacpp-presets/wiki/Build-Environments#windows-x86-and-x86_64

**Comment by jduke32** [comment]
yes, i followed already

**Comment by jduke32** [comment]
bash script is not compatible on some environments

**Comment by saudet** [comment]
Yes, I understand that, but it works fine under MSYS2 on my machine. If you
could propose a change that would make it work on your machine, please send
a pull request and I'll merge it in! Thanks
