### ISSUE TITLE
Rebuilding

### ISSUE THREAD

**Issue by doktor-ziel** [bytedeco/javacpp-presets#1043]
Hello Guys!
I started working on the new preset. I followed [the instruction](https://github.com/bytedeco/javacpp-presets/wiki/Create-New-Presets). I managed to create `cppbuild.sh` script. I'm still working on Java configuration. 
I run build of my preset using the following command:
```
doktor@DESKTOP-0BB9FUV:~/code/javacpp-presets$ mvn clean install --projects .,cocoa
```
But it keeps building the whole preset from the scratch. It takes very long time. The build fails (and it is normal). I'd like to restart build from the place of failure, just like maven suggests:
```
mvn -rf :cocoa clean install
```
however it starts the whole build from beginning...

Maybe there is the other way to perform just parsing operation? Any help will be appreciated.

**Comment by saudet** [comment]
There are a couple of properties we can use to skip the different phases of the build:
https://github.com/bytedeco/javacpp-presets/blob/master/pom.xml#L60

**Comment by doktor-ziel** [comment]
Thanks! That's very useful comment:)
