### ISSUE TITLE
RuntimeException at org.bytedeco.hyperscan.global.hyperscan.hs_scan

### ISSUE THREAD

**Issue by xishian** [bytedeco/javacpp-presets#1049]
I use this library match many regexes, but this exception throws, and after a period of time, the matcher cannot match any regexes.

Perhaps, that's a bug of hyperscan?

Hyperscan 5.4.0-1.5.5

java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.Runti
        at org.bytedeco.hyperscan.global.hyperscan.hs_scan(Native Method) ~[hyperscan-5.4.0-1.5.5.jar:5.4.0-1.5.5]

**Comment by saudet** [comment]
Maybe something is getting garbage collected prematurely. Try to set the "org.bytedeco.javacpp.nopointergc" system property to "true", and if it doesn't crash, that's what is happening.

**Comment by xishian** [comment]
thanks, but it doesn't work for me

**Comment by saudet** [comment]
If it works fine from a single thread, then yes the problem is probably an issue related to thread safety.
