### ISSUE TITLE
Spinnaker, how to access the image data?

### ISSUE THREAD

**Issue by micheleSolutions** [bytedeco/javacpp-presets#1053]
I'm trying to access the pixel data of the image, but there is no information on how to get byte array from PointerPointer.
If I pass a fresh byte array to the constructor of the PointerPointer, it is not altereated after a successfully call to spinImageGetData..

  byte[ ] outPixels = new byte[(int) bufferSize.get()];
  PointerPointer data = new PointerPointer(outPixels);
  err = Spinnaker_C.spinImageGetData(hResultImage, data);

**Comment by jpsacha** [comment]
@micheleSolutions In general you first load image pixels through a BytePointer. Here is an example where you start with a `spinImage`
```java
spinImage image = ???
BytePointer data = new BytePointer();
spinImageGetData(image, data);

SizeTPointer bufferSize = new SizeTPointer(1);
spinImageGetBufferSize(image, bufferSize);
data.capacity(bufferSize.get());
```
If you have 8- bit format, like `PixelFormat_Mono8`, you just read from BytePointer any usual way provided by JavaCPP. If you have other format, say, `PixelFormat_Mono16` or `PixelFormat_BGR8` you will need to create pixels from bytes appropriately.

**Comment by micheleSolutions** [comment]
Thanks a lot, it works!
