### ISSUE TITLE
Is it possible to generate some header or class to different java packages?

### ISSUE THREAD

**Issue by egolearner** [bytedeco/javacpp-presets#1066]
The following will generate all the java classes to the same package.
```java
@Properties(
        target = "com.mycompany.package",
        global = "com.mycompany.package.global",
)
```
We'd like to introduce sub package, i.e. generating some class to `com.mycompany.package.group1`.
It seems impossible to write multiple preset class as there're header dependencies. `group1` depends on `core` definition.
```java
@Properties(
        target = "com.mycompany.package",
        global = "com.mycompany.package.global",
        include = "core/xxxx.h",
)
class package {
}


@Properties(
        target = "com.mycompany.package.group1",
        global = "com.mycompany.package.group1.global",
        include = "group1/xxxx.h",
)
class group1 {
}

```

**Comment by saudet** [comment]
That should already work with `@Properties(inherit = core.class, ...`. What do you get with this?

**Comment by egolearner** [comment]
It works! Thanks @saudet !
