### ISSUE TITLE
Memory leak for ffmpeg avio reader

### ISSUE THREAD

**Issue by nanguantong** [bytedeco/javacpp-presets#1072]
Hi, @saudet 
   I use ffmpeg preset(version: 4.4-1.5.6) to read custom stream from network as following:

```
BlockingQueue<Object> recvQueue = xxxxx;
ReadPacketCallback readBufferCbPtr = new ReadPacketCallback();
private static class ReadPacketCallback extends Read_packet_Pointer_BytePointer_int {
        @Override
        public int call(Pointer opaque, BytePointer buf, int buf_size) {
            byte[] recvBuf = recvQueue.poll(5, TimeUnit.MILLISECONDS);
            if (null == recvBuf ) {
                return -1; // AVERROR_EOF
            }
            int size = Math.min(size, 1024*1024);
            buf.put(recvBuf, 0, size);
            return size;
        }
}

.....

AVFormatContext ifmtCtx = avformat_alloc_context();
BytePointer readBuf = new BytePointer(av_malloc(1024*1024));
AVIOContext iavioCtx =  avio_alloc_context(readBuf, 1024*1024, 0, ifmtCtx, readBufferCbPtr, null, null);
ifmtCtx.pb(iavioCtx);
ifmtCtx.flags(ifmtCtx.flags() | AVFormatContext.AVFMT_FLAG_CUSTOM_IO);
ifmtCtx.flags(ifmtCtx.flags() | AVFormatContext.AVFMT_FLAG_NOBUFFER);

......

int ret;
AVPacket pkt = new AVPacket();
while (true) {
    if (null != pkt) {
        av_packet_unref(pkt);
    }
    ret = av_read_frame(ifmtCtx, pkt);
    if (ret == AVERROR_EAGAIN()) {
         Thread.sleep(10);
         continue;
     } else if (ret < 0) {
          break;
     }
}

... // free ......
```

I found the memory keeps growing in 8K steps at function `call`  while reading network stream, so why?  Please help me see what the problem is?

**Comment by saudet** [comment]
Make sure to call close() on all objects before returning. We can do that
easily with PointerScope.

**Comment by nanguantong** [comment]
> Make sure to call close() on all objects before returning. We can do that easily with PointerScope.

Yes, I did.

**Comment by nanguantong** [comment]
![image](https://user-images.githubusercontent.com/12180902/130344391-053a7d16-84b9-4efe-b57f-77f6976975b0.png)
![image](https://user-images.githubusercontent.com/12180902/130344394-3355fd31-4e82-4e0e-a0e3-3770223f284d.png)

**Comment by nanguantong** [comment]
<img width="1002" alt="image" src="https://user-images.githubusercontent.com/12180902/159185191-4a07a460-7e3e-4b3b-8b2a-83407b119705.png">

```
int probeSize = 1024*1024;
ByteBuffer readBuf = ByteBuffer.allocateDirect(probeSize);
AVIOContext iavioCtx = avio_alloc_context(readBuf, probeSize, 0, ifmtCtx, readBufferCbPtr, null, null);
```

Why?

**Comment by saudet** [comment]
You can set that to 0 if you don't need it.

**Comment by nanguantong** [comment]
> <img alt="image" width="1002" src="https://user-images.githubusercontent.com/12180902/159185191-4a07a460-7e3e-4b3b-8b2a-83407b119705.png">
> 
> ```
> int probeSize = 1024*1024;
> ByteBuffer readBuf = ByteBuffer.allocateDirect(probeSize);
> AVIOContext iavioCtx = avio_alloc_context(readBuf, probeSize, 0, ifmtCtx, readBufferCbPtr, null, null);
> ```
> 
> Why?

Crash `while buf.put(recvBuf, 0, size).`, because out of array index.

**Comment by nanguantong** [comment]
> 

However, the memory still increased slowly in the step 8K, why?

**Comment by saudet** [comment]
> Crash while calling `buf.put(recvBuf, 0, size).`, because out of array index.

What is recvBuf?

**Comment by nanguantong** [comment]
> > Make sure to call close() on all objects before returning. We can do that easily with PointerScope.
> 
> Yes, I did.

However, the memory still increased slowly in the step 8K, why?

**Comment by nanguantong** [comment]
> > Crash while calling `buf.put(recvBuf, 0, size).`, because out of array index.
> 
> What is recvBuf?

Yes.

**Comment by nanguantong** [comment]
> > Crash while calling `buf.put(recvBuf, 0, size).`, because out of array index.
> 
> What is recvBuf?

byte[] recvBuf = new byte[4096];

**Comment by saudet** [comment]
> > 
> 
> However, the memory still increased slowly in the step 8K, why?

You'll need to find where this is happening in your code. That's unrelated to JavaCPP, JavaCV, or FFmpeg.

**Comment by saudet** [comment]
> > > Crash while calling `buf.put(recvBuf, 0, size).`, because out of array index.
> > 
> > 
> > What is recvBuf?
> 
> byte[] recvBuf = new byte[4096];

So I'd recommend to use BytePointer instead of ByteBuffer.

**Comment by nanguantong** [comment]
So is this a bug for using `Read_packet_Pointer_byte___int` or `Read_packet_Pointer_ByteBuffer_int`?

**Comment by nanguantong** [comment]
> > > 
> > 
> > 
> > However, the memory still increased slowly in the step 8K, why?
> 
> You'll need to find where this is happening in your code. That's unrelated to JavaCPP, JavaCV, or FFmpeg.




`
    FileInputStream in = null;
    byte[] recvBuf = new byte[4096];
    int probeSize = 1024 * 1024;
    int maxProbePackets = 500;
    int analyzeDuration = 5000;
    int readTimeout = 30000;
    AtomicLong lastFrameTime = new AtomicLong(0);
    AtomicBoolean timeouted = new AtomicBoolean(false);
    int streamMappingSize = 0;
    AVFormatContext ifmtCtx;
    int videoIndex = -1, audioIndex = -1;

    private final ReadPacketCallback readBufferCbPtr = new ReadPacketCallback();
    private class ReadPacketCallback extends Read_packet_Pointer_BytePointer_int {
        @Override
        public int call(Pointer opaque, BytePointer buf, int buf_size) {
            int size = 0;
            try {
                size = in.read(recvBuf);
                if (size <= 0) {
                    System.out.println("reset file read");
                    in.getChannel().position(0);
                    size = in.read(recvBuf);
                }
                //System.out.println("file read " + size);

                size = Math.min(size, probeSize);
                buf.put(recvBuf, 0, size);
                return size;
            } catch (IOException e) {
                e.printStackTrace();
            }

            return -1;
        }
    }

    private final InterruptCallback interruptCbPtr = new InterruptCallback();
    private class InterruptCallback extends AVIOInterruptCB.Callback_Pointer {
        @Override
        public int call(Pointer opaque) {
            if (lastFrameTime.get() + readTimeout < System.currentTimeMillis()) {
                System.out.println("Decode frame read timeout");
                timeouted.set(true);
                return 1; // exit
            }
            return 0;
        }
    }

    @Test
    public void testFFmpegReadIo() throws IOException, InterruptedException {
        System.out.println("Read few frame and write to image");
        int ret = -1, i = 0;
        String fmt = "mpeg";

        //try (PointerScope scope = new PointerScope()) {
        do {
            in = new FileInputStream(vf_path);

            ifmtCtx = avformat_alloc_context();
            AVInputFormat ifmt = null;
            AVIOContext iavioCtx = null;
            AVIOInterruptCB interruptCB = null;
            BytePointer readBuf = null;
            //ByteBuffer readBuf = null;
            AVDictionary dict = null;

            interruptCB = new AVIOInterruptCB();
            interruptCB.callback(interruptCbPtr);
            interruptCB.opaque(ifmtCtx);
            ifmtCtx.interrupt_callback(interruptCB);

            readBuf = new BytePointer(av_malloc(probeSize));
            //readBuf = ByteBuffer.allocateDirect(probeSize);
            iavioCtx = avio_alloc_context(readBuf, probeSize, 0, ifmtCtx,
                    readBufferCbPtr, null, null);
            if (iavioCtx == null) {
                ret = AVERROR_ENOMEM();
                System.out.println("Alloc avio context failed");
                break;
            }

            iavioCtx.max_packet_size(probeSize);

            ifmt = av_find_input_format(fmt);

            ifmtCtx.pb(iavioCtx);
            ifmtCtx.flags(ifmtCtx.flags() | AVFormatContext.AVFMT_FLAG_CUSTOM_IO);

            lastFrameTime.set(System.currentTimeMillis());
            ret = avformat_open_input(ifmtCtx, "", ifmt, dict);
            if (null != dict) {
                av_dict_free(dict); dict = null;
            }
            if (ret < 0) {
                System.out.println("Open input media failed, ret {}" + ret);
                break;
            }
            System.out.println("Open input ok");

            if (useAudio) {
                ifmtCtx.max_probe_packets(maxProbePackets);
            }
            if (probeSize > 0) {
                ifmtCtx.probesize(probeSize);
                ifmtCtx.max_ts_probe(); // 50 packets
                ifmtCtx.max_analyze_duration(analyzeDuration * 1000L);
                //ifmtCtx.fps_probe_size(fpsProbeSize);
            }

            ret = avformat_find_stream_info(ifmtCtx, dict);
            if (ret < 0) {
                System.out.println("Failed to find input stream info, ret {}" + ret);
                break;
            }
            System.out.println("Find stream info ok");

            av_dump_format(ifmtCtx, 0, "", 0);

            streamMappingSize = ifmtCtx.nb_streams();
            streamMapping = new ArrayList<>(streamMappingSize);
            int streamIndex = 0;
            for (i = 0; i < streamMappingSize; i++) {
                AVStream inStream = ifmtCtx.streams(i);
                AVCodecContext codec = inStream.codec();
                AVCodecParameters inCodecpar = inStream.codecpar();
                int codecId = inCodecpar.codec_id();
                BytePointer codecName = avcodec_get_name(codecId);
                BytePointer codecTypeName = av_get_media_type_string(inCodecpar.codec_type());
                long streamDuration = inStream.duration();

                log.info("Found {} {} stream index {}, start time {} - {}, {} {}",
                        codecTypeName == null ? "" : codecTypeName.getString(),
                        codecName == null ? "" : codecName.getString(),
                        inStream.index(), inStream.start_time(), ifmtCtx.start_time(),
                        inStream.probe_packets(), inStream.codec_info_nb_frames());
                if (null != codecName) { codecName.close(); }
                if (null != codecTypeName) { codecTypeName.close(); }

                if (AVMEDIA_TYPE_AUDIO == inCodecpar.codec_type()) {
                    if (codec.sample_rate() <= 0 || codec.channels() <= 0 || codec.sample_fmt() < 0) {
                        log.warn("Invalid audio stream info: samplerate={}, channels={}, samplefmt={}",
                                codec.sample_rate(), codec.channels(), codec.sample_fmt());
                        continue;
                    }
                    BytePointer sampleFmtName = av_get_sample_fmt_name(codec.sample_fmt());
                    log.info("{} hz / {} channel / {}", codec.sample_rate(), codec.channels(),
                            sampleFmtName == null ? "" : sampleFmtName.getString());
                    if (null != sampleFmtName) sampleFmtName.close();
                    audioIndex = i;
                } else if (AVMEDIA_TYPE_VIDEO == inCodecpar.codec_type()) {
                    if ((inCodecpar.width() <= 0 || inCodecpar.height() <= 0) && (codec.width() <= 0 || codec.height() <= 0)) {
                        System.out.println("Invalid video stream info");
                        continue;
                    }
                    if (AV_CODEC_ID_H264 != codecId && AV_CODEC_ID_H265 != codecId) {
                        System.out.println("Unsupported video codec {}, only h264 or h265" + codecId);
                        continue;
                    }
                    AVRational fps = av_guess_frame_rate(ifmtCtx, inStream, null);
                    AVRational fps1 = inStream.avg_frame_rate();
                    AVRational fps2 = inStream.r_frame_rate();
                    AVRational fps3 = codec.framerate();
                    log.info("{}x{}, guess fps {}/{}, avg fps {}/{}, r fps {}/{}, codec fps {}/{}",
                            inCodecpar.width() > 0 ? inCodecpar.width() : codec.width(),
                            inCodecpar.height() > 0 ? inCodecpar.height() : codec.height(),
                            fps.num(), fps.den(), fps1.num(), fps1.den(), fps2.num(), fps2.den(), fps3.num(), fps3.den());
                    if (fps.den() <= 0 || (fps.num() / fps.den() > 150) || (fps.num() / fps.den() <= 1)) {
                        System.out.println("fps is abnormal, adjust to 25");

                        if (inStream.time_base().den() == fps.num() && inStream.time_base().num() == fps.den()) {
                            System.out.println("Maybe invalid rfps");
                            fps.num(25).den(1);
                            inStream.r_frame_rate(fps);
                        }
                        fps.num(25).den(1);
                    }
                    videoIndex = i;
                } else {
                    continue;
                }

                streamIndex++;
            }

            if (streamIndex == 0) {
                ret = AVERROR_STREAM_NOT_FOUND;
                System.out.println("Not found valid streams");
                break;
            }
        } while (false);

        if (ret != 0) {
            return;
        }

        //AVPacket pkt = av_packet_alloc();
        AVPacket pkt = new AVPacket();
        initPacket(pkt);
        while (true) {
            av_packet_unref(pkt);
            lastFrameTime.set(System.currentTimeMillis());
            ret = av_read_frame(ifmtCtx, pkt);
            if (ret == AVERROR_EAGAIN()) {
                Thread.sleep(10);
                continue;
            } else if (ret < 0) {
                System.out.println("Read frame finished, " + getErrorString(ret));
                break;
            }
            Thread.sleep(40);
        }
        //}

        AVIOContext avio = ifmtCtx.pb();
        if (null != avio) {
            if (avio.buffer() != null) {
                av_free(avio.buffer());
                avio.buffer(null);
            }
            avio_context_free(avio);
            ifmtCtx.pb(null);
        }
        //av_packet_free(pkt);
        avformat_close_input(ifmtCtx);
        System.out.println("Shutdown");
        System.exit(0);
    }`

**Comment by nanguantong** [comment]
> So is this a bug for using `Read_packet_Pointer_byte___int` or `Read_packet_Pointer_ByteBuffer_int`?

And, if I delete `buf.put(recvBuf, 0, size);`, instead of `return 0`; directly, the memory is normal.
So the `av_read_frame()` looks like OOM?

**Comment by saudet** [comment]
> So is this a bug for using `Read_packet_Pointer_byte___int` or `Read_packet_Pointer_ByteBuffer_int`?

It's not a bug, the size information isn't available from a pointer. You need to take it from buf_size.

**Comment by nanguantong** [comment]
So  how to use the `Read_packet_Pointer_byte___int` or `Read_packet_Pointer_ByteBuffer_int`?

**Comment by nanguantong** [comment]
> > So is this a bug for using `Read_packet_Pointer_byte___int` or `Read_packet_Pointer_ByteBuffer_int`?
> 
> It's not a bug, the size information isn't available from a pointer. You need to take it from buf_size.

The read-only buf_size is the input probeSize len, buf is the ByteBuffer.allocateDirect(probeSize); need to write into from recvBuf.

**Comment by saudet** [comment]
> So how to use the `Read_packet_Pointer_byte___int` or `Read_packet_Pointer_ByteBuffer_int`?

We probably can't use them, so don't use them!

**Comment by adiantek** [comment]
There is another problem with that:
```
    public static void main(String[] args) throws InterruptedException {
        ArrayList<AVIOContext> contexts = new ArrayList<>();
        while (true) {
            AVIOContext pb = avformat.avio_alloc_context(null, 0, 0, null, new Read_packet_Pointer_BytePointer_int() {
    
                @Override
                public int call(org.bytedeco.javacpp.Pointer s, org.bytedeco.javacpp.BytePointer bb, int size) {
                    System.out.println("read called " + size);
                    return 0;
                }
            }, null, new Seek_Pointer_long_int() {
    
    
                public long call(org.bytedeco.javacpp.Pointer s, long offset, int whence) {
                    System.out.println("seek, whence: " + whence + ", offset: " + offset);
                    return 0;
                }
            });
            contexts.add(pb);
            System.out.println("test: " + avformat.avio_seek(pb, 2, avformat.AVSEEK_SIZE));
            Thread.sleep(100);
        }
    }
```
Output of this code:
```
seeking, whence: 65536, offset: 2
test: 0
seeking, whence: 65536, offset: 2
test: 0
seeking, whence: 65536, offset: 2
test: 0
seeking, whence: 65536, offset: 2
test: 0
seeking, whence: 65536, offset: 2
test: 0
seeking, whence: 65536, offset: 2
test: 0
seeking, whence: 65536, offset: 2
test: 0
seeking, whence: 65536, offset: 2
test: 0
seeking, whence: 65536, offset: 2
test: 0
seeking, whence: 65536, offset: 2
test: 0
test: -40
test: -40
test: -40
test: -40
test: -40
test: -40
test: -40
test: -40
```

**Comment by saudet** [comment]
You're exceeding the callback allocation maximum size. Please deallocate the callbacks you do not need anymore. GC doesn't guarantee when deallocation happens.

**Comment by adiantek** [comment]
> 

Thanks, I solved that making one global instance and using opaque (pointer from callbacks)

**Comment by saudet** [comment]
Duplicate of https://github.com/bytedeco/javacpp/issues/611
