### ISSUE TITLE
Access Violation with QMenu and QAction when using more than 10 Elements

### ISSUE THREAD

**Issue by newhinton** [bytedeco/javacpp-presets#1077]
When i run the Example-Systray privided by this project, it works as long as no more than 10 QActions are added to the Systray/QMenu. When using more than 10 elements, every element after this cannot have an callback, because it crashes with an access violation. 

```

QAction action = new QAction(QString.asprintf(name));
TriggeredCallback callback = new TriggeredCallback() {
    @Override
    public void triggered(boolean checked) {
        System.err.println("Show now: "+name);
    }
};
QAction_triggered(action, mSystemTray, callback, callback.id);
```

Add this in a loop to add many more items with a simple callback
Clicking 1 to 11 results in the appropriate message, but every element after that produces that exception:

```
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x0000000000000000, pid=6088, tid=4732
```

Why is that and how can i fix this?

**Comment by newhinton** [comment]
Probably duplicate of #1062

**Comment by saudet** [comment]
Correct, this is a duplicate of #1062.
