### ISSUE TITLE
Shipping LLVM native libraries on mac/arm64

### ISSUE THREAD

**Issue by oxisto** [bytedeco/javacpp-presets#1091]
Great project! We are currently using it to natively access LLVM in our code analysis project. I was wondering.. Would it be possible to ship the LLVM native binaries also for mac/arm64? It seems that this particular combination is missing. Compiling and running it is no issue, so at least there should not be a technical blocker for it.

Keep up the good work!

**Comment by saudet** [comment]
Everything is on the following page, but in this case we only need to add the entries for "macosx-arm64", obviously:
https://github.com/bytedeco/javacpp-presets/wiki/Create-New-Presets
