### ISSUE TITLE
Enable ffmpeg with libwebp

### ISSUE THREAD

**Issue by minzhang-haus** [bytedeco/javacpp-presets#1099]
Trying to use javacv to generate animated `webp` from video. But it doesn't look like javacv supports it. In the cppbuild.sh, libwebp is not enabled either. 

Is there plan to support that? 

the cmd that i tried to achieve with javacv: https://gist.github.com/witmin/1edf926c2886d5c8d9b264d70baf7379

**Comment by saudet** [comment]
We just need to add builds for it, yes. Contributions are welcome!

**Comment by bradh** [comment]
@saudet Working this. Do you want to assign it to me?

**Comment by saudet** [comment]
BTW, configure commands to build libwebp itself are already in the script for Leptonica:
https://github.com/bytedeco/javacpp-presets/blob/master/leptonica/cppbuild.sh

**Comment by bradh** [comment]
> BTW, configure commands to build libwebp itself are already in the script for Leptonica: https://github.com/bytedeco/javacpp-presets/blob/master/leptonica/cppbuild.sh
Wish I'd seen this comment earlier. I spent most of the weekend working it...

**Comment by saudet** [comment]
Thanks to @bradh, we now have support for WebP encoding!
@minzhang-haus Please give it a try with the snapshots: http://bytedeco.org/builds/

**Comment by minzhang-haus** [comment]
@saudet @bradh thank you guys! will give a try 👍
