### ISSUE TITLE
ngt (ann vector search) - help wanted adding to presets - how to package for x86_64 only?

### ISSUE THREAD

**Issue by xlfe** [bytedeco/javacpp-presets#1103]
Hi there - thanks for these amazing colleciton of libraries. 

I'm trying to add https://github.com/yahoojapan/NGT and I've been able to get it compiling https://github.com/xlfe/javacpp-presets/tree/ngt by hacking lots of skip()s into the definition.

Here's the compliation steps I'm using

```bash
pushd javacpp
mvn -Djavacpp.platform=linux-x86_64 -Djavacpp.platform.dependency=false clean install
popd
pushd javacpp-presets
mvn clean install --projects .,ngt -Djavacpp.platform=linux-x86_64 -Djavacpp.platform.dependency=false
mvn clean install -f platform --projects ../ngt/platform -Djavacpp.platform.host -Djavacpp.platform.dependency=false
popd
```

I was about to try and test the API, but when I try to use the compiled artifact (ngt-platform), I get an error :-

```
Error building classpath. Could not find artifact org.bytedeco:javacpp:jar:linux-armhf:1.5.7-SNAPSHOT in central (https://repo1.maven.org/maven2/)
```

Any hints would be appreciated on how I might get it to package ngt-platform without a reference to javacpp for linux-armhf ?

**Comment by saudet** [comment]
Snapshots are only available on the snapshot repository: http://bytedeco.org/builds/

**Comment by xlfe** [comment]
Right - I thought I might build and test locally before making a PR, but will do so now instead.

Thanks

**Comment by saudet** [comment]
To build only for a single platform, use the javacpp.platform system
property like this:
https://github.com/bytedeco/javacpp-presets/wiki/Build-Environments

**Comment by saudet** [comment]
If you're talking about what's in your pom.xml files, you can remove javacpp-platform and replace it manually with only the platforms you want in there.

**Comment by xlfe** [comment]
Thanks @saudet - after battling with compilation errors for a few days I'm taking a different approach (using the c api of the project with https://github.com/IGJoshua/coffi ) - thanks for your help

**Comment by saudet** [comment]
We can map C APIs with JavaCPP too, and it's a lot easier as well. Panama is just never going to C++ APIs at all...
