### ISSUE TITLE
error when running "uber jar" for tritonserver

### ISSUE THREAD

**Issue by jackyh** [bytedeco/javacpp-presets#1111]
I add something in the build part of "javacpp-presets/tritonserver/samples/pom.xml" as attached.
[pom.zip](https://github.com/bytedeco/javacpp-presets/files/7763304/pom.zip)

When I execute like this:
root@b9283522f78a:/opt/tritonserver/javacpp-presets/tritonserver/samples/target# java -jar simple-1.5.7-SNAPSHOT.jar
Error: Unable to initialize main class Simple
Caused by: java.lang.NoClassDefFoundError: org/bytedeco/tritonserver/tritonserver/TRITONSERVER_Server

I guess I set the wrong value for the mainClass part, but it's too late here, I can not resolve it this night. need your help. @saudet  

thanks, Samuel.

**Comment by saudet** [comment]
It works fine for me, if I remove the filters:
```xml
    <filters>
      <filter>
            <artifact>org.bytedeco:tritonserver</artifact>
            <includes>
              <include>tritonserver/**</include>
          </includes>
      </filter>
      <filter>
            <artifact>com.google.code.gson:gson</artifact>
            <includes>
              <include>gson/**</include>
          </includes>
      </filter>
    </filters>
```
These rules exclude the `org/bytedeco/tritonserver/tritonserver/TRITONSERVER_Server.class` file.
