### ISSUE TITLE
Feature Request: MKL Presets

### ISSUE THREAD

**Issue by bashimao** [bytedeco/javacpp-presets#112]
I would like to see presets for Intel MKL. Specifically parts that are not covered by netlib-java. For example the Vector Statistical Library (VSL) (chapter 9 in MKL documentation, https://software.intel.com/en-us/articles/intel-math-kernel-library-documentation). I know MKL is vast. But it would definitely help a lot of people to have Intel's arsenal available in Java.

**Comment by saudet** [comment]
I'm adding presets for OpenBLAS that indirectly link with MKL when available. Please check it out and let me know what you think! Thanks

**Comment by saudet** [comment]
I've finally added presets for the whole of MKL: https://github.com/bytedeco/javacpp-presets/commit/190fcfc6a728874a423161b87619e40df9418282  Enjoy!

**Comment by saudet** [comment]
And now it has been released!
http://search.maven.org/#artifactdetails%7Corg.bytedeco.javacpp-presets%7Cmkl%7C2017.3-1.3%7Cjar
