### ISSUE TITLE
A problem for capturing frames from .mp4 file with opencv 

### ISSUE THREAD

**Issue by wureka** [bytedeco/javacpp-presets#1120]
I know that the default configuration for opencv does not turn on `WITH_FFMPEG`. And this results in a issue. It will not work when I use `VideoCapture` in opencv to grab frames from a .mp4 file.  `videoCapture.open('foo.mp4');` will always return false no matter what fourcc I try.

Well, it is the last thing that I clone javacpp-presets, turn on `WITH_FFMPEG` flag, and build opencv myself. 
Any suggestion ?

**Comment by saudet** [comment]
Anything wrong with FFmpegFrameGrabber?

**Comment by wureka** [comment]
Well, FFmpegFrameGrabber is the object of JavaCV. I use javacpp-presets/opencv. They seem to be different.
And for JavaCV, yes, FFmpegFrameGrabber can successfully grab frames from .mp4 files. However, as I reported to you that  JavaCV has problems combining the Depthai package
[https://github.com/bytedeco/javacpp-presets/issues/1118)](https://github.com/bytedeco/javacpp-presets/issues/1118)

JavaCV could be another solution. But my current code is all based on opencv, so I may need more time to verify the linkage between JavaCV and Depthai and convert to JavaCV's functions.

By the way, does JavaCV support Raspberry PI ?

**Comment by saudet** [comment]
JavaCV simply uses OpenCV and FFmpeg from the JavaCPP Presets. It doesn't do anything special.
