### ISSUE TITLE
how to make dependency compile automatically if the dependency can not get from repo

### ISSUE THREAD

**Issue by jackyh** [bytedeco/javacpp-presets#1122]
When we git clone the src and do this in "javacpp-presets/tritonserver/samples/":

mvn compile exec:java -Djavacpp.platform=linux-x86_64 -Dexec.args="-r /workspace"

It will get failed with error:

[ERROR] Failed to execute goal on project simple: Could not resolve dependencies for project org.bytedeco.tritonserver:simple:jar:1.5.7-SNAPSHOT: Could not find artifact org.bytedeco:tritonserver-platform:jar:2.17-1.5.7-SNAPSHOT -> [Help 1]

This is because we have to compile tritonserver-platform:jar:2.17-1.5.7-SNAPSHOT manually before we compile sample. 

My question is: can be set pom.xml or other ways to make the dependency of "tritonserver-platform:jar:2.17-1.5.7-SNAPSHOT" be compiled automatically when we want to compile sample.java?

If not, can we store "tritonserver-platform:jar:2.17-1.5.7-SNAPSHOT" in some repo so that we do not need to compile it each time?

**Comment by saudet** [comment]
It gets deployed in the same repo at the main "tritonserver" artifact, for example, here:
https://oss.sonatype.org/content/repositories/snapshots/org/bytedeco/tritonserver/
https://oss.sonatype.org/content/repositories/snapshots/org/bytedeco/tritonserver-platform/
If you're installation of Maven isn't able to see it in the repo, it's a problem with its repo settings properly.

**Comment by jackyh** [comment]
> It gets deployed in the same repo as the main "tritonserver" artifact, for example, here: https://oss.sonatype.org/content/repositories/snapshots/org/bytedeco/tritonserver/ https://oss.sonatype.org/content/repositories/snapshots/org/bytedeco/tritonserver-platform/ If you're installation of Maven isn't able to see it in the repo, it's probably a problem with its repo settings.

you mean I need to modify my local settings to add oss.sonatype?
do we have any examples?

**Comment by saudet** [comment]
No, you can use whatever repo you wish, but if you want to use the snapshots repository from Sonatype OSSRH, yes, you'll need to add it, see http://bytedeco.org/builds/
