### ISSUE TITLE
Error building presets for Android on ubuntu x_86

### ISSUE THREAD

**Issue by androiddevaccnt7** [bytedeco/javacpp-presets#113]
Almost certainly user-error here, I've hit an issue building according to the README of this project. 

The first part, 
>ANDROID_NDK=/path/to/android-ndk/ bash cppbuild.sh -platform android-arm install opencv ffmpeg

seems to work fine. 

After that, I cannot complete the Maven portion of the build steps. 

>mvn clean install -Pandroid-arm -Dplatform.root=/path/to/android-ndk/ --projects .,opencv,ffmpeg

The above command fails quickly, with the following error. 

>Failed to execute goal org.bytedeco:javacpp:1.2-SNAPSHOT:build (generate-sources) on project opencv: Failed to execute JavaCPP Builder: Could not parse "opencv2/hal/defs.h": File does not exist -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.bytedeco:javacpp:1.2-SNAPSHOT:build (generate-sources) on project opencv: Failed to execute JavaCPP Builder

The missing file does exist under my javapresets directory. I feel like there is something basic I must be missing here, like building 'javacpp' first. I've seen that mentioned in serveral previous issues, but its unclear to me how to do so in a way that would effect my presets build.

**Comment by ongakuer** [comment]
same here. I change to use the release 1.1 version.https://github.com/bytedeco/javacpp-presets/releases/tag/1.1

**Comment by saudet** [comment]
Please also execute the `cppbuild.sh` script as explained here:
https://github.com/bytedeco/javacpp-presets/#build-instructions
