### ISSUE TITLE
Missing macros.h in avutil @Properties

### ISSUE THREAD

**Issue by jfehr67** [bytedeco/javacpp-presets#1134]
https://github.com/bytedeco/javacpp-presets/blob/da8c22aaa0b7a4b395aaea406e6727c7cf58d14f/ffmpeg/src/main/java/org/bytedeco/ffmpeg/presets/avutil.java#L48

Many macros were moved into macros.h, but macros.h wasn't added to the @Properties, so aren't generated in the ffmpeg/src/gen/java/org/bytedeco/ffmpeg/global/avutil.java file.

**Comment by bradh** [comment]
@jfehr67 What do you use from the macros? I'm not doubting there is a valid need, just want to try adding a unit test to "back stop" this change.

**Comment by jfehr67** [comment]
The only usage we had was the MKTAG macro. Could work around it, but since afaik macros.h isn't supposed to be private, it should be ok to add it I think.

PR coming shortly. Not sure about what the naming conventions are for branches, but you can always correct me.

**Comment by bradh** [comment]
No problem.  I agree it should be in the mix. If you want to add that file, go ahead.

If its in your tree, you can call it anything reasonable. Something like `issue_1134` would be a suggestion, but definitely up to you. 

I will follow up with a test to ensure no regression.

**Comment by jfehr67** [comment]
So I made the change and tested it to make sure global/avutils.java is updated (which it is), but git status shows that ffmpeg/src/gen/java/org/bytedeco/ffmpeg/global/avutil.java is also changed. Should I include that in my PR? It looks like its all generated when you build, so I'm not sure why ffmpeg/src/gen in the repo.

**Comment by bradh** [comment]
Include the `src/gen`. I don't know the rationale, but it is usual to include them.

**Comment by saudet** [comment]
Yes, please update `src/gen`, it's there only because there's no other better places to put generated source code that we can refer to easily from the browser.

**Comment by jfehr67** [comment]
Getting a permission error after creating a new token to do the push.

Username for 'https://github.com': jfehr67
Password for 'https://jfehr67@github.com': 
remote: Permission to bytedeco/javacpp-presets.git denied to jfehr67.
fatal: unable to access 'https://github.com/bytedeco/javacpp-presets.git/': The requested URL returned error: 403

I've included the diff here if that's easier then figuring out my permission ssieu.

[issue_1134_diff.txt](https://github.com/bytedeco/javacpp-presets/files/7922611/issue_1134_diff.txt)

**Comment by saudet** [comment]
Create your own fork first: https://docs.github.com/en/get-started/quickstart/contributing-to-projects

**Comment by jfehr67** [comment]
K, I think it worked. https://github.com/bytedeco/javacpp-presets/pull/1135

**Comment by saudet** [comment]
Thanks for the fix!
