### ISSUE TITLE
MacOS issue dlopening libjniavutil.dylib: Library not loaded: /usr/local/opt/libx11/lib/libX11.6.dylib

### ISSUE THREAD

**Issue by jfehr67** [bytedeco/javacpp-presets#1136]
I can build my code if I also build the ffmpeg and ffmpeg-platform on my local mac and install into my local ~/.m2 repo, but if I try to use the snapshot from sonotype, I get a weird error:

UnknownClass.Failed to load test from ...: 'no jniavutil in java.library.path' FAILED
    java.lang.UnsatisfiedLinkError: no jniavutil in java.library.path
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1875)
        at java.lang.Runtime.loadLibrary0(Runtime.java:872)
        at java.lang.System.loadLibrary(System.java:1124)
        at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1773)
        at org.bytedeco.javacpp.Loader.load(Loader.java:1375)
        at org.bytedeco.javacpp.Loader.load(Loader.java:1187)
        at org.bytedeco.javacpp.Loader.load(Loader.java:1163)
        at org.bytedeco.ffmpeg.global.avutil.<clinit>(avutil.java:14)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at org.bytedeco.javacpp.Loader.load(Loader.java:1242)
        at org.bytedeco.javacpp.Loader.load(Loader.java:1187)
        at org.bytedeco.javacpp.Loader.load(Loader.java:1163)
        at org.bytedeco.ffmpeg.avformat.Read_packet_Pointer_BytePointer_int.<clinit>(Read_packet_Pointer_BytePointer_int.java:45)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)

and a bit farther down:

        Caused by:
        java.lang.UnsatisfiedLinkError: <$home>/.javacpp/cache/ffmpeg-5.0-1.5.7-20220124.104125-151-macosx-x86_64.jar/org/bytedeco/ffmpeg/macosx-x86_64/libjniavutil.dylib: dlopen(<$home>/.javacpp/cache/ffmpeg-5.0-1.5.7-20220124.104125-151-macosx-x86_64.jar/org/bytedeco/ffmpeg/macosx-x86_64/libjniavutil.dylib, 0x0001): Library not loaded: /usr/local/opt/libx11/lib/libX11.6.dylib
          Referenced from: <$home>/.javacpp/cache/ffmpeg-5.0-1.5.7-20220124.104125-151-macosx-x86_64.jar/org/bytedeco/ffmpeg/macosx-x86_64/libavutil.57.dylib
          Reason: tried: '/usr/local/opt/libx11/lib/libX11.6.dylib' (no such file), '/usr/lib/libX11.6.dylib' (no such file)
            at java.lang.ClassLoader$NativeLibrary.load(Native Method)
            at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1950)
            at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1832)
            at java.lang.Runtime.load0(Runtime.java:811)
            at java.lang.System.load(System.java:1088)
            at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1720)

How are the macos build built on sonotype? Is there any reason it would link with X11?

**Comment by saudet** [comment]
It looks like libxcb gets enabled on Mac by default now, for some reason.
Let's try to disable it explicitly by appending `--disable-libxcb` to this line:
https://github.com/bytedeco/javacpp-presets/blob/master/ffmpeg/cppbuild.sh#L1590

**Comment by jfehr67** [comment]
Weird. Wonder why its not enabled on my mac. (I just pulled master.) Also tried it on an M1 mac, and also not enabled there. (Or at least, in both cases I don't get that error at runtime.)

Did you want me to put in a PR? I can, just not sure how to test the change.

**Comment by saudet** [comment]
Yes, please open a pull request. When libxcb is disabled, it won't show up in the build log.

**Comment by jfehr67** [comment]
https://github.com/bytedeco/javacpp-presets/pull/1137

Any easy way for me to check if it works? (Not sure where the build log is at.)

**Comment by saudet** [comment]
It's going to show up here: https://github.com/bytedeco/javacpp-presets/runs/4929898188

**Comment by jfehr67** [comment]
I don't see it on any of the mac builds via that link. Should be good to go!

**Comment by saudet** [comment]
Thanks for reporting and thanks for the fix!

**Comment by jfehr67** [comment]
I pulled a fresh snapshot this morning, and got the same error. Took a look at dependencies, and this is what it showed:

{noformat}
(base) Johns-iMac:t john.fehr$ otool -L ~/.javacpp/cache/ffmpeg-5.0-1.5.7-SNAPSHOT-macosx-x86_64.jar/org/bytedeco/ffmpeg/macosx-x86_64/libjniavutil.dylib
/Volumes/TB3/Users/john.fehr/.javacpp/cache/ffmpeg-5.0-1.5.7-SNAPSHOT-macosx-x86_64.jar/org/bytedeco/ffmpeg/macosx-x86_64/libjniavutil.dylib:
	libjniavutil.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libavutil.57.dylib (compatibility version 57.0.0, current version 57.17.100)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 902.1.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1281.100.1)
(base) Johns-iMac:t john.fehr$ otool -L ~/.javacpp/cache/ffmpeg-5.0-1.5.7-SNAPSHOT-macosx-x86_64.jar/org/bytedeco/ffmpeg/macosx-x86_64/libavutil.57.dylib 
/Volumes/TB3/Users/john.fehr/.javacpp/cache/ffmpeg-5.0-1.5.7-SNAPSHOT-macosx-x86_64.jar/org/bytedeco/ffmpeg/macosx-x86_64/libavutil.57.dylib:
	@rpath/libavutil.57.dylib (compatibility version 57.0.0, current version 57.17.100)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1281.100.1)
	/System/Library/Frameworks/VideoToolbox.framework/Versions/A/VideoToolbox (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/opt/libx11/lib/libX11.6.dylib (compatibility version 11.0.0, current version 11.0.0)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1677.104.0)
	/System/Library/Frameworks/CoreMedia.framework/Versions/A/CoreMedia (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/CoreVideo.framework/Versions/A/CoreVideo (compatibility version 1.2.0, current version 1.5.0)
	/System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices (compatibility version 1.0.0, current version 1069.24.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 902.1.0)
(base) Johns-iMac:t john.fehr$ 
{noformat}

Not sure why I didn't see this  yesterday, maybe I had my own build cached. (Cleared all my caches before doing a fresh build of my own code today.) Should i open a new issue for this or should I reopen this?

**Comment by saudet** [comment]
No need to open new issues when they are about the same thing, just reopen them, yes.

It looks like it links with X11 by default, this is weird. Anyway, I've added another flag to disable that in commit https://github.com/bytedeco/javacpp-presets/commit/62cf8bc07ca6eda02343b0c2be4aa8731a83128a and I'm not seeing any traces of X11 in the latest snapshots. Let me know if you're still having problems though, thanks!

**Comment by jfehr67** [comment]
Awesome. That fixed it! Thanks!

**Comment by jfehr67** [comment]
I'm getting the same issue on linux. Sorry for creating a new issue, thought a different platform would mean a different issue, but I suppose there are two macos platforms and you wanted to keep both on this issue so I should have added it here.

Anyway, same issue on linux. However, in the cppbuild.sh file I see '--enable-libxcb' on 3 of the 5 linux builds. Previous versions didn't link to X11, so I'm not sure if its ok to remove/disable libxcb and X11 for all linux platforms or not.
