### ISSUE TITLE
No platform/gpl ffmpeg-5.0-1.5.7-SNAPSHOT-macosx-arm64-gpl.jar being built

### ISSUE THREAD

**Issue by jfehr67** [bytedeco/javacpp-presets#1139]
The macosx x86_64 version of platform and platform/gpl of ffmpeg are being built, but only the platform version of macosx arm64 is being built, no platform/gpl version.

**Comment by saudet** [comment]
Oops, looks like I forgot to add it in platform/gpl/pom like I did with platform/pom.xml though. If you don't send a pull request, I'll do that tomorrow!

**Comment by jfehr67** [comment]
https://github.com/bytedeco/javacpp-presets/pull/1140

BOOM

**Comment by saudet** [comment]
Thanks for the fix!
