### ISSUE TITLE
Adding bindings for IUP, CD and IM library

### ISSUE THREAD

**Issue by 3oheicrw** [bytedeco/javacpp-presets#1144]
https://sourceforge.net/projects/iup/

https://sourceforge.net/projects/canvasdraw/

https://sourceforge.net/projects/imtoolkit/

Please consider. Thanks.

**Comment by 3oheicrw** [comment]
@saudet Please consider adding bindings for them. I could create bindings using Swig and it works but it's not pleasant to use at all. I searching a lot in the internet and finally find this project.

**Comment by saudet** [comment]
It's also possible to create bindings with JavaCPP:
https://github.com/bytedeco/javacpp-presets/wiki/Create-New-Presets
