### ISSUE TITLE
[PyTorch] not found pytorch-platform-gpu in snapshot server

### ISSUE THREAD

**Issue by tgg9527** [bytedeco/javacpp-presets#1147]
Hi, I have used the 1.10.0 PyTorch binding with GPU support, but I found that this version is not on the snapshot server now, do you have a plan about when the new GPU-supported version will release?

thank you!

**Comment by saudet** [comment]
Builds for PyTorch 1.10.2 have just been released:
https://repo1.maven.org/maven2/org/bytedeco/pytorch/1.10.2-1.5.7/
Enjoy!
