### ISSUE TITLE
Leptonica build problem

### ISSUE THREAD

**Issue by mkolod** [bytedeco/javacpp-presets#115]
Hi,

I tried running the Leptonica demo in javacpp-presets/leptonica as follows:
```
mvn package exec:java -Dexec.mainClass=SudokuTest
```
Unfortunately, I got the following error:
```
[ERROR] Failed to execute goal org.bytedeco:javacpp:1.2-SNAPSHOT:build (generate-sources) on project leptonica: Failed to execute JavaCPP Builder: Could not parse "leptonica/alltypes.h": File does not exist -> [Help 1]
```
I then thought that it might be necessary to first run cppbuild in the root directory, so I did. Unfortunately, that step was also unsuccessful - see
[cppbuild.txt](https://github.com/bytedeco/javacpp-presets/files/38145/cppbuild.txt)

I'm not sure what to do next. I am looking forward to building Leptonica to use it on its own, and also because it's a dependency for Tesseract, which I'm also hoping to use via javacpp, instead of writing my own JNI bindings ;)

I also tried importing built jars directly, instead of building from source. I'm using sbt, so the import looks as follows in build.sbt:
```scala
classpathTypes += "maven-plugin"

libraryDependencies ++= Seq(
  "org.bytedeco" % "javacpp" % "1.1",
  "org.bytedeco.javacpp-presets" % "leptonica" % "1.72-1.1",
  "org.bytedeco.javacpp-presets" % "tesseract" % "3.04-1.1"
)
```
Unfortunately, running either the Tesseract or the Leptonica sample results in an UnsatisfiedLinkError being thrown:
```
java.lang.UnsatisfiedLinkError: no jnilept in java.library.path
```
I would really appreciate your help. I checked out StackOverflow posts regarding some of these issues, including the [UnsatisfiedLinkError for jnilept](http://stackoverflow.com/questions/30925074/javacpp-liblept-4-dylib-library-not-loaded), but that didn't really resolve the above issue. 

Also, I tried the above on both OS X (Yosemite) and Ubuntu 15.10 - same issues in both cases.

Thanks in advance for looking into this!

Marek

**Comment by saudet** [comment]
Try to use version 1.1, instead of 1.2-SNAPSHOT, then you won't need to
build everything.

**Comment by mkolod** [comment]
Great, thank you, I'll try it right away!

**Comment by mkolod** [comment]
Actually I used 1.1 as the above sbt example shows.

**Comment by saudet** [comment]
We need to add the platform dependent native artifacts too.

**Comment by mkolod** [comment]
Ah, good point, I just saw those other artifacts on Maven Central just now. I'll give them a try. Maybe I'll submit a PR to the documentation (at least I missed that aspect while reading through the Github readmes).

**Comment by mkolod** [comment]
OK, looks like the following set seems to be working (on OS X, see below).
Would it help to put something along these lines in the documentation?
In hindsight, it seems obvious that I should have done it, but I was following
the readme verbatim and I think I didn't see it spelled out there.


lazy val javaCppVer = "1.1"
lazy val tessVer = s"3.04-$javaCppVer"
lazy val leptoVer = s"1.72-$javaCppVer"
lazy val os = "macosx-x86_64"

libraryDependencies ++= Seq(
  "org.bytedeco"                            % "javacpp"         % javaCppVer,
  "org.bytedeco.javacpp-presets"  %  "tesseract"      % tessVer,
  "org.bytedeco.javacpp-presets"  %  "tesseract"      % tessVer classifier os,
  "org.bytedeco.javacpp-presets"  %  "leptonica"      % leptoVer,
  "org.bytedeco.javacpp-presets"  %  "leptonica"      % leptoVer classifier os
)

**Comment by saudet** [comment]
But it is very clearly spelled out in bold here:
https://github.com/bytedeco/javacpp-presets/#downloads
If you would like to add a couple more lines to spell this out even more clearly, that would be great. Please send a pull request!

**Comment by mkolod** [comment]
OK sorry, I must have missed it ther.

**Comment by saudet** [comment]
But you're right, we could make it more explicit by adding the revelant line to the sample config for sbt.
