### ISSUE TITLE
DepthAi: Access to NN FP16 output layer causes JVM dump

### ISSUE THREAD

**Issue by ecmnet** [bytedeco/javacpp-presets#1155]
Running a neural network via Java on DepthAI works fine as long as I do not try to access FP16 data. 

Example

`NNData seg = nn.getNNData();
FloatBuffer output_0 = seg.getLayerFp16("output_0");
float value = output_0.get();`

Any access to the data of this Buffer fails and causes a dump of the JVM. The limit and capacity of this buffer seems to be correct
with 10752 bytes (shown as DirectByteBuffer) as I have 2688 FP16 values (2688*4) in the output layer.

Could it be that FP16 -> Java Float is not supported properly?

**Comment by saudet** [comment]
Could you try to use `FloatPointer` instead, something like ` seg.getLayerFp16(new BytePointer("output_0")).get(0)`?

**Comment by ecmnet** [comment]
@saudet Perfect, this seems to work. What's the background here?

**Comment by saudet** [comment]
JavaCPP doesn't allocate memory for new `Buffer` objects returned, and with the `@StdVector` annotation, the memory allocated gets released on return of the function. We could allocate memory with `ByteBuffer.allocateDirect()`, but then there isn't any way to deallocate that memory. We could also use Java arrays, but... I don't think there's a good way to go about this. `Pointer` is there for cases like that anyway and it works well enough.

**Comment by ecmnet** [comment]
Thanks for your explanation. I‘ll close the issue.

**Comment by saudet** [comment]
I've improved somewhat the mappings for this in commit https://github.com/bytedeco/javacpp-presets/commit/0dca099687141b8352250a61b722680e2b352a33 such that we now get a `float[]` from `getLayerFp16(String)`. This way we don't have any allocation issues since everything is on the Java heap. Please give it a try with the snapshots: http://bytedeco.org/builds/
