### ISSUE TITLE
Missing bindings in org.bytedeco.pytorch.IValue

### ISSUE THREAD

**Issue by hal-314** [bytedeco/javacpp-presets#1156]
Hi again,

I notice that there are some methods missing for `IValue` ([javadoc](http://bytedeco.org/javacpp-presets/pytorch/apidocs/org/bytedeco/pytorch/IValue.html)) when comparing to [C++ API](https://pytorch.org/cppdocs/api/structc10_1_1_i_value.html#struct-ivalue). For example, several `toX` methods like `toTuple` are missing, although their equivalent `isX` exist in the JavaCPP binding.  

Torch presets seems to include [`ivalue.h` C++ header](https://github.com/bytedeco/javacpp-presets/blob/master/pytorch/src/main/java/org/bytedeco/pytorch/presets/torch.java). So, I was wondering if something is missing or JavaCPP doesn't support `ivalue::Tuple`. 

### Use case ###
A model that return a couple of tensors like:
```python
def forward(self, x) -> typing.Tuple[torch.Tensor, torch.Tensor]:
      ....
      return tensor1, tensor2
```

An easy workaround on Python side is to annotate that the method returns a list of tensors like:
```python
def forward(self, x) -> typing.List[torch.Tensor]:
      ....
      return [tensor1, tensor2]
```
And update the docs to clearly state that it always returns 2 tensors. The main limitation is that if you want to use this model some other place, you can do `tensor1, tensor2 = my_workaround_model(x)` without a warning.

**Comment by saudet** [comment]
PyTorch uses a lot of C++ templates, so, yes not everything is there. In this case, toTuple() doesn't return Tuple, but `c10::intrusive_ptr<ivalue::Tuple>`. I'm sure there's some way to map this, but someone will need to look into it. When at least a couple of other people start asking about this, I'll consider looking into it myself, or maybe @HGuillemet.

BTW, it looks like in the next release we're going to get a toTupleRef() that does return Tuple, see https://github.com/pytorch/pytorch/commit/d9bac7c316a2b94006b2fb5041c1c67c98b848b8.

**Comment by saudet** [comment]
@hal-314 FYI, I've upgraded the presets to PyTorch 1.11.0 in commit https://github.com/bytedeco/javacpp-presets/commit/e6140a9dfd45b25f2004968f057306909a6cd219, and that comes with a `IValue.toTupleRef()` method. Please give it a try with the snapshots: http://bytedeco.org/builds/ But let me know if this isn't enough for your purposes, thanks!

**Comment by hal-314** [comment]
@saudet Currently, I can't give it a try. However, from the commit code, I think it would be enough. Thanks!
