### ISSUE TITLE
CUDA presents lack backend bindings

### ISSUE THREAD

**Issue by bashimao** [bytedeco/javacpp-presets#1158]
There seems to be an entire set of APIs missing from the CUDA presets.

In particular
```
cudnnBackendCreateDescriptor(...)
cudnnBackendDestroyDescriptor(...)
cudnnBackendExecute(...)
cudnnbBackendFinalize(...)
cudnnBackendGetAttribute(...)
cudnnBackendInitialize(...)
cudnnBackendSetAttribute(...)
```
, as well as all associated data structures (e.g., `cudnnPointwiseMode_t`).

The documentation of these APIs can be found here:
- [Backend API](https://docs.nvidia.com/deeplearning/cudnn/api/index.html#cudnn-backend-api)
- [cudnnBackendCreateDescriptor](https://docs.nvidia.com/deeplearning/cudnn/api/index.html#cudnnBackendCreateDescriptor) and other APIs
- [cudnnPointwiseMode_t](https://docs.nvidia.com/deeplearning/cudnn/api/index.html#cudnnPointwiseMode_t) and other data structures

Having these Java bindings would be really neat.

**Comment by saudet** [comment]
Sure! It's only a matter of including cudnn_backend.h, which I've done in commit https://github.com/bytedeco/javacpp-presets/commit/59a889e8673a22b283533a4e3156638114601232.
Thanks for reporting this issue and please give it a try with the snapshots: http://bytedeco.org/builds/
