### ISSUE TITLE
Issue: missing ./configure file while updating libjpeg-turbo dependency of leptonica from v1.5.3 to >v2.0.4

### ISSUE THREAD

**Issue by vibhasg** [bytedeco/javacpp-presets#1163]
Hi, 

I wanted to rebuild the leptonica preset with the LIBJPEG v2.0.4 or higher. I am currently on a Windows 10 environment.

I tried to change the version here: 
https://github.com/bytedeco/javacpp-presets/blob/78540be41638b6b19bcc12982152d5beba464984/leptonica/cppbuild.sh#L13

and also here: https://github.com/bytedeco/javacpp-presets/blob/78540be41638b6b19bcc12982152d5beba464984/leptonica/cppbuild.sh#L21

However, unlike LIBJPEG v1.5.x, there is no ./configure file in LIBJPEG v2.x. Can someone please help with making the changes to cppbuild.sh script?

**Comment by vibhasg** [comment]
Hi @saudet 
Apologies for the delay. I was able to confirm that the updates you made are indeed working. May I know if and when it is possible to see your changes in master?

**Comment by saudet** [comment]
They already are in master.

**Comment by vibhasg** [comment]
Thanks for that update @saudet ! Do you have a rough timeline on when v1.5.8 will be released?

**Comment by saudet** [comment]
Well, 1.5.7 was just released, so not too soon! You need to tell me about this before making releases, not after. That's why there are snapshots.

**Comment by jd3nn1s** [comment]
I'm curious when there might be a release to resolve this? Thanks.

**Comment by saudet** [comment]
Probably sometime this fall

**Comment by saudet** [comment]
This has been released with version 1.5.8. Enjoy!
