### ISSUE TITLE
Missing bindings in OpenCV (connectedComponentsWithStats)

### ISSUE THREAD

**Issue by jibidus** [bytedeco/javacpp-presets#1173]
There seems to be some missing bindings in the OpenCV preset (`opencv2/imgproc.hpp`), especially this one:

```
int cv::connectedComponentsWithStats(InputArray img_, OutputArray _labels, OutputArray statsv, OutputArray centroids, int connectivity, int ltype, int ccltype)
```

[OpenCV 4.5.5 api documentation](https://docs.opencv.org/4.5.5/d3/dc0/group__imgproc__shape.html#ga107a78bf7cd25dec05fb4dfc5c9e765f)
[OpenCV 4.5.5 hpp](https://github.com/opencv/opencv/blob/4.5.5/modules/imgproc/include/opencv2/imgproc.hpp#L3911)

Note: another function with same name, but without `ccltype` parameter, is already declared.

Let me know if I can help to add this binding (didn't find how to do that, and test it).

**Comment by saudet** [comment]
It seems to be mapped: http://bytedeco.org/javacpp-presets/opencv/apidocs/org/bytedeco/opencv/global/opencv_imgproc.html#connectedComponentsWithStatsWithAlgorithm-org.bytedeco.opencv.opencv_core.Mat-org.bytedeco.opencv.opencv_core.Mat-org.bytedeco.opencv.opencv_core.Mat-org.bytedeco.opencv.opencv_core.Mat-int-int-int-
What's missing from this one?

**Comment by jibidus** [comment]
:+1: You're right, I didn't see these methods with `WithAlgorithm` suffix!

Thanks for the quick answer, I close this issue.
