### ISSUE TITLE
Tesseract versions confusion

### ISSUE THREAD

**Issue by maximumspatium** [bytedeco/javacpp-presets#1176]
Tesseract versions in the Javacpp-presets 1.5.7 seem to be confusing:
the build script says it's `5.1.0` but the tag in the artifacts is `5.0.1`. What's true and what's false?

**Comment by saudet** [comment]
Where??
https://github.com/bytedeco/javacpp-presets/blob/1.5.7/tesseract/cppbuild.sh#L10

**Comment by maximumspatium** [comment]
Oops, sorry! Tesseract version has been recently bumped to 5.1.0.
v1.5.7 contains correct version.
