### ISSUE TITLE
Caused by: java.lang.UnsatisfiedLinkError: org.opencv.core.Mat.n_Mat()J

### ISSUE THREAD

**Issue by zouguoyan000** [bytedeco/javacpp-presets#1183]
when i want to use opencv, the maven dependencies like the following, the error in the title always orrcurs. so it is necessary to use .so papackge when it is in linux system?
 <dependency>
            <groupId>org.bytedeco</groupId>
            <artifactId>opencv</artifactId>
            <version>4.5.5-1.5.7</version>
        </dependency>
        <dependency>
            <groupId>org.bytedeco</groupId>
            <artifactId>opencv</artifactId>
            <version>4.5.5-1.5.7</version>
            <classifier>linux-x86_64</classifier>
        </dependency>
        <dependency>
            <groupId>org.bytedeco</groupId>
            <artifactId>javacv</artifactId>
            <version>1.5.7</version>
            <exclusions>
                <exclusion>
                    <groupId>org.bytedeco.javacpp-presets</groupId>
                    <artifactId>*</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

**Comment by saudet** [comment]
As per the sample pom.xml files, you'll also need either javacv-platform or opencv-platform. If you're trying to reduce the download size, please see https://github.com/bytedeco/javacpp-presets/wiki/Reducing-the-Number-of-Dependencies.
