### ISSUE TITLE
Arm server reports an error 版本1.5.7

### ISSUE THREAD

**Issue by 13633444651** [bytedeco/javacpp-presets#1184]
![image](https://user-images.githubusercontent.com/46671482/171090415-c287558a-ba48-445c-b66f-7d4bf4e6a919.png)

**Comment by saudet** [comment]
Please try again with the snapshots, there might be some bugs that were fixed: http://bytedeco.org/builds/

**Comment by saudet** [comment]
I'm assuming all is working well with 1.5.8-SNAPSHOT, but please let me know if this isn't the case.
