### ISSUE TITLE
Bullet Sources Jars Missing in Latest SNAPSHOT

### ISSUE THREAD

**Issue by calvertdw** [bytedeco/javacpp-presets#1187]
Hi there! We're evaluating the new Bullet snapshot. It looks like the sources JAR are missing from the latest build.

See here, the 20220429.120928-10 build misses the sources:
https://oss.sonatype.org/content/repositories/snapshots/org/bytedeco/bullet/3.24-1.5.8-SNAPSHOT/

Thanks!

**Comment by saudet** [comment]
Done in commit https://github.com/bytedeco/javacpp-presets/commit/489cabfe56e22853423854e280d574a4f1329403! Enjoy
