### ISSUE TITLE
Missing dependencies when switching from DEPTHAI 2.15.4 to 2.16.0

### ISSUE THREAD

**Issue by ecmnet** [bytedeco/javacpp-presets#1190]
Using 1.5.8 snapshot, I receive the following error at runtime when switching DEPTHAI from 2.15.4 to 2.16.0:

Caused by: java.lang.UnsatisfiedLinkError: /Users/ecmnet/.javacpp/cache/opencv-4.6.0-1.5.8-SNAPSHOT-macosx-x86_64.jar/org/bytedeco/opencv/macosx-x86_64/libjniopencv_core.dylib: dlopen(/Users/ecmnet/.javacpp/cache/opencv-4.6.0-1.5.8-SNAPSHOT-macosx-x86_64.jar/org/bytedeco/opencv/macosx-x86_64/libjniopencv_core.dylib, 0x0001): Library not loaded: @rpath/libopencv_imgproc.406.dylib
  Referenced from: /Users/ecmnet/.javacpp/cache/opencv-4.6.0-1.5.8-SNAPSHOT-macosx-x86_64.jar/org/bytedeco/opencv/macosx-x86_64/libjniopencv_core.dylib
  Reason: tried: '/Users/ecmnet/.javacpp/cache/opencv-4.6.0-1.5.8-SNAPSHOT-macosx-x86_64.jar/org/bytedeco/opencv/macosx-x86_64/./libopencv_imgproc.406.dylib' (no such file), '/Users/runner/work/javacpp-presets/javacpp-presets/opencv/cppbuild/macosx-x86_6

Compiling however is fine.

**Comment by saudet** [comment]
It looks like it's trying to load OpenCV 4.5.5. You sure you don't have that anywhere in the your dependencies? It seems like you have JavaCV in your dependencies though, and I hadn't updated this one to OpenCV 4.6.0, so I've just done that in commit https://github.com/bytedeco/javacv/commit/d05adb803610814a7b7ef82e7a73e36c776cf57a. Please try again with the new snapshots.

**Comment by ecmnet** [comment]
I tried again and it worked. Thank you very much. I am closing the issue.
