### ISSUE TITLE
EXCEPTION_ACCESS_VIOLATION using BULLET btMultiBodyDynamicsWorld.stepSimulation

### ISSUE THREAD

**Issue by tvanderhey** [bytedeco/javacpp-presets#1191]
We are using the Bullet Physics Engine with our simulation application. Our application can run with different physics engines by setting a parameter. We have it working with libgdx’s version of Bullet and now would like to get it working with bytedeco’s 1.5.8-SNAPSHOT. However, we are receiving an EXCEPTION_ACCESS_VIOLATION when accessing the method btMultiBodyDynamicsWorld.stepSimulation(timeStep, maxSubSteps, fixedTimeStep). The method works if I call it directly from a program. The issue comes when we call the method from our simulation program which is in a different package.

Below is a partial listing of the class that calls the stepSimulation method. I read some of the other issues where it was recommended to use the Dependencies program to test for missing dependencies so I added that logic and it did not produce an exception so did not bring up the Dependencies program. I also added some System.out.println commands to show it is reading the btMultiBodyDynamicsWorld object.
```java
public class BulletMultiBodyDynamicsWorld
{
   private final btCollisionConfiguration btCollisionConfiguration;
   private final btCollisionDispatcher btCollisionDispatcher;
   private final btBroadphaseInterface btBroadphaseInterface;
   private final btMultiBodyConstraintSolver btMultiBodyConstraintSolver;
   private final btMultiBodyDynamicsWorld btMultiBodyDynamicsWorld;
   private btIDebugDraw btIDebugDraw;
   private final ArrayList<BulletTerrainObject> terrainObjects = new ArrayList<>();
   private final ArrayList<BulletMultiBodyRobot> multiBodyRobots = new ArrayList<>();
   private final btVector3 btGravity = new btVector3();

   public BulletMultiBodyDynamicsWorld()
   {
      btCollisionConfiguration = new btDefaultCollisionConfiguration();
      btCollisionDispatcher = new btCollisionDispatcher(btCollisionConfiguration);
      btBroadphaseInterface = new btDbvtBroadphase();
      btMultiBodyConstraintSolver = new btMultiBodyConstraintSolver();
      btIDebugDraw = null;
      btMultiBodyDynamicsWorld = new btMultiBodyDynamicsWorld(btCollisionDispatcher,
                                                              btBroadphaseInterface,
                                                              btMultiBodyConstraintSolver,
                                                              btCollisionConfiguration);
   }
   public int stepSimulation(float timeStep, int maxSubSteps, float fixedTimeStep) throws IOException, InterruptedException
   {
      Class<?> clazz = org.bytedeco.bullet.BulletDynamics.btDiscreteDynamicsWorld.class;
      try {
          Loader.load(clazz);
      } catch (UnsatisfiedLinkError e) {
          String path = Loader.cacheResource(clazz, "windows-x86_64/jniBulletDynamics.dll").getPath();
          new ProcessBuilder("C:/Users/tvanderhey/Downloads/Dependencies_x64_Release", path).start().waitFor();
      }
      
      System.out.println("timestep: " + timeStep);
      System.out.println("maxSubSteps: " + maxSubSteps);
      System.out.println("fixedTimeStep: " + fixedTimeStep);
      System.out.println("getNumCollisionObjects: " + btMultiBodyDynamicsWorld.getNumCollisionObjects());
      System.out.println("getNumConstraints: " + btMultiBodyDynamicsWorld.getNumConstraints());
      System.out.println("getNumMultibodies: " + btMultiBodyDynamicsWorld.getNumMultibodies());
      System.out.println("getWorldType: " + btMultiBodyDynamicsWorld.getWorldType());
      System.out.println("getApplySpeculativeContactRestitution: " + btMultiBodyDynamicsWorld.getApplySpeculativeContactRestitution());
      System.out.println("getGravity().getZ(): " + btMultiBodyDynamicsWorld.getGravity().getZ());
      System.out.println("getMultiBody(0).getBaseMass(): " + btMultiBodyDynamicsWorld.getMultiBody(0).getBaseMass());

      return btMultiBodyDynamicsWorld.stepSimulation(timeStep, maxSubSteps, fixedTimeStep);
   }
```
…more methods

Output when running the simulation program
timestep: 0.1
maxSubSteps: 1
fixedTimeStep: 0.1
getNumCollisionObjects: 1
getNumConstraints: 0
getNumMultibodies: 1
getWorldType: 2
getApplySpeculativeContactRestitution: false
getGravity().getZ(): -9.81
getMultiBody(0).getBaseMass(): 2.0

 A fatal error has been detected by the Java Runtime Environment:

  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ffd1382c685, pid=40496, tid=42652

 JRE version: OpenJDK Runtime Environment Zulu17.34+19-CA (17.0.3+7) (build 17.0.3+7-LTS)
 Java VM: OpenJDK 64-Bit Server VM Zulu17.34+19-CA (17.0.3+7-LTS, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, windows-amd64)
 Problematic frame:
 C  [jniBulletDynamics.dll+0x15c685]

 No core dump will be written. Minidumps are not enabled by default on client versions of Windows

 An error report file with more information is saved as:
 C:\repos\ByteDeco_Bullet\repository-group\simulation-construction-set-2\scs2-examples\hs_err_pid40496.log

 If you would like to submit a bug report, please visit:
   http://www.azul.com/support/
 The crash happened outside the Java Virtual Machine in native code.
 See problematic frame for where to report the bug.

[hs_err_pid40496.log](https://github.com/bytedeco/javacpp-presets/files/8928217/hs_err_pid40496.log)

**Comment by saudet** [comment]
> siginfo: EXCEPTION_ACCESS_VIOLATION (0xc0000005), reading address 0xffffffffffffffff

Sounds like something isn't getting initialized properly. @mode89 Would you know?

**Comment by mode89** [comment]
> > siginfo: EXCEPTION_ACCESS_VIOLATION (0xc0000005), reading address 0xffffffffffffffff
> 
> Sounds like something isn't getting initialized properly. @mode89 Would you know?

Sorry, don't know anything about configuration of Bullet. Funny thing, I haven't yet had a chance to try these bindings out :)

**Comment by mode89** [comment]
Hi @tvanderhey :)

The log shows that the simulation step runs inside a thread pool worker. Is it a long-running thread? If it is a short-lived thread, could there be a race condition?

**Comment by tvanderhey** [comment]
Thanks for the information. I'll check to see if that is the issue.

**Comment by tvanderhey** [comment]
It looks like to me that part of the issue is that the memory for the btCollisionShapes attached to the btMultiBodyLinkColliders and btRigidBodies is being re-purposed. When the stepSimulation method tries to access the methods for btCollisionShapes, it crashes. I changed the logic to hold pointers in my classes for the btCollisionShapes and that solved some of the problems. Does that sound possible that the memory would be repurposed if I only do btMultiBodyLinkCollider.setCollisionShape(shape) without saving a pointer to the btCollisionShape in my class?

**Comment by saudet** [comment]
Yes, ideally we should keep those in fields, like you did for the rest of the objects. The issue is that the C++ library can't keep a reference to the Java objects, so they can get deallocated prematurely by the GC. Keeping references in fields prevents that from happening.

**Comment by tvanderhey** [comment]
Thanks again for the help.

**Comment by tvanderhey** [comment]
You can close this issue. I have it all working.
