### ISSUE TITLE
Question: Is nvjpeg supported

### ISSUE THREAD

**Issue by ecmnet** [bytedeco/javacpp-presets#1193]
I saw that nvcodec is supported. My question is, whether there is a reason, why nvjpeg is not.

**Comment by saudet** [comment]
No reason other than no one has ever needed it, but contributions are welcome!

**Comment by devjeonghwan** [comment]
Ok, I added `nvjpeg.h` header in cuda preset.

You can check in https://github.com/bytedeco/javacpp-presets/pull/1195

**Comment by ecmnet** [comment]
Thanks a lot - will try it asap.

**Comment by saudet** [comment]
These new wrappers have now been released with version 1.5.8! Enjoy and thanks for the contribution @devjeonghwan
