### ISSUE TITLE
Android specific opencv helper

### ISSUE THREAD

**Issue by lu-zero** [bytedeco/javacpp-presets#12]
The current code works in android but since some optional parts use awt and that triggers lots of misleading warnings and the debugger is set on hold for each awt import.

Probably would be possible either replace the helper with a version w/out the awt code or replace such code with android-specific one (Rect vs Rectangle and such).

**Comment by saudet** [comment]
Hi, it's been a while, but I've finally figured out something nice. Let me know what you think of the latest changes in these commits: https://github.com/bytedeco/javacpp-presets/commit/0574e664e4bc4b1dd907591cc9798ee55ba3b8ef 
https://github.com/bytedeco/javacv/commit/7ee75f80a8ba96b31e079331629fa909e6d44ad7 
Thanks!!

**Comment by lu-zero** [comment]
I had been horribly busy as well =/ I'll try to check if the people using JavaCV can update to this version and try. Thanks a lot!

**Comment by saudet** [comment]
Changes included in the -0.11 release. Check out the details here: http://bytedeco.org/news/2015/04/04/javacv-frame-converters/ Let me know when you have some free time to work on something, thanks!
