### ISSUE TITLE
Is this memory overflow issue in TensorRT? or my mistake?

### ISSUE THREAD

**Issue by devjeonghwan** [bytedeco/javacpp-presets#1206]
Here is my cuda device properties query code.

``` java
this.info = new CudaDeviceInfo();

this.info.id(id);
this.info.properties(new cudaDeviceProp().retainReference());

if ((returnValue = cudaGetDeviceProperties(this.info.properties(), id)) != CUDA_SUCCESS) {
    this.info.properties().deallocate();
    this.info.deallocate();
    throw new CudaException(returnValue);
}
```

and When I called TensorRT API `createInferBuilder` then `this.info.properties()` memory broken.

``` java
System.out.println("Before\t : " + this.info.properties().maxThreadsPerBlock());
this.builder = createInferBuilder(this.logger);
System.out.println("After\t : " + this.info.properties().maxThreadsPerBlock());
```

Output is 

```
Before	 : 1024
I/TensorRTLogger: kINFO, [MemUsageChange] Init CUDA: CPU +451, GPU +0, now: CPU 22085, GPU 1887 (MiB)
I/TensorRTLogger: kINFO, [MemUsageSnapshot] Begin constructing builder kernel library: CPU 22083 MiB, GPU 1887 MiB
I/TensorRTLogger: kINFO, [MemUsageSnapshot] End constructing builder kernel library: CPU 22253 MiB, GPU 1931 MiB
After	 : 32
```

Is this TensorRT problem or mis-usage to JavaCPP?

**Comment by saudet** [comment]
I'm not sure what you're trying to do, but if you want to prevent `new cudaDeviceProp()` from getting garbage collected, you should keep a reference to do it somewhere. If that's impossible, calling `deallocate(false)` also works, but then you'll probably end up with a memory leak.

**Comment by devjeonghwan** [comment]
@saudet As per your advice, kept a reference to the `cudaDeviceProp` instance via field. Then no problem! But before, I had called `retainReference`. Why is it garbage collected?

**Comment by saudet** [comment]
That only does for reference counting such as with PointerScope. It doesn't affect the ReferenceQueue for GC.

**Comment by saudet** [comment]
And conversely, setting the "org.bytedeco.javacpp.nopointergc" system property to "true" only affects the ReferenceQueue for GC, not reference counting with PointerScope.
