### ISSUE TITLE
Pytorch Error When Using concat method

### ISSUE THREAD

**Issue by HichemMaiza** [bytedeco/javacpp-presets#1210]
Hello, 

@saudet thank you for creating this project. I was testing pytorch-presets basic operations until I came across this error. The application crashes when the concatenation operation is used. I may miss something here but the error can be reproduced by calling concat on two tensors.

I'am experimenting with: 

- OS : Windows 10
- Java version: 11.0.16 
- The latest snapshot version of pytorch: 1.12.0-1.5.8-SNAPSHOT  

```java
Tensor a = Tensor.create(1,2,3,4) ;
Tensor b = Tensor.create(5,6,7,8) ;
Tensor c = concat(new TensorArrayRef(a, b)) ;
```

# Error 

`A fatal error has been detected by the Java Runtime Environment:

  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ffd65951903, pid=4624, tid=10632

 JRE version: Java(TM) SE Runtime Environment 18.9 (11.0.16+11) (build 11.0.16+11-LTS-199)
 Java VM: Java HotSpot(TM) 64-Bit Server VM 18.9 (11.0.16+11-LTS-199, mixed mode, tiered, compressed oops, g1 gc, `windows-amd64)`
 Problematic frame:
 C  [torch_cpu.dll+0xb61903]

 No core dump will be written. Minidumps are not enabled by default on client versions of Windows

 An error report file with more information is saved as:
 D:\Myprojets\javatorch-discovery\hs_err_pid4624.log

 If you would like to submit a bug report, please visit:
   https://bugreport.java.com/bugreport/crash.jsp
 The crash happened outside the Java Virtual Machine in native code.
 See problematic frame for where to report the bug.`

**Comment by saudet** [comment]
That constructor only works when the Tensor objects are from an array. For Tensor objects that are unrelated such as in this case, the easiest way to create one is with TensorVector: `concat(new TensorArrayRef(new TensorVector(a, b))`.

**Comment by HichemMaiza** [comment]
Hello @saudet, Thank you for looking at this issue, I appreciate your help. I did a quick test and your solution worked perfectly for one dimensional as well as two dimensional tensors ! 

for future readers, we can use the dimension parameter to choose in which direction we want to do the concatenation. 
```java
concat(new TensorArrayRef(new TensorVector(a, b), 0) // first dimension or x axis 
concat(new TensorArrayRef(new TensorVector(a, b), 1) // second dimension or y axis 
```
