### ISSUE TITLE
How to  debug the javacpp pytorch  batch train  data real value?

### ISSUE THREAD

**Issue by mullerhai** [bytedeco/javacpp-presets#1216]
HI:
   when I debug the pytorch  example SimpleMNIST ,want to watch the real value in Tensor data, only  see its datatype,
![image](https://user-images.githubusercontent.com/6143404/186131826-c858c918-556f-4352-8d64-de7e1f74ebe8.png)
![image](https://user-images.githubusercontent.com/6143404/186131867-3e57ce44-ebce-4101-988e-cb6c60fdd513.png)

**Comment by saudet** [comment]
We can call something like `shiftLeft(cout(), batch.data)` to get its content printed on the console. Is this what you're looking for?

**Comment by mullerhai** [comment]
> We can call something like `shiftLeft(cout(), batch.data())` to get its content printed on the console. Is this what you're looking for?

HI ,just to look the matrix every column each row  number data in console, 
example
```
println(batch.data())

console:
[[ 0.25405225 0.44904745 -1.5468271 -0.835405 0.34003055]
[ 1.9063158 1.1063404 1.2292559 -0.83762854 -0.02943441]
[ 1.0375446 -1.0552472 -1.1881195 -0.3283966 0.812467 ]
[ 0.55426043 -0.4972653 0.6334804 0.262765 0.0152008 ]
[-1.7565544 -0.08327941 0.00738091 1.0632299 1.0563724 ]]



```

**Comment by saudet** [comment]
PyTorch doesn't have a println() function, but it does have shiftLeft() functions that do just that. It's just the name that is a bit weird.

**Comment by mullerhai** [comment]
> PyTorch doesn't have a println() function, but it does have shiftLeft() functions that do just that. It's just the name that is a bit weird.

thanks
