### ISSUE TITLE
build pytorch example project failed

### ISSUE THREAD

**Issue by mullerhai** [bytedeco/javacpp-presets#1218]
HI :
       I  want to build our pytorch  project with run SimpleMNIST.java ,build  three day ,finally meet the last error cannot solve,
the  env
jdk: 11
maven: 3.6.3
os: mac

``
[INFO] Targeting /Users/muller/Downloads/javacpp-presets/pytorch/src/gen/java/org/bytedeco/pytorch/SGD.java
[INFO] Targeting /Users/muller/Downloads/javacpp-presets/pytorch/src/gen/java/org/bytedeco/pytorch/LRScheduler.java
[INFO] Targeting /Users/muller/Downloads/javacpp-presets/pytorch/src/gen/java/org/bytedeco/pytorch/StepLR.java
[INFO] 
[INFO] --- maven-resources-plugin:3.1.0:resources (default-resources) @ pytorch ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/muller/Downloads/javacpp-presets/pytorch/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ pytorch ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 1486 source files to /Users/muller/Downloads/javacpp-presets/pytorch/target/classes
[INFO] /Users/muller/Downloads/javacpp-presets/pytorch/src/gen/java/org/bytedeco/pytorch/RecordFunction.java: Some input files use unchecked or unsafe operations.
[INFO] /Users/muller/Downloads/javacpp-presets/pytorch/src/gen/java/org/bytedeco/pytorch/RecordFunction.java: Recompile with -Xlint:unchecked for details.
[INFO] 
[INFO] --- exec-maven-plugin:3.1.0:java (default-cli) @ pytorch ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  34:09 min
[INFO] Finished at: 2022-08-25T14:08:01+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:3.1.0:java (default-cli) on project pytorch: The parameters 'mainClass' for goal org.codehaus.mojo:exec-maven-plugin:3.1.0:java are missing or invalid -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginParameterException
(base) muller@mullermac pytorch % mvn -version
`

```

**Comment by saudet** [comment]
It looks like your version of Maven needs mainClass to be set on the command line like `-Dexec.mainClass=SimpleClass`.
