### ISSUE TITLE
HI,how to convert normal java Array or ArrayList to Pytorch Tensor or IValue in javacpp

### ISSUE THREAD

**Issue by mullerhai** [bytedeco/javacpp-presets#1220]
HI , I can not find the method  how to convert normal java Array or ArrayList to Pytorch Tensor or IValue in javacpp,for the office pytorch , it has  some convert method like 
```
import org.pytorch.IValue
import org.pytorch.Module
import org.pytorch.Tensor
  val data: Tensor =
    Tensor.fromBlob(
      Array[Int](1), // data
      Array[Long](1, 3, 224, 224) // shape
    )

  val result: IValue = mod.forward(IValue.from(data), IValue.from(3.0));
  val output: Tensor = result.toTensor();
```
 why our javacpp package not have these, how to convert normal java array  or arraylist to javacpp pytorch tensor

thanks

**Comment by saudet** [comment]
If you're looking for the from_blob() factory method, it's available here:
http://bytedeco.org/javacpp-presets/pytorch/apidocs/org/bytedeco/pytorch/global/torch.html#from_blob-org.bytedeco.javacpp.Pointer-org.bytedeco.pytorch.LongArrayRef-org.bytedeco.pytorch.LongArrayRef-org.bytedeco.pytorch.presets.torch.Deleter-org.bytedeco.pytorch.TensorOptions-

However, the methods available here are easier to use:
http://bytedeco.org/javacpp-presets/pytorch/apidocs/org/bytedeco/pytorch/AbstractTensor.html

**Comment by mullerhai** [comment]
> http://bytedeco.org/javacpp-presets/pytorch/apidocs/org/bytedeco/pytorch/AbstractTensor.html

very thanks , I got it,
