### ISSUE TITLE
support h265 over flv?

### ISSUE THREAD

**Issue by nanguantong** [bytedeco/javacpp-presets#1226]
Hi, @saudet
   Could you please  patch https://github.com/kn007/patch/blob/master/ffmpeg-let-rtmp-flv-support-hevc-h265-opus.patch to ffmpeg and build javacpp ffmpeg snapshot version?

**Comment by saudet** [comment]
It looks simple enough, sure. Please open a pull request to that effect!

**Comment by nanguantong** [comment]
@saudet 
https://github.com/bytedeco/javacpp-presets/pull/1228
