### ISSUE TITLE
Unable to run Tesseract sample-usage using Mac M2 processors

### ISSUE THREAD

**Issue by nawaphonOHM** [bytedeco/javacpp-presets#1246]
Hi, I have tried to run tesseract sample usage from the below link, and didn't work. It gave an error `no jnilept in java.library.path:` I only know java couldn't find out jnilept which probaly is c++ lib or something like that but I don't know how to fix it. Could someone please give me a guild. I'm new to using java connected to C++ modules. Thank you

https://github.com/bytedeco/javacpp-presets/tree/master/tesseract#sample-usage

**Comment by saudet** [comment]
Please try with the snapshots: http://bytedeco.org/builds/

**Comment by saudet** [comment]
Duplicate of #1069
