### ISSUE TITLE
Bullet Preset btIDebugDraw lacks no-arg constructor

### ISSUE THREAD

**Issue by calvertdw** [bytedeco/javacpp-presets#1249]
Currently, there is only a constructor that accepts a Pointer, so you have to do `new btIDebugDraw((Pointer) null)`

**Comment by saudet** [comment]
That means it's an abstract class, that's normal. Are you saying it's not supposed to be an abstract class?

**Comment by calvertdw** [comment]
In Bullet, you're expected to instantiate this interface, implementing the methods, and pass it to a World instance. Then it calls back to your implemented methods with information you need to draw the debug geometries into your scene, using whatever graphics API you want.

If this will work just fine with the `(Pointer) null` argument, then that works for me. I didn't know if there was a better way.

I still haven't gotten the debug drawing to work, but I haven't narrowed down the problem yet.

**Comment by saudet** [comment]
Right, so to do that, it needs to be virtualized: 
https://github.com/bytedeco/javacpp/wiki/Mapping-Recipes#dealing-with-abstract-classes-and-virtual-methods
Could you give that a try?

**Comment by saudet** [comment]
@mode89 Thanks for pull request!

@calvertdw Please give it a try with the updated snapshots: http://bytedeco.org/builds/

**Comment by calvertdw** [comment]
Debug drawing is working! Thank you.

https://youtu.be/6LFsytAMIAc
