### ISSUE TITLE
Totally confusing problem on Android with opencv_stab

### ISSUE THREAD

**Issue by TinoGuo** [bytedeco/javacpp-presets#125]
Firstly, I use gradle to import javacv and javacpp-presets, see the bottom
<img width="951" alt="2015-12-10 21 10 27" src="https://cloud.githubusercontent.com/assets/4519784/11716119/7e47df06-9f82-11e5-96ce-b1f9c311d313.png">
Then i write the codes to run, i got an strange problem. I use debug step by step to locate the line of wrong code, I find when i call the method of 'nextFrame' of 'opencv_videostab.TwoPassStabilizer', it got crashing. Also see the bottom.
<img width="705" alt="2015-12-10 21 15 05" src="https://cloud.githubusercontent.com/assets/4519784/11716209/1f6ba962-9f83-11e5-9841-37709c73d4b7.png">
Finally I open the jniDebug at the gradle, I just get the confusing log.You can see the bottom too.
<img width="625" alt="2015-12-10 21 19 22" src="https://cloud.githubusercontent.com/assets/4519784/11716324/edf22478-9f83-11e5-96ec-45bea58d0fdf.png">
<img width="787" alt="2015-12-10 21 19 36" src="https://cloud.githubusercontent.com/assets/4519784/11716330/f6dcb9ae-9f83-11e5-8b1b-411009d3f5c1.png">
<img width="1127" alt="2015-12-10 21 20 32" src="https://cloud.githubusercontent.com/assets/4519784/11716334/feb3a48a-9f83-11e5-857c-d3ff7a8b0dda.png">

I search all the google, but i can't find the solution. It makes me crazy.Did I config the javacpp or  javacv wrong?
Any help would be THX.

**Comment by saudet** [comment]
Does that code work on Linux, Mac, or Windows?

**Comment by TinoGuo** [comment]
@saudet it works on Mac

**Comment by saudet** [comment]
Does it also happen in the emulator or only on your device?

**Comment by TinoGuo** [comment]
@saudet I just use my devices include S5 ,Note3 and Smartisan, get the same log

**Comment by TinoGuo** [comment]
@saudet Besides, I also try to set the hardwareAccelerated=false or allowClearUserData=true, but i seems didn't  work

**Comment by saudet** [comment]
Anyway, could you post a small self-contained code sample that crashes, so that I could try to debug this here? Thanks!

**Comment by TinoGuo** [comment]
@saudet 
<code>
opencv_videostab imageFrameResource = new opencv_videostab.IFrameSource();

opencv_videostab.TwoPassStabilizer twoPassStabilizer = new opencv_videostab.	TwoPassStabilizer();
twoPassStabilizer.setFrameSource(imageFrameResource);

opencv_videostab.MotionEstimatorRansacL2 ransacL2 = new opencv_videostab.MotionEstimatorRansacL2(5);
ransacL2.setRansacParams(ransacL2.ransacParams().size(3).thresh(3.0f).eps(0.5f));
ransacL2.setMinInlierRatio(0.1f);

twoPassStabilizer.setRadius(15);
twoPassStabilizer.setCorrectionForInclusion(false);
twoPassStabilizer.setBorderMode(1);

opencv_features2d.GFTTDetector detector = opencv_features2d.GFTTDetector.create();
opencv_videostab.KeypointBasedMotionEstimator motionEstimator = new opencv_videostab.KeypointBasedMotionEstimator(ransacL2);
motionEstimator.setDetector(detector);
motionEstimator.setOutlierRejector(new opencv_videostab.NullOutlierRejector());

twoPassStabilizer.setMotionStabilizer(new opencv_videostab.GaussianMotionFilter(15, 4f));
twoPassStabilizer.setMotionEstimator(motionEstimator);

opencv_core.Mat mat = twoPassStabilizer.nexFrame();
</code>

Actually I use a subclass extends from the class IFrameSource to implement my custom requirement, but I log the process, it didn't make any error.So u can simply consider these above codes is all.

**Comment by saudet** [comment]
It's not possible to subclass `IFrameSource` with JavaCV 1.1 (see issue bytedeco/javacv#277). Please try again with the latest code including this commit: https://github.com/bytedeco/javacpp-presets/commit/24ee87a49f80a6bf480e780f82c9f97cc9c1d3eb

**Comment by TinoGuo** [comment]
@saudet Ok, it means I should git clone the latest code, and thank u for your great work!
