### ISSUE TITLE
pytorch: how to register hook function

### ISSUE THREAD

**Issue by lzmchina** [bytedeco/javacpp-presets#1251]
hello,I want to know how to register hook function in pytorch?

**Comment by saudet** [comment]
If you have a working example in C++, please provide it. It should be easy to translate it to Java.

**Comment by lzmchina** [comment]
there are some tests about tensor's hooks:
https://github.com/pytorch/pytorch/blob/8abf37d74eac82876f1e2a6626d04ba3b06cd1dd/test/cpp/api/autograd.cpp#L737

**Comment by saudet** [comment]
Ah, I see, that's not currently getting mapped. It looks a bit hard to map that to Java, but I'm sure it can be done if we spend enough on it: https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/core/TensorBase.h#L788

If you would like to give it a try, hacking this with custom Java code seems like the most promising path:
https://github.com/bytedeco/javacpp/wiki/Mapping-Recipes#mapping-a-declaration-to-custom-code

**Comment by HGuillemet** [comment]
`TensorBase.register_hook` has been mapped since 2.0.1.
