### ISSUE TITLE
quick question:Anyone know the right api for Opencv set videocapture resolution?

### ISSUE THREAD

**Issue by RESDXChgfore9hing** [bytedeco/javacpp-presets#1254]
I tried to find around the javadoc couldnt find it.
I think it also need some constant to go along with it.

like
video.set(cv2.CAP_PROP_FRAME_WIDTH, 1280);
    video.set(cv2.CAP_PROP_FRAME_HEIGHT, 720);

but where is the CAP_PROP_FRAME_HEIGHT in the javacpp api?or like a respective version?

**Comment by saudet** [comment]
OpenCV doesn't support that, you'll need to use some other API...

**Comment by saudet** [comment]
For example, if you're trying to do this on Windows, please use videoInput instead:
https://github.com/bytedeco/javacpp-presets/tree/master/videoinput

**Comment by RESDXChgfore9hing** [comment]
it worked.but how do i convert org.bytedeco.javacpp.BytePointer to opencv mat?

is there a way to quickly find the right api?

**Comment by saudet** [comment]
You could use VideoInputFrameGrabber with OpenCVFrameConverter:
http://bytedeco.org/news/2015/04/04/javacv-frame-converters/

**Comment by RESDXChgfore9hing** [comment]
i tried and it kinda doesnt work well with the other api.
The frame.grab(); seems to be limited to a single snapshot. its in a while loop. 

currently its something like>
org.bytedeco.javacv.OpenCVFrameGrabber grabber = org.bytedeco.javacv.OpenCVFrameGrabber.createDefault(0);
        grabber.setFrameRate(15);//doesnt seems to have effect.
        grabber.start();//

while(){
fr=grabber.grab();
......
}

**Comment by RESDXChgfore9hing** [comment]
actually its ok,its my own code that calls to other function that leas to the crash.
