### ISSUE TITLE
Need help ：make the normal pytorch  torch.utils.data.DataLoader  &  torch.utils.data.dataset class  implement in javacpp please 

### ISSUE THREAD

**Issue by mullerhai** [bytedeco/javacpp-presets#1263]
Hi ,
     Great javacpp coder, as we all know ,the normal model service pipeline , we need to load batch etl  model input data, then we can train our model. but now javacpp only supply mnist  dataset  but not supply the normal pytorch  api :torch.utils.data.DataLoader  &  torch.utils.data.dataset class  implement, we can not write user-defined pytorch model dataloader & dataset which extends inherit from  the normal pytorch  torch.utils.data.DataLoader  &  torch.utils.data.dataset api. unless  make  first priority operation to implement them  Please , or the javacpp pytorch will can not use in real business online deploy environment !  it is will only became the toy for  ml beginner or lab . eagerly need  the dataloader and dataset pytorch api in javacpp. 
         Best Regards

**Comment by saudet** [comment]
Duplicate of #1215
