### ISSUE TITLE
DepthAI does not work with 1.5.8

### ISSUE THREAD

**Issue by ecmnet** [bytedeco/javacpp-presets#1266]
Latest release 1.5.8 does not work for DepthAI. Great if DepthAI 2.19.1 could be included into 1.5.9-SNAPSHOT.
Please refer to https://github.com/luxonis/depthai-core/issues/626 for details.

**Comment by saudet** [comment]
Please open a pull request: https://github.com/bytedeco/javacpp-presets/pulls

**Comment by saudet** [comment]
Done in commit https://github.com/bytedeco/javacpp-presets/commit/bfb993988291d3a744c520edbd1163e56ec1ab2e. Enjoy!
