### ISSUE TITLE
shipping pytorch preset error

### ISSUE THREAD

**Issue by oOTWK** [bytedeco/javacpp-presets#1270]
I compiled and packaged pytorch-preset in one machine and shipped the jar files to another machine.
Got an error in the other machine says libjnitorch.so: libmpi.so.20 no such file.
In this machine, I found libmpi.so.40 installed so I created symlink of libmpi.so.20 pointing to libmpi.so.40.

Is there a better way to resolve this problem?
Is there a way to include all dependency shared libraries in jar?

Thank you!

**Comment by saudet** [comment]
The easiest way is to run the build in a Docker container that doesn't
contain any dependencies you do not wish.

**Comment by oOTWK** [comment]
Okay, I will try that. Thank you!

**Comment by saudet** [comment]
Something like this here: https://github.com/bytedeco/javacpp-presets/wiki/Build-Environments#linux-x86-and-x86_64
