### ISSUE TITLE
[PyTorch] Need help with custom operator

### ISSUE THREAD

**Issue by doudouyzgf** [bytedeco/javacpp-presets#1274]
Hi 👋 

In our application, we found that with a custom operator, we can reduce the memory consumption of a PyTorch model a lot. According to the [PyTorch doc](https://pytorch.org/tutorials/advanced/torch_script_custom_ops.html#using-the-torchscript-custom-operator-in-c), a model with custom op can be scripted and loaded. But it requires a specific CMakeLists file and a specific file structure. I wonder how to achieve it in Java. Is it supported in javacpp-presets pytorch? Would appreciate any suggestion and help! Thanks in advance!

**Comment by saudet** [comment]
It should be possible to create a custom Java operator like that, that we can then implement in Java, but it's not something that's currently available. Contributions are welcome though!

**Comment by doudouyzgf** [comment]
Thanks for the prompt response! In our case, we already implemented the custom op in c++ and can generate an .so file. It runs fine in python at training time with something like the following:

```python
import torch
torch.ops.load_library("build/custom_op.so")
```

We then convert the model to a TorchScript model to serve in a non-python env hence are using javacpp-presets :) . Scripting the model in python is not an issue I guess. The challenging part is to load it and run it in jvm.

Would the current release of javacpp-presets pytorch be able to support our use case?

**Comment by saudet** [comment]
What's the equivalent in the C++ API for that load_library()?

**Comment by doudouyzgf** [comment]
According to [PyTorch doc](https://pytorch.org/tutorials/advanced/torch_script_custom_ops.html#using-the-torchscript-custom-operator-in-c) on how to run it in C++, there's no C++ API for load_library. But there needs to be a CMakeLists file and a specific file structure to link the custom op library.

```
cmake_minimum_required(VERSION 3.1 FATAL_ERROR)
project(example_app)

find_package(Torch REQUIRED)

add_subdirectory(warp_perspective) <----------

add_executable(example_app main.cpp)
target_link_libraries(example_app "${TORCH_LIBRARIES}")
target_link_libraries(example_app -Wl,--no-as-needed warp_perspective) <--------- 
target_compile_features(example_app PRIVATE cxx_range_for)
```

Their explanation on linking libraries may be related.

> There is one crucial detail embedded in the above example: The -Wl,--no-as-needed prefix to the warp_perspective link line. **This is required because we will not actually be calling any function from the warp_perspective shared library in our application code. We only need the TORCH_LIBRARY function to run.** Inconveniently, this confuses the linker and makes it think it can just skip linking against the library altogether. On Linux, the -Wl,--no-as-needed flag forces the link to happen (NB: this flag is specific to Linux!). 

Thanks for looking into this issue.

**Comment by saudet** [comment]
Ok, that sounds like you could just call `System.load()` on your library, and it should work.

**Comment by doudouyzgf** [comment]
Cool. Thanks! I'll give it a try and will report back.

**Comment by doudouyzgf** [comment]
I tried the `System.load()` idea, but it throws `UnsatisfiedLinkError`. 

```
java.lang.UnsatisfiedLinkError: {absolute path of custom-op.so}: dlopen({absolute path of custom-op.so}, 0x0001): Library not loaded: @rpath/libtorch_python.dylib
  Referenced from: {absolute path of custom-op.so}
  Reason: tried: '/Users/xxx/opt/anaconda3/lib/libtorch_python.dylib' (no such file), '/Users/xxx/opt/anaconda3/lib/libtorch_python.dylib' (no such file), '/Users/xxx/opt/anaconda3/lib/libtorch_python.dylib' (no such file), '/Users/xxx/opt/anaconda3/lib/libtorch_python.dylib' (no such file), '/Library/Java/JavaVirtualMachines/zulu1.8.0_181.jdk/Contents/Home/jre/lib/server/./libtorch_python.dylib' (no such file), '/Library/Java/JavaVirtualMachines/zulu1.8.0_181.jdk/Contents/Home/jre/lib/server/../libtorch_python.dylib' (no such file), '/Library/Java/JavaVirtualMachines/zulu1.8.0_181.jdk/Contents/Home/bin/./libtorch_python.
```

After I manually find `libtorch_python.dylib` on my machine and call `System.load({absolute path of libtorch_python.dylib})`. It throws another error on `libmkl_intel_lp64.dylib`.  

I wonder if there's any dependency that contains all the needed `.dylib` files. Googled a bit but didn't find a working solution. Below is a list of my current deps. Any suggestions? 

```
implementation "org.bytedeco:pytorch:1.12.1-1.5.8"
implementation "org.bytedeco:pytorch:1.12.1-1.5.8:linux-x86_64"
implementation "org.bytedeco:pytorch:1.12.1-1.5.8:macosx-x86_64"
```

Many thanks!

**Comment by saudet** [comment]
It looks like your library needs a version of PyTorch already installed on your machine. We can use it with JavaCPP as well by setting a system property: https://github.com/bytedeco/javacpp-presets/tree/master/pytorch#documentation

**Comment by doudouyzgf** [comment]
Thanks @saudet ! As long as the so files are built with the same pytorch version as javacpp-presets, it works. Thanks for the great work!
