### ISSUE TITLE
[DepthAI] 2.19.1 not working

### ISSUE THREAD

**Issue by ecmnet** [bytedeco/javacpp-presets#1278]
Just as a notice : 2.17.4 seems to be the last working DepthAI release with javacpp. 2.19.1 gets stuck when polling frames. Callbacks are not triggered at all.

For details refer to https://github.com/luxonis/depthai-core/issues/626

**Comment by saudet** [comment]
So there's something that broke between 2.17.4 and 2.18.0? Let's see, from the list of changes at https://github.com/luxonis/depthai-core/releases/tag/v2.18.0, this one looks like it could cause most problems with Java:
> - Added monitor to DeviceBootloader

Try to disable the monitor thread and see if that fixes anything.

**Comment by saudet** [comment]
Maybe it's been fixed in a more recent version? I've upgraded the presets to 2.21.2 in commit https://github.com/bytedeco/javacpp-presets/commit/9c1f78a2ed1581ae55cff1b74757ebb0528a5eb7.
Please give it a try with the snapshots: http://bytedeco.org/builds/

**Comment by ecmnet** [comment]
Perfect. Thanks! 2.21.2 is working fine.
