### ISSUE TITLE
[pytorch] where is  tensor..new_tensor() and how to use torch.nn.ModuleList in javacpp

### ISSUE THREAD

**Issue by mullerhai** [bytedeco/javacpp-presets#1280]
HI:
        in pytorch python ,I  defined layer  code
```
class FieldAwareLayer(torch.nn.Module):

    def __init__(self, field_dims, embed_dim):
        super().__init__()
        self.num_fields = len(field_dims)
        self.embeddings = torch.nn.ModuleList([      
            torch.nn.Embedding(sum(field_dims), embed_dim) for _ in range(self.num_fields)
        ])   //here

        self.offsets = np.array((0, *np.cumsum(field_dims)[:-1]), dtype=np.long)
        for embedding in self.embeddings:
            torch.nn.init.xavier_uniform_(embedding.weight.data)

    def forward(self, x):
        """
        :param x: Long tensor of size ``(batch_size, num_fields)``
        """
        x = x + x.new_tensor(self.offsets).unsqueeze(0)     ///here 
        xs = [self.embeddings[i](x) for i in range(self.num_fields)]
        ix = list()
        for i in range(self.num_fields - 1):
            for j in range(i + 1, self.num_fields):
                ix.append(xs[j][:, i] * xs[i][:, j])
        ix = torch.stack(ix, dim=1)
        return ix


```

when I recode this layer in pytorch ,I can not found   tensor..new_tensor() method , and ModuleList the use style not same as  python, I don't know  how to do ,need help

**Comment by saudet** [comment]
You should look at examples using the C++ API, not the Python API. We can probably clone a Tensor using the copy constructor: http://bytedeco.org/javacpp-presets/pytorch/apidocs/org/bytedeco/pytorch/Tensor.html#Tensor-org.bytedeco.pytorch.Tensor-

And it looks like we can call ModuleList.insert() to add modules like that to a list:
http://bytedeco.org/javacpp-presets/pytorch/apidocs/org/bytedeco/pytorch/ModuleListImpl.html#insert-long-org.bytedeco.pytorch.Module-
