### ISSUE TITLE
[pytorch]  how to select some dimesion  data of the tensor 

### ISSUE THREAD

**Issue by mullerhai** [bytedeco/javacpp-presets#1281]
HI: 
       In Pytorch ,for the pytorch tensor ,we can easy select demesion data of tensor ,
like 
```

tensor = Torch.randn(28,32,40)

select_tensor = tensor[:, 10:-1, :]

```
but not found in javacpp pytorch ,how to do like this? thanks

**Comment by saudet** [comment]
It looks like that's what the index_select() function is for:
https://pytorch.org/docs/stable/generated/torch.index_select.html

**Comment by mullerhai** [comment]
> It looks like that's what the index() function is for: https://pytorch.org/cppdocs/notes/tensor_indexing.html

thank ,I use the index api , it can  select the data ,but  I not found how to select the dim

···

    val tensor = torch.randn(34, 30,28,40)
    val slice =new Slice(new LongOptional(1),new LongOptional(20),new LongOptional(2))
    val indexSlice = new TensorIndex(slice)
    val indexSliceArrayRef = new  TensorIndexArrayRef(indexSlice)
    val sliceTensor = tensor.index(indexSliceArrayRef).index(indexSliceArrayRef)

···

console
sliceTensor 19，30,28,40

**Comment by mullerhai** [comment]
now I found  use   [TensorIndexVector]  class  can  select dim, thanks
