### ISSUE TITLE
No AV_CHANNEL_LAYOUT_STEREO in java lib

### ISSUE THREAD

**Issue by rantianhua** [bytedeco/javacpp-presets#1286]
In sample [muxing.c](http://ffmpeg.org/doxygen/5.1/muxing_8c-example.html), [AV_CHANNEL_LAYOUT_STEREO](http://ffmpeg.org/doxygen/5.1/group__lavu__audio.html#ga59db80472380a3c66c52f2296232244d) is used. But I cannot find the definition in java lib.

**Comment by saudet** [comment]
We'd have to map them, which shouldn't be too hard actually. Would you like to give it a try?

**Comment by saudet** [comment]
Done in commit https://github.com/bytedeco/javacpp-presets/commit/bd67bb63b35b3560ed5d31a89ce91368cb655c7b. Please give it a try with the snapshots: http://bytedeco.org/builds/

**Comment by rantianhua** [comment]
Thanks so much, I'm still studying JavaCPP, you've done the job.

**Comment by saudet** [comment]
Fix released with version 1.5.9! Thanks for reporting
