### ISSUE TITLE
[pytorch] how to release gpu memory?

### ISSUE THREAD

**Issue by lzmchina** [bytedeco/javacpp-presets#1288]
I have a model training in a GPU, but I find it's difficult to release gpu memory.
```java
try (PointerScope scope = new PointerScope()) {
gradient = this.autoChangeTensorDevice(gradient);
Tensor output = this.model.forward(Xinputs);
this.optimizer.zero_grad();
output.backward(gradient, null, false, null);
this.optimizer.step();
scope.deallocate();
 }
```
Although I call `scope.deallocate();`, the GPU memory is still growing and finally it's out of memory.
So how can I release GPU memory?

**Comment by saudet** [comment]
There must be some Tensor objects somewhere that are not getting deallocated. Try with a very small model, it should help you figure out where the leak is happening.

**Comment by HGuillemet** [comment]
Do you still get the out of memory without `scope.deallocate()` ?
The automatic closing of the scope at the end of the block should be enough.
