### ISSUE TITLE
[ffmpeg] Linux natives use an old version of VAAPI

### ISSUE THREAD

**Issue by silenium-dev** [bytedeco/javacpp-presets#1289]
When using VAAPI with the ffmpeg libraries, opening a VAAPI hwdevice fails because the old version of VAAPI can't call the new vendor libraries on the system.

Error messages:
```
libva info: VA-API version 0.40.0
libva info: va_getDriverName() returns 0
libva info: User requested driver 'iHD'
libva info: Trying to open /usr/lib64/dri/iHD_drv_video.so
libva error: /usr/lib64/dri/iHD_drv_video.so has no function __vaDriverInit_0_32
libva info: va_openDriver() returns -1
[AVHWDeviceContext @ 0x7f937c7662c0] Failed to initialise VAAPI connection: -1 (unknown libva error).
```

Currently used version is 0.40.0, but the most recent version is 1.16.0

**Comment by silenium-dev** [comment]
This issue is likely caused by the outdated OS used for building: CentOS 6, which is EOL since November 2020

**Comment by saudet** [comment]
It's actually CentOS 7, which has not reached EOL. Until we figure out if there's something we can do for that, you'll need to build from source.

**Comment by silenium-dev** [comment]
If I read the install-travis.sh script correctly, it uses CentOS 6 for everything except hyperscan, tensorflow, ngraph, qt and skia

**Comment by silenium-dev** [comment]
I would like to help, but I don't know how to test the CI pipelines, as it requires Travis CI which either costs money or takes forever to complete, as this repo has a lot of jobs. I'm open for any ideas on this

**Comment by saudet** [comment]
This scripts are not used. Use GitHub Actions.

**Comment by silenium-dev** [comment]
Ah, my bad, thank you, this'll make things much easier

**Comment by silenium-dev** [comment]
I've managed to get the Linux x86_64 build to work with Fedora 37 instead of CentOS 7, so the libraries are now up-to-date. I've chosen Fedora, because CentOS Stream 9, the latest CentOS release available, doesn't have the latest VAAPI version in its repos.
It'll be impossible to update the 32bit build, as neither CentOS 8, Stream 9 nor Fedora 37 provide 32bit container images.
But a part of the other builds, which I haven't modified, are failing.
My fork: https://github.com/silenium-dev/javacpp-presets
