### ISSUE TITLE
torch.cat is missing since update to PyTorch 1.13

### ISSUE THREAD

**Issue by sbrunk** [bytedeco/javacpp-presets#1293]
Before the update to PyTorch 1.13 in b2b8eb93, the PyTorch bindings included the following functions

```java
@Namespace("at") public static native @ByVal Tensor cat(@ByVal TensorArrayRef tensors, @Cast("int64_t") long dim/*=0*/);
@Namespace("at") public static native @ByVal Tensor cat(@ByVal TensorArrayRef tensors);
```

as well as a few variants like `cat_out`, all coming from `ATen/ops/cat.h`, which has the following diff:

```diff
-TORCH_API inline at::Tensor cat(at::TensorList tensors, int64_t dim=0) {
+inline at::Tensor cat(const at::ITensorListRef & tensors, int64_t dim=0) {
    return at::_ops::cat::call(tensors, dim);
}
```

So the type changed from `TensorList` to `ITensorListRef` which seems to be skipped in the mappings:

https://github.com/bytedeco/javacpp-presets/blob/c0d15db924e1c10de7e6999ac2d105ff479e5754/pytorch/src/main/java/org/bytedeco/pytorch/presets/torch.java#L2369

Could this be the reason why `cat` is not mapped anymore?

**Comment by saudet** [comment]
Good catch! Done in commit https://github.com/bytedeco/javacpp-presets/commit/10ddc85ac667da74ec96b364605d48b07c276ea7. Thanks

**Comment by sbrunk** [comment]
Thanks for adding! Could you perhaps re-trigger the CI? The windows build timed out and I think that prevented publishing the snapshots.

**Comment by sbrunk** [comment]
Works like a charm with the new snapshot. :)
```scala
val t = torch.Tensor(Seq(1,2,3))                                                                                                                                                                                                 
// t: Tensor[Int32] = dtype=int32, shape=[3], device=CPU 
// [1, 2, 3]
torch.cat(Seq(t,t))
// res0: Tensor[Int32] = dtype=int32, shape=[6], device=CPU 
// [1, 2, 3, 1, 2, 3]
```
So I think we can close this.
