### ISSUE TITLE
libuvc presets

### ISSUE THREAD

**Issue by lobsteroh** [bytedeco/javacpp-presets#130]
as i have managed to work through the tutorials (with a lot of @saudet's help), i am attempting to create a new javacpp module for wrapping **libuvc**, which should be a useful addition to the bunch, given the AVMedia focus of several other wrapped libs.

so I am starting with the cppbuild.sh file and i manage to download the zipped lib (at least for unix/macosx as a start) and i unzip to the cppbuild directory.

the problem i am running into is in line 42 ...
`./configure --prefix=.. --static`
which throws 
`../cppbuild.sh: line 42: ./configure: No such file or directory`
I believe that this is where I control the cmake by calling a script, like the zlib example seems to call MakeFile (?). I assume this is where I set the gcc and stuff. in my case, libuvc does not have a Makefile or Makefile.in and i suspect this is the reason why it fails with the missing file error. It instead has a libuvcConfig.cmake.in file. Is this what i need to call here? how far off am i with my understanding of the process?

the compile for the library itself would look then straight forward with 
`mkdir build`
`cd build`
`cmake ..`
`make && sudo make install`

any suggestions on how to properly complete the cppbuild.sh file is greatly welcome. am eager to move past this stage so i can get to the meat of the exercise. be well all, merry xmas, and party on ...

**Comment by saudet** [comment]
Well, you've followed the instructions here:
https://github.com/bytedeco/javacpp-presets/wiki/Create-New-Presets
So, start by modifying the `cppbuild.sh` file to whatever is needed to build libuvc. If you're having problems with that, you should contact the authors of that project. It's not something I can help you with.

**Comment by lobsteroh** [comment]
yes, i did work through the create new presets page and i am further along in the libuvc specific project info than the javacpp side. i am managing to get the lib code downloaded and unzipped. what i am hoping to get more info on is what the role of 
`./configure --prefix=.. --static` in the sample buildcpp.sh script is. in the zlib example it appears to call MakeFile. is this correct? the info on the page was not sufficient for me to judge ghe exact purpose. once i know what this line is supposed to do, then i have a better idea about what i need to make happen for the libuvc. thanks a major stack

**Comment by saudet** [comment]
It's just a standard command to get the library installed in the parent directory, that's all.
