### ISSUE TITLE
[libffi] remove constant global.ffi.FFI_DEFAUL_ABI and friends and point to platform-specific preset.ffi.FFI_DEFAULT_ABI

### ISSUE THREAD

**Issue by drcicero** [bytedeco/javacpp-presets#1315]
Hi, I am using `"org.bytedeco" % "libffi-platform" % "3.4.4-1.5.8"` (via Scala) on Linux.

I think the enum values:
https://github.com/bytedeco/javacpp-presets/blob/86a78a6bca5cadc01d33933ce7a77fa6a29f1219/libffi/src/gen/java/org/bytedeco/libffi/global/ffi.java#L85-L103 should be removed, as there platform specific, e.g., the comments still show that in C they were platform-specifically defined via `#ifdef`.

It seems the correct way to go is to use the already defined `presets.ffi.FFI_DEFAULT_ABI()` methods and friends, which are defined as native and supplied from somewhere else:
https://github.com/bytedeco/javacpp-presets/blob/86a78a6bca5cadc01d33933ce7a77fa6a29f1219/libffi/src/main/java/org/bytedeco/libffi/presets/ffi.java#L85-L103
I'm not sure where the native things get their value from, but those have the right value for me.

(I noticed this, because in the current state they are easy to confuse, e.g, when your call the method `FFI_DEFAULT_ABI()` you get the right value, but when you access the field `FFI_DEFAULT_ABI` you get the wrong value, and an error later when you try to pass it to prepare. They are even easier to confuse in Scala, where syntactic sugar often allows one to shorten `x.f()` to `x.f`.)

**Comment by saudet** [comment]
We can probably get that done with a couple of Info.skip.
Please open a pull request to that effect, contributions are welcome!

**Comment by drcicero** [comment]
Instead of skipping lines by regex i would prefer to skip these by variable name; however it seems that's only possible with fields/methods; not enum fields, is it?

**Comment by saudet** [comment]
I don't think it's possible to skip individual enumerators at the moment, but it should be possible to skip whole enumerations. If you've tried something specific that doesn't work, please show me what you've tried exactly.

**Comment by saudet** [comment]
Fix released with JavaCPP 1.5.9! Thanks for the contribution
