### ISSUE TITLE
OpenCV memory.hpp:54: error: (-217:Gpu API call) the provided PTX was compiled with an unsupported toolchain. in function 'ManagedPtr'

### ISSUE THREAD

**Issue by campin11** [bytedeco/javacpp-presets#1317]
machine nvidia-smi
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 515.86.01    Driver Version: 515.86.01    CUDA Version: 11.7     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:07:00.0  On |                  N/A |
|  5%   38C    P8     1W /  38W |    105MiB /  2048MiB |      5%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      1884      G   /usr/lib/xorg/Xorg                 75MiB |
|    0   N/A  N/A      2451      G   /usr/bin/gnome-shell               17MiB |
|    0   N/A  N/A      2815      G   ...mviewer/tv_bin/TeamViewer        4MiB |
|    0   N/A  N/A      5505      G   ...RendererForSitePerProcess        0MiB |
+-----------------------------------------------------------------------------+
```

current sbt looks like:  
```
  val javacppVersion = "1.5.8"
  val betterMonadicFor = "0.3.1"
  val opencv = "4.6.0"
  val opencvPlatform = s"4.6.0-$javacppVersion"
  val cudaPlatform = s"11.8-8.6-$javacppVersion"

  .settings(libraryDependencies += "org.bytedeco" % "javacpp" % Project.javacppVersion classifier Project.cpuPlatform)
  .settings(libraryDependencies += "org.bytedeco" % "javacv" % Project.javacppVersion)
  .settings(libraryDependencies += "org.bytedeco" % "ffmpeg-platform" % Project.ffmpegPlatform)
  .settings(libraryDependencies += "org.bytedeco" % "opencv-platform-gpu" % Project.opencvPlatform)
  .settings(libraryDependencies += "org.bytedeco" % "cuda-platform" % Project.cudaPlatform)
  .settings(libraryDependencies += "org.bytedeco" % "cuda-platform-redist" % Project.cudaPlatform)
```

opencv BuildInformation
```
  NVIDIA CUDA:                   YES (ver 11.0, CUFFT CUBLAS)
    NVIDIA GPU arch:             35
    NVIDIA PTX archs:            35

  cuDNN:                         YES (ver 8.0)
  
```
  when using YOLO darknet with cuda , it throws and error as following
  java.lang.RuntimeException: OpenCV(4.6.0) /__w/javacpp-presets/javacpp-presets/opencv/cppbuild/linux-x86_64-gpu/opencv-`4.6.0/modules/dnn/src/cuda4dnn/csl/memory.hpp:54: error: (-217:Gpu API call) the provided PTX was compiled with an unsupported toolchain. in function 'ManagedPtr'`
  
By looking through these setups, it seems like my machine's Cuda version is not the one used in the dependencies. but looking at the previously mentioned issues [#923](https://github.com/bytedeco/javacpp-presets/issues/923#issuecomment-674318583) it seems like it doesn't matter if i have the right cuda version as long as I import cuda-platform-redist to the stack.
but I'm still hitting the error above, I doubt if I understand the concept correctly. Please advice. thank you.

**Comment by saudet** [comment]
Updating your driver to the latest version available from NIVIDIA should fix that.

**Comment by campin11** [comment]
may i know what is the purpose of cuda-platform-redist

**Comment by saudet** [comment]
It contains the runtime for CUDA, so users don't need to install it on their machines, but they still need to install the video driver. That's not something we can bundle because it needs to be installed with root privileges on the host machine.

**Comment by campin11** [comment]
> redist, the latest video driver version from nvidia would be cud

ahh appreciate the info. 

> It contains the runtime for CUDA, so users don't need to install it on their machines, but they still need to install the video driver. That's not something we can bundle because it needs to be installed with root privileges on the host machine.

ahhh, appreciate the info, thanks saudet.
