### ISSUE TITLE
Can't install leptonica

### ISSUE THREAD

**Issue by kiquetal** [bytedeco/javacpp-presets#132]
Previous steps:

-Download javaccp
-mvn install

libjpeg-turbo-1.4.1/config.h.in
libjpeg-turbo-1.4.1/bmp.c
libjpeg-turbo-1.4.1/jdmarker.c
libjpeg-turbo-1.4.1/sharedlib/
libjpeg-turbo-1.4.1/sharedlib/CMakeLists.txt
libjpeg-turbo-1.4.1/jidctint.c

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
~/Documents/codes/2016/ocr/javacpp-presets/leptonica

I already removed the download folder in javaccp-presets,but the same error appear when running:

./cppbuild.sh install leptonica.

**Comment by saudet** [comment]
It sounds like your version of curl isn't able to download libjpeg-turbo properly or something. Just download it some other way, and save it in the "downloads" folder before running the build.
