### ISSUE TITLE
Some MKL methods skipped in javacpp-presets

### ISSUE THREAD

**Issue by blueberry** [bytedeco/javacpp-presets#1326]
I wanted to use cblas_saxpby and cblas_daxpby, but they are unavailable in JavaCPP's MKL presets.

I found out that they are explicitly excluded, by the following line:

https://github.com/bytedeco/javacpp-presets/blob/a036172bfd52d5511f49bda5bce4fe01e742451a/mkl/src/main/java/org/bytedeco/mkl/presets/mkl_rt.java#L134

Is this intentional, or just for compatibility with other BLAS/LAPACK implementations such as openblas? Can they be included in the next release?

There might be more useful MKL methods that are missing, but these two are what I had use for...

**Comment by saudet** [comment]
They are missing from MKL. Please ask Intel about that.

**Comment by blueberry** [comment]
Is this only missing in the C++ API? I have been calling it with no problems from the C api from years.

https://github.com/uncomplicate/neanderthal-native/blob/46e9f7fdd981dff4c90f3fe3f555007c944e4755/neanderthal-mkl/src/main/c/neanderthal.c#L1325

**Comment by saudet** [comment]
It's missing from mkl_rt, the recommended way to use MKL: https://www.intel.com/content/www/us/en/develop/documentation/onemkl-windows-developer-guide/top/linking-your-application-with-onemkl/linking-quick-start/using-the-single-dynamic-library.html

**Comment by blueberry** [comment]
Now I'm confused, because in C, I put =#include "mkl.h"=, then link to =mkl_rt=, and it works (MKL 2022.2, MKL from 2017 etc.)

Now, you probably know this better than I am, and I have a workaround for that particular function.

**Comment by saudet** [comment]
Well, I've removed them from the skip list in commit https://github.com/bytedeco/javacpp-presets/commit/dabd151be44202bdc7e31e1063780926857ebeed and the builds are not failing, so I guess they must have fixed that at some point.

**Comment by blueberry** [comment]
Thank you.
