### ISSUE TITLE
Android min sdk version

### ISSUE THREAD

**Issue by xiaos** [bytedeco/javacpp-presets#1329]
Hi @saudet , 

I saw below params in the ffmpeg cpp build file, does it mean the min sdk version should be 24 when we inlucde this native lib in the android app? thanks. 

CFLAGS="$ANDROID_FLAGS" LDFLAGS="$ANDROID_FLAGS" make -j $MAKEJ PREFIX=$INSTALL_PATH OS=android ARCH=arm USE_ASM=No NDKROOT="$ANDROID_NDK" NDK_TOOLCHAIN_VERSION="clang" TARGET="android-24" install-static

**Comment by saudet** [comment]
No, it doesn't have to be.
