### ISSUE TITLE
Missing mkl_somatcopy and relatives

### ISSUE THREAD

**Issue by blueberry** [bytedeco/javacpp-presets#1331]
Hi,

I'm using JavaCPP 1.5.8, but judging by the generated mkl_rt.java in 1.5.9-SNAPSHOT= it is the same in the latest master.

I noticed that =mkl_rt= is missing the mkl_?omatcopy function that is defined in MKL and that is present in mkl_rt for years (similarly to #1326 ).

There is a difference, though, because judging by the JavaCPP MKL configuration source, this function should be available! https://github.com/bytedeco/javacpp-presets/blob/138c9b09c56330fbdc9cca69c88a6ddd10329df5/mkl/src/main/java/org/bytedeco/mkl/presets/mkl_rt.java#L67

What is also strange is that batched variants of mkl_?omatcopy are present! (mkl_rt/mkl_somatcopy_batch etc.) 

The same problem is present with mkl_?omatadd..

BTW the mentioned functions are present and vailable in vanilla MKL; I've been using it via custom C JNI bindings for years.

**Comment by saudet** [comment]
Their symbols do appear to be defined in mkl_rt, but their declarations is no where to be found in the header files. How did you figure out their signatures?

**Comment by saudet** [comment]
Ah, no, they seem to be available in "mkl_trans.h" these days. They used to have some strange macros attached, but that's now all in "mkl_trans_names.h" so as long as we don't try to parse that we should be fine. :thinking:

**Comment by blueberry** [comment]
I used a mkl.h that came with intel's MKL installation on linux. I was using the C API, though; wasn't aware that there could be something messed up in the C++ part...

**Comment by saudet** [comment]
I've removed those lines in commit https://github.com/bytedeco/javacpp-presets/commit/41d9d2beaf4bec164b989440937aef7022b28065 and the builds are not failing, so it looks like there are no problems.
Please give it a try with the snapshots: http://bytedeco.org/builds/

**Comment by saudet** [comment]
Probably something like that, yes.
