### ISSUE TITLE
Question: Difference between org.opencv and org.bytedeco.opencv

### ISSUE THREAD

**Issue by calvertdw** [bytedeco/javacpp-presets#1338]
I noticed there's `org.opencv.objdetect.ArucoDetector` and `org.bytedeco.opencv.opencv_objdetect.ArucoDetector`. What's the difference?

**Comment by calvertdw** [comment]
Oh I think maybe the `org.opencv` is the official OpenCV Java files included for reference, but it looks like they don't link by default. That's alright, and answers my question. I'll just use the `org.bytedeco.opencv` one. :)
```
java.lang.UnsatisfiedLinkError: 'long org.opencv.objdetect.ArucoDetector.ArucoDetector_3()'
```

**Comment by saudet** [comment]
Yes, that's correct: https://github.com/bytedeco/javacpp-presets/tree/master/opencv#documentation
