### ISSUE TITLE
no jnicaffe in java.library.path 

### ISSUE THREAD

**Issue by awayhome113** [bytedeco/javacpp-presets#134]
Runing caffe.java on Windows7 x64 give me the error:" no jnicaffe in java.library.path: no opencv_ffmpeg300_64 in java.library.", I simply add javacpp-presets caffe in my pom.xml, and doesn't do anything else, Is there something I missed?

**Comment by saudet** [comment]
There's no Windows build for Caffe yet. It would be very welcome if you
could
make a contribution in that sense.

**Comment by saudet** [comment]
Duplicate of #34
