### ISSUE TITLE
Has Mat.createFrom(BufferedImage) been deleted from javacpp-opencv?

### ISSUE THREAD

**Issue by awayhome113** [bytedeco/javacpp-presets#135]
I want to use java's BufferedImage as parameter, but it's hard for me to convert BufferedImage to Mat in javacpp. I search on the net for a while and get the solution Mat.createFrom(BufferedImage). But I can't find this function. Any idea?

**Comment by saudet** [comment]
The information you are looking for is here:
http://bytedeco.org/news/2015/04/04/javacv-frame-converters/
