### ISSUE TITLE
preset ffmpeg has no filter "scale_cuda"

### ISSUE THREAD

**Issue by nanguantong** [bytedeco/javacpp-presets#1362]
@saudet 
While running the command: `C:\Users\xxx\.javacpp\cache\ffmpeg-5.1.2-1.5.8-windows-x86_64.jar\org\bytedeco\ffmpeg\windows-x86_64\ffmpeg.exe`

print out:
> ..C scale                 V->V       Scale the input video size and/or convert the image format.
>  ... scale_qsv          V->V       QuickSync video scaling and format conversion
>  ..C scale2ref         VV->VV     Scale the input video size and/or convert the image format to the given reference.

not found `scale_cuda`, could you please re-build with the filter?

**Comment by saudet** [comment]
Please open a pull request! Contributions are welcome

**Comment by nanguantong** [comment]
Need to add `--enable-cuda-nvcc` and `--enable-libnpp` into the configure in `ffmpeg/cppbuild.sh`.

**Comment by saudet** [comment]
Duplicate of #857

**Comment by saudet** [comment]
> Need to add `--enable-cuda-nvcc` and `--enable-libnpp` into the configure in `ffmpeg/cppbuild.sh`.

Please open a pull request! Contributions are welcome
