### ISSUE TITLE
Does the newest version just compatible with CUDA-7.5

### ISSUE THREAD

**Issue by awayhome113** [bytedeco/javacpp-presets#138]
I use it with CUDA support, but it's still show me "java.lang.UnsatisfiedLinkError: /tmp/javacpp*/libjnicaffe.so: libcudart.so.7.5", but my server's CUDA version is 7.0, Is it possible to specified the version of CUDA?

**Comment by saudet** [comment]
Although I haven't tested it, it should fine with CUDA 7.0 if you rebuild it:
https://github.com/bytedeco/javacpp-presets/#build-instructions

**Comment by saudet** [comment]
BTW, @cypof wants to bundle the CUDA libraries themselves to avoid this kind of issue. This is something that might happen sooner than later if we could have people like you testing this out. :)

**Comment by awayhome113** [comment]
I just download it using maven. I will have a try to rebuild it, Thanks a lot!

**Comment by saudet** [comment]
Sure! BTW, check out pull request #101 and if interested please participate in the discussion! If all works out, we will be able, for example, to bundle CUDA 7.5 so that it works even on machines where only CUDA 7.0 has been installed.
