### ISSUE TITLE
【pytorch] when will have  normal dataloader  dataset  thses classs for load data  

### ISSUE THREAD

**Issue by mullerhai** [bytedeco/javacpp-presets#1396]
HI,  these class is important ,why in new version  also no have these? please  implement  BatchDataset batchDataset   
 StatelessDataLoader DataLoader these class is so important

**Comment by mullerhai** [comment]
by the way  what different  Example  from TensorExample ,and  how to convert each obj

**Comment by mullerhai** [comment]
by the way ,ExampleIterator now can not use, I think it need develop for could  convert each with ExampleVector

**Comment by mullerhai** [comment]
Now  I could use Apache Spark  pipeline  train build javacpp pytorch model ,just need  BatchDataset,  StatelessDataLoader, please make them really use in javacpp,thanks @HGuillemet  @saudet

**Comment by HGuillemet** [comment]
These classes have been added in commit  [5507552](https://github.com/bytedeco/javacpp-presets/commit/550755207e4729f692e5079c1aa998722eb1334e) and are available in 2.1.0-1.5.10-SNASHOT.
Note that only the template instances for `Example<Tensor,Tensor>` (`Example` in Java) and `Example<Tensor,NoTarget>` (`TensorExample` in Java) are mapped.
The corresponding virtual classes for datasets and data loaders are called in Java `JavaDataset`, `JavaRandomDataLoader`,  `JavaTensorDataset`, etc...
