### ISSUE TITLE
[Pytorch]  Tensor Slice param has change ?

### ISSUE THREAD

**Issue by mullerhai** [bytedeco/javacpp-presets#1398]
hi ,I found  the Tensor Slice param  has change ,but I not know how to set for  Null param ,
old version 
```
           val sliceA = new Slice(new LongOptional(t + 1), new LongOptional(null), new LongOptional(1))


```
new version
```
 
      val sliceA = new Slice(new SymIntOptional(new SymInt (t + 1)), new SymIntOptional(new SymInt(null)), new SymIntOptional(new SymInt(1)))

```

**Comment by mullerhai** [comment]
val sliceA = new Slice(new SymIntOptional(new SymInt (t + 1)), new SymIntOptional(null), new SymIntOptional(new SymInt(1)))

**Comment by HGuillemet** [comment]
Yes, use `new XXXXOptional()` to create any no-value optional.
Or just `null` should work too .

Please close your issues when they are solved.
