### ISSUE TITLE
How should freetype 1.5.9 compile for opencv

### ISSUE THREAD

**Issue by ScienceNoBorders** [bytedeco/javacpp-presets#1403]
In “javacpp-presets/opencv/SRC/main/Java/org/bytedeco/opencv/presets/opencv_freetype.java"  after adding files still couldn't compile the freetype in jar package

**Comment by saudet** [comment]
You'll probably need to update cppbuild.sh as well to enable that module.

**Comment by ScienceNoBorders** [comment]
> You'll probably need to update cppbuild.sh as well to enable that module.

I've already opened it
<img width="325" alt="image" src="https://github.com/bytedeco/javacpp-presets/assets/37797698/c985eb5e-1df4-4120-8756-ad91ae2865f3">
