### ISSUE TITLE
Please add torch.cuda.[selected methods]

### ISSUE THREAD

**Issue by jxtps** [bytedeco/javacpp-presets#1410]
Right now `torch.cuda` maps to a `Symbol`. It would be very useful if some of the items listed on https://pytorch.org/docs/stable/cuda.html were made available. Specifically: 

1. ~~[synchronize](https://pytorch.org/docs/stable/generated/torch.cuda.synchronize.html#torch.cuda.synchronize)~~ *already added in `torch.cuda_synchronize()`*
2. [utilization](https://pytorch.org/docs/stable/generated/torch.cuda.utilization.html#torch.cuda.utilization)
3. [memory_usage](https://pytorch.org/docs/stable/generated/torch.cuda.memory_usage.html#torch.cuda.memory_usage)
4. get_arch_list
5. get_device_properties

Memory related, the ones referenced on https://pytorch.org/docs/stable/notes/cuda.html#memory-management and listed on https://pytorch.org/docs/stable/cuda.html#memory-management

Now, clicking through to the source of these on their respective doc pages I'm realizing that these are implemented in python, referencing various `torch._C._cuda_xyz()` methods. 

That makes this a little trickier of course in that not only would the `torch._C._cuda...` plumbing code need to appropriately mapped, then there's the entire convenience layer on top that would either need to be re-implemented by each user, or added as java glue code to the project. 

Maybe we could start by mapping the key plumbing code? Specifically: 

1. `torch._C._cuda_memoryStats()`
2. `torch._C._cuda_memorySnapshot()`
3. `torch._C._cuda_getArchFlags()`
4. Was unable to trace how `get_device_properties()` gets mapped. It's lazy loaded, but I can't find the source for `_get_device_properties()`: https://pytorch.org/docs/stable/_modules/torch/cuda.html#get_device_properties

The performance metrics (`utilization` & `memory_usage`) are coming from nvml which I guess is mapped in `cuda-platform-redist`? Maybe all of the above are as well? I've been using `libtorch` instead of `cuda-platform-redist` - maybe getting these features would require a switch?

**Comment by HGuillemet** [comment]
We are limited to what the C++ Pytorch API can offer (https://pytorch.org/cppdocs/).
Is there any problem in using the cuda presets for getting these informations ?
Example:
```Java
nvmlInit_v2();

int[] cudaVersion = new int[1];
int ret = nvmlSystemGetCudaDriverVersion_v2(cudaVersion);
if (ret != NVML_SUCCESS) throw new RuntimeException("Cannot get cuda driver version: " + ret);
System.out.println("CUDA version: " + cudaVersion[0]);

long devCount = cuda_device_count();
for (int dev = 0; dev < devCount; dev++) {
    nvmlDevice_st device = new nvmlDevice_st();
    ret = nvmlDeviceGetHandleByIndex_v2(dev, device);
    System.out.println("DEVICE "+dev);
    if (ret != NVML_SUCCESS) throw new RuntimeException("Cannot get cuda device struct: " + ret);
    int[] arch = new int[1];
    ret = nvmlDeviceGetArchitecture(device, arch);
    if (ret != NVML_SUCCESS) throw new RuntimeException("Cannot get cuda device arch: " + ret);
    System.out.println(" Arch: "+arch[0]);
    nvmlMemory_t memoryInfo = new nvmlMemory_t();
    ret = nvmlDeviceGetMemoryInfo(device, memoryInfo);
    if (ret != NVML_SUCCESS) throw new RuntimeException("Cannot get cuda memory info: " + ret);
    System.out.println(" Memory: "+memoryInfo.total()+" total, "+memoryInfo.used()+" used, "+memoryInfo._free()+" free");
    nvmlUtilization_t utilization = new nvmlUtilization_t();
    ret = nvmlDeviceGetUtilizationRates(device, utilization);
    if (ret != NVML_SUCCESS) throw new RuntimeException("Cannot get cuda utilization info: " + ret);
    System.out.println(" Utilization: "+utilization.gpu()+" % gpu, "+utilization.memory()+" % memory");
}
```
Output for me:
```
CUDA version: 12020
DEVICE 0
 Arch: 7
 Memory: 8589934592 total, 1282473984 used, 7307460608 free
 Utilization: 10 % gpu, 16 % memory
```

**Comment by jxtps** [comment]
Yeah, sounds like I need to switch from `libtorch` to `cuda-platform-redist`.
