### ISSUE TITLE
Update to 1.5.9 give error on java cpp module not found. 

### ISSUE THREAD

**Issue by AKMANSoft** [bytedeco/javacpp-presets#1414]
I have recently updated to javacpp and java cv to 1.5.9 it start giving me error. 

java.lang.module.FindException: Module org.bytedeco.flandmark not found, required by org.bytedeco.javacv
I don't need the flandmark, still add it, another issue. 

flandmark is not available with 1.5.9 but available with 1.5.8, i think updated needed on the version no. i find it by investigating the pom. another confusing it shows a different version no in the readme file, then inside the pom file, check the screenshot. 

![image](https://github.com/bytedeco/javacpp-presets/assets/21236130/04e0a680-8b1e-4b2a-b015-78f2df3b0836)

manage to resolve issue by adding 
<dependency>
	<groupId>org.bytedeco</groupId>
	<artifactId>flandmark</artifactId>
	<version>1.07-1.5.8</version>
</dependency>

**Comment by saudet** [comment]
You can ignore that dependency, yes. How you need to go about that is going to depend on the tools you're using.

**Comment by saudet** [comment]
Ah, I see, you're using modules. So we need to remove it from module-info.java, yes. I'll fix that

**Comment by saudet** [comment]
Fixed in commit https://github.com/bytedeco/javacv/commit/b42450be42460977e6492af0b668cac34373e949.
Please give it a try  with the snapshots: http://bytedeco.org/builds/

**Comment by AKMANSoft** [comment]
Thank you it is resolved.

**Comment by saudet** [comment]
Fix released JavaCV 1.5.10. Thanks for reporting!
