### ISSUE TITLE
How to use FFmpeg in Android?

### ISSUE THREAD

**Issue by OmidNejadabbasi** [bytedeco/javacpp-presets#1416]
I have added the following gradle deps to the build.gradle file but I can't import the classes in my android project:

```
implementation 'org.bytedeco:ffmpeg-platform-gpl:6.0-1.5.9'
```

Can you explain how to use it in Android/gradle

**Comment by saudet** [comment]
Please try with the Platform Plugin of Gradle JavaCPP:   
https://github.com/bytedeco/gradle-javacpp#the-platform-plugin

**Comment by OmidNejadabbasi** [comment]
> Please try with the Platform Plugin of Gradle JavaCPP: https://github.com/bytedeco/gradle-javacpp#the-platform-plugin

@saudet 
I did use the plugin but got another error. I opened an issue in that repo : https://github.com/bytedeco/gradle-javacpp/issues/32

**Comment by saudet** [comment]
Duplicate of https://github.com/bytedeco/gradle-javacpp/issues/32
