### ISSUE TITLE
pixWrite seemingly fails if filepath has accented character in it

### ISSUE THREAD

**Issue by sanya911201** [bytedeco/javacpp-presets#1419]
pixWrite seemingly fails if filepath has accented character in it

With this code i have no problem:
`pixWrite(C:/Users/bsany/Desktop/ocrtest/output/image.png", croppedImage, IFF_PNG);`

But this code fails:
`pixWrite(C:/Users/bsany/Desktop/Új mappa (3)/output/image.png", croppedImage, IFF_PNG);`

I got the following error:

> Error in fopenWriteStream: stream not opened
Error in pixWrite: stream not opened

**Comment by saudet** [comment]
It's possible Leptonica doesn't support non-ASCII paths.

**Comment by saudet** [comment]
Please try again with JavaCV 1.5.9.

**Comment by sanya911201** [comment]
> Please try again with JavaCV 1.5.9.

I'm using 1.5.9 and the problem occurs with it.

**Comment by sanya911201** [comment]
Is there a simple workaround to use pixWrite or something similar to it with non-ASCII paths?

**Comment by HGuillemet** [comment]
You must figure out what encoding the C++ `pixWrite` expects, then you can use the version of the Java `pixWrite` that takes a `BytePointer` instead of a `String` and pass it something like `new BytePointer("C:/Users/bsany/Desktop/Új mappa (3)/output/image.png", "UTF-8")`.

**Comment by sanya911201** [comment]
> You must figure out what encoding the C `pixWrite` expects, then you can use the version of the Java `pixWrite` that takes a `BytePointer` instead of a `String` and pass it something like `new BytePointer("C:/Users/bsany/Desktop/Új mappa (3)/output/image.png", "UTF-8")`.

I managed to figure out that pixWrite expects Windows-1252 encoding. So now it is working with your BytePointer solution:

`BytePointer bp2 = new BytePointer("C:/Users/bsany/Desktop/Új mappa (3)/output/image.png", "Windows-1252");`

Thank you for your help! :)

**Comment by saudet** [comment]
That means your OS is using Windows-1252, so you should probably set "file.encoding" to Windows-1252, or you'll get problems with other libraries as well.
