### ISSUE TITLE
[Pytroch] Tensors of Type Float and BFloat16 have different values. 

### ISSUE THREAD

**Issue by Omar122** [bytedeco/javacpp-presets#1425]
Hello,
I have noticed that creating Tensor of Type float and BFloat16 produce different Tensors.
 
Is this because of the FloatPointer? 
```
Tensor t1 = torch.from_blob(new FloatPointer(3, -4), new long[]{2}, new TensorOptions(torch.ScalarType.Float));
Tensor t2 = torch.from_blob(new FloatPointer(3, -4), new long[]{2}, new TensorOptions(torch.ScalarType.BFloat16));

 torch.print(t1);
 torch.print(t2);
 torch.print(t1.eq(t2));
 t2 = t1.clone();
 torch.print(t2);
 torch.print(t1.eq(t2));
```

**Output:**
t1: 3 -4 [ CPUFloatType{2} ]
t2: 0 3 [ CPUBFloat16Type{2} ]
t1.eq(t2):0 0 [ CPUBoolType{2} ]
t2 after clone: 3 -4 [ CPUFloatType{2} ]
t1.eq(t2):1 1 [ CPUBoolType{2} ]

I tested similar code in python I didn't find this difference between the two Tensors.

```
import torch
t1 = torch.tensor([3 ,-4],dtype=torch.bfloat16)
t2 = torch.tensor([3, -4],dtype=torch.float)
print(t1)
print(t2)
print(t1.eq(t2))

```
**Output:**
tensor([ 3., -4.], dtype=torch.bfloat16)
tensor([ 3., -4.])
tensor([True, True])

**Versions**

```
 <dependency>
      <groupId>org.bytedeco</groupId>
      <artifactId>pytorch-platform</artifactId>
      <version>2.0.1-1.5.10-SNAPSHOT</version>
    </dependency>

    <dependency>
      <groupId>org.bytedeco</groupId>
      <artifactId>pytorch-platform-gpu</artifactId>
      <version>2.0.1-1.5.10-SNAPSHOT</version>
    </dependency>
```

**Comment by saudet** [comment]
BFloat16Type doesn't work with float data, you'll need to give it bfloat16 data.

**Comment by HGuillemet** [comment]
Indeed, with the JavaCPP version you are creating a 4-bytes, 2-BFloat16 tensor from a 8-bytes buffer, resulting with a first BFloat16 having a representation equal to the first half of 3F and another BFloat16 with a representation equal to the second half of 3F. There is nothing converting the floats to BFloat16s.
In the Python version, you are creating tensors by copying the data from the list [3,4], using proper conversion.

This should work, even if there may exists something more efficient:
```Java
ShortPointer f16Array = new ShortPointer(new BFloat16(3F).x(), new BFloat16(-4F).x());
Tensor t2 = torch.from_blob(f16Array, new long[]{2}, new TensorOptions(torch.ScalarType.BFloat16));
```

**Comment by HGuillemet** [comment]
> even if there may exist something more efficient:

Like:
```Java
Tensor t2 = t1.to(ScalarType.BFloat16);
```

**Comment by Omar122** [comment]
Thanks for the answers. I was curious so I decide to benchmark both ways, Full report in the attachment. 
[jhm.txt](https://github.com/bytedeco/javacpp-presets/files/12909995/jhm.txt)
**Benchmark                                         Mode  Cnt       Score        Error   Units**
Benchmark.UsingToScalarType                      thrpt    5   94805.737 ± 111116.818   ops/s
Benchmark.UsingToScalarType:·gc.alloc.rate       thrpt    5      54.236 ±     63.578  MB/sec
Benchmark.UsingToScalarType:·gc.alloc.rate.norm  thrpt    5     600.000 ±      0.001    B/op
Benchmark.UsingToScalarType:·gc.count            thrpt    5      24.000               counts
Benchmark.UsingToScalarType:·gc.time             thrpt    5    4875.000                   ms
Benchmark.UsinngFromBlob                         thrpt    5  111044.694 ±  16152.008   ops/s
Benchmark.UsinngFromBlob:·gc.alloc.rate          thrpt    5     105.896 ±     15.398  MB/sec
Benchmark.UsinngFromBlob:·gc.alloc.rate.norm     thrpt    5    1000.000 ±      0.001    B/op
Benchmark.UsinngFromBlob:·gc.count               thrpt    5      53.000               counts
Benchmark.UsinngFromBlob:·gc.time                thrpt    5   10360.000                   ms

Final question, any idea on how to use ArrayRef such as  **BFloat16ArrayRef** ?

**Comment by HGuillemet** [comment]
ArrayRefs are non-owning views of contiguous arrays. You get instances of ArrayRefs from the library or you can create them from an existing array. There is no ArrayRef constructors that allocates memory.

For instance if f16Array is a pointer to an existing memory area containing 1000 BFloat16:
```Java
BFloat16ArrayRef f16ArrayRef = new BFloat16ArrayRef(f16Array, 1000);
Tensor t2 = torch.tensor(f16ArrayRef, new TensorOptions(gpu));
```
