### ISSUE TITLE
arrow module - Downloading http://zlib.net/zlib-1.2.13.tar.gz http error 404

### ISSUE THREAD

**Issue by archenroot** [bytedeco/javacpp-presets#1450]
The url in the script doesn't work, there is new working URL: https://www.zlib.net/fossils/zlib-1.2.13.tar.gz

**Comment by saudet** [comment]
I'm not maintaining those presets myself, but you're welcome to provide a fix!

**Comment by saudet** [comment]
Duplicate of #1451

**Comment by archenroot** [comment]
This one is not duplicate of #1451 - these are 2 different issues, I just fixed this one here: https://github.com/bytedeco/javacpp-presets/commit/869a41c4684086733ad7e0130be12eed9c5e2c8e

**Comment by saudet** [comment]
That's fine, just open a pull request.
