### ISSUE TITLE
the javacpp pytorch package need publish 2.1.2-1.5.10 release version and could use  Flash Attention in javacpp pytorch?

### ISSUE THREAD

**Issue by mullerhai** [bytedeco/javacpp-presets#1458]
HI ,half year  later,I think   the javacpp pytorch package need publish 2.1.2-1.5.10 release version  ,because now not ok release  version could use in produce invironment ,I think  it stable to suit the normal env, please

**Comment by mullerhai** [comment]
> @saudet is in the release process. Please be patient for 1 or 2 more weeks.
> 
> Concerning flash attention, what makes you think it's not used by JavaCPP Pytorch ? It should be enabled by default, and you can disable it with `setSDPUseFlash` in `Context`. However, I think it needs CUDA compute capability 8.0, so you must either:
> 
> * use current presets snapshot
> * wait for 2.1.2-1.5.10
> * use a previous version of the presets, but with official libtorch binary

Feel happy to hear the new release for javacpp pytorch，having waiting for half year，2.1.2-1.5.10 version will be powerful  in  my scala pytorch applications ，because of the snapshot in my work need  upload local nexus jar package server and it also update some code by days  ，is  unconvient for me, so we need stable release version .very thanks for release

**Comment by saudet** [comment]
Version 1.5.10 has been released! Enjoy

**Comment by mullerhai** [comment]
> Version 1.5.10 has been released! Enjoy

Excited ！！
