### ISSUE TITLE
Missing libfreenect and librealsense 1.5.10 artifacts on Maven Central

### ISSUE THREAD

**Issue by edwinRNDR** [bytedeco/javacpp-presets#1465]
I can't find the javacpp preset 1.5.10 artifacts for libfreenect and librealsense on Maven Central

https://repo1.maven.org/maven2/org/bytedeco/libfreenect/
https://repo1.maven.org/maven2/org/bytedeco/librealsense/

Potentially other artifacts are missing too. Is this intentional and should I use the 1.5.9 presets with javacpp 1.5.10?

**Comment by saudet** [comment]
There's nothing new with them and JavaCPP 1.5.x is backward compatible so no need for new releases, just use 1.5.9
