### ISSUE TITLE
opencv cudawraping is missing. 

### ISSUE THREAD

**Issue by MachineIntelligence6** [bytedeco/javacpp-presets#1467]
I was comparing the opencv contribute modules with the bytecode/opencv module and didn't find the cuda warping. 

I was trying to use the resize function in it, it there a reason for that?

here are the links

[OpenCV contribute Cuda Wraping](https://github.com/opencv/opencv_contrib/tree/4.x/modules/cudawarping)

[Bytedeco Alternative to use in Java](https://github.com/bytedeco/javacpp-presets/tree/master/opencv/src/gen/java/org/bytedeco/opencv)

**Comment by saudet** [comment]
Contributions are welcome!

**Comment by TomaszTB** [comment]
What about this guy? [opencv_cudawarping.java](https://github.com/bytedeco/javacpp-presets/blob/master/opencv/src/gen/java/org/bytedeco/opencv/global/opencv_cudawarping.java)

**Comment by saudet** [comment]
Thanks @TomaszTB ! I overlooked it :) So it's already there
