### ISSUE TITLE
ffmpeg6+ drawtext filter support

### ISSUE THREAD

**Issue by bmaassenee** [bytedeco/javacpp-presets#1470]
It seems that from release 6.1+ of ffmpeg the requirements for the drawtext filter has changed:

Where in 6.0 the docs state: https://github.com/FFmpeg/FFmpeg/blob/release/6.0/doc/filters.texi#L12064-L12069
> To enable compilation of this filter, you need to configure FFmpeg with @code{--enable-libfreetype}.

While in 6.1 it has changed to: https://github.com/FFmpeg/FFmpeg/blob/release/6.1/doc/filters.texi#L12368-L12373
> To enable compilation of this filter, you need to configure FFmpeg with @code{--enable-libfreetype} and @code{--enable-libharfbuzz}.

This has not been updated in the `ffmpeg/cppbuild.sh` and as a result the filter is not usable

**Comment by saudet** [comment]
Contributions are welcome!

**Comment by bmaassenee** [comment]
Sorry for the duplicate, did a search for drawtext and found nothing. Am considering having a go at it, unfortunately i'm a windows user, which i'm afraid is the hardest env to do these builds :(

**Comment by saudet** [comment]
Fixed with pull https://github.com/bytedeco/javacpp-presets/pull/1731.
Please try again with the snapshots: https://central.sonatype.com/service/rest/repository/browse/maven-snapshots

**Comment by bmaassenee** [comment]
Thank you, did try to resolve this, but didn't manage to make it work

**Comment by saudet** [comment]
Fix released with JavaCV 1.5.13! Enjoy
