### ISSUE TITLE
Strange callback methods in bullet3

### ISSUE THREAD

**Issue by alfabouh** [bytedeco/javacpp-presets#1474]
I'm facing a problem that I can't create a collision filter. The method is simply not overridden
```
this.btOverlapFilterCallback = new btOverlapFilterCallback(this.discreteDynamicsWorld.getPairCache().getOverlapFilterCallback()) {
            @Override
            public @Cast("bool") boolean needBroadphaseCollision(btBroadphaseProxy proxy0, btBroadphaseProxy proxy1) {
                System.out.println("FWE");
                return false;
            }
        };
        this.discreteDynamicsWorld.getPairCache().setOverlapFilterCallback(this.btOverlapFilterCallback);
```
I think this is because in the btOverlapFilterCallback class, the needBroadphaseCollision method is not defined as @Virtual. The exact same situation applies to callback classes in the btCollisionWorld class. Maybe I'm doing something wrong?

**Comment by saudet** [comment]
Please do try to make them virtual!

**Comment by alfabouh** [comment]
What do you mean? Do I need to create a pull request?
