### ISSUE TITLE
macosx-arm64 for TensorFlow Lite 

### ISSUE THREAD

**Issue by Vane101** [bytedeco/javacpp-presets#1477]
Thank you, this is a great repo. I am working on a Macbook M1 and wondering if there was a way of getting a macosx-arm64.jar for tensorflow-lite. Found nothing on the snapshot builds

**Comment by saudet** [comment]
Contributions are welcome!

**Comment by saudet** [comment]
Duplicate of #1069

**Comment by saudet** [comment]
I've added macosx-arm64 to the builds for TensorFlow Lite.
Please give it a try with the snapshots: http://bytedeco.org/builds/
