### ISSUE TITLE
arpack-ng-platform adds macosx-arm64 support

### ISSUE THREAD

**Issue by haifengl** [bytedeco/javacpp-presets#1495]
Can you please add `macosx-arm64` support to `arpack-ng-platform`? This package is often used along with LAPACK and `javacpp-openblas` already supports `macosx-arm64` for a while. Thanks!

**Comment by saudet** [comment]
Duplicate of https://github.com/bytedeco/javacpp-presets/issues/1069

**Comment by haifengl** [comment]
Thanks. I am aware of #1069. But when I try the snapshot `"org.bytedeco" % "arpack-ng" % "3.9.1-1.5.11-SNAPSHOT"  classifier "macosx-arm64"`, I get this error
```
https://oss.sonatype.org/content/repositories/snapshots/org/bytedeco/arpack-ng/3.9.1-1.5.11-SNAPSHOT/arpack-ng-3.9.1-1.5.11-SNAPSHOT-macosx-arm64.jar: not found: https://oss.sonatype.org/content/repositories/snapshots/org/bytedeco/arpack-ng/3.9.1-1.5.11-SNAPSHOT/arpack-ng-3.9.1-1.5.11-SNAPSHOT-macosx-arm64.jar
```

**Comment by saudet** [comment]
That's right, it doesn't exist. Someone needs to work on it

**Comment by saudet** [comment]
I've added macosx-arm64 to the builds for ARPACK-NG.
Please give it a try with the snapshots: http://bytedeco.org/builds/

**Comment by haifengl** [comment]
Thanks a lot! Will try.

**Comment by haifengl** [comment]
It works well for me. Thanks!
