### ISSUE TITLE
tar: Error exit delayed from previous errors.

### ISSUE THREAD

**Issue by hobart1987hu** [bytedeco/javacpp-presets#150]
I'm use mac Mac OS X (x86_64) to build project:

Mac OS X (x86_64)

OS X Mavericks (10.9) is the first version of Mac OS X to support C++11 fully and properly, so to preserve your sanity, we do not recommend trying to build or use the JavaCPP Presets on any older versions of Mac OS X.

Preparations

Install Xcode and Homebrew
Run the following commands to install the JDK, among other things Apple left out of Xcode:

$ brew install caskroom/cask/brew-cask
$ brew cask install cuda java
$ brew install bazel cmake libusb maven nasm yasm xz
After which the following commands can be used to start the build inside the javacpp-presets directory:

$ bash cppbuild.sh install
$ mvn clean install

when  i run  bash cppbuild.sh install command ,get errors :
x opencv3.1.0/doc/tutorials/core/mat_the_basic_image_container/mat_the_basic_image_container.markdown
x opencv-3.1.0/doc/tutorials/core/random_generator_and_text/
x opencv-3.1.0/doc/tutorials/core/random_generator_and_text/images/
x opencv-3.1.0/doc/tutorials/core/random_generator_and_text/images/Drawing_2_Tutorial_Result_0.jpg
x opencv-3.1.0/doc/tutorials/core/random_generator_and_text/images/Drawing_2_Tutorial_Result_2.jpg
x opencv-3.1.0/doc/tutorials/core/random_generator_and_text/images/Drawing_2_Tutorial_Result_3.jpg
x opencv-3.1.0/doc/tutorials/core/random_generator_and_text/images/Drawing_2_Tutorial_Result_5.jpg
x opencv-3.1.0/doc/tutorials/core/random_generator_and_text/images/Drawing_2_Tutorial_Result_big.jpg
x opencv-3.1.0/doc/tutorials/core/random_generator_and_text/random_generator_and_text.markdown
x opencv-3.1.0/doc/tutorials/core/table_of_content_core.markdown
x opencv-3.1.0/doc/tutorials/features2d/
x opencv-3.1.0/doc/tutorials/features2d/akaze_matching/
x opencv-3.1.0/doc/tutorials/features2d/akaze_matching/akaze_matching.markdown
x opencv-3.1.0/doc/tutorials/features2d/akaze_matching/images/
x opencv-3.1.0/doc/tutorials/features2d/akaze_matching/images/graf.png
x opencv-3.1.0/doc/tutorials/features2d/akaze_matching/images/res.png: (Empty error message)
tar: Error exit delayed from previous errors.

how to fix it ??

**Comment by saudet** [comment]
It probably just means that the download failed. Try to removed the `downloads` directory and run the command again...

**Comment by saudet** [comment]
I'm guessing removing the `downloads` directory fixed that error, but let me know if this is still happening. Thanks!
