### ISSUE TITLE
[PyTorch 2.2.2-1.5.11-SNAPSHOT] Exception java.lang.UnsatisfiedLinkError: no jnitorch in java.library.path on WIndows

### ISSUE THREAD

**Issue by haifengl** [bytedeco/javacpp-presets#1500]
The same code works fine with 2.2.1-1.5.11-SNAPSHOT.

**Comment by saudet** [comment]
Which platform?

**Comment by haifengl** [comment]
It doesn't work on Windows 10. It works on Ubuntu 22.04 and macOS 13/14. It doesn't work on older macOS though (e.g. macOS 11). It is fine to drop the support of older macOS.

**Comment by saudet** [comment]
Could you check what the Dependencies tool says is missing?
https://github.com/bytedeco/javacpp-presets/wiki/Debugging-UnsatisfiedLinkError-on-Windows

**Comment by saudet** [comment]
@haifengl @sbrunk Could you please test the builds on Windows and Mac?

**Comment by saudet** [comment]
BTW, macOS 11 is no longer supported by either Apple or GitHub, so please upgrade to at least macOS 12

**Comment by haifengl** [comment]
It is okay to drop supporting macOS 11. Does PyTorch 2.2.2-1.5.11-SNAPSHOT support macOS on arm64 yet?

**Comment by HGuillemet** [comment]
I run a test on a windows 10 VM with 2.2.2 and it works, but jnitorch.dll is indeed linked with libomp140.x86_64.dll that is found in my \windows\system32. It probably came with VS or another software.

I guess we should include an OpenMP library in the jar. I'm seeing that the official libtorch archive includes the Intel version.

 @saudet, what's the best way to do this ? the Pytorch CMakeList.txt doesn't use InstallRequiredSystemLibraries

**Comment by saudet** [comment]
That's apparently a file that comes with Visual Studio, so we should add it to this preload list here:
https://github.com/bytedeco/javacpp/blob/master/src/main/java/org/bytedeco/javacpp/presets/javacpp.java#L42

**Comment by HGuillemet** [comment]
Ok.
Openmp is not used by many presets. Shouldn't we add it to the preload list of presets needing it only ?

**Comment by saudet** [comment]
No, please don't do that

**Comment by HGuillemet** [comment]
Ok, would you like a PR for this or can you add it directly ?

**Comment by saudet** [comment]
Yes, pull requests always welcome :) Thanks

**Comment by haifengl** [comment]
Thanks. It runs on Windows now. However, it doesn't produce good models on Windows though. I will create a new ticket about it.
