### ISSUE TITLE
Shaka-Packager Preset

### ISSUE THREAD

**Issue by zaki699** [bytedeco/javacpp-presets#1505]
Hi Everyone,

I have completed the integration of the preset Shaka-Packager.  

What should I do next to share it with the community ?

**Comment by saudet** [comment]
Please open a pull request for review: https://github.com/bytedeco/javacpp-presets/pulls

**Comment by zaki699** [comment]
Pull request has been opened. Thanks for your help.

**Comment by saudet** [comment]
Duplicate of https://github.com/bytedeco/javacpp-presets/pull/1506
