### ISSUE TITLE
[PyTroch] torch_cuda.set_device() and torch.manual_seed() hang

### ISSUE THREAD

**Issue by haifengl** [bytedeco/javacpp-presets#1508]
App will hang if call either of these functions.

**Comment by haifengl** [comment]
In fact, these functions hang on multi-GPU box. They work fine on a single GPU box. I tried official libtorch build from pytorch.org. I suspect that the issue is not with PyTorch but with `cuda-platform` package. `cudart.cudaDeviceProp` method hangs on multi-GPU box too.

**Comment by saudet** [comment]
That basically just calls the CUDA functions through JNI, so I'm guessing that calling them directly from C++ also hangs, right?

**Comment by haifengl** [comment]
Python wrapper of these methods work fine. I don't think that C++ functions would hang. I guess that we may have to do some extra initialization work on multi-GPU systems?

**Comment by saudet** [comment]
I guess not calling cuInit() could do that?
https://docs.nvidia.com/cuda/cuda-driver-api/group__CUDA__INITIALIZE.html

**Comment by haifengl** [comment]
`cuInit` does the magic. Thanks a lot! It is interesting why we don't need to call it in single GPU system.
