### ISSUE TITLE
Tensorflow code generation failure

### ISSUE THREAD

**Issue by sinjax** [bytedeco/javacpp-presets#152]
When compiling tensorflow the cppbuild.sh works, but mvn install fails with the following error:
https://gist.github.com/sinjax/499b77786169d21aea53

The line making it freak out in java is here:

`public native @ByVal tensorflow::gtl::InlinedVector<long long,4> dim_sizes();`

looks like a code generation failure

**Comment by saudet** [comment]
Fixed in this commit:
https://github.com/bytedeco/javacpp-presets/commit/9f71533db4324cbc0bcce686b4f4a2e30a95b1f0
Enjoy!
