### ISSUE TITLE
fftw_plan_guru_r2r seems to have wrong parameter type

### ISSUE THREAD

**Issue by igrqb** [bytedeco/javacpp-presets#1541]
https://github.com/bytedeco/javacpp-presets/blob/dc8e6a55c82cacee4124ffeece583c99069f5f34/fftw/src/gen/java/org/bytedeco/fftw/global/fftw3.java#L973

According to the FFTW documentation [4.5.5 Guru Real-to-real Transforms](https://www.fftw.org/fftw3_doc/Guru-Real_002dto_002dreal-Transforms.html),  the `dims` and `howmany_dims` are **arrays** of type `fftw_iodim`.

The current JavaCPP presets for FFTW don't have these parameters as an `fftw_iodim` array or pointer.

[Here](https://agentzlerich.blogspot.com/2010/01/using-fftw-for-in-place-matrix.html) is an example of `fftw_plan_guru_r2r` that I have been able to successfully integrate using JNI. Am trying to compare how the same could be done with JavaCPP.

**Comment by saudet** [comment]
fftw_iodim is a Pointer, so we can create one from an array, that's fine.

**Comment by igrqb** [comment]
Hi @saudet,
Thanks for the pointer! (pun intended 😉)  

Here's a test snippet that is working.

Do you have any feedback/suggestions regarding the code?

```java
import org.bytedeco.fftw.global.fftw3;
import org.bytedeco.javacpp.DoublePointer;
import org.bytedeco.javacpp.IntPointer;
import org.junit.jupiter.api.Test;

import static org.bytedeco.fftw.global.fftw3.*;

public class FFTW3Test {
  @Test
  public void testInPlaceTranspose() {
    int flags = FFTW_ESTIMATE;

    int rows = 3;
    int cols = 2;

/* Initial attempt that was on the wrong track */
//    fftw_iodim[] howmany_dims = new fftw_iodim[] {
//        new fftw_iodim(),
//        new fftw_iodim(),
//    };
//
//    howmany_dims[0].n(rows);
//    howmany_dims[0].is(1);
//    howmany_dims[0].os(cols);
//    howmany_dims[1].n(cols);
//    howmany_dims[1].is(rows);
//    howmany_dims[1].os(1);

/* This worked - due to the fftw_iodim structs having all members of type int */
    IntPointer ptr = new IntPointer(rows, 1, cols, cols, rows, 1);

    int howmany_rank = 2;

    double[] data = {1.0, 2.0, 3.0, 4.0, 5.0, 6.0};

    DoublePointer in = new DoublePointer(data);

    fftw3.fftw_plan plan = fftw_plan_guru_r2r(0, null, howmany_rank, new fftw_iodim(ptr), in, in, null, flags);

    fftw_execute(plan);

    fftw_destroy_plan(plan);

    for (int i = 0; i < data.length; i++) {
      System.out.println(in.get(i));
    }
  }
}

```

Output (as expected):
```bash
1.0
4.0
2.0
5.0
3.0
6.0
```

**Comment by saudet** [comment]
Looks fine :+1:

**Comment by saudet** [comment]
Though you may want to use PointerScope to manage the lifetime of the Pointer objects:
http://bytedeco.org/news/2018/07/17/bytedeco-as-distribution/

**Comment by igrqb** [comment]
Thanks @saudet 

I have a related question -- not sure if posting here is the best place -- maybe others will find your insights valuable (as I have), as you have a lot of experience with C, C++ and Java.

If I need to use MKL and FFTW in the same project, then there seems to be an issue. It looks like once MKL is loaded, the MKL interface for FFTW is called, instead of the original FFTW.

Here's an example:

```java
  @Test
  public void testInPlaceTranspose() {
    int rows = 3;
    int cols = 2;
    fftwInplaceTranspose(rows, cols, new double[] {1.0, 2.0, 3.0, 4.0, 5.0, 6.0});
    mklInplaceTranspose(rows, cols, new double[] {1.0, 2.0, 3.0, 4.0, 5.0, 6.0});
  }

  private void fftwInplaceTranspose(int rows, int cols, double[] data) {
    try (PointerScope pointerScope = new PointerScope()) {
      IntPointer ptr = new IntPointer(rows, 1, cols, cols, rows, 1);
      int howmany_rank = 2;
      DoublePointer in = new DoublePointer(data);
      fftw3.fftw_plan plan = fftw_plan_guru_r2r(0, null, howmany_rank, new fftw_iodim(ptr), in, in, null, FFTW_ESTIMATE);
      fftw_execute(plan);
      fftw_destroy_plan(plan);

      System.out.println("FFTW:");
      for (int i = 0; i < data.length; i++) {
        System.out.println(in.get(i));
      }
    }
  }

  private void mklInplaceTranspose(int rows, int cols, double[] data) {
    System.out.println("MKL:");
    try (PointerScope pointerScope = new PointerScope()) {
      mkl_dimatcopy((byte) 'c', (byte) 't', rows, cols, 1.0, data, rows, cols);
      for (int i = 0; i < data.length; i++) {
        System.out.println(data[i]);
      }
    }
  }
```

Output:
```bash
FFTW:
1.0
4.0
2.0
5.0
3.0
6.0
MKL:
1.0
4.0
2.0
5.0
3.0
6.0
✅
```

If `mklInplaceTranspose(...)` is called first, the fftw doesn't work:
```bash
MKL:
1.0
4.0
2.0
5.0
3.0
6.0
FFTW:
1.0
2.0
3.0
4.0
5.0
6.0
❌
```

I've tried implementing this directly with JNI and it seems to be that once the MKL libraries are loaded by the ClassLoader, the original FFTW routines are not called any more. This is problematic because the MKL interfaces don't have some of the functionality that the original FFTW has.

Tried [this](https://community.intel.com/t5/Intel-oneAPI-Math-Kernel-Library/How-to-use-both-FFTW3-and-MKL/td-p/1018724) in JNI but could not get it to work.

Any thoughts on how to work with both MKL and FFTW at the same time?

Many thanks!

**Comment by saudet** [comment]
Yeah, MKL is problematic is a variety of ways. If OpenBLAS does what you need, please use that
