### ISSUE TITLE
HI ,when we will relese javacpp pytorch  for PyTorch 2.5.0 https://pytorch.org/

### ISSUE THREAD

**Issue by mullerhai** [bytedeco/javacpp-presets#1547]
Hi, we need  PyTorch 2.5.0 particular ,so I wanna know when we will releses  pytorch 2.5 version  package, now only snapshot.
thanks

**Comment by saudet** [comment]
Sometime before the end of the year?

In any case, please test with 2.5.1, not 2.5.0:
https://oss.sonatype.org/content/repositories/snapshots/org/bytedeco/pytorch/2.5.1-1.5.11-SNAPSHOT/
