### ISSUE TITLE
[HDF5] building on an arm64 Linux machine

### ISSUE THREAD

**Issue by grohli** [bytedeco/javacpp-presets#1552]
Hi,

I encountered some issues trying to build the hdf5 library into a `hdf5-linux-arm64.jar`: it seems as though in [hdf5/cppbuild.sh, there's a platform check to make sure we're compiling for the right machine type](https://github.com/bytedeco/javacpp-presets/blob/2d25547d3206f256146e6b34ed1af5d5bfc6a5e6/hdf5/cppbuild.sh#L92). I encountered two problems that arose from this while building on an arm64 Linux machine: 
1) the name of my machine isn't arm64, it's aarch64, so the current cppbuild.sh doesn't actually hit the proper if statement (rather it thinks I'm cross compiling and goes to the else statement); and 
2) even when changing the if statement to be `if [[ "$MACHINE_TYPE" =~ aarch64 ]];` the command in the if statement fails because of its `-m64` flags for `gcc` and `g++`.

I made a workaround by changing those lines to be:
```
linux-arm64)
        ...
        ...
        MACHINE_TYPE=$( uname -m )
        if [[ "$MACHINE_TYPE" =~ aarch64 ]]; then
          ./configure --prefix=$INSTALL_PATH CC="gcc" CXX="g++" --enable-cxx --enable-java
          make -j $MAKEJ
          make install-strip
```

Which generates a proper `hdf5-linux-arm64.jar` file.

**Comment by saudet** [comment]
Sounds good, please open a pull request!

**Comment by grohli** [comment]
Done and done https://github.com/bytedeco/javacpp-presets/pull/1553
