### ISSUE TITLE
javacpp-presets cppbuild.sh fails

### ISSUE THREAD

**Issue by lobsteroh** [bytedeco/javacpp-presets#156]
hi all,

am returning to troubleshoot some install instructions in a blog and what used to work before, seems to fail now. here is what i did in case you want to reproduce the issue ... i am on mac osx 10.11.3

    $ git clone https://github.com/bytedeco/javacpp-presets.git
    $ cd javacpp-presets
    $ bash cppbuild.sh -platform macosx-x86_64 install

this chugs along with a lot of general comments such as 

    /opt/local/bin/ranlib: file: /Users/lobsterman/Documents/workspace/javacpp-presets/ffmpeg/cppbuild/macosx-x86_64/lib/libssl.a.new(kssl.o) has no symbols

i assume these are ok to ignore ... but then it fatally drops (in ffmpeg) with 

    nasm -DUNIX64 -DPREFIX -f macho64 -I./codec/common/x86/   -o codec/common/x86/intra_pred_com.o codec/common/x86/intra_pred_com.asm
    nasm: nasm: fatal: fatal: unrecognised output format `macho64' - use -hf for a listunrecognised output format `macho64' - use -hf for a list
    type `nasm -h' for help

    type `nasm -h' for help
    nasm: fatal: unrecognised output format `macho64' - use -hf for a list
    type `nasm -h' for help
    nasm: fatal: unrecognised output format `macho64' - use -hf for a list
    type `nasm -h' for help
    make: *** [codec/common/x86/expand_picture.o] Error 1
    make: *** Waiting for unfinished jobs....
    make: *** [codec/common/x86/intra_pred_com.o] Error 1
    make: *** [codec/common/x86/deblock.o] Error 1
    make: *** [codec/common/x86/cpuid.o] Error 1

it appears that that cannot be ignored because subsequent  call to install libdc1294 ...

    $ mvn clean install --projects .,libdc1394

fails with ...

    [INFO] Targeting /Users/lobsterman/Documents/workspace/javacpp-presets/libdc1394/src/main/java/org/bytedeco/javacpp/dc1394.java
    [ERROR] Failed to execute JavaCPP Builder: Could not parse "dc1394/dc1394.h": File does not exist
    [INFO] ------------------------------------------------------------------------
    [INFO] Reactor Summary:
    [INFO] 
    [INFO] JavaCPP Presets .................................... SUCCESS [  5.172 s]
    [INFO] JavaCPP Presets for libdc1394 ...................... FAILURE [  3.888 s]
    [INFO] ------------------------------------------------------------------------
    [INFO] BUILD FAILURE
    [INFO] ------------------------------------------------------------------------
    [INFO] Total time: 11.105 s
    [INFO] Finished at: 2016-02-18T10:45:09-05:00
    [INFO] Final Memory: 25M/164M
    [INFO] ------------------------------------------------------------------------

any suggested way to fix?

also just to confirm that mvn install for opencv still works ...

    $ mvn clean install --projects .,opencv

with 

    INFO] Installing /Users/lobsterman/Documents/workspace/javacpp-presets/opencv/target/opencv-javadoc.jar to /Users/lobsterman/.m2/repository/org/bytedeco/javacpp-presets/opencv/3.1.0-1.2-SNAPSHOT/opencv-3.1.0-1.2-SNAPSHOT-javadoc.jar
    [INFO] ------------------------------------------------------------------------
    [INFO] Reactor Summary:
    [INFO] 
    [INFO] JavaCPP Presets .................................... SUCCESS [  0.704 s]
    [INFO] JavaCPP Presets for OpenCV ......................... SUCCESS [03:01 min]
    [INFO] ------------------------------------------------------------------------
    [INFO] BUILD SUCCESS
    [INFO] ------------------------------------------------------------------------
    [INFO] Total time: 03:03 min
    [INFO] Finished at: 2016-02-18T10:59:57-05:00
    [INFO] Final Memory: 45M/742M
    [INFO] ------------------------------------------------------------------------

thanks, ciao,

**Comment by saudet** [comment]
As documented [here](https://github.com/bytedeco/javacpp-presets/wiki/Build-Environments#mac-os-x-x86_64), please install Homebrew run the following commands
```
$ brew install caskroom/cask/brew-cask
$ brew cask install cuda java
$ brew install bazel cmake libusb maven nasm yasm xz
```

**Comment by lobsteroh** [comment]
just a quick confirm for anyone ending up in this thread - the solution worked

the buildscript prompted question:

    Do you wish to build TensorFlow with GPU support? [y/N] 

answer (N) is ok, while answer (y) leads to 

    Please specify the Cuda SDK version you want to use, e.g. 7.0. [Leave empty to use system default]: 
    Please specify the location where CUDA  toolkit is installed. Refer to README.md for more details. [Default is /usr/local/cuda]: 
    Invalid path to CUDA  toolkit. /usr/local/cuda/lib64/libcudart.so cannot be found

i can find no file with that name on my machine, so suggested answer is N :-) in any case,

    $ mvn clean install --projects .,libdc1394

now results in build success :-), thanks saudet

**Comment by lobsteroh** [comment]
however, I do have file ...

    /usr/local/cuda/lib/libcudart.dylib

**Comment by saudet** [comment]
Right, if the only thing you're interested in is libdc1394, for sure don't try to install the tensorflow module ;)
