### ISSUE TITLE
Building javacpp-presets HEAD

### ISSUE THREAD

**Issue by pcmoritz** [bytedeco/javacpp-presets#157]
Dear all,

if I try to build the javacpp-presets from the git head (for example commit `db27cf52`) with the following command:
```
mvn clean install -Djavacpp.platform=linux-x86_64 --projects .
```

I get this error message:
```
[ERROR] Failed to execute goal on project javacpp-presets: Could not resolve dependencies for project org.bytedeco:javacpp-presets:pom:1.2-SNAPSHOT: Could not find artifact org.bytedeco:javacpp-presets:jar:linux-x86_64:1.2-SNAPSHOT -> [Help 1]
```

With previous versions (where javacpp-presets:jar:linux-x86_64 is presumably loaded from the online maven repo) it works. Why is it not built? Let me know if you have an idea how to fix this.

Thanks,
Philipp.

**Comment by saudet** [comment]
Try to add `-Djavacpp.platform.dependency=false` to the command. 

I'm trying to use a buggy feature that was fixed only in Maven 3.2.2 apparently: 
https://issues.apache.org/jira/browse/MNG-4565
Let's see how much trouble that causes or not...

**Comment by pcmoritz** [comment]
Thanks a lot for the quick response, that did the trick

**Comment by pcmoritz** [comment]
I updated the wiki according to the fix suggestion

**Comment by saudet** [comment]
Good idea, thanks!
