### ISSUE TITLE
[Tensorflow] Reading out attributes from NodeDef

### ISSUE THREAD

**Issue by pcmoritz** [bytedeco/javacpp-presets#162]
I am trying to read out shape information from TensorFlow placeholders at the moment (these are the input nodes of a Tensorflow graph). For this, access to the attr field of NodeDef is required. The definition is as follows (see `tensorflow/core/framework/graph.proto`):

```proto
message NodeDef {
  // stuff
  map<string, AttrValue> attr = 5;
}
```
and the generated code I am interested in wrapping looks like this (see `graph.pb.h` generated by BAZEL):
```cpp
  ::google::protobuf::Map< ::std::string, ::tensorflow::AttrValue >*
      mutable_attr();
```
With current master, the parser doesn't seem to be able to handle this. I tried to add
```java
.put(new Info("std::map<std::string,tensorflow::AttrValue>").pointerTypes("StringAttributes").define())
```
in the tensorflow.java configuration file and this leads to StringAttribute being defined which looks reasonable, but the field is still not wrapped.

Any help on this is appreciated!

**Comment by saudet** [comment]
It doesn't look like it's `std::map` itself, so we'll need to tell JavaCPP about that container type first. Something like this should work, but haven't tested it yet:
```java
.put(new Info("basic/containers").cppTypes("google::protobuf::Map")
.put(new Info("google::protobuf::Map<std::string,tensorflow::AttrValue>").pointerTypes("StringAttributes").define())
```

**Comment by pcmoritz** [comment]
awesome, thanks

tested it and your fix works, I created a pull request
