### ISSUE TITLE
Cannot execute a Ffmpeg command

### ISSUE THREAD

**Issue by ChristopheCVB** [bytedeco/javacpp-presets#171]
How to execute a Ffmpeg command with that library on Android ?

After adding `compile 'org.bytedeco.javacpp-presets:ffmpeg:2.8.1-1.1'` to my build.gradle, how can I call the `ffmpeg.main` method ?

Do I need to compile it specifically for ARM and x86 or it already comes compiled ?

**Comment by saudet** [comment]
The archive doesn't contain the `ffmpeg` application. If that's what you're looking for you'll need to either look for it elsewhere or compile it yourself. The `cppbuild.sh` script should help you get started.

**Comment by saudet** [comment]
With commit https://github.com/bytedeco/javacpp-presets/commit/13ffffd191fa48d9d9d1d8a64e0c4d64c9da1134 the `ffmpeg` program now gets bundled and can be used easily from Java! Please give it a try with 1.5-SNAPSHOT before the release: http://bytedeco.org/builds/
