### ISSUE TITLE
using gsl with shared libcblas instead of javacpp's provided libgslblas

### ISSUE THREAD

**Issue by blueberry** [bytedeco/javacpp-presets#18]
Hi, thank you for this fantastic project. I imported the library, an it works.

I would like to use atlas blas implementation for the blas part of gsl. In c, that would mean changing the make file to link libcblas and/or atlas instead of libgslblas. However, javacpp provides the prepackaged build that ignores system's files and uses the one provided in a platform jar.
Is there a way to specify which (shared) libraries to use instead of the ones provided inside jars?

If I'd have to build javacpp's gsl manually, where should i change the libcblas setting?

**Comment by saudet** [comment]
It's been a while, but with the commit above, presets for GSL now link automatically with OpenBLAS, MKL, Accelerate, etc instead of GSL CBLAS, and they do not try to catch C++ exceptions anymore, so they should be pretty much as fast as manually written JNI wrapper code.
