### ISSUE TITLE
Failed to execute goal on project javacpp-presets

### ISSUE THREAD

**Issue by coralinejones1985** [bytedeco/javacpp-presets#180]
Hello. I'm trying to build x86 android version, but I get "Failed to execute goal on project javacpp-presets: Could not resolve dependencies for project org.bytedeco:javacpp-presets:pom:1.2-SNAPSHOT: Could not find artifact org.bytedeco:javacpp-presets:jar:android-x86:1.2-SNAPSHOT" error.
I followed this instruction: https://github.com/bytedeco/javacpp-presets/wiki/Build-Environments
Here's the output:
                                                                      
[INFO] ------------------------------------------------------------------------
[INFO] Building JavaCPP Presets 1.2-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] JavaCPP Presets ................................... FAILURE [0.073s]
[INFO] JavaCPP Presets for OpenCV ........................ SKIPPED
[INFO] JavaCPP Presets for FFmpeg ........................ SKIPPED
[INFO] JavaCPP Presets for FlyCapture .................... SKIPPED
[INFO] JavaCPP Presets for libdc1394 ..................... SKIPPED
[INFO] JavaCPP Presets for libfreenect ................... SKIPPED
[INFO] JavaCPP Presets for videoInput .................... SKIPPED
[INFO] JavaCPP Presets for ARToolKitPlus ................. SKIPPED
[INFO] JavaCPP Presets for Chilitags ..................... SKIPPED
[INFO] JavaCPP Presets for flandmark ..................... SKIPPED
[INFO] JavaCPP Presets for FFTW .......................... SKIPPED
[INFO] JavaCPP Presets for GSL ........................... SKIPPED
[INFO] JavaCPP Presets for LLVM .......................... SKIPPED
[INFO] JavaCPP Presets for Leptonica ..................... SKIPPED
[INFO] JavaCPP Presets for Tesseract ..................... SKIPPED
[INFO] JavaCPP Presets for Caffe ......................... SKIPPED
[INFO] JavaCPP Presets for CUDA .......................... SKIPPED
[INFO] JavaCPP Presets for MXNet ......................... SKIPPED
[INFO] JavaCPP Presets for TensorFlow .................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.558s
[INFO] Finished at: Mon Mar 14 13:09:36 KRAT 2016
[INFO] Final Memory: 12M/150M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project javacpp-presets: Could not resolve dependencies for project org.bytedeco:javacpp-presets:pom:1.2-SNAPSHOT: Could not find artifact org.bytedeco:javacpp-presets:jar:android-x86:1.2-SNAPSHOT`

**Comment by saudet** [comment]
You're using an old version of Maven... See #157 for workaround

**Comment by coralinejones1985** [comment]
Thank you, @saudet it helped me, but now I'm getting:
Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.4.0:exec (javacpp.cppbuild) on project ffmpeg: Command execution failed. Process exited with an error: 77 (Exit value: 77)

**Comment by saudet** [comment]
I wonder what that means... Anyway we can skip that with `-Djavacpp.cppbuild.skip`.

**Comment by saudet** [comment]
I guess it's this error#define EX_NOPERM       77  /* permission denied */

**Comment by coralinejones1985** [comment]
Thank you very much. Jars that I need are generated! :) 

I've built 1.2-SNAPSHOT (javacv, javacpp, ffmpeg and opencv jars) to get "no relocations"-version, but still got ones. Also some errors appeared:
Failed to load class org.bytedeco.javacv.FFmpegFrameRecorder 
NoClassDefFoundError: java.lang.ClassNotFoundException: org.bytedeco.javacpp.avutil
UnsatisfiedLinkError: dlopen failed: /lib/x86/libavcodec.so: has text relocations

**Comment by saudet** [comment]
Make sure to delete everything and reclone everything from scratch...

**Comment by coralinejones1985** [comment]
I removed everything and built it again from scratch and it didn't work out..

**Comment by coralinejones1985** [comment]
@saudet when do you plan to make 1.2-SNAPSHOT release?

**Comment by saudet** [comment]
If you could pinpoint the library that causes those text relocations, it would help.

About the release, I don't know. Sooner than later I hope :)

**Comment by coralinejones1985** [comment]
I think it was ffmpeg. I tried to biuld presets for android x86

**Comment by saudet** [comment]
Version 1.2 has been released. Enjoy!
