### ISSUE TITLE
How to convert opencv_core.Mat to Bitmap object in android application?

### ISSUE THREAD

**Issue by playeryan** [bytedeco/javacpp-presets#185]
Hi bytedeco:
I'm a beginner on android developing and image processing.
Recently I have a problem. After image processing, I should store images or do other things. But I don't know how to convert opencv_core.Mat object to Bitmap object in android application.
So how can I get Bitmap from opencv_core.Mat?

I appreciate for your help.

**Comment by playeryan** [comment]
P.S.
And accordingly, how to convet Bitmap to opencv_core.Mat in android application?

**Comment by saudet** [comment]
With AndroidFrameConverter and OpenCVFrameConverter:
http://bytedeco.org/javacv/apidocs/org/bytedeco/javacv/AndroidFrameConverter.html
http://bytedeco.org/javacv/apidocs/org/bytedeco/javacv/OpenCVFrameConverter.html

As explained here:
http://bytedeco.org/news/2015/04/04/javacv-frame-converters/

**Comment by playeryan** [comment]
@saudet 
At the suggestion of your comment, I convert bitmap and store images successfully. 
Thank you very much! You've been very helpful.
