### ISSUE TITLE
How to step over the cppbuild.sh?

### ISSUE THREAD

**Issue by zjulzq** [bytedeco/javacpp-presets#186]
In my case, I get an API with 4 header files and 2 so files. But there is no way to obtain the source code. Can I step over the `cppbuild.sh`? How to generate the required jar from the header files and so files?

**Comment by saudet** [comment]
Sure, just skip over the `exec-maven-plugin`, either through it's own configuration or by setting the `javacpp.cppbuild.skip` property.

**Comment by saudet** [comment]
The rest of the steps are explained on this page:
https://github.com/bytedeco/javacpp-presets/wiki/Create-New-Presets
