### ISSUE TITLE
This happens on phones which called "LeTV". What is the problem？

### ISSUE THREAD

**Issue by weining** [bytedeco/javacpp-presets#193]
dlopen("/data/app/com.baidu.exp.cam-1/lib/arm/libjniavutil.so", RTLD_LAZY) failed: dlopen failed: cannot locate symbol "av_fifo_generic_peek" referenced by "libjniavutil.so"...

Other phones are fine. No crash. Must I build arm64 so for it？

**Comment by saudet** [comment]
64-bit phones support 32-bit binaries just fine, that's the the issue. Could you try these SNAPSHOT binaries and let me know if they work any better?
https://oss.sonatype.org/content/repositories/snapshots/org/bytedeco/javacpp/1.2-SNAPSHOT/
https://oss.sonatype.org/content/repositories/snapshots/org/bytedeco/javacpp-presets/ffmpeg/3.0-1.2-SNAPSHOT/
https://oss.sonatype.org/content/repositories/snapshots/org/bytedeco/javacv/1.2-SNAPSHOT/
Thanks

**Comment by saudet** [comment]
Anyway, should be fixed with version 1.2, so please try again and let me know if you still have any problems! Thanks
