### ISSUE TITLE
Compiling opencv preset Mac El Capitan

### ISSUE THREAD

**Issue by gunther82** [bytedeco/javacpp-presets#194]
Has someone been able to compile the opencv preset 3.1.0 on OSX El Capitan version 10.11.4?
I followed the instruction here (https://github.com/bytedeco/javacpp-presets/wiki/Build-Environments#mac-os-x-x86_64), but I got a lot of errors.

**Comment by saudet** [comment]
Could you provide a sample of these errors?

**Comment by gunther82** [comment]
Here you can find the complete list of the errors I got:
https://www.dropbox.com/s/zhh7paln3ow9xgc/javacv-preset%20opencv%20MAC%20error.txt?dl=0

**Comment by saudet** [comment]
Looks like a problem with OpenCV. Could you report that upstream and ask clarifications on their support for OS X 10.11.4? It would be very helpful! Thanks in advance

**Comment by saudet** [comment]
Have you reported it upstream? If so, please provide a link here so we can track the progress. Thanks!

**Comment by saudet** [comment]
OpenCV 3.4.0 now builds fine on Mac:
https://github.com/bytedeco/javacpp-presets/tree/master/opencv
