### ISSUE TITLE
cudnn5.0 support

### ISSUE THREAD

**Issue by yunge** [bytedeco/javacpp-presets#199]
Nvidia just released cudnn5.0 with RNN/Dropout support，could you please update to it? thanks.

**Comment by saudet** [comment]
Should be pretty easy to do. Could you give it a try by changing the version in presets/cudnn.java and send a pull request?

**Comment by yunge** [comment]
I checked, there are some new structs such as cudnnRNNDescriptor_t/cudnnDropoutDescriptor_t, and I'm not fimilar with cuda & javacpp, so maybe others will do it better than me, I apologize.

**Comment by saudet** [comment]
We just need to replicate what's being done for the other structs...

**Comment by saudet** [comment]
Ok, it's in: https://github.com/bytedeco/javacpp-presets/commit/bfa77a2f8bd474440c25553bdcb6e413cd5ec467

**Comment by yunge** [comment]
Thanks. I apologize again that I'm really unfamiliar with cpp and afraid to ruin the code.

**Comment by saudet** [comment]
Included in the release of version 1.2. Enjoy!
