### ISSUE TITLE
Why its not working ?

### ISSUE THREAD

**Issue by knaytac** [bytedeco/javacpp-presets#202]
```
cam.Connect(guid);
            			cam.StartCapture();	
            		    int fcc =VideoWriter.fourcc('D','I','V','3');
            			org.bytedeco.javacpp.opencv_core.Size frameSize =new org.bytedeco.javacpp.opencv_core.Size(1920,1200);
            			writer=new org.bytedeco.javacpp.opencv_videoio.VideoWriter(textField.getText()+"\\"+Integer.toString(sayi)+".avi",fcc,fps,frameSize);
            			bayrak=false;
            			}
            			cam.RetrieveBuffer(rawImage);
            			org.bytedeco.javacpp.FlyCapture2.Image rgbImage=new org.bytedeco.javacpp.FlyCapture2.Image(); 
            			rawImage.Convert(PIXEL_FORMAT_MONO8, rgbImage);
            			double rowBytes = (double)rgbImage.GetReceivedDataSize()/(double)rgbImage.GetRows();
            			org.bytedeco.javacpp.opencv_core.Mat cvframe = new org.bytedeco.javacpp.opencv_core.Mat(rgbImage.GetRows(), rgbImage.GetCols(), CvType.CV_8UC3,rgbImage.GetData(), (int)rowBytes);
            			
            			
//            			byte[] data = new byte[1920 * 1200 * (int)cvframe.elemSize()];
            			BytePointer outputPointer = new BytePointer();
           			    org.bytedeco.javacpp.opencv_imgcodecs.imencode(".bmp", cvframe, outputPointer);
           			    byte[] outputBuffer = new byte[outputPointer.limit()];
           			    outputPointer.get(outputBuffer);
           			    BufferedImage buff = new BufferedImage(1920,1200,BufferedImage.TYPE_3BYTE_BGR);
            			buff.getRaster().setDataElements(0, 0, 1920,1200,outputBuffer);
```

**Comment by saudet** [comment]
What doesn't work? Could you also provide the error message you are getting?

**Comment by knaytac** [comment]
I think problem is in that line:
org.bytedeco.javacpp.opencv_imgcodecs.imencode(".bmp", cvframe, outputPointer);

and the problem is there is no error message.when I try to compile it , Java stops working immediately. I tried to change extensions ".bmp" ".jpg" ".jpeg" but its not working.

**Comment by saudet** [comment]
Does it work any better initializing the outputPointer this way?
```
BytePointer outputPointer = new BytePointer(null);
```

**Comment by knaytac** [comment]
No it says "The constructor BytePointer(String) is ambiguous"
and I am sorry I forgot to tell that I am working with java

**Comment by saudet** [comment]
Yes, that's alright. Sorry, I meant `BytePointer outputPointer = new BytePointer((Pointer)null);`

**Comment by knaytac** [comment]
I am sure its better now :D thank you but I am getting error again in this line 
org.bytedeco.javacpp.opencv_imgcodecs.imencode(".bmp", cvframe, outputPointer);
is there any alternative for converting it to bufferedImage?

**Comment by saudet** [comment]
With Java2DFrameConverter and OpenCVFrameConverter:
http://bytedeco.org/javacv/apidocs/org/bytedeco/javacv/Java2DFrameConverter.html
http://bytedeco.org/javacv/apidocs/org/bytedeco/javacv/OpenCVFrameConverter.html

As explained here:
http://bytedeco.org/news/2015/04/04/javacv-frame-converters/
