### ISSUE TITLE
torch7 preset

### ISSUE THREAD

**Issue by edudar** [bytedeco/javacpp-presets#203]
`torch7` is another popular deep learning framework along with `caffe` and `tensorflow`. It would be very helpful to have similar bindings to Java for it

**Comment by saudet** [comment]
According to https://github.com/torch/torch7/issues/477 there's not much documentation for the C backend apparently. So, I'm not sure what the demand for this would be, but if you're willing to give it a try, sure.

**Comment by saudet** [comment]
FIY, this seems to have a better C/C++ API: 
https://github.com/pytorch/pytorch/tree/master/torch/lib

/cc @ctongfei

**Comment by saudet** [comment]
PyTorch now has a more complete C++ API, and I think it makes more sense to use that these, so marking as duplicate of #623.
