### ISSUE TITLE
Use Mac rebuild for android

### ISSUE THREAD

**Issue by martinLilili** [bytedeco/javacpp-presets#204]
My system is OS X EI Caption, but I want rebuild the javacv for android,
My command is :
`$ mvn install --projects ffmpeg -Djavacpp.platform=android-arm -Djavacpp.platform.root=/Users/martin/Development/Android/android-ndk-r10e/ -Djavacpp.platform.compiler=/Users/martin/Development/Android/android-ndk-r10e/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-g++`

ffmpeg is build fine,but the last step come out a error :

`[INFO] --- maven-compiler-plugin:3.3:compile (default-compile) @ ffmpeg ---

[INFO] Changes detected - recompiling the module!
[INFO] Compiling 8 source files to /Users/martin/Downloads/javacpp-presets/ffmpeg/target/classes
[INFO] /Users/martin/Downloads/javacpp-presets/ffmpeg/src/main/java/org/bytedeco/javacpp/avutil.java: Some input files use unchecked or unsafe operations.
[INFO] /Users/martin/Downloads/javacpp-presets/ffmpeg/src/main/java/org/bytedeco/javacpp/avutil.java: Recompile with -Xlint:unchecked for details.
[INFO] 
[INFO] --- javacpp:1.2-SNAPSHOT:build (javacpp.compiler) @ ffmpeg ---
[INFO] Generating /Users/martin/Downloads/javacpp-presets/ffmpeg/target/classes/org/bytedeco/javacpp/jniavcodec.cpp
[INFO] Compiling /Users/martin/Downloads/javacpp-presets/ffmpeg/target/classes/org/bytedeco/javacpp/android-arm/libjniavcodec.dylib
[WARNING] Could not get the property named "platform.compiler.nodeprecated"
[INFO] /Users/martin/Development/Android/android-ndk-r10e/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-g++ /Users/martin/Downloads/javacpp-presets/ffmpeg/cppbuild/android-arm/include/ /Users/martin/Downloads/javacpp-presets/ffmpeg/target/classes/org/bytedeco/javacpp/jniavcodec.cpp libjniavcodec.dylib /Users/martin/Downloads/javacpp-presets/ffmpeg/cppbuild/android-arm/lib/ avcodec swresample avutil 
arm-linux-androideabi-g++: error: libjniavcodec.dylib: No such file or directory
arm-linux-androideabi-g++: error: avcodec: No such file or directory
arm-linux-androideabi-g++: error: swresample: No such file or directory
arm-linux-androideabi-g++: error: avutil: No such file or directory`

Why need libjniavcodec.dylib??    how to fix it?
someone please help me, thanks!

**Comment by saudet** [comment]
It just looks like your system is picking up a very old version of JavaCPP. Try to run `mvn install` on the latest code from the master branch of the javacpp repository as well.

**Comment by martinLilili** [comment]
thinks, it worked for me. maybe something I changed before caused the prpblem
