### ISSUE TITLE
flycapture save Image to avi

### ISSUE THREAD

**Issue by knaytac** [bytedeco/javacpp-presets#205]
```
AVIOption option;
AVIRecorder aviRecorder;

cam.Connect(guid);
cam.StartCapture();
float fps = 10 ;
option.frameRate(fps);
aviRecorder.AVIOpen("sa", option);
cam.RetrieveBuffer(rawImage);
aviRecorder.AVIAppend(rawImage);
```
Hey its me again I dont know what am I doing wrong I just want to grab frames from cam and save into to avi file and no problem about the grabbing frames from cam

**Comment by saudet** [comment]
This doesn't look like wrappers created with JavaCPP. If you'd like to use something done with JavaCPP, try FlyCaptureFrameGrabber and FFmpegFrameRecorder from JavaCV.
