### ISSUE TITLE
cannot build with ndk-r10e.

### ISSUE THREAD

**Issue by breezehou** [bytedeco/javacpp-presets#208]
OS: OS X 10.11.4

Steps:
1. Execute 'ANDROID_NDK=~/Downloads/android-ndk-r10e bash cppbuild.sh -platform android-xxx install'

Logs:
... ...
x opencore-amr-0.1.3/opencore/codecs_v2/audio/gsm_amr/common/dec/include/pvgsmamrdecoderinterface.h: (Empty error message)
tar: Error exit delayed from previous errors.

**Comment by saudet** [comment]
Delete the downloads directory and try again.

**Comment by breezehou** [comment]
Still build failed.
... ...
x opencv_contrib-3.1.0/samples/python2/common.py
x opencv_contrib-3.1.0/samples/python2/seeds.py
x opencv_contrib-3.1.0/samples/python2/video.py
CMake Error at platforms/android/android.toolchain.cmake:809 (message):
  Specified Android native API level 'android-8' is not supported by your
  NDK/toolchain.
Call Stack (most recent call first):
  CMakeFiles/3.2.3/CMakeSystem.cmake:6 (include)
  CMakeLists.txt:93 (project)

**Comment by saudet** [comment]
It works fine here, but if you still have problems, that would be something to report upstream!
