### ISSUE TITLE
Error: Specified Android native API level 'android-8' is not supported by your   NDK/toolchain.

### ISSUE THREAD

**Issue by breezehou** [bytedeco/javacpp-presets#209]
Logs:
... ...
x opencv_contrib-3.1.0/samples/python2/
x opencv_contrib-3.1.0/samples/python2/common.py
x opencv_contrib-3.1.0/samples/python2/seeds.py
x opencv_contrib-3.1.0/samples/python2/video.py
CMake Error at platforms/android/android.toolchain.cmake:809 (message):
  Specified Android native API level 'android-8' is not supported by your
  NDK/toolchain.
Call Stack (most recent call first):
  CMakeFiles/3.2.3/CMakeSystem.cmake:6 (include)
  CMakeLists.txt:93 (project)

**Comment by saudet** [comment]
It works fine here, so like I said, could you please report this upstream to the developers of OpenCV?

**Comment by breezehou** [comment]
OK. I See.

**Comment by alexkarargyris** [comment]
@breezehou I face same error. How did you resolve this?

**Comment by akhilc1** [comment]
I am getting this error as well, I posted a question in the opencv github page asking how to set native android api level but they closed the issue.

**Comment by hannesa2** [comment]
I was able to solve this issue with
`./scripts/cmake_android_arm.sh -DANDROID_NATIVE_API_LEVEL=android-15`
but then the next issue raises
