### ISSUE TITLE
Error: javacpp-presets/ffmpeg/cppbuild/android-arm/ssl/man/man3/hmac.3: Too many levels of symbolic links

### ISSUE THREAD

**Issue by breezehou** [bytedeco/javacpp-presets#210]
Version: 1.2-SNAPSHOT
OS: Mac 10.11.4
NDK: r10e
Logs:
... ...
installing man3/engine.3
installing man3/err.3
installing man3/evp.3
installing man3/hmac.3
/bin/sh: ~/Downloads/gitrepo/javacpp-presets/ffmpeg/cppbuild/android-arm/ssl/man/man3/hmac.3: Too many levels of symbolic links
make: *** [install_docs] Error 1

**Comment by saudet** [comment]
Could you modify the script to not install the docs and try again? Let me know if that works! Thanks

**Comment by breezehou** [comment]
@saudet It works!

**Comment by saudet** [comment]
Great! Could you send a pull request with the modifications?

**Comment by breezehou** [comment]
@saudet The makefile is in openssl-1.0.2g.tar.gz, I removed <install_docs> option, and repack it.
