### ISSUE TITLE
Error: unzip:  cannot find zipfile directory in one of ../libfreenect-0.5.3.zip

### ISSUE THREAD

**Issue by breezehou** [bytedeco/javacpp-presets#212]
Version: 1.2-SNAPSHOT
OS: Mac 10.11.4
NDK: r10e
Logs:
... ...
Installing "libfreenect"
~/Downloads/gitrepo/javacpp-presets/libfreenect/cppbuild ~/Downloads/gitrepo/javacpp-presets
Archive:  ../libfreenect-0.5.3.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of ../libfreenect-0.5.3.zip or
        ../libfreenect-0.5.3.zip.zip, and cannot find ../libfreenect-0.5.3.zip.ZIP, period.

**Comment by saudet** [comment]
Like I said, could you fix all those errors and send a pull request with the patch to fix all this? It would help a lot. Thanks!

**Comment by breezehou** [comment]
It downloads failed. It is ok after download again.
