### ISSUE TITLE
maven can not find tensorflow preset

### ISSUE THREAD

**Issue by dtracers** [bytedeco/javacpp-presets#213]
I am trying to use the pom file of the example but it keeps saying that there is no artifact with the given example.  And I can not find it on maven central even though a majority of the presets still exist

**Comment by dtracers** [comment]
It appears in the 1.1 build opencv does not compile.

Log https://jitpack.io/com/github/bytedeco/javacpp-presets/1.1/build.log

**Comment by saudet** [comment]
Could you try the latest code from the master branches?

**Comment by saudet** [comment]
Version 1.2 has been released with binaries for TensorFlow on the Maven Central Repository. Enjoy!
