### ISSUE TITLE
today's troublesome build fixes

### ISSUE THREAD

**Issue by jamesneville** [bytedeco/javacpp-presets#215]
Hi all,

Been trying to build this all day, and the wiki didn't quite cover all the steps required for a Mac OS X build.
Here's what I needed to do to get it working. 

'# xcode-select --install'
'# /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"'
'# brew install caskroom/cask/brew-cask'
'# brew cask install cuda java'
'# brew install bazel cmake libusb maven nasm yasm xz'
'# brew install pkg-config'
'# brew install clang-omp'
'# brew install swig'
'# bash cppbuild.sh install'

Hope this helps someone - the build takes a very, very, very, verrrrryyyyyyyy long time :-)

**Comment by saudet** [comment]
Thanks! Please update the wiki file

**Comment by jamesneville** [comment]
Sorted - close this then :-)

**Comment by saudet** [comment]
Great! Thanks
