### ISSUE TITLE
Unable to obtain 64 bit libraries from maven

### ISSUE THREAD

**Issue by mtadmk** [bytedeco/javacpp-presets#223]
I want to run javacpp-presets ffmpeg with 64 bit java. In pom.xml 
```xml
<dependency>
            <groupId>org.bytedeco.javacpp-presets</groupId>
            <artifactId>ffmpeg</artifactId>
            <version>2.8.1-1.1</version>
            <classifier>windows-x86_64</classifier>
        </dependency>
```
was added to get 64 bit libraries from maven. 
Native libs seems to be downloaded however there is no ffmpeg java library. [screen](https://dl.dropboxusercontent.com/u/13951446/screen1.png).
Is it possible to get 64 bit libraries or should I build it manually?

**Comment by saudet** [comment]
You also need to add a dependency for the artifact containing the Java classes:
```xml
<dependency>
    <groupId>org.bytedeco.javacpp-presets</groupId>
    <artifactId>ffmpeg</artifactId>
    <version>2.8.1-1.1</version>
</dependency>
```
