### ISSUE TITLE
tessedit_write_images has no effect

### ISSUE THREAD

**Issue by saywow95** [bytedeco/javacpp-presets#226]
Hi,
I can't get the resulting tessinput.tif by setting tessedit_write_images to true : 

```
def my_method(File image) {
        BytePointer output;
        TessBaseAPI tessBaseAPI = new TessBaseAPI();
        if (tessBaseAPI.Init(".", "ENG") != 0) {
            //..
        }
        //returns true : 
        tessBaseAPI.SetVariable("tessedit_write_images","true")
        PIX temp = pixRead(image.getAbsolutePath())
        tessBaseAPI.SetImage(temp)
        output = tessBaseAPI.GetUTF8Text()
        String contenu = output.getString()
        tessBaseAPI.End()
        output.deallocate()
        image.delete()
        pixDestroy(temp)
        ....
    }
```

Am I doing something wrong? where am I supposed to find the file?

**Comment by saudet** [comment]
What is that code supposed to do? Where should that file get written to?

**Comment by saywow95** [comment]
this code is returning the image's text, I supposed that when I set "tessedit_write_images" to "true" or "1" the picture will be written to the application's root folder or in tesseract folder but can't find anything

**Comment by saudet** [comment]
You're not doing anything with either `output` or `contenu`, so it won't get written to a file. 
You could also try to print it to the screen as with the BasicExample:
https://github.com/bytedeco/javacpp-presets/tree/master/tesseract#the-srcmainjavabasicexamplejava-source-file
