### ISSUE TITLE
curl certificate error when building from source

### ISSUE THREAD

**Issue by fancyerii** [bytedeco/javacpp-presets#237]
$ mvn install --projects ffmpeg
Detected platform "linux-x86_64"
Building for platform "linux-x86_64"
Installing "ffmpeg"
~/javacpp-presets/ffmpeg/cppbuild ~/javacpp-presets
Downloading http://sourceforge.net/projects/opencore-amr/files/opencore-amr/opencore-amr-0.1.3.tar.gz/download
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0   410    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (77) error setting certificate verify locations:
  CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE

**Comment by saudet** [comment]
So update your certificates!

**Comment by saudet** [comment]
I'm assuming that updating your certificates solved this issue, but please let me know if you still have issues with that.
