### ISSUE TITLE
Incomplete OpenCV jar file in maven

### ISSUE THREAD

**Issue by Neiko2002** [bytedeco/javacpp-presets#244]
Compiling the OpenCV javacpp-presets creates 25 independent libraries. Downloading any (Linux, OSX, Win) jar file from maven does only contain 21 of those libs. The missing ones are:
libopencv_aruco.so.3.1
libopencv_fuzzy.so.3.1
libopencv_plot.so.3.1
libopencv_stereo.so.3.1

This leads to problems in other presets depending on OpenCV. E.g. the mxnet libraries have dependencies to those missing ones.

**Comment by saudet** [comment]
Sure, we would need to add those modules. Would you like to make a contribution in that sense?

**Comment by saudet** [comment]
Or is the problem that mxnet shouldn't link with those modules to start with?

**Comment by Neiko2002** [comment]
MXNet does not need those modules. The PKG_CONFIG_PATH gets configures in the build script
https://github.com/bytedeco/javacpp-presets/blob/master/mxnet/cppbuild.sh

and mxnet simply uses all the modules installed on your system for its linkining process
https://github.com/dmlc/mxnet/blob/master/Makefile

```
ifeq ($(USE_OPENCV), 1)
	CFLAGS += -DMXNET_USE_OPENCV=1 `pkg-config --cflags opencv`
	LDFLAGS += `pkg-config --libs opencv`
	BIN += bin/im2rec
else
	CFLAGS+= -DMXNET_USE_OPENCV=0
endif
```

OpenCV itself is optional in mxnet. In fact the windows binaries (they provide) does not even have a dependencies for it. We could remove it from the mxnet preset and rewrite the java sample (I already wrote a OpenCV free version of it).

**Comment by saudet** [comment]
So we should create a patch for mxnet so it links only with the module it uses.

**Comment by saudet** [comment]
Or remove the dependency, yes that's fine too, I suppose, but I was under the impression that it wouldn't support images if we didn't use OpenCV, no?

**Comment by Neiko2002** [comment]
This should fix the problem. https://github.com/bytedeco/javacpp-presets/pull/247
