### ISSUE TITLE
buildcpp.sh results in 404 on multiple archives

### ISSUE THREAD

**Issue by javadba** [bytedeco/javacpp-presets#245]
Here is one example:  boost_1_57_0.tar.gz

The requested URL /project/boost/boost/1.57.0/boost_1_57_0.tar.gz was not found on this server.

We end up with 404 on the url  and the build stops. Broken. I have to download the file manually (from ) and then start the whole thing over - another 30+ minutes.

Here are two files so far:

libpng-1.6.17.tar.gz

I downloaded it manually from: 

 http://pkgs.fedoraproject.org/repo/pkgs/libpng/libpng-1.6.17.tar.gz

view-source:pkgs.fedoraproject.org/repo/pkgs/libpng/libpng-1.6.17.tar.gz/134282f1752dcf4cd81a37b8ff421cef/libpng-1.6.17.tar.gz

Another:  boost_1_57_0.tar.gz

Still re-running: so there may be yet additional stale download url's. I will update if that were the case.

**Comment by javadba** [comment]
There is a somewhat different error on the caffe build:  it is giving 

unrecognized file format

The 'tar' command is not seeing a valid .gz file.  But for caffe the file looks to have been successfully downloaded . So  in this case the root cause is unclear.

ls -lrta downloads
..
-rw-r--r--   1 macuser  staff   8487187 Jun 30 11:11 caffe-master.tar.gz
-rw-r--r--@  1 macuser  staff  73472080 Jun 30 11:16 boost_1_57_0.tar.gz

**Comment by saudet** [comment]
You're using an old version of the file. Please try again with the latest version:
https://github.com/bytedeco/javacpp-presets/blob/master/caffe/cppbuild.sh
