### ISSUE TITLE
Tensor DT_STRING createBuffer() doesn't work

### ISSUE THREAD

**Issue by lakshmanok** [bytedeco/javacpp-presets#249]
This code:

               Tensor fn = new Tensor(tensorflow.DT_STRING, new TensorShape(1));
		CharBuffer buffer = fn.createBuffer();

results in a null buffer.  However,

                Tensor fn = new Tensor(tensorflow.DT_FLOAT, new TensorShape(1));
		FloatBuffer buffer = fn.createBuffer();

works fine.

**Comment by saudet** [comment]
`DT_STRING` data cannot be represented by primitive types in Java, so we need something else to access it. I've created a `StringArray` helper class for that in the commit above, so we can do stuff like this:
```java
Tensor x = new Tensor(DT_STRING, new TensorShape(2, 2));
StringArray a = x.createStringArray().position(3);
a.position(0).put("foo");
a.position(3).put("bar");
System.out.println(a.position(0)); // prints "foo"
```
Let me know if that satisfies your needs!

**Comment by lakshmanok** [comment]
Thanks ... tensorflow.jar that I get from Maven doesn't seem to have been updated?

**Comment by saudet** [comment]
Need to rebuild from source...

**Comment by saudet** [comment]
Update binaries are now on the central:
http://search.maven.org/#artifactdetails%7Corg.bytedeco.javacpp-presets%7Ctensorflow%7C0.9.0-1.2%7Cjar
Thanks for reporting this issue!
