### ISSUE TITLE
cudnnGetPoolingNdForwardOutputDim missing from cudnn bindings

### ISSUE THREAD

**Issue by cnuernber** [bytedeco/javacpp-presets#250]
We are getting issues where our convolution,pooling layers have different calculated sizes from what cudnn calculates.  I would like to have runtime checks to make sure things line up but this function appears to be missing from the cudnn bindings.

**Comment by saudet** [comment]
You mean the strides? There are functions to specify custom strides. In any
case, could you point out what is missing exactly?

**Comment by cnuernber** [comment]
The specific function named in the title and the fix is in the linked pull request.

**Comment by saudet** [comment]
Yes, saw that after. Sorry :) Thanks a lot for fixing this, will merge

**Comment by cnuernber** [comment]
Totally understand.  I spoke to the cudnn guys and this fix isn't absolutely necessary:

https://devtalk.nvidia.com/default/topic/949999/cuda-programming-and-performance/cudnn-calculates-layer-sizes-different-than-caffe/

Thus you *have* to check convolution sizes but you do *not* have to check pooling sizes.

**Comment by saudet** [comment]
Thanks for the fix! It is now included in version 1.3.
