### ISSUE TITLE
[libjvm.so+0x638a68]  jni_invoke_nonstatic(JNIEnv_*, JavaValue*, _jobject*, JNICallType, _jmethodID*, JNI_ArgumentPusher*, Thread*)+0x1b8

### ISSUE THREAD

**Issue by NacyLiu** [bytedeco/javacpp-presets#257]
@saudet  it seems that the problem raised in C++ , But what is wrong with it ?

[libjvm.so+0x638a68]  jni_invoke_nonstatic(JNIEnv__, JavaValue_, _jobject_, JNICallType, _jmethodID_, JNI_ArgumentPusher_, Thread_)+0x1b8

Stack: [0x00007feef3173000,0x00007feef3274000],  sp=0x00007feef3271b50,  free space=1018k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
V  [libjvm.so+0x638a68]  jni_invoke_nonstatic(JNIEnv__, JavaValue_, _jobject_, JNICallType, _jmethodID_, JNI_ArgumentPusher_, Thread_)+0x1b8
V  [libjvm.so+0x649019]  jni_CallIntMethodA+0xe9

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
J 589  org.bytedeco.javacpp.avformat.av_read_frame(Lorg/bytedeco/javacpp/avformat$AVFormatContext;Lorg/bytedeco/javacpp/avcodec$AVPacket;)I (0 bytes) @ 0x00007fef791b9343 [0x00007fef791b92e0+0x63]
J 746 C2 detect.screenshot.ScreenShotFFMPEG.run()V (1530 bytes) @ 0x00007fef7924b580 [0x00007fef7924ab00+0xa80]
v  ~StubRoutines::call_stub

**Comment by saudet** [comment]
Please provide a code snippet to reproduce this error.

**Comment by NacyLiu** [comment]
actually, i do not know how it raised, maybe multi-threading ..., i copy the code from https://github.com/bytedeco/javacpp-presets/tree/master/ffmpeg

**Comment by saudet** [comment]
I won't be able to help you if you don't provide more details about this...
