### ISSUE TITLE
Linux distro cross-test results

### ISSUE THREAD

**Issue by jjYBdx4IL** [bytedeco/javacpp-presets#26]
I have implemented simple tests that are checking whether the Libs generated on Debian Squeeze can be loaded on newer Ubuntu/Debian OSes. I'm also parsing and printing out the dynamic sections of the libraries there.

The log files (and results) have the format testlog.$project.$buildos.$testos.log and can be found there:

https://github.com/jjYBdx4IL/javacpp-presets

4 projects cannot be built because sources are not available or incomplete (flandmark depends on opencv, for example). These projects are listed in the allow_failure section of https://github.com/jjYBdx4IL/javacpp-presets/blob/develop/.travis.yml

Just FYI.

**Comment by saudet** [comment]
BTW, Docker works great. I've used it for the latest release (version 1.1). I'm guessing it would work fine on Travis CI as well!

**Comment by saudet** [comment]
Thanks to @vb216 we now have the builds running on Travis CI and AppVeyor for Android, Linux, Mac, and Windows, so I'm considering this issue solved. Thanks for your interest though! We still need help maintaining the system, for example, getting the samples running as tests would be a good thing to have...
