### ISSUE TITLE
ERROR: x265 not found using pkg-config

### ISSUE THREAD

**Issue by yuanice** [bytedeco/javacpp-presets#261]
I compiled in centos7 ffmpeg code, the following error occurred：
make[1]: Nothing to be done for `install'.
ERROR: x265 not found using pkg-config

Can you give me some  idea ! thanks

**Comment by saudet** [comment]
Please follow the build instructions here:
https://github.com/bytedeco/javacpp-presets/wiki/Build-Environments#linux-x86-and-x86_64
