### ISSUE TITLE
ffmpeg could not find ffmpeg-windows-x86_64.jar in gradle.

### ISSUE THREAD

**Issue by xav9211** [bytedeco/javacpp-presets#263]
I have problem when I try to add ffmpeg jar file by gradle project in intelij. When I refresh gradle project I have warning:

Warning:<i><b>root project <projectName>: Unable to resolve additional project configuration.</b>
Details: org.gradle.api.artifacts.ResolveException: Could not resolve all dependencies for configuration ':ffmpeg-player:compile'.
Caused by: org.gradle.internal.resolve.ArtifactNotFoundException: Could not find ffmpeg-windows-x86_64.jar (org.bytedeco.javacpp-presets:ffmpeg:2.8.1-1.1).
Searched in the following locations:
    file:/C:/Users/xav92/.m2/repository/org/bytedeco/javacpp-presets/ffmpeg/2.8.1-1.1/ffmpeg-2.8.1-1.1-windows-x86_64.jar</i>

My build.gradle for ffmpeg-player component looks like:

```
dependencies {
    compile project(':common')
    compile project(':common-test')

    compile group: 'org.bytedeco.javacpp-presets', name: 'ffmpeg', version: '2.8.1-1.1', classifier: 'windows-x86_64'
    compile group: 'org.bytedeco.javacpp-presets', name: 'ffmpeg', version: '2.8.1-1.1'

    compile group: 'org.apache.commons', name: 'commons-collections4', version: '4.1'
}
```

**Comment by saudet** [comment]
Please try again with version 1.2

**Comment by saudet** [comment]
Given the lack of feedback, I'm assuming that it works fine with version 1.2 (or 1.3), but please let me know if you are still having trouble, thanks!
