### ISSUE TITLE
Get the Bounding box at the RIL_WORD level

### ISSUE THREAD

**Issue by pony-boy** [bytedeco/javacpp-presets#267]
I am trying to extract the bounding boxes of each word from the javacpp tesseract. This appears to be the bounding box call (my full code below):

boolean box = ri.BoundingBox(RIL_WORD, coord1, coord2, coord3, coord4)
RIL_WORD is the iterator level that can be adjusted for words, sentences, and paragraphs. The coordinates are IntPointers (included class with javacpp).

The api says this returns the bounding box coordinates but returns a boolean instead. SO at this point I know there is a bounding box but still cannot get the actual coordinates. Does anyone know how to get the bounding box rectangles out of java cpp tessaract? Thanks for the help. I have posted my working code for getting the individual words and the confidence level below because I had such a hard time finding examples.
```java
    public class TesseractOCR {
        public void OCRText() {
            BytePointer outText;

        TessBaseAPI api = new TessBaseAPI();
        // Initialize tesseract-ocr with English, without specifying tessdata path

    if (api.Init(null, "eng") != 0) {
        System.err.println("Could not initialize tesseract.");
        System.exit(1);
    }

    // Open input image with leptonica library

    org.bytedeco.javacpp.lept.PIX image = pixRead("testimage.png");


    // Get OCR result
    outText = api.GetUTF8Text();
    System.out.println("OCR output:\n" + outText.getString());


    final ResultIterator ri = api.GetIterator();

    int x1 = 0;
    int y1 = 0;
    int x2 = 0;
    int y2 = 0;

    IntPointer coord1 = new IntPointer(x1);
    IntPointer coord2 = new IntPointer(y1);
    IntPointer coord3 = new IntPointer(x2);
    IntPointer coord4 = new IntPointer(y2);

    ri.Begin();

    if (ri !=null) {

        do {
            BytePointer word = ri.GetUTF8Text(RIL_WORD);
            float conf  = ri.Confidence(RIL_WORD);
            boolean box = ri.BoundingBox(RIL_WORD, coord1, coord2, coord3, coord4);

            System.out.println(word.getString());
            System.out.println(conf);
            System.out.println(box);


        } while (ri.Next(RIL_WORD));

    }



    api.End();
    outText.deallocate();
    pixDestroy(image);
    }
}
```

**Comment by saudet** [comment]
Since these are output arguments, initializing them with `new
IntPointer(1)` and calling `get()` after the call should get the values you
are after.

**Comment by pvorb** [comment]
@saudet Thanks! This was helpful -- at least for me.

My problem was that I initialized the `IntPointer`s without an argument

~~~ java
// pointers to the bounding box coordinates
final IntPointer left = new IntPointer();
final IntPointer top = new IntPointer();
final IntPointer right = new IntPointer();
final IntPointer bottom = new IntPointer();

// get bounding box
tesseract.TessPageIteratorBoundingBox(pageIt, level, left, top, right, bottom);
~~~

which caused the JVM to crash.

Initializing the pointers with `new IntPointer(1)` helped.
