### ISSUE TITLE
tensorflow: Scalar Tensor String initialization

### ISSUE THREAD

**Issue by Mistobaan** [bytedeco/javacpp-presets#268]
I am creating a Scalar Tensor String to use inside inception. This is the only code that seems to work, which seems strange. Am I missing something ?

```java
       Tensor image_data = new Tensor(DT_STRING, new TensorShape(img.length));
        StringArray buffer_image_data = image_data.createStringArray();
        //buffer_image_data.put(new StringArray().data().put(img));
        buffer_image_data.resize(img.length);
        buffer_image_data.data().put(img);
```

**Comment by saudet** [comment]
If you just need to initialize one string, TensorShape should be 1, but
looks fine otherwise, yes. What is strange about it?
