### ISSUE TITLE
how to use javacpp/tensorflow to init variable random

### ISSUE THREAD

**Issue by fancyerii** [bytedeco/javacpp-presets#269]
I want to train a simple model with javacpp/tensorflow. I have read
the ExampleTrainer. But I don't know how to init tensorflow variable.

I want to rewrite the get-started example
https://www.tensorflow.org/versions/r0.10/get_started/index.html

``` python
x_data = np.random.rand(100).astype(np.float32)
y_data = x_data * 0.1 + 0.3

# Try to find values for W and b that compute y_data = W * x_data + b
# (We know that W should be 0.1 and b 0.3, but TensorFlow will
# figure that out for us.)
W = tf.Variable(tf.random_uniform([1], -1.0, 1.0))
```

for java ,it's something like:

``` java
        Tensor x = new Tensor(DT_FLOAT, new TensorShape(new long[]{100}));

        FloatBuffer x_flat = x.createBuffer();
        for(int i=0;i<100;i++){
            x_flat.put(i, (float)Math.random());
        }


        GraphDefBuilder b = new GraphDefBuilder();
        Node x_data =Const(x, b.opts().WithName("x"));
        Node y_data = Add(Mul(x_data, Const(0.1f, b.opts()),
b.opts()), Const(0.3f, b.opts()), b.opts().WithName("y_data"));

        Node w=tensorflow.Variable(new TensorShape(new long[]{100}),
DT_FLOAT, b.opts().WithName("w"));
```

But with Node w, I don't know how to init it because I can't get the
tensor from w.

**Comment by saudet** [comment]
If you have some example that works in C++, it would help. Thanks!

**Comment by saudet** [comment]
The API for the ops changed a lot with 0.10.0. Check it out, maybe that's one of the things it now makes possible: https://github.com/bytedeco/javacpp-presets/commit/dd4ffa747a2e6848271efd9f98ac17ec72597a94

**Comment by Neiko2002** [comment]
Converting your code to the new API would look like this for the first part.
```
Scope scope = Scope.NewRootScope();
Output x_data = Const(scope.WithOpName("x"), x);
Output scale = Const(scope.WithOpName("scale"), 0.1f);
Output offset = Const(scope.WithOpName("offset"), 0.3f);
Multiply x_data_scaled = new Multiply(scope, new Input(x_data), new Input(scale));
Add y_data = new Add(scope.WithOpName("y_data"), x_data_scaled.asInput(), new Input(offset));
```

Using Variables is more complex. Initializing them with random values is shown here:  
[CarPricePredictionExample.java#L81](https://github.com/bytedeco/javacpp-presets/blob/master/tensorflow/samples/src/main/java/org/bytedeco/javacpp/samples/tensorflow/CarPricePredictionExample.java#L81)

**Comment by saudet** [comment]
Thanks for answering this question @Neiko2002 !!
