### ISSUE TITLE
javacpp presets ffmpeg not supporting alsa

### ISSUE THREAD

**Issue by blablaita** [bytedeco/javacpp-presets#276]
I’ve tried to use javacpp-presets ffmpeg on a RPI (ffmpeg-3.0.2-1.2-linux-armhf.jar  ffmpeg.jar  javacpp.jar). It seems that the ALSA device is not included in the ffmpeg libraries.

It may be because the libraries were generated on a cross-compiling environment, where the libasound2-dev headers are not included, and therefore not considered in the ffmpeg .configure step.

Is it possible to build the .so in ffmpeg-3.0.2-1.2-linux-armhf.jar including  alsa?

**Comment by saudet** [comment]
@vb216 ?

**Comment by vb216** [comment]
Sure, looking at it. Built, just want to test it still all runs OK.  Don't seem able to deploy snapshots anymore though.. will stick it on a google drive link

**Comment by blablaita** [comment]
Ok thanks, let me know.

**Comment by vb216** [comment]
Sorry that took a while.. trying to wrap up a few fixes to the arm-hf pi build and test them at the same time. From the config.log it looks like the error message about no asound header has gone away.. could you give it a test? (Also, might be a bit faster than the current included armhf libs)

[Link here](https://drive.google.com/open?id=0B2xpvMUzviShMEs0bzV2YTJQQzA)

**Comment by blablaita** [comment]
Thanks vb216.
Tested, but still have the problem.
On RPI where FFMPEG was built and installed, using ffmpeg "command" to show devices, the alsa device is included (Mux/Demux):

```
pi@rmo:~ $ ffmpeg -devices
ffmpeg version N-81335-g3a81775 Copyright (c) 2000-2016 the FFmpeg developers
  built with gcc 4.9.2 (Raspbian 4.9.2-10)
  configuration: --arch=armel --target-os=linux --enable-gpl --enable-libx264 --enable-nonfree --enable-omx --enable-omx-rpi
  libavutil      55. 28.100 / 55. 28.100
  libavcodec     57. 51.102 / 57. 51.102
  libavformat    57. 46.101 / 57. 46.101
  libavdevice    57.  0.102 / 57.  0.102
  libavfilter     6. 51.100 /  6. 51.100
  libswscale      4.  1.100 /  4.  1.100
  libswresample   2.  1.100 /  2.  1.100
  libpostproc    54.  0.100 / 54.  0.100
Devices:
 D. = Demuxing supported
 .E = Muxing supported
 --
 DE alsa            ALSA audio output
 D  dv1394          DV1394 A/V grab
 DE fbdev           Linux framebuffer
 D  lavfi           Libavfilter virtual input device
 DE oss             OSS (Open Sound System) playback
  E v4l2            Video4Linux2 output device
 D  video4linux2,v4l2 Video4Linux2 device grab
```



This is the code snippet used to show available devices:
```
	public void showDev(){
		avdevice.avdevice_register_all();
		avcodec_register_all();
		av_register_all();

		System.out.println("-Audio input devices-");
		AVInputFormat inputAudio = null;
		while ((inputAudio = avdevice.av_input_audio_device_next(inputAudio))!= null){
				System.out.print(inputAudio.name().getString()+ " = ");
				System.out.println(inputAudio.long_name().getString());
		}
		System.out.println("-Audio output devices-");
		AVOutputFormat outputAudio = null;
		while ((outputAudio = avdevice.av_output_audio_device_next(outputAudio))!= null){
				System.out.print(outputAudio.name().getString()+ " = ");
				System.out.println(outputAudio.long_name().getString());
		}
		System.out.println("-Video Input devices-");
		AVInputFormat inputtVideo = null;
		while ((inputtVideo = avdevice.av_input_video_device_next(inputtVideo))!= null){
			System.out.print(inputtVideo.name().getString()+ " = ");
			System.out.println(inputtVideo.long_name().getString());
		}
		
		System.out.println("-Video output devices-");
		AVOutputFormat outputVideo = null;
		while ((outputVideo = avdevice.av_output_video_device_next(outputVideo))!= null){
			System.out.print(outputVideo.name().getString()+ " = ");
			System.out.println(outputVideo.long_name().getString());
		
		}
	}

```
Result using previous libraries

```
pi@rmo:~ $ java -cp libs/ffmpeg.jar:libs/javacpp.jar:libs/ffmpeg-3.0.2-1.2-linux-armhf.jar:. tester.VideoStreamer
-Audio input devices-
lavfi = Libavfilter virtual input device
oss = OSS (Open Sound System) capture
-Audio output devices-
oss = OSS (Open Sound System) playback
-Video Input devices-
dv1394 = DV1394 A/V grab
fbdev = Linux framebuffer
lavfi = Libavfilter virtual input device
video4linux2,v4l2 = Video4Linux2 device grab
-Video output devices-
fbdev = Linux framebuffer
v4l2 = Video4Linux2 output device


```
same result using new libraries:

```
pi@rmo:~ $ java -cp libs/ffmpeg.jar:libs/javacpp.jar:libs/ffmpeg-linux-armhf.jar:. tester.VideoStreamer
-Audio input devices-
lavfi = Libavfilter virtual input device
oss = OSS (Open Sound System) capture
-Audio output devices-
oss = OSS (Open Sound System) playback
-Video Input devices-
dv1394 = DV1394 A/V grab
fbdev = Linux framebuffer
lavfi = Libavfilter virtual input device
video4linux2,v4l2 = Video4Linux2 device grab
-Video output devices-
fbdev = Linux framebuffer
v4l2 = Video4Linux2 output device

```

**Comment by vb216** [comment]
Ah OK.. Think I've cracked it. Thanks for the detailed output, that helped alot to compare and find the problem. I ended up cross compiling alsa inside the docker container I've been using for the Pi, I wonder if it was having trouble finding an arm library, and I added -lasound to the arm build step for ffmpeg. If you download these two jars: [ffmpeg-linux-armhf.jar](https://drive.google.com/open?id=0B2xpvMUzviShQXhybmhYNGxhNG8) and [ffmpeg.jar](https://drive.google.com/open?id=0B2xpvMUzviShMUpWQXVEZGVJSUk), replacing the ones in the earlier full distro I linked to, it looks much more promising:

     [java] -Audio input devices-
     [java] alsa = ALSA audio input
     [java] lavfi = Libavfilter virtual input device
     [java] oss = OSS (Open Sound System) capture
     [java] -Audio output devices-
     [java] alsa = ALSA audio output
     [java] oss = OSS (Open Sound System) playback
     [java] -Video Input devices-
     [java] dv1394 = DV1394 A/V grab
     [java] fbdev = Linux framebuffer
     [java] lavfi = Libavfilter virtual input device
     [java] video4linux2,v4l2 = Video4Linux2 device grab
     [java] -Video output devices-
     [java] fbdev = Linux framebuffer
     [java] v4l2 = Video4Linux2 output device

Let me know how it goes this time round

**Comment by blablaita** [comment]
OK, tested, now ALSA device is available.
Thank you very much.
