### ISSUE TITLE
OpenCV build fails when executing bash cppbuild.sh -platform linux-x86_64

### ISSUE THREAD

**Issue by jenniferwillow** [bytedeco/javacpp-presets#277]
When executing the cppbuild.sh script, OpenCV 3.1.0 fails to build when it reaches 76% and is compiling the cap_gphoto2.cpp file.  Here's the error:

[ 76%] Building CXX object modules/videoio/CMakeFiles/opencv_videoio.dir/src/cap_gphoto2.cpp.o
/home/developer/andor_development_stargate/working/opencv/javacpp-presets/javacpp-presets/opencv/cppbuild/linux-x86_64/opencv-3.1.0/modules/videoio/src/cap_mjpeg_encoder.cpp: In member function ‘void cv::mjpeg::MotionJpegWriter::writeFrameData(const uchar*, int, int, int)’:
/home/developer/andor_development_stargate/working/opencv/javacpp-presets/javacpp-presets/opencv/cppbuild/linux-x86_64/opencv-3.1.0/modules/videoio/src/cap_mjpeg_encoder.cpp:325: warning: dereferencing pointer ‘hbuffer’ does break strict-aliasing rules [-Wstrict-aliasing]
/home/developer/andor_development_stargate/working/opencv/javacpp-presets/javacpp-presets/opencv/cppbuild/linux-x86_64/opencv-3.1.0/modules/videoio/src/cap_mjpeg_encoder.cpp:1769: note: initialized from here
/home/developer/andor_development_stargate/working/opencv/javacpp-presets/javacpp-presets/opencv/cppbuild/linux-x86_64/opencv-3.1.0/modules/videoio/src/cap_gphoto2.cpp:171: error: ISO C++ forbids initialization of member ‘context’ [-fpermissive]
/home/developer/andor_development_stargate/working/opencv/javacpp-presets/javacpp-presets/opencv/cppbuild/linux-x86_64/opencv-3.1.0/modules/videoio/src/cap_gphoto2.cpp:171: error: making ‘context’ static [-fpermissive]
/home/developer/andor_development_stargate/working/opencv/javacpp-presets/javacpp-presets/opencv/cppbuild/linux-x86_64/opencv-3.1.0/modules/videoio/src/cap_gphoto2.cpp:171: error: invalid in-class initialization of static data member of non-integral type ‘GPContext*’
/home/developer/andor_development_stargate/working/opencv/javacpp-presets/javacpp-presets/opencv/cppbuild/linux-x86_64/opencv-3.1.0/modules/videoio/src/cap_gphoto2.cpp:177: error: ISO C++ forbids initialization of member ‘camera’ [-fpermissive]
/home/developer/andor_development_stargate/working/opencv/javacpp-presets/javacpp-presets/opencv/cppbuild/linux-x86_64/opencv-3.1.0/modules/videoio/src/cap_gphoto2.cpp:177: error: making ‘camera’ static [-fpermissive]
/home/developer/andor_development_stargate/working/opencv/javacpp-presets/javacpp-presets/opencv/cppbuild/linux-x86_64/opencv-3.1.0/modules/videoio/src/cap_gphoto2.cpp:177: error: invalid in-class initialization of static data member of non-integral type ‘Camera*’
/home/developer/andor_development_stargate/working/opencv/javacpp-presets/javacpp-presets/opencv/cppbuild/linux-x86_64/opencv-3.1.0/modules/videoio/src/cap_gphoto2.cpp:181: error: ISO C++ forbids initialization of member ‘rootWidget’ [-fpermissive]
/home/developer/andor_development_stargate/working/opencv/javacpp-presets/javacpp-presets/opencv/cppbuild/linux-x86_64/opencv-3.1.0/modules/videoio/src/cap_gphoto2.cpp:181: error: making ‘rootWidget’ static [-fpermissive]
/home/developer/andor_development_stargate/working/opencv/javacpp-presets/javacpp-presets/opencv/cppbuild/linux-x86_64/opencv-3.1.0/modules/videoio/src/cap_gphoto2.cpp:181: error: invalid in-class initialization of static data member of non-integral type ‘CameraWidget*’
/home/developer/andor_development_stargate/working/opencv/javacpp-presets/javacpp-presets/opencv/cppbuild/linux-x86_64/opencv-3.1.0/modules/videoio/src/cap_gphoto2.cpp:213: error: ISO C++ forbids initialization of member ‘abilitiesList’ [-fpermissive]
/home/developer/andor_development_stargate/working/opencv/javacpp-presets/javacpp-presets/opencv/cppbuild/linux-x86_64/opencv-3.1.0/modules/videoio/src/cap_gphoto2.cpp:213: error: making ‘abilitiesList’ static [-fpermissive]
/home/developer/andor_development_stargate/working/opencv/javacpp-presets/javacpp-presets/opencv/cppbuild/linux-x86_64/opencv-3.1.0/modules/videoio/src/cap_gphoto2.cpp:213: error: invalid in-class initialization of static data member of non-integral type ‘CameraAbilitiesList*’
/home/developer/andor_development_stargate/working/opencv/javacpp-presets/javacpp-presets/opencv/cppbuild/linux-x86_64/opencv-3.1.0/modules/videoio/src/cap_gphoto2.cpp:214: error: ISO C++ forbids initialization of member ‘capablePorts’ [-fpermissive]
/home/developer/andor_development_stargate/working/opencv/javacpp-presets/javacpp-presets/opencv/cppbuild/linux-x86_64/opencv-3.1.0/modules/videoio/src/cap_gphoto2.cpp:214: error: making ‘capablePorts’ static [-fpermissive]
/home/developer/andor_development_stargate/working/opencv/javacpp-presets/javacpp-presets/opencv/cppbuild/linux-x86_64/opencv-3.1.0/modules/videoio/src/cap_gphoto2.cpp:214: error: invalid in-class initialization of static data member of non-integral type ‘GPPortInfoList*’
/home/developer/andor_development_stargate/working/opencv/javacpp-presets/javacpp-presets/opencv/cppbuild/linux-x86_64/opencv-3.1.0/modules/videoio/src/cap_gphoto2.cpp:215: error: ISO C++ forbids initialization of member ‘allDevices’ [-fpermissive]
/home/developer/andor_development_stargate/working/opencv/javacpp-presets/javacpp-presets/opencv/cppbuild/linux-x86_64/opencv-3.1.0/modules/videoio/src/cap_gphoto2.cpp:215: error: making ‘allDevices’ static [-fpermissive]
/home/developer/andor_development_stargate/working/opencv/javacpp-presets/javacpp-presets/opencv/cppbuild/linux-x86_64/opencv-3.1.0/modules/videoio/src/cap_gphoto2.cpp:215: error: invalid in-class initialization of static data member of non-integral type ‘CameraList*’
/home/developer/andor_development_stargate/working/opencv/javacpp-presets/javacpp-presets/opencv/cppbuild/linux-x86_64/opencv-3.1.0/modules/videoio/src/cap_gphoto2.cpp: In member function ‘void cv::gphoto2::DigitalCameraCapture::initContext()’:
/home/developer/andor_development_stargate/working/opencv/javacpp-presets/javacpp-presets/opencv/cppbuild/linux-x86_64/opencv-3.1.0/modules/videoio/src/cap_gphoto2.cpp:323: error: ‘context’ was not declared in this scope
/home/developer/andor_development_stargate/working/opencv/javacpp-presets/javacpp-presets/opencv/cppbuild/linux-x86_64/opencv-3.1.0/modules/videoio/src/cap_gphoto2.cpp:332: error: ‘abilitiesList’ was not declared in this scope
/home/developer/andor_development_stargate/working/opencv/javacpp-presets/javacpp-presets/opencv/cppbuild/linux-x86_64/opencv-3.1.0/modules/videoio/src/cap_gphoto2.cpp:333: error: ‘abilitiesList’ was not declared in this scope
/home/developer/andor_development_stargate/working/opencv/javacpp-presets/javacpp-presets/opencv/cppbuild/linux-x86_64/opencv-3.1.0/modules/videoio/src/cap_gphoto2.cpp:336: error: ‘capablePorts’ was not declared in this scope
/home/developer/andor_development_stargate/working/opencv/javacpp-presets/javacpp-presets/opencv/cppbuild/linux-x86_64/opencv-3.1.0/modules/videoio/src/cap_gphoto2.cpp:337: error: ‘capablePorts’ was not declared in this scope
/home/developer/andor_development_stargate/working/opencv/javacpp-presets/javacpp-presets/opencv/cppbuild/linux-x86_64/opencv-3.1.0/modules/videoio/src/cap_gphoto2.cpp:340: error: ‘allDevices’ was not declared in this scope
/home/developer/andor_development_stargate/working/opencv/javacpp-presets/javacpp-presets/opencv/cppbuild/linux-x86_64/opencv-3.1.0/modules/videoio/src/cap_gphoto2.cpp:341: error: ‘allDevices’ was not declared in this scope
/home/developer/andor_development_stargate/working/opencv/javacpp-presets/javacpp-presets/opencv/cppbuild/linux-x86_64/opencv-3.1.0/modules/videoio/src/cap_gphoto2.cpp:341: error: ‘gp_camera_autodetect’ was not declared in this scope
/home/developer/andor_development_stargate/working/opencv/javacpp-presets/javacpp-presets/opencv/cppbuild/linux-x86_64/opencv-3.1.0/modules/videoio/src/cap_gphoto2.cpp:342: error: ‘allDevices’ was not declared in this scope
/home/developer/andor_development_stargate/working/opencv/javacpp-presets/javacpp-presets/opencv/cppbuild/linux-x86_64/opencv-3.1.0/modules/videoio/src/cap_gphoto2.cpp: In destructor ‘virtual cv::gphoto2::DigitalCameraCapture::~DigitalCameraCapture()’:
/home/developer/andor_development_stargate/working/opencv/javacpp-presets/javacpp-presets/opencv/cppbuild/linux-x86_64/opencv-3.1.0/modules/videoio/src/cap_gphoto2.cpp:388: error: ‘abilitiesList’ was not declared in this scope
/home/developer/andor_development_stargate/working/opencv/javacpp-presets/javacpp-presets/opencv/cppbuild/linux-x86_64/opencv-3.1.0/modules/videoio/src/cap_gphoto2.cpp:389: error: ‘abilitiesList’ was not declared in this scope
/home/developer/andor_development_stargate/working/opencv/javacpp-presets/javacpp-presets/opencv/cppbuild/linux-x86_64/opencv-3.1.0/modules/videoio/src/cap_gphoto2.cpp:390: error: ‘capablePorts’ was not declared in this scope
/home/developer/andor_development_stargate/working/opencv/javacpp-presets/javacpp-presets/opencv/cppbuild/linux-x86_64/opencv-3.1.0/modules/videoio/src/cap_gphoto2.cpp:391: error: ‘capablePorts’ was not declared in this scope
/home/developer/andor_development_stargate/working/opencv/javacpp-presets/javacpp-presets/opencv/cppbuild/linux-x86_64/opencv-3.1.0/modules/videoio/src/cap_gphoto2.cpp:392: error: ‘allDevices’ was not declared in this scope
/home/developer/andor_development_stargate/working/opencv/javacpp-presets/javacpp-presets/opencv/cppbuild/linux-x86_64/opencv-3.1.0/modules/videoio/src/cap_gphoto2.cpp:393: error: ‘allDevices’ was not declared in this scope
/home/developer/andor_development_stargate/working/opencv/javacpp-presets/javacpp-presets/opencv/cppbuild/linux-x86_64/opencv-3.1.0/modules/videoio/src/cap_gphoto2.cpp:394: error: ‘context’ was not declared in this scope
/home/developer/andor_development_stargate/working/opencv/javacpp-presets/javacpp-presets/opencv/cppbuild/linux-x86_64/opencv-3.1.0/modules/videoio/src/cap_gphoto2.cpp: In member function ‘bool cv::gphoto2::DigitalCameraCapture::open(int)’:
/home/developer/andor_development_stargate/working/opencv/javacpp-presets/javacpp-presets/opencv/cppbuild/linux-x86_64/opencv-3.1.0/modules/videoio/src/cap_gphoto2.cpp:418: error: ‘camera’ was not declared in this scope
/home/developer/andor_development_stargate/working/opencv/javacpp-presets/javacpp-presets/opencv/cppbuild/linux-x86_64/opencv-3.1.0/modules/videoio/src/cap_gphoto2.cpp:419: error: ‘allDevices’ was not declared in this scope
/home/developer/andor_development_stargate/working/opencv/javacpp-presets/javacpp-presets/opencv/cppbuild/linux-x86_64/opencv-3.1.0/modules/videoio/src/cap_gphoto2.cpp:420: error: ‘allDevices’ was not declared in this scope
/home/developer/andor_development_stargate/working/opencv/javacpp-presets/javacpp-presets/opencv/cppbuild/linux-x86_64/opencv-3.1.0/modules/videoio/src/cap_gphoto2.cpp:423: error: ‘abilitiesList’ was not declared in this scope
/home/developer/andor_development_stargate/working/opencv/javacpp-presets/javacpp-presets/opencv/cppbuild/linux-x86_64/opencv-3.1.0/modules/videoio/src/cap_gphoto2.cpp:424: error: ‘abilitiesList’ was not declared in this scope
/home/developer/andor_development_stargate/working/opencv/javacpp-presets/javacpp-presets/opencv/cppbuild/linux-x86_64/opencv-3.1.0/modules/videoio/src/cap_gphoto2.cpp:425: error: ‘camera’ was not declared in this scope
/home/developer/andor_development_stargate/working/opencv/javacpp-presets/javacpp-presets/opencv/cppbuild/linux-x86_64/opencv-3.1.0/modules/videoio/src/cap_gphoto2.cpp:428: error: ‘capablePorts’ was not declared in this scope
/home/developer/andor_development_stargate/working/opencv/javacpp-presets/javacpp-presets/opencv/cppbuild/linux-x86_64/opencv-3.1.0/modules/videoio/src/cap_gphoto2.cpp:429: error: ‘capablePorts’ was not declared in this scope
/home/developer/andor_development_stargate/working/opencv/javacpp-presets/javacpp-presets/opencv/cppbuild/linux-x86_64/opencv-3.1.0/modules/videoio/src/cap_gphoto2.cpp:430: error: ‘camera’ was not declared in this scope
/home/developer/andor_development_stargate/working/opencv/javacpp-presets/javacpp-presets/opencv/cppbuild/linux-x86_64/opencv-3.1.0/modules/videoio/src/cap_gphoto2.cpp:433: error: ‘camera’ was not declared in this scope
/home/developer/andor_development_stargate/working/opencv/javacpp-presets/javacpp-presets/opencv/cppbuild/linux-x86_64/opencv-3.1.0/modules/videoio/src/cap_gphoto2.cpp:433: error: ‘context’ was not declared in this scope
/home/developer/andor_development_stargate/working/opencv/javacpp-presets/javacpp-presets/opencv/cppbuild/linux-x86_64/opencv-3.1.0/modules/videoio/src/cap_gphoto2.cpp: In member function ‘void cv::gphoto2::DigitalCameraCapture::close()’:
/home/developer/andor_development_stargate/working/opencv/javacpp-presets/javacpp-presets/opencv/cppbuild/linux-x86_64/opencv-3.1.0/modules/videoio/src/cap_gphoto2.cpp:476: error: ‘camera’ was not declared in this scope
/home/developer/andor_development_stargate/working/opencv/javacpp-presets/javacpp-presets/opencv/cppbuild/linux-x86_64/opencv-3.1.0/modules/videoio/src/cap_gphoto2.cpp:478: error: ‘context’ was not declared in this scope
/home/developer/andor_development_stargate/working/opencv/javacpp-presets/javacpp-presets/opencv/cppbuild/linux-x86_64/opencv-3.1.0/modules/videoio/src/cap_gphoto2.cpp:492: error: ‘rootWidget’ was not declared in this scope
/home/developer/andor_development_stargate/working/opencv/javacpp-presets/javacpp-presets/opencv/cppbuild/linux-x86_64/opencv-3.1.0/modules/videoio/src/cap_gphoto2.cpp: In member function ‘virtual double cv::gphoto2::DigitalCameraCapture::getProperty(int) const’:
/home/developer/andor_development_stargate/working/opencv/javacpp-presets/javacpp-presets/opencv/cppbuild/linux-x86_64/opencv-3.1.0/modules/videoio/src/cap_gphoto2.cpp:607: error: ‘rootWidget’ was not declared in this scope
/home/developer/andor_development_stargate/working/opencv/javacpp-presets/javacpp-presets/opencv/cppbuild/linux-x86_64/opencv-3.1.0/modules/videoio/src/cap_gphoto2.cpp: In member function ‘virtual bool cv::gphoto2::DigitalCameraCapture::setProperty(int, double)’:
/home/developer/andor_development_stargate/working/opencv/javacpp-presets/javacpp-presets/opencv/cppbuild/linux-x86_64/opencv-3.1.0/modules/videoio/src/cap_gphoto2.cpp:805: error: ‘camera’ was not declared in this scope
/home/developer/andor_development_stargate/working/opencv/javacpp-presets/javacpp-presets/opencv/cppbuild/linux-x86_64/opencv-3.1.0/modules/videoio/src/cap_gphoto2.cpp:805: error: ‘rootWidget’ was not declared in this scope
/home/developer/andor_development_stargate/working/opencv/javacpp-presets/javacpp-presets/opencv/cppbuild/linux-x86_64/opencv-3.1.0/modules/videoio/src/cap_gphoto2.cpp:805: error: ‘context’ was not declared in this scope
/home/developer/andor_development_stargate/working/opencv/javacpp-presets/javacpp-presets/opencv/cppbuild/linux-x86_64/opencv-3.1.0/modules/videoio/src/cap_gphoto2.cpp: In member function ‘virtual bool cv::gphoto2::DigitalCameraCapture::grabFrame()’:
/home/developer/andor_development_stargate/working/opencv/javacpp-presets/javacpp-presets/opencv/cppbuild/linux-x86_64/opencv-3.1.0/modules/videoio/src/cap_gphoto2.cpp:839: error: ‘camera’ was not declared in this scope
/home/developer/andor_development_stargate/working/opencv/javacpp-presets/javacpp-presets/opencv/cppbuild/linux-x86_64/opencv-3.1.0/modules/videoio/src/cap_gphoto2.cpp:839: error: ‘context’ was not declared in this scope
/home/developer/andor_development_stargate/working/opencv/javacpp-presets/javacpp-presets/opencv/cppbuild/linux-x86_64/opencv-3.1.0/modules/videoio/src/cap_gphoto2.cpp:844: error: ‘camera’ was not declared in this scope
/home/developer/andor_development_stargate/working/opencv/javacpp-presets/javacpp-presets/opencv/cppbuild/linux-x86_64/opencv-3.1.0/modules/videoio/src/cap_gphoto2.cpp:844: error: ‘context’ was not declared in this scope
/home/developer/andor_development_stargate/working/opencv/javacpp-presets/javacpp-presets/opencv/cppbuild/linux-x86_64/opencv-3.1.0/modules/videoio/src/cap_gphoto2.cpp:845: error: ‘camera’ was not declared in this scope
/home/developer/andor_development_stargate/working/opencv/javacpp-presets/javacpp-presets/opencv/cppbuild/linux-x86_64/opencv-3.1.0/modules/videoio/src/cap_gphoto2.cpp:845: error: ‘context’ was not declared in this scope
/home/developer/andor_development_stargate/working/opencv/javacpp-presets/javacpp-presets/opencv/cppbuild/linux-x86_64/opencv-3.1.0/modules/videoio/src/cap_gphoto2.cpp:847: error: ‘camera’ was not declared in this scope
/home/developer/andor_development_stargate/working/opencv/javacpp-presets/javacpp-presets/opencv/cppbuild/linux-x86_64/opencv-3.1.0/modules/videoio/src/cap_gphoto2.cpp:847: error: ‘context’ was not declared in this scope
/home/developer/andor_development_stargate/working/opencv/javacpp-presets/javacpp-presets/opencv/cppbuild/linux-x86_64/opencv-3.1.0/modules/videoio/src/cap_gphoto2.cpp: In member function ‘int cv::gphoto2::DigitalCameraCapture::findDevice(const char*) const’:
/home/developer/andor_development_stargate/working/opencv/javacpp-presets/javacpp-presets/opencv/cppbuild/linux-x86_64/opencv-3.1.0/modules/videoio/src/cap_gphoto2.cpp:914: error: ‘allDevices’ was not declared in this scope
/home/developer/andor_development_stargate/working/opencv/javacpp-presets/javacpp-presets/opencv/cppbuild/linux-x86_64/opencv-3.1.0/modules/videoio/src/cap_gphoto2.cpp: In member function ‘void cv::gphoto2::DigitalCameraCapture::reloadConfig()’:
/home/developer/andor_development_stargate/working/opencv/javacpp-presets/javacpp-presets/opencv/cppbuild/linux-x86_64/opencv-3.1.0/modules/videoio/src/cap_gphoto2.cpp:936: error: ‘rootWidget’ was not declared in this scope
/home/developer/andor_development_stargate/working/opencv/javacpp-presets/javacpp-presets/opencv/cppbuild/linux-x86_64/opencv-3.1.0/modules/videoio/src/cap_gphoto2.cpp:945: error: ‘camera’ was not declared in this scope
/home/developer/andor_development_stargate/working/opencv/javacpp-presets/javacpp-presets/opencv/cppbuild/linux-x86_64/opencv-3.1.0/modules/videoio/src/cap_gphoto2.cpp:945: error: ‘rootWidget’ was not declared in this scope
/home/developer/andor_development_stargate/working/opencv/javacpp-presets/javacpp-presets/opencv/cppbuild/linux-x86_64/opencv-3.1.0/modules/videoio/src/cap_gphoto2.cpp:945: error: ‘context’ was not declared in this scope
/home/developer/andor_development_stargate/working/opencv/javacpp-presets/javacpp-presets/opencv/cppbuild/linux-x86_64/opencv-3.1.0/modules/videoio/src/cap_gphoto2.cpp:949: error: ‘rootWidget’ was not declared in this scope
/home/developer/andor_development_stargate/working/opencv/javacpp-presets/javacpp-presets/opencv/cppbuild/linux-x86_64/opencv-3.1.0/modules/videoio/src/cap_gphoto2.cpp: In member function ‘int cv::gphoto2::DigitalCameraCapture::widgetDescription(std::ostream&, CameraWidget*) const’:
/home/developer/andor_development_stargate/working/opencv/javacpp-presets/javacpp-presets/opencv/cppbuild/linux-x86_64/opencv-3.1.0/modules/videoio/src/cap_gphoto2.cpp:1036: error: ‘gp_widget_get_readonly’ was not declared in this scope
make[2]: *** [modules/videoio/CMakeFiles/opencv_videoio.dir/src/cap_gphoto2.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [modules/videoio/CMakeFiles/opencv_videoio.dir/all] Error 2
make: *** [all] Error 2

Here's the configuration details:

-- Detected version of GNU GCC: 44 (404)
-- checking for module 'gtk+-3.0'
--   package 'gtk+-3.0' not found
-- checking for module 'libv4l1'
--   package 'libv4l1' not found
-- checking for module 'libv4l2'
--   package 'libv4l2' not found
-- Looking for linux/videodev.h
-- Looking for linux/videodev.h - found
-- Looking for linux/videodev2.h
-- Looking for linux/videodev2.h - found
-- Looking for sys/videoio.h
-- Looking for sys/videoio.h - not found
-- To enable PlantUML support, set PLANTUML_JAR environment variable or pass -DPLANTUML_JAR=<filepath> option to cmake
-- Could NOT find PythonLibs (missing:  PYTHON_LIBRARIES PYTHON_INCLUDE_DIRS) (Required is exact version "2.7.12")
-- Could NOT find PythonInterp: Found unsuitable version "2.7.12", but required is at least "3.4" (found /usr/local/palomar/anaconda/bin/python)
-- Could NOT find PythonInterp: Found unsuitable version "2.7.12", but required is at least "3.2" (found /usr/local/palomar/anaconda/bin/python)
-- Found apache ant 1.7.1: /usr/bin/ant
-- Could NOT find Matlab (missing:  MATLAB_MEX_SCRIPT MATLAB_INCLUDE_DIRS MATLAB_ROOT_DIR MATLAB_LIBRARIES MATLAB_LIBRARY_DIRS MATLAB_MEXEXT MATLAB_ARCH MATLAB_BIN) 
-- VTK is not found. Please set -DVTK_DIR in CMake to VTK build directory, or to VTK install subdirectory with VTKConfig.cmake file
-- Caffe:   NO
-- Protobuf:   NO
-- Glog:   NO
-- HDF5:   YES
-- Module opencv_sfm disabled because the following dependencies are not found: Eigen Glog/Gflags
-- Tesseract:   NO
-- Module opencv_structured_light disabled because opencv_rgbd dependency can't be resolved!
-- HDF5:   YES
-- Could NOT find PROTOBUF (missing:  PROTOBUF_LIBRARY PROTOBUF_INCLUDE_DIR) 
-- Build libprotobuf from sources:
--     libprotobuf not found into system
--     The protocol buffer compiler not found
-- Checking for C++ hash_map implementation...
-- C++ hash_map found in 'ext' dir in namespace __gnu_cxx::
-- Checking for C++ hash_set implementation...
-- C++ hash_set found in 'ext' dir in namespace __gnu_cxx::
-- 
-- General configuration for OpenCV 3.1.0 =====================================
--   Version control:               576a262
-- 
--   Platform:
--     Host:                        Linux 2.6.32-504.el6.x86_64 x86_64
--     CMake:                       2.8.12.2
--     CMake generator:             Unix Makefiles
--     CMake build tool:            /usr/bin/gmake
--     Configuration:               Release
-- 
--   C/C++:
--     Built as dynamic libs?:      YES
--     C++ Compiler:                /usr/bin/g++  -m64 (ver 4.4.7)
--     C++ flags (Release):         -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -fdiagnostics-show-option -Wno-long-long -pthread -fomit-frame-pointer -msse -msse2 -mno-avx -msse3 -mno-ssse3 -mno-sse4.1 -mno-sse4.2 -ffunction-sections -fvisibility=hidden -fvisibility-inlines-hidden -fopenmp -O3 -DNDEBUG  -DNDEBUG
--     C++ flags (Debug):           -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -fdiagnostics-show-option -Wno-long-long -pthread -fomit-frame-pointer -msse -msse2 -mno-avx -msse3 -mno-ssse3 -mno-sse4.1 -mno-sse4.2 -ffunction-sections -fvisibility=hidden -fvisibility-inlines-hidden -fopenmp -g  -O0 -DDEBUG -D_DEBUG
--     C Compiler:                  /usr/bin/gcc  -m64
--     C flags (Release):           -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -fdiagnostics-show-option -Wno-long-long -pthread -fomit-frame-pointer -msse -msse2 -mno-avx -msse3 -mno-ssse3 -mno-sse4.1 -mno-sse4.2 -ffunction-sections -fvisibility=hidden -fopenmp -O3 -DNDEBUG  -DNDEBUG
--     C flags (Debug):             -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -fdiagnostics-show-option -Wno-long-long -pthread -fomit-frame-pointer -msse -msse2 -mno-avx -msse3 -mno-ssse3 -mno-sse4.1 -mno-sse4.2 -ffunction-sections -fvisibility=hidden -fopenmp -g  -O0 -DDEBUG -D_DEBUG
--     Linker flags (Release):      
--     Linker flags (Debug):        
--     Precompiled headers:         NO
--     Extra dependencies:          gtk-x11-2.0 gdk-x11-2.0 atk-1.0 gio-2.0 pangoft2-1.0 pangocairo-1.0 gdk_pixbuf-2.0 cairo pango-1.0 freetype fontconfig gobject-2.0 gmodule-2.0 gthread-2.0 glib-2.0 gphoto2 gphoto2_port exif usb /usr/local/palomar/anaconda/lib/libhdf5_hl.so /usr/local/palomar/anaconda/lib/libhdf5.so /usr/lib64/librt.so /usr/lib64/libz.so /usr/lib64/libdl.so /usr/lib64/libm.so dl m pthread rt
--     3rdparty dependencies:       zlib libjpeg libwebp libpng libtiff libjasper IlmImf libprotobuf
-- 
--   OpenCV modules:
--     To be built:                 core flann hdf imgproc ml photo video dnn imgcodecs shape videoio highgui objdetect superres face features2d calib3d videostab xfeatures2d ximgproc optflow stitching
--     Disabled:                    java world aruco bgsegm bioinspired ccalib contrib_world datasets dpm fuzzy line_descriptor plot reg rgbd saliency stereo surface_matching text tracking xobjdetect xphoto
--     Disabled by dependency:      structured_light
--     Unavailable:                 cudaarithm cudabgsegm cudacodec cudafeatures2d cudafilters cudaimgproc cudalegacy cudaobjdetect cudaoptflow cudastereo cudawarping cudev python2 python3 ts viz cvv matlab sfm
-- 
--   GUI: 
--     QT:                          NO
--     GTK+ 2.x:                    YES (ver 2.24.23)
--     GThread :                    YES (ver 2.28.8)
--     GtkGlExt:                    NO
--     OpenGL support:              NO
--     VTK support:                 NO
-- 
--   Media I/O: 
--     ZLib:                        build (ver 1.2.8)
--     JPEG:                        build (ver 90)
--     WEBP:                        build (ver 0.3.1)
--     PNG:                         build (ver 1.6.19)
--     TIFF:                        build (ver 42 - 4.0.2)
--     JPEG 2000:                   build (ver 1.900.1)
--     OpenEXR:                     build (ver 1.7.1)
--     GDAL:                        NO
-- 
--   Video I/O:
--     DC1394 1.x:                  NO
--     DC1394 2.x:                  NO
--     FFMPEG:                      NO
--       codec:                     NO
--       format:                    NO
--       util:                      NO
--       swscale:                   NO
--       resample:                  NO
--       gentoo-style:              NO
--     GStreamer:                   NO
--     OpenNI:                      NO
--     OpenNI PrimeSensor Modules:  NO
--     OpenNI2:                     NO
--     PvAPI:                       NO
--     GigEVisionSDK:               NO
--     UniCap:                      NO
--     UniCap ucil:                 NO
--     V4L/V4L2:                    YES/YES
--     XIMEA:                       NO
--     Xine:                        NO
--     gPhoto2:                     YES
-- 
--   Parallel framework:            OpenMP
-- 
--   Other third-party libraries:
--     Use IPP:                     NO
--     Use IPP Async:               NO
--     Use VA:                      NO
--     Use Intel VA-API/OpenCL:     NO
--     Use Eigen:                   NO
--     Use Cuda:                    NO
--     Use OpenCL:                  NO
--     Use custom HAL:              NO
-- 
--   Python 2:
--     Interpreter:                 /usr/local/palomar/anaconda/bin/python2.7 (ver 2.7.12)
-- 
--   Python 3:
--     Interpreter:                 NO
-- 
--   Python (for build):            /usr/local/palomar/anaconda/bin/python2.7
-- 
--   Java:
--     ant:                         /usr/bin/ant (ver 1.7.1)
--     JNI:                         /usr/local/palomar/java/jdk1.8.0_77/include /usr/local/palomar/java/jdk1.8.0_77/include/linux /usr/local/palomar/java/jdk1.8.0_77/include
--     Java wrappers:               NO
--     Java tests:                  NO
-- 
--   Matlab:                        Matlab not found or implicitly disabled
-- 
--   Documentation:
--     Doxygen:                     /usr/bin/doxygen (ver 1.6.1)
--     PlantUML:                    NO
-- 
--   Tests and samples:
--     Tests:                       NO
--     Performance tests:           NO
--     C/C++ Examples:              NO
-- 
--   Install path:                  /home/developer/andor_development_stargate/working/opencv/javacpp-presets/javacpp-presets/opencv/cppbuild/linux-x86_64
-- 
--   cvconfig.h is in:              /home/developer/andor_development_stargate/working/opencv/javacpp-presets/javacpp-presets/opencv/cppbuild/linux-x86_64/opencv-3.1.0
-- -----------------------------------------------------------------
-- 
CMake Warning at CMakeLists.txt:1250 (message):
  The source directory is the same as binary directory.  "make clean" may
  damage the source tree

-- Configuring done
CMake Warning at cmake/OpenCVUtils.cmake:767 (add_library):
  Cannot generate a safe runtime search path for target opencv_hdf because
  files in some directories may conflict with libraries in implicit
  directories:

    runtime library [libz.so.1] in /usr/lib64 may be hidden by files in:
      /usr/local/palomar/anaconda/lib

  Some of these libraries may not be found correctly.
Call Stack (most recent call first):
  cmake/OpenCVModule.cmake:783 (ocv_add_library)
  cmake/OpenCVModule.cmake:730 (_ocv_create_module)
  cmake/OpenCVModule.cmake:939 (ocv_create_module)
  /home/developer/andor_development_stargate/working/opencv/javacpp-presets/javacpp-presets/opencv/cppbuild/linux-x86_64/opencv_contrib-3.1.0/modules/hdf/CMakeLists.txt:17 (ocv_define_module)

-- Generating done
-- Build files have been written to: /home/developer/andor_development_stargate/working/opencv/javacpp-presets/javacpp-presets/opencv/cppbuild/linux-x86_64/opencv-3.1.0

**Comment by saudet** [comment]
This is just libraries installed on your system that are conflicting with the build. Try to provide a clean environment for the build (with Docker, for example).

**Comment by jenniferwillow** [comment]
This is just about the most careless and stupid answer I have EVER encountered on a bulletin board.  No explanation other than to blame "something" on the system.  I've repeated this build problem on two different Linux boxes and on a Mac.  The problem is in the videoio module of Opencv 3.1 and the cppbuild.sh script doesn't allow you to do any configuration of the environment.
    In order to get OpenCV 3.1 to build on my systems I needed to remove the videoio module that was causing the problem.  If I do the same thing in this environment the script just downloads the module again.  This question SHOULD NOT HAVE BEEN CLOSED with this kind of answer.  The answer is useless, uninformative and careless.

**Comment by saudet** [comment]
Yes, it is a problem with OpenCV. There are a lot of problems like that with OpenCV and other libraries. The common solution is to use Docker, but if you do not want to use Docker, you can report this particular problem upstream, and maybe someone from the OpenCV project will fix it. It's not something I created. It was already like that in OpenCV. If you do not like OpenCV to be this way, and they refuse to fix this problem, I'm afraid you will either have use something else than OpenCV that doesn't have that problem, or you will need to fix OpenCV yourself!

**Comment by saudet** [comment]
In your case though if you are happy to have a build of OpenCV that does not include opencv_videoio and that builds fine, then that's alright. That's how we can customize the builds, by modifying the script and the source code, so you've answered your own question.
