### ISSUE TITLE
“double free or corruption” /  “invalid pointer”

### ISSUE THREAD

**Issue by songoo** [bytedeco/javacpp-presets#280]
Please help (http://stackoverflow.com/questions/39365972/what-causes-double-free-or-corruption-and-invalid-pointer-in-javacpp-ffmpe)

When i am calling avformat_open_input/avformat_close_input i randomly (never at first call) get those errors :

Error in `/usr/lib/jvm/java-8-oracle/bin/java': double free or corruption (out): 0x00007fe79c194aa0 or

Error in `/usr/lib/jvm/java-8-oracle/bin/java': double free or corruption (!prev): 0x00007fe51c3ffb60 or

Error in `/usr/lib/jvm/java-8-oracle/bin/java': double free or corruption (fasttop): 0x00007fcdc40fe4a0

I cant find out how to solve this, please help.

There is my implementation :
```
    private static void registerComponents() {
        if (!componentsRegistered) {
            componentsRegistered = true;
            av_register_all();
        }
    }

    public static void decodeFrame(ByteBuffer frameData) {
        registerComponents();

        AVFormatContext pFormatCtx = avformat_alloc_context();
        int i, videoStream;
        AVCodecContext pCodecCtx = null;
        AVCodec pCodec = null;
        AVFrame pFrame = null;
        AVFrame pFrameRGB = null;

        int[] frameFinished = new int[1];
        int numBytes;
        BytePointer buffer = null;

        AVDictionary    optionsDict = null;
        SwsContext      sws_ctx = null;

        AVIOContext ioContext = avio_alloc_context(new BytePointer(frameData), frameData.capacity(), 0, null, null, null, null);
        pFormatCtx.pb(ioContext);

        if (avformat_open_input(pFormatCtx, "", null, null) < 0) {
            logger.error(MarkerFactory.getMarker("ffmpeg"), "Problem with load video from memory.");
            return;
        }

       avformat_close_input(pFormatCtx);       
    }


```

**Comment by saudet** [comment]
You're probably using the API incorrectly. Make sure you understand how we're supposed to use each function. You could also try to use Valgrind:
https://github.com/deeplearning4j/libnd4j/wiki/Debugging-libnd4j
In any case, this isn't a problem with JavaCPP, but with FFmpeg, so if you believe there is an issue, please post a ticket over there. Thank you!
