### ISSUE TITLE
ffmpeg: AVStream.index_entries() should return AVIndexEntry[] instead of AVIndexEntry

### ISSUE THREAD

**Issue by xylo** [bytedeco/javacpp-presets#285]
At the moment it is not possible to access all index entries of a media file, since AVStream.index_entries() returns only the first AVIndexEntry.  Could you extend the API so that all index entries are accessible?

**Comment by saudet** [comment]
AVIndexEntry is a Pointer, so try to call position(int i).

**Comment by xylo** [comment]
Oh, you're right.  Thanks for the tip!
