### ISSUE TITLE
HDF5 download link

### ISSUE THREAD

**Issue by ckchow** [bytedeco/javacpp-presets#286]
The HDF5 group changed their links again, so caffe (for example) will die when trying to install HDF5 support. Their new ftp server is at https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.10/hdf5-1.10.0-alpha0/

**Comment by saudet** [comment]
Could you send a pull request? Thanks!

**Comment by saudet** [comment]
Done: https://github.com/bytedeco/javacpp-presets/pull/287 Thanks for the update!
