### ISSUE TITLE
Caffe: FloatSolverRegistry.CreateSolver(solver_param) does not return FloatRMSPropSolver

### ISSUE THREAD

**Issue by melroderick** [bytedeco/javacpp-presets#288]
When I call "FloatSolverRegistry.CreateSolver(solver_param)" using a solver file that specifies the "solver_type" (RMSPROP), it creates and returns an FloatSGDSolver instead of the specified solver type (FloatRMSPropSolver).

You can verify it is not running the initialization code for rmsprop_solver by setting the "rms_decay" flag in the solver file to 1. This should result in an error on Caffe's side when initializing the rmsprop_solver.

However, running "new FloatRMSPropSolver(solver_param)" does run the rmsprop_solver initilization code and, if rms_decay = 1, it will throw an error.

**Comment by saudet** [comment]
Sounds like a bug in Caffe's loader, no? I'm guessing the same would happen
calling it directly in C++.

**Comment by melroderick** [comment]
You're probably right. Sorry about that. I'll close this for now and look into it using C++.
