### ISSUE TITLE
TensorShape(int length) fails to instantiate a 1d tensor

### ISSUE THREAD

**Issue by urimerhav** [bytedeco/javacpp-presets#290]
Hi guys,

`new TensorShape(rows, columns)` correctly instantiates a 2d tensor, an equivalent `new TensorShape(length)` fails to generate a 1D tensor (and instead instantiates a tensor with 0 dims). 

@jpbottaro suspects that the cause is that TensorShape constructor is overloaded in javacpp. So, when we send only 1 input it actually calls TensorShape(long size) instead of TensorShape(long... dim_sizes).

**Comment by saudet** [comment]
Yes, do it explicitly with new TensorShape(new long[]{shape}) instead.
