### ISSUE TITLE
FFmpeg3.1.2-1.2 have problem when load avformat-57.dll in packet “ffmpeg-3.1.2-1.2-windows-x86_64.jar

### ISSUE THREAD

**Issue by JoyChung** [bytedeco/javacpp-presets#293]
Hi, I  use ffmpeg 3.1.2-1.2 by maven as follows:	
```
       <dependency>
		<groupId>org.bytedeco.javacpp-presets</groupId>
		<artifactId>ffmpeg</artifactId>
		<version>3.1.2-1.2</version>
	</dependency>
```
but,when I use function avformat.avio_open or avformat.avio_open2 to open a outputFile ,it throw a problem:
```
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ff9ea3d88e8, pid=15364, tid=0x0000000000000278
#
# JRE version: Java(TM) SE Runtime Environment (8.0_101-b13) (build 1.8.0_101-b13)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.101-b13 mixed mode windows-amd64 compressed oops)
# Problematic frame:
# C  [avformat-57.dll+0x288e8]

```
How should I solve this ?

**Comment by saudet** [comment]
That probably means that you made an error using the API of FFmpeg. Please refer to the documentation and make sure that you are using it correctly:
https://www.ffmpeg.org/doxygen/3.1/index.html

**Comment by JoyChung** [comment]
Sorry, I still can't find any solution.  My codes are as follows:
`	public static int encoder(String infile, String outfile){
	    AVFormatContext pFormatCtx;  
	    AVOutputFormat outFormat = null;  
	    AVStream audioStream;  
	    AVCodecContext pCodecCtx;  
	    AVCodec pCodec;  
	    
	    byte[] frameBuf;
	    AVFrame pFrame;  
	    AVPacket pPacket=new AVPacket();  
 
	    int ret=0; 
	    int size=0;
	    int frameNum=1000;
	    
	    avformat.av_register_all();
	    pFormatCtx = avformat.avformat_alloc_context();
	    outFormat = avformat.av_guess_format(null, outfile, null);
	    if(outFormat.isNull()){
	    	System.out.println("can not guess output format from outfile name");
	    	return -1;
	    }
	    pFormatCtx.oformat(outFormat);
	    if(avformat.avio_open2(pFormatCtx.pb(), outfile, avformat.AVIO_FLAG_WRITE,null,null)<0){
	    	System.out.println("can not open outputfile to FormatContext AVIO pointer");
	    	return -1;
	    }`
when run  if(avformat.avio_open2(pFormatCtx.pb(), outfile, avformat.AVIO_FLAG_WRITE,null,null)<0){
then I get that problem

**Comment by saudet** [comment]
Try to do it the same way as in JavaCV: https://github.com/bytedeco/javacv/search?q=avio_open

**Comment by JoyChung** [comment]
I have try function avio_open already. It got the same problem

**Comment by saudet** [comment]
Does FFmpegFrameRecorder work? If it works, you're probably doing something wrong.
