### ISSUE TITLE
GPU not working in Tensorflow?

### ISSUE THREAD

**Issue by ckchow** [bytedeco/javacpp-presets#294]
I'm using a prebuilt version of javacpp-presets's tensorflow bindings. (for SparkNet, specifically here https://github.com/amplab/SparkNet). However, whenever I create a graph with GPU nodes and load it with javacpp-tensorflow, the placement log says they are all placed on CPU. nvidia-smi does not report any GPU memory usage by the JVM either. Has anyone gotten GPU stuff to work on javacpp-tensorflow?

**Comment by saudet** [comment]
The binaries are not compiled with CUDA enabled. Rebuilding them with CUDA enabled will work, but the binaries might stop working on machines without GPU. That's something I'd like to check. Could you help out with that?

**Comment by saudet** [comment]
Version 1.3 now contains a build with GPU support enabled. Enjoy!
