### ISSUE TITLE
CUDA 8 support

### ISSUE THREAD

**Issue by Enet4** [bytedeco/javacpp-presets#300]
CUDA 8 has been stable for a while now. Since JavaCPP doesn't seem to support this version yet, many of its presets just stop working when this version is installed in the system. My attempts to build the preset myself with an updated version only brought a bunch of "could not find symbol `cudaDataType`" compilation errors in some of the generated files: cublas.java, cusolver.java and cusparse.java. Is there any progress on this matter?

**Comment by saudet** [comment]
Yes, it's supported: http://search.maven.org/#search%7Cga%7C1%7Cjavacpp%20cuda

**Comment by Enet4** [comment]
I stand corrected. My main culprit was actually that the Caffe preset isn't working on CUDA 8. I'll look deeper into my problem and file a more specific issue if it's deemed necessary.

Also note that the [readme file](https://github.com/bytedeco/javacpp-presets/blob/master/README.md#the-maven-modules) only states version 7.5 on the list of supported library versions.

**Comment by saudet** [comment]
Ah, ok, so we need a version of Caffe that supports CUDA 8...

**Comment by Enet4** [comment]
> Ah, ok, so we need a version of Caffe that supports CUDA 8...

Yes, maybe I should have been more specific. 😬 Caffe itself is already compatible with CUDA 8. But I had to build the 1.2.5-SNAPSHOT version of the Caffe preset myself to make it link to the CUDA 8.0 dynamic libraries. It seems to me that the latest provided binaries are still linking to CUDA 7.5.

So it seems my particular problem is solved. Thank you for your time, nevertheless.
