### ISSUE TITLE
Is it possible to build presets for android 64-bit arch

### ISSUE THREAD

**Issue by coralinejones1985** [bytedeco/javacpp-presets#304]
> With
>  the above in working order, simply execute
> bash
> $ ANDROID_NDK=/path/to/android-ndk/ bash cppbuild.sh [-platform <name>] <install | clean> [projects]
> 
> where possible platform names are: `android-arm`, `android-x86`, `linux-x86`, `linux-x86_64`, `linux-arm`, `macosx-x86_64`, `windows-x86`, `windows-x86_64`, etc.

I need to build presets for android-x86-64. Is it possible? What should I modify to do it right?

**Comment by saudet** [comment]
Sure it's possible. First provide a build in the `cppbuild.sh` file, and then it should work.

**Comment by saudet** [comment]
Marking as duplicate of #52

**Comment by saudet** [comment]
64-bit builds for Android (as the "android-arm64" and "android-x86_64" platforms) are now available, so please give it a try! Binaries for 1.4.1-SNAPSHOT can be downloaded from the snapshot repository: http://bytedeco.org/builds/
