### ISSUE TITLE
Preset for MediaInfo

### ISSUE THREAD

**Issue by beligum** [bytedeco/javacpp-presets#306]
Hi all,

I'm thinking about building a JavaCPP MediaInfo preset (see https://mediaarea.net/en/MediaInfo and https://sourceforge.net/projects/mediainfo/). MediaInfo is a very qualitative (and fairly simple) video metadata-extraction library that get's a lot more out of media files (compared to eg. FFmpeg), supporting (and funded by) international standards like EBUCore.

I'm looking for some help to kick off the project; can anyone point me in the right direction to some howto-articles? Anyone who wishes to help is, of course, very welcome.

thanks!

b.

**Comment by saudet** [comment]
Sure, please start here:
https://github.com/bytedeco/javacpp-presets/wiki/Create-New-Presets
Let me know if you have any additional questions! Thanks

**Comment by beligum** [comment]
Hi Samuel,

Let me come back to this:
I recently discovered the MediaInfo project has it's own JNI bindings, rendering this enhancement a bit obsolete. It would be cool to stitch it in with javacpp, but since it's basically there already, it's doubling the effort, so I'll close this request.

b.
