### ISSUE TITLE
UserSetting&  How to convert this type?

### ISSUE THREAD

**Issue by 275873859** [bytedeco/javacpp-presets#312]
Such as:  
```cpp
typedef int ErrorInfo;

virtual void getSetting(int type, std::function<void(ErrorInfo, UserSetting&)> cb) = 0;
```
I am now writing：
```java
.put(new Info("std::function<void(ErrorInfo,UserSetting&)>").cast().pointerTypes("FnCbErrUserSetting"))

	public static class FnCbErrUserSetting extends FunctionPointer {
		static {
			Loader.load();
		}
		/** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
		public FnCbErrUserSetting(Pointer p) {
			super(p);
		}
		protected FnCbErrUserSetting() {
			allocate();
		}
		private native void allocate();
		public void call(int code,@Cast("UserSetting*")Pointer p) {
			System.out.println("=> FnCbErrUserSetting call");
		}
	}
```
Error Info:
'UserSetting' does not refer to a value
 ptr->getSetting(arg0, *(std::function<void(ErrorInfo,UserSetting&)>*)ptr1);

I think may be & problem, and has the difference & other examples.

**Comment by saudet** [comment]
That should work, could you provide an example?

**Comment by 275873859** [comment]
I'm sorry, is my problem, is not to create public static class XXX extends FunctionPointer problem

**Comment by saudet** [comment]
`ErrorInfo` and `UserSetting` are probably in a namespace, and if so, you forgot to specify it.

**Comment by 275873859** [comment]
Thank you very much, our project was almost done, finally, to ask a question:
```cpp
	virtual int64 downloadFile(DownloadFileProperty &fileProperty, std::function<void(ErrorInfo, const std::string&, int64)> cb, std::function<void(int32, int32, const std::string&)> pro = nullptr) = 0;
```
```java
	public native @Cast("int64") long downloadFile(@ByRef DownloadFileProperty fileProperty, @ByVal FnCbErrStrLong cb, @ByVal(nullValue = "nullptr") FnCb2IntStr pro/*=nullptr*/);
	public native @Cast("int64") long downloadFile(@ByRef DownloadFileProperty fileProperty, @ByVal FnCbErrStrLong cb);
```
ErrorInfo ：
non-pointer operand
      type 'JavaCPP_00024FnCb2IntStr' incompatible with nullptr  int64 rvalue = (int64)ptr->downloadFile(*ptr0, *ptr1, ptr2 == NULL ? nullptr : *ptr2);
Excuse me, are for `= nullptr` this have what good method? Did not find relevant examples

**Comment by saudet** [comment]
This should be fixed with https://github.com/bytedeco/javacpp/commit/cba7a5918bac72a21d3da2beaf235019105da00d

**Comment by 275873859** [comment]
thanks,After using the latest compilation of javacpp. Jar, perfect through, our project finally replace out.
