### ISSUE TITLE
Using LLVM javacpp-presets with gradle

### ISSUE THREAD

**Issue by ftomassetti** [bytedeco/javacpp-presets#314]
Specifying:
```compile 'org.bytedeco.javacpp-presets:llvm:3.8.0-1.2:linux-x86_64'```

I get:

```Could not find javacpp-presets-Linux-amd64.jar (org.bytedeco:javacpp-presets:1.2).```

While specifying:
```org.bytedeco.javacpp-presets:llvm:3.8.0-1.2```

I get:

```Could not find javacpp-presets-${os.name}-${os.arch}.jar (org.bytedeco:javacpp-presets:1.2).```

Any idea?

**Comment by ftomassetti** [comment]
It seems a known issue with gradle. Workaround:

```
configurations {
    all*.exclude group: 'org.bytedeco', module: 'javacpp-presets'
}
```
Should this one be closed?

**Comment by saudet** [comment]
Yes it's documented here:
https://github.com/bytedeco/javacpp-presets/wiki/Issues-with-Build-Tools#gradle
