### ISSUE TITLE
java.lang.UnsatisfiedLinkError with LLVM on Travis

### ISSUE THREAD

**Issue by phase** [bytedeco/javacpp-presets#318]
[My project](https://github.com/phase/lang-kotlin-antlr-compiler) builds fine locally, but it doesn't build so fine on Travis. I have a [test suite to test LLVM compilation](https://github.com/phase/lang-kotlin-antlr-compiler/blob/fbd4362917852844ab942e5ee2274c3186e55ddd/src/test/kotlin/xyz/jadonfowler/compiler/LLVMTest.kt), and running it on Travis gives an error:

```
xyz.jadonfowler.compiler.LLVMTest > genGlobalConstant FAILED
    java.lang.UnsatisfiedLinkError at LLVMTest.kt:19
        Caused by: java.lang.UnsatisfiedLinkError at LLVMTest.kt:19
xyz.jadonfowler.compiler.LLVMTest > genVariableDeclaration FAILED
    java.lang.NoClassDefFoundError at LLVMTest.kt:44
xyz.jadonfowler.compiler.LLVMTest > genComplexExpressions FAILED
    java.lang.NoClassDefFoundError at LLVMTest.kt:59
xyz.jadonfowler.compiler.LLVMTest > genIfStatement FAILED
    java.lang.NoClassDefFoundError at LLVMTest.kt:93
xyz.jadonfowler.compiler.LLVMTest > genGlobalsInFunctions FAILED
    java.lang.NoClassDefFoundError at LLVMTest.kt:122
xyz.jadonfowler.compiler.LLVMTest > genFunction FAILED
    java.lang.NoClassDefFoundError at LLVMTest.kt:31
xyz.jadonfowler.compiler.LLVMTest > genVariableReassignment FAILED
    java.lang.NoClassDefFoundError at LLVMTest.kt:75
```

I am not sure what is causing these errors, nor how to solve them. I am using the [LLVM 3.8](https://github.com/phase/lang-kotlin-antlr-compiler/blob/fbd4362917852844ab942e5ee2274c3186e55ddd/build.gradle#L36) bindings because 3.8 is the latest on the Ubuntu repositories.

**Comment by phase** [comment]
Travis' default version of LLVM is 3.4, updating it with the `apt` addon fixed the build.

```yaml
addons:
  apt:
    packages:
      - llvm-3.8
      - clang-3.8
```

I hope this helps someone on their travels!

**Comment by saudet** [comment]
Awesome! Thanks for the feedback
