### ISSUE TITLE
How to map char array in C

### ISSUE THREAD

**Issue by hzyfox** [bytedeco/javacpp-presets#325]
I define a C Struct, and there is a member: char buffer[256]; and I want to use JavaCpp to map it, I use the following code:
public native @Cast("char *")BytePointer buffer(); piblic native void buffer(@Cast("char *")BytePointer buffer);

but cause incompatible cast error: from 'char [256]' to 'char*'
Can some one help me how to map it, thank you!

**Comment by saudet** [comment]
Duplicate of https://github.com/bytedeco/javacpp/issues/147
