### ISSUE TITLE
Adding support for WebM VP8 & VP9 to ffmpeg

### ISSUE THREAD

**Issue by beligum** [bytedeco/javacpp-presets#33]
Hi all,

I've patched the ffmpeg/cppbuild.sh script to include support for libvpx (to encode WebM videos).
Here's the gist: https://gist.github.com/beligum/f4a46aac90b807aa6907
For now, it's only implemented for linux x64, since it's the only architecture I have access to. Sources are downloaded from the official Google repo.

Enabling compilation for other platforms should be trivial.

Feel free to post feedback, follow-up or suggestions.

b.

**Comment by saudet** [comment]
Thanks!! Looks good. Could you modify that to download the source archive instead? I'm not sure if they recommend to pick the master branch like the x264 guys, but if they do, that would be:
https://chromium.googlesource.com/webm/libvpx/+archive/master.tar.gz
This way we don't need to add a dependency on git.

As for the platform, I didn't check, but it looks like `--target=x86_64-linux-gcc` should be added for  x64_86 in case someone tries to cross-compile, and we can also build 32-bit x86 on 64-bit Linux, so give it a try with `--target=x86-linux-gcc`, and send me a pull request to have all this merged! Thanks

**Comment by saudet** [comment]
Support included in version 1.0. Enjoy!
