### ISSUE TITLE
Can‘t support android studio gradle compile 'org.bytedeco.javacpp-presets:opencv:3.1.0-1.2'

### ISSUE THREAD

**Issue by luorenjin** [bytedeco/javacpp-presets#330]
Error:Could not find javacpp-presets-Windows 8.1-amd64.jar (org.bytedeco:javacpp-presets:1.2).
Searched in the following locations:
    https://jcenter.bintray.com/org/bytedeco/javacpp-presets/1.2/javacpp-presets-1.2-Windows 8.1-amd64.jar

why?

**Comment by saudet** [comment]
https://github.com/bytedeco/javacpp-presets/wiki/Issues-with-Build-Tools#gradle
