### ISSUE TITLE
Working with filter "overlay"

### ISSUE THREAD

**Issue by FanSerg2** [bytedeco/javacpp-presets#336]
I have a problem with overlaying image on video.  This is my filters string:

`"movie=" + imagePath + " [effect];" + "[in][effect]overlay=format=yuv420 [out]";`

This is part of code where I create record video:

```
while ((frame = grabberMain.grab()) != null) {
    if (frame.image != null) {
        filter.push(frame, grabberMain.getPixelFormat());
        while ((frame2 = filter.pull()) != null) {
            recorder.record(frame2, grabberMain.getPixelFormat());
        }
    } else {
        recorder.record(frame);
    }
}

```
This code works fine in library version 2.8.1-1.1, but in version 3.2.1-1.3 in result I have video without overlayed image.
Also, I tried to use this filter:

`"color=color=red@.3:size=320x480 [over]; [in][over] overlay=format=yuv420 [out]"`

It works like filter “overlay”, in version 2.8.1-1.1 I see video with red rectangle on top left corner. But in version 3.2.1-1.3 I see only video.

Filters like “transpose”, “rotate” or “scale” work fine.
I downloaded ffmpeg.exe for windows OS from http://ffmpeg.org/ and tried to use the same filters (overlay, transpose, rotate, scale). They worked fine.

Why filter “overlay” doesn’t work in version 3.2.1-1.3?

I use Nexus 5 with Android 6.0.1 and tablet Asus K011 with Android 4.4.

**Comment by saudet** [comment]
Like I said, it's probably a bug in FFmpeg. Please file a ticket over there: https://ffmpeg.org/bugreports.html

**Comment by FanSerg2** [comment]
Does filter "overlay" work fine in your projects?

**Comment by saudet** [comment]
No, if you have a complete sample that you could contribute, that would be very welcome!

**Comment by FanSerg2** [comment]
I have uploaded example application on github (https://github.com/FanSerg2/FFmpegTest)
If you could look at it I will be very grateful.

**Comment by saudet** [comment]
This has been fixed with commit https://github.com/bytedeco/javacv/commit/35dd7f8134ff4b31e6ff94ab6049f2a13418cc5a, enjoy!
