### ISSUE TITLE
UnsatisfiedLinkError on Windows flycapture "The specified procedure could not be found"

### ISSUE THREAD

**Issue by bjfiedler** [bytedeco/javacpp-presets#337]
Hi,
I followed the [Example from the Readme](https://github.com/bytedeco/javacpp-presets/blob/master/flycapture/README.md)

mvn compile exec::java gave me:
`
Caused by: java.lang.UnsatisfiedLinkError: C:\Users\bjoern\.javacpp\cache\flycapture-2.9.3.43-1.3-windows-x86_64.jar\org\bytedeco\javacpp\windows-x86_64\jniFlyCapture2.dll: Die angegebene Prozedur wurde nicht gefunden
`
aka
`The specified procedure could not be found`
for full output see logfile

Dependency Walker output is attached.

My environment:

Win10
FlyCapture 2.10.3.266 SDK - Windows (64-bit) — 11/22/2016
javac 1.8.0_25

Thanks 
Björn

![depends exe screenshot](https://cloud.githubusercontent.com/assets/5951570/21294300/ed104922-c539-11e6-9779-26d8af272e1e.jpg)
[stdout_log.txt](https://github.com/bytedeco/javacpp-presets/files/659475/stdout_log.txt)

[jniFlyCapture2_DependencyWalker.zip](https://github.com/bytedeco/javacpp-presets/files/659476/jniFlyCapture2_DependencyWalker.zip)

**Comment by saudet** [comment]
Hum, that's a known bug in FlyCapture2, and the workaround in place used to work, but it looks like it doesn't work anymore, so we'll need to update that.

**Comment by saudet** [comment]
Ok, fixed in the commit above! SNAPSHOT binaries available here: https://oss.sonatype.org/content/repositories/snapshots/org/bytedeco/javacpp-presets/flycapture/2.9.3.43-1.3.1-SNAPSHOT/
Thank you for reporting.

**Comment by saudet** [comment]
Thanks to @jpsacha, presets for version 2.11 have been released with JavaCPP 1.4:
http://search.maven.org/#search%7Cga%7C1%7Cbytedeco%20flycapture
They should be working well, but if you have any issues, please let me know! Thanks
