### ISSUE TITLE
builder  android-arm  3rdparty/libtiff/CMakeFiles/libtiff.dir/tif_open.c.o] Error 1

### ISSUE THREAD

**Issue by luorenjin** [bytedeco/javacpp-presets#339]
my Environment
centos 7
cmake version 2.8.12.2
g++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-4)

-- Configuring done
-- Generating done
-- Build files have been written to: /root/javacv/javacpp-presets/opencv/cppbuild/android-arm/opencv-3.1.0
[  3%] Built target zlib
[  9%] Built target libjpeg
[ 15%] [ 23%] Built target libjasper
Built target libwebp
[ 23%] Building C object 3rdparty/libtiff/CMakeFiles/libtiff.dir/tif_open.c.o
[ 26%] Built target libpng
/root/javacv/javacpp-presets/opencv/cppbuild/android-arm/opencv-3.1.0/3rdparty/libtiff/tif_open.c: In function 'TIFFClientOpen':
/root/javacv/javacpp-presets/opencv/cppbuild/android-arm/opencv-3.1.0/3rdparty/libtiff/tif_open.c:352:27: error: #if with no expression
         #if HOST_BIGENDIAN
                           ^
make[2]: *** [3rdparty/libtiff/CMakeFiles/libtiff.dir/tif_open.c.o] Error 1
make[1]: *** [3rdparty/libtiff/CMakeFiles/libtiff.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 31%] Built target libprotobuf
[ 39%] Built target opencv_core
[ 50%] Built target IlmImf
make: *** [all] Error 2

**Comment by saudet** [comment]
Please follow the instructions here:
https://github.com/bytedeco/javacpp-presets/wiki/Build-Environments#android-arm-and-x86
