### ISSUE TITLE
Update LLVM Preset to 3.9.1

### ISSUE THREAD

**Issue by phase** [bytedeco/javacpp-presets#341]
[LLVM 3.9.1](http://releases.llvm.org/3.9.1/docs/ReleaseNotes.html) was released, and it has a lot of bugfixes.

**Comment by saudet** [comment]
Cool, should be just a matter of updating the version in the cppbuild.sh
file and in  the 3 pom.xml files. Mind giving it a try?

**Comment by phase** [comment]
Working on it now

**Comment by saudet** [comment]
Thanks for checking this out!
