### ISSUE TITLE
Cppbuild.sh Broken for latest Tensorflow

### ISSUE THREAD

**Issue by hollinwilkins** [bytedeco/javacpp-presets#357]
It seems like there is an error with cppbuild.sh and tensorflow for version 0.12.1, I get the following error when I try to run it from my Macbook Pro:

```
Detected platform "macosx-x86_64"
Building for platform "macosx-x86_64"
Installing "tensorflow"
~/Workspace/lb-client/javacpp-presets/tensorflow/cppbuild ~/Workspace/lb-client/javacpp-presets
Decompressing archives
sed: 1: "tensorflow/workspace.bzl": undefined label 'ensorflow/workspace.bzl'
~/Workspace/lb-client/javacpp-presets/tensorflow
```

**Comment by saudet** [comment]
Looks like the `sed` command doesn't always work too well on Mac. Anyway, we don't need it anymore with TensorFlow 1.0.0-alpha and I've just updated the presets with that version, so please try again!

@andreas-eberle BTW, your patch for Android doesn't work anymore with TensorFlow 1.0.0-alpha. I spent a bit of time trying to fix it, but was unsuccessful. Could you take a look at that?

**Comment by andreas-eberle** [comment]
@saudet: Is it already fixed in the current master? Or did you just merge your last state into master? I will try to have a look at it.

**Comment by saudet** [comment]
No, not fixed yet. Thanks!

**Comment by saudet** [comment]
@andreas-eberle They've just released 1.0.0-rc0, so try to make it work that version instead. Thanks!

**Comment by saudet** [comment]
@andreas-eberle Actually, they seemed to have fixed something related to Android in rc0. Your patch now works again! So, closing this.

**Comment by andreas-eberle** [comment]
:D that's always the best way to fix problems ;)

**Comment by saudet** [comment]
@andreas-eberle It's broken on TensorFlow 1.1.0 though :( Do you think you could take a look at it?
https://travis-ci.org/bytedeco/javacpp-presets/jobs/236043941
Thanks!
