### ISSUE TITLE
Error when building with gradle ("Could not find javacpp-presets.jar...")

### ISSUE THREAD

**Issue by kthxb** [bytedeco/javacpp-presets#361]
So I'm trying to build my app with gradle, and I get this error:

>Error:Gradle: A problem occurred configuring project ':app'.
 Could not find javacpp-presets-Windows 10-amd64.jar (org.bytedeco:javacpp-presets:1.2).
  Searched in the following locations:
      https://jcenter.bintray.com/org/bytedeco/javacpp-presets/1.2/javacpp-presets-1.2-Windows 10-amd64.jar

I already read about this issue (https://github.com/bytedeco/javacpp-presets/issues/220), but when adding the suggested workaround

`configurations {
    all*.exclude group: 'org.bytedeco', module: 'javacpp-presets'
}`

it either says that it can't resolve "all*" or "exclude", depending on where I add it in.
I really don't know a lot about gradle and this stuff, so I'm not 100% sure where to paste the code, too -- in the build.gradle inside the /app or outside? Just at the bottom of the file or in one of the scopes (like android{}, ...)?
Also sorry if this is the wrong place to ask, but thanks in advance for any help

**Comment by phase** [comment]
[Here](https://github.com/phase/lang-kotlin-antlr-compiler/blob/master/build.gradle) is my build file. You should have Maven Central in your repositories.

```gradle
repositories {
    mavenCentral()
}
```

**Comment by saudet** [comment]
That was solved with version 1.3. Please upgrade to version 1.3.
