### ISSUE TITLE
OpenCV 3.2 Support

### ISSUE THREAD

**Issue by archenroot** [bytedeco/javacpp-presets#366]
Hi guys,

if you plan to do 3.2 support, when it could be expected (in weeks/months). 

Thanks for this great work.

Ladislav

**Comment by saudet** [comment]
Done! https://github.com/bytedeco/javacpp-presets/commit/7e2b6004277b8c8baf57d8b1a17957204dad3440

**Comment by archenroot** [comment]
@saudet you are ninja!

**Comment by BloomyPiggy** [comment]
Awesome :D 

Will Opencv 3.2 be uploaded to [maven repository](https://mvnrepository.com/artifact/org.bytedeco.javacpp-presets/opencv) ?

**Comment by saudet** [comment]
Binaries are now available on Maven:
http://repo1.maven.org/maven2/org/bytedeco/javacpp-presets/opencv/3.2.0-1.3/
https://github.com/bytedeco/javacpp-presets/tree/master/opencv#the-pomxml-build-file
Enjoy!
