### ISSUE TITLE
libvpx 1.6.1 on android x86 failing

### ISSUE THREAD

**Issue by vb216** [bytedeco/javacpp-presets#375]
Is the new libvpx1.6.1 building OK for others? Looks like something changed from 1.6.0 (that still builds fine for me), I get error below. I've tried a few variations on build params and paths, but the best I managed is substituting one error for another

...
    [AS] vp9/encoder/x86/vp9_dct_sse2.asm.o
    [AS] vp9/encoder/x86/vp9_error_sse2.asm.o
    [CREATE] vpx.pc
    [AR] libvpx_g.a
    [STRIP] libvpx.a < libvpx_g.a
    [DEP] tools/tiny_ssim.c.d
    [CC] tools/tiny_ssim.c.o
    [LD] tools/tiny_ssim
/opt/Android/android-ndk-r13b/toolchains/x86-4.9/prebuilt/linux-x86_64/bin/../lib/gcc/i686-linux-android/4.9.x/../../../../i686-linux-android/bin/ld: error: cannot find -lm
tools/tiny_ssim.c.o:tiny_ssim.c:function vp9_mse2psnr: error: undefined reference to 'log10'
tools/tiny_ssim.c.o:tiny_ssim.c:function main: error: undefined reference to '__sF'
tools/tiny_ssim.c.o:tiny_ssim.c:function main: error: undefined reference to '__sF'
tools/tiny_ssim.c.o:tiny_ssim.c:function main: error: undefined reference to 'sscanf'
tools/tiny_ssim.c.o:tiny_ssim.c:function main: error: undefined reference to '__sF'
tools/tiny_ssim.c.o:tiny_ssim.c:function main: error: undefined reference to 'fprintf'
tools/tiny_ssim.c.o:tiny_ssim.c:function main: error: undefined reference to 'sscanf'
tools/tiny_ssim.c.o:tiny_ssim.c:function main: error: undefined reference to 'fopen'
tools/tiny_ssim.c.o:tiny_ssim.c:function main: error: undefined reference to 'fopen'
tools/tiny_ssim.c.o:tiny_ssim.c:function main: error: undefined reference to '__sF'
tools/tiny_ssim.c.o:tiny_ssim.c:function main: error: undefined reference to 'fprintf'
tools/tiny_ssim.c.o:tiny_ssim.c:function main: error: undefined reference to 'malloc'
tools/tiny_ssim.c.o:tiny_ssim.c:function main: error: undefined reference to 'malloc'
tools/tiny_ssim.c.o:tiny_ssim.c:function main: error: undefined reference to 'fread'
tools/tiny_ssim.c.o:tiny_ssim.c:function main: error: undefined reference to 'fread'
tools/tiny_ssim.c.o:tiny_ssim.c:function main: error: undefined reference to 'free'
tools/tiny_ssim.c.o:tiny_ssim.c:function main: error: undefined reference to 'free'
tools/tiny_ssim.c.o:tiny_ssim.c:function main: error: undefined reference to 'printf'
tools/tiny_ssim.c.o:tiny_ssim.c:function main: error: undefined reference to 'printf'
tools/tiny_ssim.c.o:tiny_ssim.c:function main: error: undefined reference to 'pow'
tools/tiny_ssim.c.o:tiny_ssim.c:function main: error: undefined reference to 'printf'
tools/tiny_ssim.c.o:tiny_ssim.c:function main: error: undefined reference to 'printf'
tools/tiny_ssim.c.o:tiny_ssim.c:function main: error: undefined reference to 'strcmp'
tools/tiny_ssim.c.o:tiny_ssim.c:function main: error: undefined reference to 'strcmp'
tools/tiny_ssim.c.o:tiny_ssim.c:function main: error: undefined reference to 'fclose'
tools/tiny_ssim.c.o:tiny_ssim.c:function main: error: undefined reference to 'fread'
tools/tiny_ssim.c.o:tiny_ssim.c:function main: error: undefined reference to '__errno'
tools/tiny_ssim.c.o:tiny_ssim.c:function main: error: undefined reference to 'strerror'
tools/tiny_ssim.c.o:tiny_ssim.c:function main: error: undefined reference to '__errno'
tools/tiny_ssim.c.o:tiny_ssim.c:function main: error: undefined reference to 'strerror'
tools/tiny_ssim.c.o:tiny_ssim.c:function main: error: undefined reference to 'fprintf'
tools/tiny_ssim.c.o:tiny_ssim.c:function main: error: undefined reference to 'fclose'
collect2: error: ld returned 1 exit status

**Comment by saudet** [comment]
We don't need the tools, we can disable them with `./configure --disable-tools` if required...

**Comment by vb216** [comment]
Yeah that PR fixed it

**Comment by saudet** [comment]
That is, pull #378? Yes, thanks! FYI, there is a way to indicate that in GitHub lingo when creating a PR: https://help.github.com/articles/closing-issues-via-commit-messages/
