### ISSUE TITLE
java.lang.UnsatisfiedLinkError: org.bytedeco.javacpp.opencv_core.CV_MAKETYPE(II)I

### ISSUE THREAD

**Issue by santhosh827** [bytedeco/javacpp-presets#376]
java.lang.UnsatisfiedLinkError: org.bytedeco.javacpp.opencv_core.CV_MAKETYPE(II)I
	at org.bytedeco.javacpp.opencv_core.CV_MAKETYPE(Native Method)
	at org.bytedeco.javacpp.opencv_core.<clinit>(opencv_core.java:1042)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.bytedeco.javacpp.Loader.load(Loader.java:464)
	at org.bytedeco.javacpp.Loader.load(Loader.java:409)
	at org.bytedeco.javacpp.flandmark.<clinit>(flandmark.java:13)

**Comment by saudet** [comment]
I see, there are a few dependencies missing from those pom.xml files.
You'll need to add OpenCV manually for now:
https://github.com/bytedeco/javacpp-presets/tree/1.3/opencv#the-pomxml-build-file
Thanks for reporting!

**Comment by santhosh827** [comment]
Dear saudet,
Thank you i added dependencies now working
but i got OutOfMemoryError and i have added heap memory -J-Xmx1040m in VM Options
please give any solutions

OpenCV Error: Insufficient memory (Failed to allocate 1398941156 bytes) in cv::OutOfMemoryError, file src\alloc.cpp, line 52
Exception in thread "main" java.lang.RuntimeException: src\alloc.cpp:52: error: (-4) Failed to allocate 1398941156 bytes in function cv::OutOfMemoryError
        at org.bytedeco.javacpp.flandmark.flandmark_detect(Native Method)
	at gui.detection.RotateFaceImage.detectLandmarks

**Comment by saudet** [comment]
That looks like limits imposed by your OS...

**Comment by santhosh827** [comment]
Dear saudet,

Thank you now i got below exception when below code is executing
final CvHaarClassifierCascade faceCascade =
cvLoadHaarClassifierCascade(file.getCanonicalPath(), cvSize(0, 0)); 
please help

Error loading class com/googlecode/javacpp/Loader.
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x560b55d0, pid=4620, tid=4236
#
# JRE version: Java(TM) SE Runtime Environment (8.0_40-b25) (build 1.8.0_40-b25)

# Java VM: Java HotSpot(TM) Client VM (25.40-b25 mixed mode windows-x86 )
# Problematic frame:
# V  [jvm.dll+0xe55d0]
#
# Failed to write core dump. Minidumps are not enabled by default on client vers
ions of Windows
#
# An error report file with more information is saved as:
# E:\SeaAPP\wildfly-8.2.0.Final\bin\hs_err_pid4620.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#

**Comment by saudet** [comment]
You're using a very old version of JavaCPP. Please upgrade that first and
then let me know if you still have problems with the newest version.

**Comment by santhosh827** [comment]
Dear saudet,

I have added new version of JavaCPP(javacpp-1.2.4.jar).But still i am facing same error.

**Comment by santhosh827** [comment]
Dear saudet,

I have added these jars in java bulid path

javacpp-1.2.4.jar
javacv-1.2.jar
javacv-0.10-sources.jar
javacv-platform.jar
opencv.jar
opencv-2.4.9-0.8.jar
opencv-2.4.10-0.10.jar
opencv-3.1.0-1.2.jar
opencv-2411.jar
opencv-windows-x86.jar

**Comment by santhosh827** [comment]
Dear saudet,

I got below exception

Caused by: java.lang.UnsatisfiedLinkError: org.bytedeco.javacpp.opencv_core.IPL_
IMAGE_MAGIC_VAL()I
        at org.bytedeco.javacpp.opencv_core.IPL_IMAGE_MAGIC_VAL(Native Method) [
opencv-2.4.10-0.10.jar:1.2.4]
        at org.bytedeco.javacpp.opencv_core.<clinit>(opencv_core.java:740) [open
cv-2.4.10-0.10.jar:1.2.4]

**Comment by saudet** [comment]
I told you, please try to use the latest version!
