### ISSUE TITLE
Skip whole operator/function from parsing

### ISSUE THREAD

**Issue by CasperReduct** [bytedeco/javacpp-presets#377]
Hi,

i'm trying parse header files and want skip some function i..e
custom.h
....
operator Labels const&() const {
... 
}
But can't figure out how to do this.
Could anyone help?

P.S. Generated java file contains:
public native @ByRef @Name("operator somenamespace::sub::Labels&") Labels asLabels();  <<--Don't want generate it at all

JNI cpp file generates with errors:
 error: 'struct somenamespace::sub::ChangableLabels' has no member named 'operator somenamespace::sub::Labels&'
 rptr = &ptr->operator somenamespace::sub::Labels&();

**Comment by saudet** [comment]
Something like `new Info("operator somenamespace::sub::Labels&").skip()` should work, but if it doesn't please provide some small sample code I can debug here. Thanks!

**Comment by CasperReduct** [comment]
Sadly it doesn't works.
h file:
namespace somenamespace {
namespace sub {
class Labels:
....
}
struct ChangableLabels {
...
    Labels const& view() const     {
        return *labels_;
    }

    operator Labels const&() const {
        return view();
    }

private:
    Labels* labels_;
}

Sorry that can't take more info due restriction

InfoMapper:
@Properties(target = "com.somepackagec.LabelLibrary", value = {
        @Platform(include = {"<label.h>"}, link = "...", define = {"SHARED_PTR_NAMESPACE std", "UNIQUE_PTR_NAMESPACE std"}
        )})
public class LabelLibrary implements InfoMapper {
    public void map(InfoMap infoMap) {
        infoMap
                .put(new Info("operator imaginesoftware::crt::Labels&").skip()) // not works (

**Comment by CasperReduct** [comment]
After debuging parser, found that need write new Info("operator somenamespace::sub::Labels()").skip().
Thanks for answer

**Comment by saudet** [comment]
Great! Thanks for the feedback. It should also accept it with the `&` though, so let's leave this open so I don't forget to fix this.

**Comment by saudet** [comment]
Finally, I've fixed this! Something like either 
`new Info("operator const somenamespace::sub::Labels&").skip()` or
`new Info("operator const somenamespace::sub::Labels&()").skip()` 
now both work. Thanks for reporting!
