### ISSUE TITLE
Seeking example code for FFMPEG CustomIO

### ISSUE THREAD

**Issue by opus111** [bytedeco/javacpp-presets#382]
Hello, this is a question, not a bug

I am trying to get AVIO CustomIO to work in JavaCPP FFMPEG.  Is there a working example and/or test code for this?  Could not find anything.  Looking for a link.

Thanks
Peter

**Comment by saudet** [comment]
There are examples of that in FFmpegFrameGrabber and FFmpegFrameRecorder:
https://github.com/bytedeco/javacv/blob/master/src/main/java/org/bytedeco/javacv/FFmpegFrameGrabber.java#L514
https://github.com/bytedeco/javacv/blob/master/src/main/java/org/bytedeco/javacv/FFmpegFrameRecorder.java#L389
