### ISSUE TITLE
Java Runtime Error - FaceRecognition 

### ISSUE THREAD

**Issue by Hmidow** [bytedeco/javacpp-presets#384]
Hello, 

I'm trying to make a program that can make face recognition. I use the opencv lib and javacpp. I run a code that works but after some loops, i don't know why but i got a Java Runtime Error saying that I have a "Exception Access Violation". The error seems to be in native code in "[opencv_core310.dll+0x110f08]"

Here is a part of the complete message : 

 A fatal error has been detected by the Java Runtime Environment:

  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ffe0fe00f08, pid=8068, tid=0x0000000000001f1c

 JRE version: Java(TM) SE Runtime Environment (8.0_121-b13) (build 1.8.0_121-b13)
 Java VM: Java HotSpot(TM) 64-Bit Server VM (25.121-b13 mixed mode windows-amd64 compressed oops)
 Problematic frame:
 C  [opencv_core310.dll+0x110f08]

 Failed to write core dump. Minidumps are not enabled by default on client versions of Windows

 If you would like to submit a bug report, please visit:
   http://bugreport.java.com/bugreport/crash.jsp
 The crash happened outside the Java Virtual Machine in native code.
 See problematic frame for where to report the bug.

---------------  T H R E A D  ---------------

Current thread (0x0000000019a1d800):  JavaThread "pool-4-thread-1" [_thread_in_native, id=7964, stack(0x0000000021490000,0x0000000021590000)]

siginfo: ExceptionCode=0xc0000005, reading address 0x000000002ddbc0ec

Registers:
RAX=0x0000000042ff4010, RBX=0x000000001ff0d1e0, RCX=0x000000001ff0d1e0, RDX=0x000000002031e0a0
RSP=0x000000002158ec00, RBP=0x000000002158ed60, RSI=0x000000002ddbc0e0, RDI=0x000000002031e0a0
R8 =0x000000002ddbc0e0, R9 =0x000000000000002c, R10=0x000000001ff0be50, R11=0x000000002158ec78
R12=0x0000000000000000, R13=0x000000001bb4aa90, R14=0x000000001ff0d1e8, R15=0x000000002158ed90
RIP=0x00007ffe0fe00f08, EFLAGS=0x0000000000010206

Top of Stack: (sp=0x000000002158ec00)
0x000000002158ec00:   00000000029b835d 0000000000000002
0x000000002158ec10:   000000002031e0a0 000000002158ec18
0x000000002158ec20:   000000002ddbc0e0 00007ffe105d6967
0x000000002158ec30:   fffffffffffffffe 000000002031e0a0
0x000000002158ec40:   0000000016c8a240 0000000000000000
0x000000002158ec50:   000000002158ecc0 00000000029b835d
0x000000002158ec60:   000000002158ed90 000000002158ed80
0x000000002158ec70:   000000002ddbc0e0 00007ffe0b99b894
0x000000002158ec80:   0000000019a1d9f8 000000002158ed60
0x000000002158ec90:   000000002031e0a0 0000000016c88900
0x000000002158eca0:   0000000023098658 0000000016c86c80
0x000000002158ecb0:   fffffffffffffffe 000000002158ece0
0x000000002158ecc0:   0000000019a1d800 000000002158ed90
0x000000002158ecd0:   00000000230660a8 00000000029c7f74
0x000000002158ece0:   0000000019a1d9f8 000000001bb4aa98
0x000000002158ecf0:   000000001ff0d1e0 00000000d7dcdaa8 

Instructions: (pc=0x00007ffe0fe00f08)
0x00007ffe0fe00ee8:   49 89 6b 10 49 89 73 18 49 8b f0 48 8b fa 48 8b
0x00007ffe0fe00ef8:   d9 8b 02 89 01 c7 41 04 02 00 00 00 4c 8d 71 08
0x00007ffe0fe00f08:   41 8b 40 0c 41 89 06 41 8b 40 08 89 41 0c 49 63
0x00007ffe0fe00f18:   48 04 48 8b 42 48 48 0f af 08 48 03 4a 10 48 89 

Register to memory mapping:

RAX=0x0000000042ff4010 is an unknown value
RBX=0x000000001ff0d1e0 is an unknown value
RCX=0x000000001ff0d1e0 is an unknown value
RDX=0x000000002031e0a0 is an unknown value
RSP=0x000000002158ec00 is pointing into the stack for thread: 0x0000000019a1d800
RBP=0x000000002158ed60 is pointing into the stack for thread: 0x0000000019a1d800
RSI=0x000000002ddbc0e0 is an unknown value
RDI=0x000000002031e0a0 is an unknown value
R8 =0x000000002ddbc0e0 is an unknown value
R9 =0x000000000000002c is an unknown value
R10=0x000000001ff0be50 is an unknown value
R11=0x000000002158ec78 is pointing into the stack for thread: 0x0000000019a1d800
R12=0x0000000000000000 is an unknown value
R13=0x000000001bb4aa90 is pointing into metadata
R14=0x000000001ff0d1e8 is an unknown value
R15=0x000000002158ed90 is pointing into the stack for thread: 0x0000000019a1d800

Stack: [0x0000000021490000,0x0000000021590000],  sp=0x000000002158ec00,  free space=1019k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [opencv_core310.dll+0x110f08]
C  [jniopencv_core.dll+0x3b894]
C  0x00000000029c7f74

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  org.bytedeco.javacpp.opencv_core$Mat.allocate(Lorg/bytedeco/javacpp/opencv_core$Mat;Lorg/bytedeco/javacpp/opencv_core$Rect;)V+0
j  org.bytedeco.javacpp.opencv_core$Mat.<init>(Lorg/bytedeco/javacpp/opencv_core$Mat;Lorg/bytedeco/javacpp/opencv_core$Rect;)V+11
j  uchrony.achihi.view.FaceDetectionController.recognizeFace(Lorg/bytedeco/javacpp/opencv_core$Mat;[Lorg/bytedeco/javacpp/opencv_core$Rect;)V+32
j  uchrony.achihi.view.FaceDetectionController.access$400(Luchrony/achihi/view/FaceDetectionController;Lorg/bytedeco/javacpp/opencv_core$Mat;[Lorg/bytedeco/javacpp/opencv_core$Rect;)V+3
j  uchrony.achihi.view.FaceDetectionController$2.run()V+38
J 2680 C1 java.util.concurrent.Executors$RunnableAdapter.call()Ljava/lang/Object; (14 bytes) @ 0x00000000031c28cc [0x00000000031c27c0+0x10c]
J 2679 C1 java.util.concurrent.FutureTask.runAndReset()Z (128 bytes) @ 0x00000000031b5bdc [0x00000000031b5980+0x25c]
J 2920 C1 java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run()V (59 bytes) @ 0x0000000002eaeeac [0x0000000002eae980+0x52c]
j  java.util.concurrent.ThreadPoolExecutor.runWorker(Ljava/util/concurrent/ThreadPoolExecutor$Worker;)V+95
j  java.util.concurrent.ThreadPoolExecutor$Worker.run()V+5
j  java.lang.Thread.run()V+11
v  ~StubRoutines::call_stub

---------------  P R O C E S S  ---------------

Java Threads: ( => current thread )
  0x0000000018f4e000 JavaThread "Keep-Alive-Timer" daemon [_thread_blocked, id=2196, stack(0x000000001b670000,0x000000001b770000)]
=>0x0000000019a1d800 JavaThread "pool-4-thread-1" [_thread_in_native, id=7964, stack(0x0000000021490000,0x0000000021590000)]
  0x00000000199f8000 JavaThread "pool-3-thread-1" [_thread_in_native, id=5236, stack(0x0000000021390000,0x0000000021490000)]
  0x00000000197ee000 JavaThread "JavaCPP Deallocator" daemon [_thread_blocked, id=4540, stack(0x000000001e120000,0x000000001e220000)]
  0x00000000197cf000 JavaThread "Prism Font Disposer" daemon [_thread_blocked, id=3020, stack(0x000000001d820000,0x000000001d920000)]
  0x00000000194fc800 JavaThread "JavaFX-Launcher" [_thread_blocked, id=5152, stack(0x000000001b970000,0x000000001ba70000)]
  0x00000000194ca000 JavaThread "Thread-2" daemon [_thread_in_native, id=3968, stack(0x000000001b870000,0x000000001b970000)]
  0x0000000019450800 JavaThread "JavaFX Application Thread" [_thread_in_native, id=6748, stack(0x0000000019f90000,0x000000001a090000)]
  0x0000000019453000 JavaThread "Thread-1" daemon [_thread_blocked, id=8020, stack(0x0000000019e90000,0x0000000019f90000)]
  0x0000000019206800 JavaThread "QuantumRenderer-0" daemon [_thread_blocked, id=4100, stack(0x0000000019c40000,0x0000000019d40000)]
  0x000000001755e800 JavaThread "Service Thread" daemon [_thread_blocked, id=5484, stack(0x0000000019240000,0x0000000019340000)]
  0x0000000017509800 JavaThread "C1 CompilerThread2" daemon [_thread_blocked, id=5932, stack(0x0000000018d40000,0x0000000018e40000)]
  0x0000000017501800 JavaThread "C2 CompilerThread1" daemon [_thread_blocked, id=6336, stack(0x0000000018c40000,0x0000000018d40000)]
  0x00000000174fd800 JavaThread "C2 CompilerThread0" daemon [_thread_blocked, id=7564, stack(0x0000000018b40000,0x0000000018c40000)]
  0x00000000174fc800 JavaThread "Attach Listener" daemon [_thread_blocked, id=5064, stack(0x0000000018a40000,0x0000000018b40000)]
  0x00000000174fb000 JavaThread "Signal Dispatcher" daemon [_thread_blocked, id=1788, stack(0x0000000018940000,0x0000000018a40000)]
  0x00000000029aa800 JavaThread "Finalizer" daemon [_thread_blocked, id=4404, stack(0x0000000018760000,0x0000000018860000)]
  0x000000000299f000 JavaThread "Reference Handler" daemon [_thread_blocked, id=4236, stack(0x0000000018660000,0x0000000018760000)]
  0x00000000028b0800 JavaThread "main" [_thread_blocked, id=4736, stack(0x00000000027b0000,0x00000000028b0000)]

Other Threads:
  0x00000000174c7800 VMThread [stack: 0x0000000018560000,0x0000000018660000] [id=812]
  0x0000000018e94000 WatcherThread [stack: 0x0000000019340000,0x0000000019440000] [id=6632]

VM state:not at safepoint (normal execution)

VM Mutex/Monitor currently owned by a thread: None

Heap:
 PSYoungGen      total 163328K, used 35189K [0x00000000d5d80000, 0x00000000e0e80000, 0x0000000100000000)
  eden space 161280K, 20% used [0x00000000d5d80000,0x00000000d7de1ff0,0x00000000dfb00000)
  from space 2048K, 99% used [0x00000000e0c80000,0x00000000e0e7b5c8,0x00000000e0e80000)
  to   space 9216K, 0% used [0x00000000dfc80000,0x00000000dfc80000,0x00000000e0580000)
 ParOldGen       total 60928K, used 13625K [0x0000000081800000, 0x0000000085380000, 0x00000000d5d80000)
  object space 60928K, 22% used [0x0000000081800000,0x000000008254e5a0,0x0000000085380000)
 Metaspace       used 22131K, capacity 22724K, committed 23036K, reserved 1069056K
  class space    used 2686K, capacity 2849K, committed 2944K, reserved 1048576K

Card table byte_map: [0x0000000011d70000,0x0000000012170000] byte_map_base: 0x0000000011964000

Marking Bits: (ParMarkBitMap*) 0x000000006a14b6d0
 Begin Bits: [0x0000000012820000, 0x00000000147c0000)
 End Bits:   [0x00000000147c0000, 0x0000000016760000)

Polling page: 0x0000000002600000

CodeCache: size=245760Kb used=9539Kb max_used=9551Kb free=236220Kb
 bounds [0x00000000029b0000, 0x0000000003310000, 0x00000000119b0000]
 total_blobs=3830 nmethods=3027 adapters=714
 compilation: enabled

Compilation events (10 events):
Event: 85.290 Thread 0x0000000017509800 3345       3       javafx.scene.layout.Region::getMinHeight (22 bytes)
Event: 85.290 Thread 0x0000000017509800 nmethod 3345 0x000000000330add0 code [0x000000000330af40, 0x000000000330b308]
Event: 85.290 Thread 0x0000000017509800 3346       3       javafx.scene.Parent::minHeight (89 bytes)
Event: 85.291 Thread 0x0000000017509800 nmethod 3346 0x000000000330b450 code [0x000000000330b620, 0x000000000330bcf8]
Event: 85.292 Thread 0x0000000017509800 3347       1       javafx.scene.layout.Region::computeMaxHeight (4 bytes)
Event: 85.292 Thread 0x0000000017509800 nmethod 3347 0x000000000330be10 code [0x000000000330bf80, 0x000000000330c090]
Event: 86.026 Thread 0x00000000174fd800 3348       4       java.util.ArrayList::indexOf (67 bytes)
Event: 86.028 Thread 0x00000000174fd800 nmethod 3348 0x000000000330ee50 code [0x000000000330efa0, 0x000000000330f0b8]
Event: 86.330 Thread 0x0000000017501800 3349       4       com.sun.javafx.tk.quantum.QuantumToolkit$$Lambda$43/2052123731::run (8 bytes)
Event: 86.332 Thread 0x0000000017501800 nmethod 3349 0x000000000330f1d0 code [0x000000000330f320, 0x000000000330f3f8]

-----

Can someone help me with an idea ?

**Comment by phase** [comment]
You can see from the _Java Frames_ where your code is erroring.

```
j org.bytedeco.javacpp.opencv_core$Mat.allocate(Lorg/bytedeco/javacpp/opencv_core$Mat;Lorg/bytedeco/javacpp/opencv_core$Rect;)V+0
j org.bytedeco.javacpp.opencv_core$Mat.(Lorg/bytedeco/javacpp/opencv_core$Mat;Lorg/bytedeco/javacpp/opencv_core$Rect;)V+11
j uchrony.achihi.view.FaceDetectionController.recognizeFace(Lorg/bytedeco/javacpp/opencv_core$Mat;[Lorg/bytedeco/javacpp/opencv_core$Rect;)V+32
```

Looks like an error when allocating a Mat.

**Comment by saudet** [comment]
Thanks @phase!

@Hmidow Have you been able to solve your issue?
If not, please provide some code to reproduce this error. Thanks!

**Comment by Hmidow** [comment]
Thanks a lot @phase 

I know where is the error and it's solved. Thanks guy.

**Comment by capristano** [comment]
Hi,
I have the same error, but I not able to solve that.
[hs_err_pid7884.log](https://github.com/bytedeco/javacpp-presets/files/1624583/hs_err_pid7884.log)

```
import net.coobird.thumbnailator.Thumbnails;

import org.bytedeco.javacpp.DoublePointer;
import org.bytedeco.javacpp.IntPointer;
import org.bytedeco.javacpp.opencv_core;
import org.bytedeco.javacpp.opencv_core.CvRect;
import org.bytedeco.javacpp.opencv_core.Mat;
import org.bytedeco.javacpp.opencv_core.MatVector;
import org.bytedeco.javacpp.opencv_face.FaceRecognizer;
import org.bytedeco.javacpp.opencv_objdetect;
import org.bytedeco.javacv.*;
import org.bytedeco.javacv.Frame;
import javax.swing.*;
import java.awt.*;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import java.util.HashMap;
import java.util.Map;
import static org.bytedeco.javacpp.helper.opencv_objdetect.cvHaarDetectObjects;
import static org.bytedeco.javacpp.opencv_core.*;
import static org.bytedeco.javacpp.opencv_face.createFisherFaceRecognizer;
import static org.bytedeco.javacpp.opencv_imgproc.*;
import static org.bytedeco.javacpp.opencv_objdetect.CV_HAAR_DO_CANNY_PRUNING;

public class App {
	
	private static MatVector images;
	private static Mat labels;	
	private static FaceRecognizer faceRecognizer;
	
	private static Thread maintThread;
    private OpenCVFrameGrabber openCVFrameGrabber;
    private OpenCVFrameConverter.ToMat openCVFrameConverter = new OpenCVFrameConverter.ToMat();
    private volatile boolean running = true;
    private static Java2DFrameConverter java2DFrameConverter = new Java2DFrameConverter();
    private JFrame window;
    private JPanel videoPanel;
    private opencv_objdetect.CvHaarClassifierCascade cvHaarClassifierCascade;
    private opencv_core.CvMemStorage cvMemStorage;
    private OpenCVFrameConverter.ToIplImage toIplImage;
    private OpenCVFrameConverter.ToMat toMatConverterCascade;
    private static int lastId = 0;

    public App() {
        window = new JFrame();
        videoPanel = new JPanel();
        window.setLayout(new BorderLayout());
        window.setSize(new Dimension(800, 700));
        window.add(videoPanel, BorderLayout.CENTER);
        window.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                stop();
            }
        });
        toIplImage = new OpenCVFrameConverter.ToIplImage();
        toMatConverterCascade = new OpenCVFrameConverter.ToMat();
        try {
            File haarCascade = new File(this.getClass().getResource("/haarcascade_frontalface_alt.xml").toURI());
            cvHaarClassifierCascade = new opencv_objdetect.CvHaarClassifierCascade(cvLoad(haarCascade.getAbsolutePath()));
        } catch (Exception e) {
            throw new IllegalStateException("Error", e);
        }
        cvMemStorage = opencv_core.CvMemStorage.create();
    }

    public void run() {
        openCVFrameGrabber = new OpenCVFrameGrabber(0);
        openCVFrameGrabber.setFormat("dshow");
        openCVFrameGrabber.setImageWidth(800);
        openCVFrameGrabber.setImageHeight(700);
        try {
            openCVFrameGrabber.start();
        } catch (FrameGrabber.Exception e) {
            throw new RuntimeException("Error", e);
        }
        SwingUtilities.invokeLater(() -> {
            window.setVisible(true);
        });
        process();
    }

    private void process() {
    	
        while (running) {
            try {
                final Frame frame = openCVFrameGrabber.grab();
                Map<CvRect, Mat> detectedFaces = detect(frame);
                Mat mat = openCVFrameConverter.convert(frame);
                
                
                detectedFaces.entrySet().forEach(rectMatEntry -> {
                	int id = predic(rectMatEntry.getValue());
                	if(id == 0) {
                		lastId++;
                		train(lastId, rectMatEntry.getValue());
                	}
                    String caption = "";
                    rectangle(mat, new opencv_core.Point(rectMatEntry.getKey().x(), rectMatEntry.getKey().y()),
                            new opencv_core.Point(rectMatEntry.getKey().width() + rectMatEntry.getKey().x(), rectMatEntry.getKey().height() + rectMatEntry.getKey().y()),
                            Scalar.GREEN, 1, CV_AA, 0);
                    int posX = Math.max(rectMatEntry.getKey().x() - 10, 0);
                    int posY = Math.max(rectMatEntry.getKey().y() - 10, 0);
                    putText(mat, caption, new opencv_core.Point(posX, posY), CV_FONT_HERSHEY_PLAIN, 1.0,
                            new Scalar(255, 0, 0, 1.0));
                });
                Frame processedFrame = openCVFrameConverter.convert(mat);
                Graphics graphics = videoPanel.getGraphics();
                BufferedImage resizedImage = getResizedBufferedImage(processedFrame, videoPanel);
                SwingUtilities.invokeLater(() -> {
                    graphics.drawImage(resizedImage, 0, 0, videoPanel);
                });
            }catch (Exception e) {
            	e.printStackTrace();
            }
        }
    }

    public void stop() {
        running = false;
        try {
            openCVFrameGrabber.release();
            openCVFrameGrabber.stop();
        } catch (FrameGrabber.Exception e) {
        }

        window.dispose();
    }

    public static void main(String[] args) {
        App app = new App();
        
        images = new MatVector(1);
		labels = new Mat(1, 1, CV_32SC1);		
		faceRecognizer = createFisherFaceRecognizer();
        
        maintThread = new Thread(app::run);
        maintThread.start();
        Runtime.getRuntime().addShutdownHook(new Thread(() -> {
        	app.stop();
        }));
        try {
            Thread.currentThread().join();
        } catch (Exception ex) {
        }
    }

    public static BufferedImage getResizedBufferedImage(Frame frame, JPanel videoPanel) {
        BufferedImage resizedImage = null;
        try {
            resizedImage = Thumbnails.of(java2DFrameConverter.getBufferedImage(frame))
                    .size(videoPanel.getWidth(), videoPanel.getHeight())
                    .asBufferedImage();
        } catch (Exception e) {
        }
        return resizedImage;
    }

    public Map<CvRect, Mat> detect(Frame frame) {
        Map<CvRect, Mat> detectedFaces = new HashMap<>();
        opencv_core.IplImage iplImage = toIplImage.convert(frame);
        opencv_core.CvSeq detectObjects = cvHaarDetectObjects(iplImage, cvHaarClassifierCascade, cvMemStorage, 1.5, 3, CV_HAAR_DO_CANNY_PRUNING);
        Mat matImage = toMatConverterCascade.convert(frame);
        int numberOfPeople = detectObjects.total();
        for (int i = 0; i < numberOfPeople; i++) {
            CvRect rect = new CvRect(cvGetSeqElem(detectObjects, i));
            Mat croppedMat = matImage.apply(new Rect(rect.x(), rect.y(), rect.width(), rect.height()));
            detectedFaces.put(rect, croppedMat);
        }
        return detectedFaces;
    }
    
    public static void train(int counter, Mat img) {
    	try {
    		images.put(counter, img);
        	faceRecognizer.train(images, labels);
		} catch (Exception e) {
			e.printStackTrace();
		}    	
    }
    
    public static int predic(Mat img) {
    	int predictedLabel = 0;
    	try {
    		IntPointer label = new IntPointer(1);
    		DoublePointer confidence = new DoublePointer(1);
    		faceRecognizer.predict(img, label, confidence);
    		predictedLabel = label.get(0);
    		
    		System.out.println("Predicted label: " + predictedLabel);
    		System.out.println("Confidence: " + confidence);
			
		} catch (Exception e) {}
        
        return predictedLabel;
    }
}

```

The error is in my train method. I can't see what is happening.
Thank you.

**Comment by MounaBC** [comment]
@Hmidow could you please give details about how you solved the problem. I have the same error
