### ISSUE TITLE
H265 Support?

### ISSUE THREAD

**Issue by yanjingjiangjun** [bytedeco/javacpp-presets#386]
avcodec_open2 error -12

**Comment by saudet** [comment]
sample code?

**Comment by yanjingjiangjun** [comment]
@saudet 

recorder = new FFmpegFrameRecorder(ffmpeg_link, imageWidth, imageHeight, 1);
        //recorder.setVideoCodec(avcodec.AV_CODEC_ID_H264);//H.264
        recorder.setVideoBitrate(1000*600);
        recorder.setVideoCodec(avcodec.AV_CODEC_ID_H265);//H.265
        recorder.setVideoCodecName("H264");
        recorder.setFormat("flv");
        recorder.setSampleRate(sampleAudioRateInHz);
        // Set in the surface changed method
        recorder.setFrameRate(frameRate);
        recorder.setGopSize(2);

It worked when H264, but error H265

**Comment by saudet** [comment]
Try to remove the call to setVideoCodecName().

**Comment by saudet** [comment]
Could you also copy/paste the error message that you get in the log?

**Comment by yanjingjiangjun** [comment]
@saudet as your mind ，I removed setVideoCodecName(). 
org.bytedeco.javacv.FrameRecorder$Exception: avcodec_open2() error -12: Could not open video codec.
org.bytedeco.javacv.FFmpegFrameRecorder.startUnsafe(FFmpegFrameRecorder.java:667)
org.bytedeco.javacv.FFmpegFrameRecorder.start(FFmpegFrameRecorder.java:351)

**Comment by saudet** [comment]
Check the log, one of those settings do not apply to H.265. The following works:
```java
recorder = new FFmpegFrameRecorder("somefile.mp4", 640, 480);
recorder.setVideoCodec(avcodec.AV_CODEC_ID_H265);
recorder.start();
```
