### ISSUE TITLE
Op type not recognized 'VariableV2'

### ISSUE THREAD

**Issue by laurenskz** [bytedeco/javacpp-presets#387]
I get an error when running the following code:

        SessionOptions options = new SessionOptions();
        Session session = new Session(options);
        GraphDef def = new GraphDef();
        tensorflow.ReadBinaryProto(Env.Default(), BASE_DIR + "trained_model.proto", def);

        Status status = session.Create(def);
        if (!status.ok()) {
            throw new RuntimeException(status.error_message().getString());
        }
The error I get is:
Exception in thread "main" java.lang.RuntimeException: Op type not registered 'VariableV2'

I am trying to load a proto file created by the following python code:

saver = tf.train.Saver([W,b])
saver_def = saver.as_saver_def()
saver.save(sess, export_path +'/trained_model.sd')

tf.train.write_graph(sess.graph_def, '.', export_path+'/trained_model.proto', as_text=False)
tf.train.write_graph(sess.graph_def, '.', export_path+'/trained_model.txt', as_text=True)

Thanks very much in advance

**Comment by saudet** [comment]
Does this happen with TensorFlow 1.0?

**Comment by laurenskz** [comment]
Yes it does, the output of tf.__version__ is 1.0.0. I don't know how to verify that I'm also using that version in java.

**Comment by saudet** [comment]
I've release binaries for version 1.0.0 so using that should solve this issue:
https://github.com/bytedeco/javacpp-presets/tree/master/tensorflow#the-pomxml-build-file
http://repo1.maven.org/maven2/org/bytedeco/javacpp-presets/tensorflow/1.0.0-1.3/
