### ISSUE TITLE
FFmpeg binaries are built disabling some avdevices such as x11grab and avfoundation

### ISSUE THREAD

**Issue by robertoandrade** [bytedeco/javacpp-presets#39]
From what I could gather ffmpeg builds automatically include `x11grab` and `avfoundation` devices (Trying to invoke the libs to replicate [the following examples](https://trac.ffmpeg.org/wiki/Capture/Desktop)) and I'm wondering what in particular in the presets' build script makes it so those are not included? I noticed [you guys build it](https://github.com/bytedeco/javacpp-presets/blob/master/ffmpeg/cppbuild.sh#L149) with `--disable-libxcb`, is that what causes these components not to be included?

**Comment by robertoandrade** [comment]
After build 0.11-SNAPSHOT (with ffmpeg 2.5.4) I was able to call into the ffmpeg functions on my Mac running OSX and pass in `format=avfoundation` and it worked just fine. So I guess this was only a problem on the stable 0.10 release. Trying to recompile it on linux to confirm `x11grab` is accessible too.

**Comment by saudet** [comment]
Thanks for the feedback! Maybe it's just my build environment that don't have the right files installed... I'll have to check that out. But that might not be that important, because eventually, I'd like to move the builds to Travis CI. Would you have any experience or interest in trying this out?

**Comment by robertoandrade** [comment]
Yeah for linux it doesn't get included, I need to remove the `--disable-libxcb` in order to bake it in and in my tests also included the `--enable-x11grab`.

**Comment by saudet** [comment]
This should all be fixed with the -0.11 release. Let me know if you still have problems! Thanks for reporting.

**Comment by Artpej** [comment]
It seems that `avfoundation` input device  is not really enabled. I think it is due to this issue : https://trac.ffmpeg.org/ticket/3570 .

**Comment by saudet** [comment]
It still doesn't work with version 0.11??

**Comment by Artpej** [comment]
There's no problem on Linux with `x11grab`, but on my OSX Mavericks `avfoundation` seems not works: 

```java
public class Devices {
  public static void main(String[] args){
    avdevice_register_all();
    avcodec_register_all();
    av_register_all();
    System.err.println(avdevice.avdevice_configuration().getString());
    AVInputFormat fmt = null;
    while ((fmt = av_input_video_device_next(fmt)) != null) {
      System.err.println("format : " + fmt.name().getString() + " (" + fmt.long_name().getString() + ")");
    }
  }
}
```

I tried multiple ways to find the  `avfoundation` device but nothing works.

For exemple:
```java
AVInputFormat fmt = av_find_input_format("avfoundation");
```
here `fmt` is always `ǹull`.

The version i use is `2.6.1-0.11`:

```xml
        <dependency>
            <groupId>org.bytedeco.javacpp-presets</groupId>
            <artifactId>ffmpeg</artifactId>
            <version>2.6.1-0.11</version>
            <classifier>macosx-x86_64</classifier>
        </dependency>  
`̀`

**Comment by saudet** [comment]
@Artpej Could you try to rebuild the binaries on your machine to see if that changes anything? Thanks!

**Comment by Artpej** [comment]
All right, after rebuilding the binaries from the `master` on my machine everithing works well. 

I don't do anithing special:
- `brew install yasm`
- `sh cppbuild.sh -platform macosx-x86_64 install ffmpeg`
- `mvn install -projects .,ffmpeg`

Hope this will help.
Tks

**Comment by saudet** [comment]
So I guess it's a problem with my build environment...

Incidentally, I would like to, for example, make the build process more automated via a cloud solution. I'm aware of Travis CI, and I believe they support builds for Mac OS X. Is this something you would be interested in helping out to set up? It would help a lot!!
