### ISSUE TITLE
Tensorflow 0.12.1 and 1.0??

### ISSUE THREAD

**Issue by BoiseBound** [bytedeco/javacpp-presets#391]
Hi, ByteDeco folks,
   You have github'd javacpp presets for Tensorflow 0.12.1 and 1.0, but the jars do not exist for either of those on the maven repository.
    Were you going to be adding those at some point by chance, or would I need to be built from src if I want them?
    I'd really like to get access to 0.12 if it is available.
    Thank you very much!!

**Comment by saudet** [comment]
Yes, I've just released binaries for version 1.0.0. They are available here:
https://github.com/bytedeco/javacpp-presets/tree/master/tensorflow#the-pomxml-build-file
http://repo1.maven.org/maven2/org/bytedeco/javacpp-presets/tensorflow/1.0.0-1.3/

**Comment by BoiseBound** [comment]
Thank you so much!!
