### ISSUE TITLE
CPU-only version of Tensorflow/CUDA object issues

### ISSUE THREAD

**Issue by BoiseBound** [bytedeco/javacpp-presets#392]
I get the comment
java.lang.UnsatisfiedLinkError: ..... libjnitensorflow.so: libcudart.so.8.0: cannot open shared object file
when trying to run versions 0.11, 0.12, and 1.0 of your Tensorflow presets.
I am trying to run on Ubuntu CPU-only.
Do you binaries accept the CPU-only version or should I try to install the cuda 8 library even when I don't have a GPU?
Thank you

**Comment by saudet** [comment]
Just install CUDA, even if you don't have a GPU. You don't need to have a GPU to install CUDA. TensorFlow will just use your CPU automatically.

**Comment by saudet** [comment]
Duplicate of #396
