### ISSUE TITLE
RTSP protocol not available for FFmpeg preset

### ISSUE THREAD

**Issue by T0in0u** [bytedeco/javacpp-presets#395]
Hi!

I just tried to get a RTSP stream on Android with FFmpeg (JavaCPP 1.3.2 and FFmpeg 3.2.1) and figured out a problem. 

"avformat_open_input(formatContext, "rtsp://auth:auth@a_valid_address", null, null)" returns "AVERROR_PROTOCOL_NOT_FOUND". Reading the cppbuild.sh for FFmpeg, I see that there is no "--enable-protocol=rtsp" nor "--enable-demuxer=rtsp". Is it a mistake?

**Comment by saudet** [comment]
Probably an oversight, please send a pull request! Thanks

**Comment by N0un** [comment]
Ok, I take care of it!

**Comment by N0un** [comment]
Well, there is a problem. I added `--enable-network --enable-protocol=tcp --enable-protocol=udp --enable-protocol=rtp --enable-demuxer=rtsp` in the cppbuild.sh file but still the same (same error code). After looking closely in the ffmpeg's configure file, I saw that:

`--disable-network        disable network support [no]`

So I think network is enabled by default. In FFmpeg's web site, I saw "When you configure your FFmpeg build, all the supported protocols are enabled by default" and "When you configure your FFmpeg build, all the supported demuxers are enabled by default". So things I added to my test are useless. I really don't why it doesn't work... Do you have an idea?

**Comment by saudet** [comment]
Checking the debug log would probably tell you more...

**Comment by N0un** [comment]
Unfortunately, there is no log at this point... (Tried with AV_LOG_MAX_OFFSET, AV_LOG_VERBOSE, AV_LOG_DEBUG, AV_LOG_WARNING, AV_LOG_INFO,...) Do the sample you provide for FFmpeg works on Android with a RTSP url?

**Comment by N0un** [comment]
News: It works when I call `av_register_all();` and `avformat_network_init();` just before calling `avformat_open_input(...);`... This is strange because I call `av_register_all();` and `avformat_network_init();` when my app start, and I never `*_deinit();` that. So I have to make a second call in the thread that use `avformat_open_input(...);`. Is it normal?

**Comment by N0un** [comment]
Ok that was nothing, problem was: me. Sorry for your time, I just have to make my own `av_register_all` method (to avoid register useless demuxer/muxers/protocols/codec) and all works fine. Maybe you can delete this issue, because it's not an issue.

**Comment by saudet** [comment]
We shouldn't need to call these functions more than once. If we have to, it's a bug in FFmpeg and should be reported upstream.

**Comment by N0un** [comment]
No we don't have, I just wrote `avcodec_register_all` instead of `av_register_all` (which call `avcodec_register_al` if and only if it is the first call)... So shame on me!

**Comment by saudet** [comment]
Oh, I see, good to know! Thanks for the explanation
