### ISSUE TITLE
Not enough info on how to setup dependencies in a project that

### ISSUE THREAD

**Issue by mkokho** [bytedeco/javacpp-presets#401]
Hi Samuel,

I have created a wiki page with an example that shows how to add javacpp-preset dependency to an Android project. If you like it, could you add a link to it in the readme? Maybe, if other people are having troubles, this will find it useful. And they might update with more information. 

The project is great, thanks for maintaining it!

Wiki page: https://github.com/bytedeco/javacpp-presets/wiki/Android:-add-javacpp-preset-dependency

Best,
Mikhail

**Comment by saudet** [comment]
Sounds great! The wiki can be modified by everyone, so please feel free to
add the page there yourself, if that 's OK. Thanks a lot!

**Comment by mkokho** [comment]
Great! Wiki page: [Android: add javacpp-preset dependency](https://github.com/bytedeco/javacpp-presets/wiki/Android:-add-javacpp-preset-dependency)
