### ISSUE TITLE
Sophisticated example for JavaCPP - Tensorflow

### ISSUE THREAD

**Issue by szingerpeter** [bytedeco/javacpp-presets#409]
Dear All,

I have seen the [example](https://github.com/bytedeco/javacpp-presets/tree/master/tensorflow#the-srcmainjavaexampletrainerjava-source-file) for using Tensorflow with Java. I did not really manage to understand what was going on in the code. Would it be possible to have some more documentation on it? 
Moreover, I would be interested in a bit more sophisticated example or at least some guidance how I should / could use Tensorflow in Java. I think it is a great initiative, but I feel a bit lost on how I could implement for example a feed-forward neural network with for example 2 hidden layers and 5 classes by using Tensorflow JavaCPP bindings. 
Thank you for any help!

Cheers,
Peter

**Comment by saudet** [comment]
It basically maps the C++ API, so for example we could easily port this example to Java:
https://github.com/tensorflow/tensorflow/tree/master/tensorflow/examples/label_image
That should be pretty easy to do! Sounds good?

**Comment by szingerpeter** [comment]
Thank you for your reply.
Unfortunately, I am not familiar with C++, but will try to make sense out of the example you sent me!

**Comment by saudet** [comment]
It shouldn't be too hard. If you have any questions, please post to the mailing list or ask on Gitter! Thanks

**Comment by allenjack** [comment]
I agree with @szingerpeter. It is better to provide an example about how to train a simple neural network. I am also facing this problem that how to start from scratch with Java API. There are few materials can be referred to.

**Comment by saudet** [comment]
@allenjack That's cool, contributions are welcome!

**Comment by saudet** [comment]
@allenjack FYI, here is a complete training example using only the C++ API:
https://matrices.io/training-a-deep-neural-network-using-only-tensorflow-c/
It should be pretty straightforward to translate this to Java, but please let me know if you encounter any issues. Thanks for your interest!

**Comment by allenjack** [comment]
Thank you so much. I will have a try and let you know.

**Comment by saudet** [comment]
Many thanks to @Neiko2002, we now have a Java translation of that complete training example:
https://github.com/bytedeco/javacpp-presets/blob/master/tensorflow/samples/src/main/java/org/bytedeco/javacpp/samples/tensorflow/CarPricePredictionExample.java
Enjoy!

**Comment by saudet** [comment]
BTW, it's now also possible to train using Keras:
https://github.com/bytedeco/javacpp-presets/blob/master/tensorflow/samples/KerasMNIST.java
This works with an embedded version of CPython, so there is no need to install anything.
