### ISSUE TITLE
TensorFlow-how to train a neural network by using the ApplyGradientDescent method?

### ISSUE THREAD

**Issue by allenjack** [bytedeco/javacpp-presets#413]
Hi,
I am currently using Java to implement some neural networks. But I am quite confused with the the ApplyGradientDescent method, can this method deal with the auto-differentiation of parameters? And how can I use this method, could anyone provide an example?

**Comment by saudet** [comment]
I don't believe the C++ API supports auto-differentiation yet, see https://github.com/tensorflow/tensorflow/issues/6268 although there appear to be some recent progress with this.

**Comment by allenjack** [comment]
Is there any convenient way to train a neural network in Java?

**Comment by saudet** [comment]
TensorFlow doesn't really offer any convenient way to train neural networks. For Java, the easier to use framework is Deeplearning4j...

**Comment by allenjack** [comment]
Thank you, I got it. I am still curious about how to use the ApplyGradientDescent method to train a neural network either in C++ or Java, could anyone give an example?

**Comment by saudet** [comment]
There's some sample code here:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/grappler/optimizers/auto_parallel_test.cc#L30
So, I'm marking this as a duplicate of #409
