### ISSUE TITLE
[FFmpeg] AVPacket size() different than AVPacket data().capacity()

### ISSUE THREAD

**Issue by N0un** [bytedeco/javacpp-presets#417]
Hi !

I'm trying to encode audio samples using FFmpeg preset (using the latest release) and I'm in front of a curious thing:

I initialize a `AVPacket` object like that:

    AVPacket packet = new AVPacket();
    av_init_packet(packet);
    // I think the two following lines are optional (no incidence on my issue)
    packet.data(null);
    packet.size(0);

Then, I build a `AVFrame` object:

    AVFrame frame = av_frame_alloc();
    frame.nb_samples(...);
    frame.format(....);
    frame.channel_layout(....);
    avcodec_fill_audio_frame(frame, ...., ...., ...., ...., ....);

And this is the problem:

    int iGotFrame = -1;
    int iRes = avcodec_send_frame(..., frame);
    if (iRes == 0) {
        iGotFrame = avcodec_receive_packet(..., packet);
    }

    if ((iRes == 0) && (iGotFrame == 0)) {
        // Here, packet.size() returns 2048 but packet.data().capacity() returns 0
        // and packet.data().isNull() returns false...
    }

Any idea please?

**Comment by saudet** [comment]
C++ pointers don't tell us their "capacity". We have to set it manually...

**Comment by N0un** [comment]
Of course! Ok thank you, I understand ^^
