### ISSUE TITLE
Manually compiled subset of JavaCPP Presets could not be accessed by Gradle

### ISSUE THREAD

**Issue by maximumspatium** [bytedeco/javacpp-presets#42]
I'm experiencing an issue when I try to use leptonica + tessseract bindings, compiled from the latest trunk and installed into Maven local repository, from within Gradle. I've correctly added all required dependencies and pointed Gradle to MavenLocal repository.

Gradle does report the following error:
```
* What went wrong:
Could not resolve all dependencies for configuration ':compile'.
> Could not resolve org.bytedeco.javacpp-presets:leptonica:1.71-0.11.
  Required by:
      :Project:unspecified
   > Could not parse POM file:/****/*****/.m2/repository/org/bytedeco/javacpp-presets/leptonica/1.71-0.11/leptonica-1.71-0.11.pom
      > Could not find org.bytedeco:javacpp-presets:0.11.
```
It looks like the parent POM is missing. I've looked into the local .m2 directory and the expected parent pom "javacpp-presets-0.11.pom" is, indeed, not there.

I'm using the following terminal commands in order to get everything built and installed:
> bash cppbuild.sh -platform linux-x86 install leptonica tesseract
> mvn install --projects leptonica,tesseract

Below the results:
```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] JavaCPP Presets for Leptonica ..................... SUCCESS [29:05.014s]
[INFO] JavaCPP Presets for Tesseract ..................... SUCCESS [1:32.344s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 30:40.956s
[INFO] Finished at: Wed Mar 18 17:44:03 CET 2015
[INFO] Final Memory: 22M/230M
```
Any ideas what's going wrong?
Thank you in advance!
Best regards
Max

**Comment by saudet** [comment]
No SNAPSHOT qualifier? Is it supported by Gradle?

**Comment by maximumspatium** [comment]
Hello Samuel,

IIRC, Gradle does support Maven snapshots. They are just called "changing modules" in the Gradle's jargon.
Anyway, I've tried without "-SNAPSHOT" as well. Neither solution works...

Best regards
Max

**Comment by saudet** [comment]
Oh, I see the problem: `mvn install --projects leptonica,tesseract` doesn't install the parent module. Using a period like this `mvn install --projects .,leptonica,tesseract` usually works. We should add that to the `README.md` file. Let me know do that...

**Comment by maximumspatium** [comment]
Hi Samuel,

oh man, that ugly Maven strikes back...

Anyway, thank you very much for the hint! It works now as expected.

The issue can be closed now. It would be nice to update the README accordigly. Smth like this:

**Please ensure that the list of comma-separated projects starts with ".". Otherwise, the generated artifacts could be incomplete.**

Thank you in advance!
Best regards
Max

**Comment by maximumspatium** [comment]
Many thanks! The issue can be closed.
Best regards
Max
