### ISSUE TITLE
'using namespace ' in cpp code prevents the Parser from correctly interpretting classnames.

### ISSUE THREAD

**Issue by adamjryan** [bytedeco/javacpp-presets#420]
For example if the cpp code contains a declaration:
`using namespace std;`
then any classes from that namespace such as vector or string in this case will not be correctly identified as coming from that namespace which leads to an error in the compilation of the generated Java-JNI cpp file of:
> error: missing template arguments before ‘adapter1’
>      VectorAdapter adapter1(ptr1, size1, owner1);

I've tried adding entries in the InfoMapper lookup such as
`.put( new Info("vector<string>").pointerTypes("StringVector").define() )`
without success.

**Comment by saudet** [comment]
The Parser won't be using the `using namespace std`, because like you say it's ambiguous at a global level. So we need to specify the namespace, like the ones in OpenCV, for example:
https://github.com/bytedeco/javacpp-presets/blob/master/opencv/src/main/java/org/bytedeco/javacpp/presets/opencv_core.java#L136

In this case:
```java
.put(new Info("std::vector<std::string>").pointerTypes("StringVector").define())
```

**Comment by adamjryan** [comment]
That is what I'm using but it requires adding back all the namespace prefixes and doesn't seem very practical, in my case the cpp code isn't very large and so adding back all the namespace prefixes is feasible however on a larger codebase this sort of change may not be possible and renders the parser useless. The parser should be able to handle a 'using namespace' declaration.

**Comment by adamjryan** [comment]
This needs a  [Won't Fix]  label.

**Comment by saudet** [comment]
I'm sorry, I don't understand how we could implement this. If you have ideas, please express them. Otherwise, I'm afraid your idea just does not make sense.
