### ISSUE TITLE
No jniflandmark in java.library.path

### ISSUE THREAD

**Issue by TechXcrafter** [bytedeco/javacpp-presets#421]
`Exception in thread "Thread-0" java.lang.UnsatisfiedLinkError: no jniflandmark in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:963)
	at org.bytedeco.javacpp.Loader.load(Loader.java:764)
	at org.bytedeco.javacpp.Loader.load(Loader.java:671)
	at org.bytedeco.javacpp.flandmark.<clinit>(flandmark.java:13)
	at me.TechXcrafter.mw.GUI.pages.DevPage.loadFLandmarkModel(DevPage.java:95)
	at me.TechXcrafter.mw.GUI.pages.DevPage.nextPicture(DevPage.java:173)
	at me.TechXcrafter.mw.Camera.CameraStream$1.run(CameraStream.java:111)
Caused by: java.lang.UnsatisfiedLinkError: /Users/tech/.javacpp/cache/flandmark-1.07-1.3-macosx-x86_64.jar/org/bytedeco/javacpp/macosx-x86_64/libjniflandmark.dylib: dlopen(/Users/tech/.javacpp/cache/flandmark-1.07-1.3-macosx-x86_64.jar/org/bytedeco/javacpp/macosx-x86_64/libjniflandmark.dylib, 1): Library not loaded: @rpath/libopencv_imgproc.3.1.dylib
  Referenced from: /Users/tech/.javacpp/cache/flandmark-1.07-1.3-macosx-x86_64.jar/org/bytedeco/javacpp/macosx-x86_64/libjniflandmark.dylib
  Reason: image not found
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:943)
	... 6 more`

My POM:
`<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>me.TechXcrafter</groupId>
    <artifactId>mw</artifactId>
    <version>1.0</version>

    <dependencies>
        <dependency>
            <groupId>org.bytedeco</groupId>
            <artifactId>javacv-platform</artifactId>
            <version>1.3.2</version>
        </dependency>
        <dependency>
            <groupId>org.bytedeco.javacpp-presets</groupId>
            <artifactId>flandmark-platform</artifactId>
            <version>1.07-1.3</version>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <source>1.8</source>
                    <target>1.8</target>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <version>2.4</version>
                <configuration>
                    <archive>
                        <manifest>
                            <addClasspath>true</addClasspath>
                            <mainClass>me.TechUndSamet.Test.Test</mainClass>
                            <classpathPrefix>lib/</classpathPrefix>
                        </manifest>
                    </archive>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-dependency-plugin</artifactId>
                <version>2.8</version>
                <executions>
                    <execution>
                        <id>copy-dependencies</id>
                        <phase>package</phase>
                        <goals>
                            <goal>copy-dependencies</goal>
                        </goals>
                        <configuration>
                            <outputDirectory>
                                ${project.build.directory}/lib/
                            </outputDirectory>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>`

Error Line:
` public static flandmark.FLANDMARK_Model loadFLandmarkModel(final File file) throws IOException {
        if (!file.exists()) {
            throw new FileNotFoundException("FLandmark model file does not exist: " + file.getAbsolutePath());
        }

        final flandmark.FLANDMARK_Model model;
        model = flandmark_init("/Users/Tech/Desktop/MW/flandmark_model.dat"); // <-----------
        if (model == null) {
            throw new IOException("Failed to load FLandmark model from file: " + file.getAbsolutePath());
        }

        return model;
    }`

The file flandmark_model.dat exists!

Thx for helping

**Comment by saudet** [comment]
I see, that version of flandmark was compiled with OpenCV 3.1.0. Try to include manually that version of `opencv-platform` as well.

**Comment by saudet** [comment]
Newly released version 1.4 fixes this:
http://search.maven.org/#search%7Cga%7C1%7Cbytedeco%20flandmark
Thanks for reporting!
