### ISSUE TITLE
Using bytedeco with Java 

### ISSUE THREAD

**Issue by okasha93** [bytedeco/javacpp-presets#422]
I am working on face recognition using java and OpenCV, and the problem is Javacv became hosted by github "bytedeco" repo , so i can't import MatVector, "createFisherFaceRecognizer" and other thing although i have added bytedeco jars in my project and OpenCV is installed on my ubuntu 14.04 LTS.

mainly i mean simple face recognizer like this: https://pcbje.github.io/misc/2012/12/01/doing-face-recognition-with-javacv.html
Please help me to install bytedeco to use it in my project 
Thanks in advance :)

**Comment by saudet** [comment]
Have you tried to use Maven?

**Comment by saudet** [comment]
An updated version of that sample is available here so just use that one:
https://github.com/bytedeco/javacv/blob/master/samples/OpenCVFaceRecognizer.java

**Comment by okasha93** [comment]
I have added JavaCV and Javacpp that hosted by bytedeco and add their JARs to my project and i can't run the sample code u have mentioned ! so, i want to ask you if i have to use Maven ? and if i don't use Maven can i do this by just adding new jars to my project libraries ?

Thanks a lot.
Really Appreciated

**Comment by saudet** [comment]
Yes, adding all JAR files also works.

**Comment by okasha93** [comment]
Javacpp presets is Mandatory ?

**Comment by saudet** [comment]
Could you clarify the issue you are facing or the question that you have?

**Comment by okasha93** [comment]
I made Face Detection and tracking using Opencv 2.4.11 on Ubuntu 14.04 and I am trying to make face recognizer also with java,
and i can't function some classes Like MatVector or createFisherFaceRecognizer() !!!
Recently i found that Opencv is hosted now by github repo "bytedeco" instead of google code.
So i have download javacv bin and javacpp bin from github and add their JARs to my project but i can't import MatVector, createFisherFaceRecognizer() there's no class by this name to import !!

I hope that's clear now for you.

if you can list all needed JARs for this ?

**Comment by saudet** [comment]
If I put all the JAR files in the classpath, it works just fine here. I can't fix that isn't broken!
