### ISSUE TITLE
sample code to reduce bitrate of input video file

### ISSUE THREAD

**Issue by vvavepacket** [bytedeco/javacpp-presets#425]
Hi, I can't find any sample on how to use this library to take an input file, and then just reduce it's bitrate. My goal is just to reduce the filesize. I'm thinking of just using the executable ffmpeg.jar but i figured out using this library is a better option. Can anyone provide / shed some light on this? Thank you.

**Comment by saudet** [comment]
You could use JavaCV for that. There is sample code available here:
https://github.com/bytedeco/javacv/blob/master/platform/src/test/java/org/bytedeco/javacv/FrameGrabberTest.java
