### ISSUE TITLE
undefined symbols: LAPACKE_dgels in libjniopenblas.so

### ISSUE THREAD

**Issue by acekillersg** [bytedeco/javacpp-presets#427]
Hi @saudet 
When I use the openblas preset with example code: ExampleDGELSrowmajor.java, I got the following error:
```
 /usr/lib/jvm/java-8-oracle/bin/java: symbol lookup error: /home/john/javacpp-presets/openblas/target/classes/org/bytedeco/javacpp/linux-x86_64/libjniopenblas.so: undefined symbol: LAPACKE_dgels
```
It seems that libjniopenblas.so doesn't contain C function: LAPACKE_dgels, then I use command "ldd -r libjniopenblas.o", the results is as follows:
```
john@john-PC:~/javacpp-presets/openblas/target/classes/org/bytedeco/javacpp/linux-x86_64$ ldd -r libjniopenblas.so 

	linux-vdso.so.1 =>  (0x00007fff90157000)
	libopenblas.so.0 => /home/john/javacpp-presets/openblas/target/classes/org/bytedeco/javacpp/linux-x86_64/./libopenblas.so.0 (0x00007f62360c5000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f6235d42000)
	libgcc_s.so.1 => /home/john/javacpp-presets/openblas/target/classes/org/bytedeco/javacpp/linux-x86_64/./libgcc_s.so.1 (0x00007f6235b2c000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f6235763000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f6235459000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f623523c000)
	libgfortran.so.3 => /home/john/javacpp-presets/openblas/target/classes/org/bytedeco/javacpp/linux-x86_64/./libgfortran.so.3 (0x00007f6234f11000)
	/lib64/ld-linux-x86-64.so.2 (0x0000558819475000)
	libquadmath.so.0 => /home/john/javacpp-presets/openblas/target/classes/org/bytedeco/javacpp/linux-x86_64/./libquadmath.so.0 (0x00007f6234cd1000)
undefined symbol: LAPACKE_dtpmqrt	(./libjniopenblas.so)
undefined symbol: LAPACKE_ctrrfs_work	(./libjniopenblas.so)
undefined symbol: LAPACKE_cpptrs_work	(./libjniopenblas.so)
undefined symbol: LAPACKE_csprfs_work	(./libjniopenblas.so)
undefined symbol: LAPACKE_zlacn2_work	(./libjniopenblas.so)
undefined symbol: LAPACKE_cggglm_work	(./libjniopenblas.so)
undefined symbol: LAPACKE_zggrqf	(./libjniopenblas.so)
undefined symbol: LAPACKE_csy_trans	(./libjniopenblas.so)
undefined symbol: LAPACKE_dpoequ	(./libjniopenblas.so)
undefined symbol: LAPACKE_spptri_work	(./libjniopenblas.so)
undefined symbol: LAPACKE_spprfs	(./libjniopenblas.so)
undefined symbol: LAPACKE_dtbcon_work	(./libjniopenblas.so)
undefined symbol: LAPACKE_dsyrfs_work	(./libjniopenblas.so)
undefined symbol: LAPACKE_cpotrf2_work	(./libjniopenblas.so)
undefined symbol: LAPACKE_dsytrs	(./libjniopenblas.so)
undefined symbol: LAPACKE_cgehrd	(./libjniopenblas.so)
undefined symbol: LAPACKE_zsytrf_work	(./libjniopenblas.so)
undefined symbol: LAPACKE_ztgevc_work	(./libjniopenblas.so)
undefined symbol: LAPACKE_cgelss	(./libjniopenblas.so)
undefined symbol: LAPACKE_sspgvx	(./libjniopenblas.so)
undefined symbol: LAPACKE_zgelsy	(./libjniopenblas.so)
undefined symbol: LAPACKE_dpb_trans	(./libjniopenblas.so)
undefined symbol: LAPACKE_ctp_trans	(./libjniopenblas.so)
undefined symbol: LAPACKE_cpoequ_work	(./libjniopenblas.so)
undefined symbol: slagsy_	(./libjniopenblas.so)
undefined symbol: LAPACKE_zgeqrt_work	(./libjniopenblas.so)
undefined symbol: LAPACKE_dsptrd_work	(./libjniopenblas.so)
undefined symbol: LAPACKE_dlarfx_work	(./libjniopenblas.so)
undefined symbol: LAPACKE_spptrs_work	(./libjniopenblas.so)
undefined symbol: LAPACKE_zstegr	(./libjniopenblas.so)
undefined symbol: LAPACKE_dpp_trans	(./libjniopenblas.so)
undefined symbol: LAPACKE_zptrfs_work	(./libjniopenblas.so)
undefined symbol: LAPACKE_zlarfb_work	(./libjniopenblas.so)
undefined symbol: LAPACKE_sgbcon_work	(./libjniopenblas.so)
undefined symbol: LAPACKE_zhptri	(./libjniopenblas.so)
undefined symbol: LAPACKE_sgeqrt2	(./libjniopenblas.so)
undefined symbol: LAPACKE_zsyswapr_work	(./libjniopenblas.so)
undefined symbol: LAPACKE_dgehrd_work	(./libjniopenblas.so)
undefined symbol: LAPACKE_dsycon	(./libjniopenblas.so)
undefined symbol: LAPACKE_ssptri	(./libjniopenblas.so)
undefined symbol: LAPACKE_zlange_work	(./libjniopenblas.so)
... ...
```
It seems that all c/c++ functions in LAPACKE are not included into this library. However, the execution of command "mvn clean install --projects .,openblas" succeeds (I have already installed javacpp, opencv, hdf5, caffe presets successfully).

Would you please suggest any hints on how to resolve this problem? Thanks in advance.

**Comment by saudet** [comment]
They are included libopenblas.so.0, libjniopenblas.o depends on it.

**Comment by acekillersg** [comment]
Hi @saudet but libopenblas.so.0 is in the same directory of libjniopenblas.so, and the former .so is also included in the latter one as show by the results of "ldd libjniopenblas.so". Why the program still cannot find the symbols? Thanks.

**Comment by saudet** [comment]
Good question, could you create a small project to reproduce this error?
It does not happen on my system with the sample one here:
https://github.com/bytedeco/javacpp-presets/tree/master/openblas#the-pomxml-build-file

**Comment by acekillersg** [comment]
Hi, @saudet , it seems like this is because I installed package libopenblas-dev during the installation of caffe. Because after I uninstalled that package or install that package after libjniopenblas.so has been generated, then it goes well. So far, I have set up everything work on my computer with the 1.3.3-SNAPSHOT version of JavaCPP and Presets. Thanks for your good work.

I think I should consider to use Docker to maintain a consistent and usable development environment in the next step. During the setting up of JavaCPP and Presets on different OS platforms (Centos 7 & Ubuntu 16.04), I found it is quite annoying to resolve various unpredictable exceptions, most of which are difficult to track (such as "a fatal error has been detected by Java Runtime Environment").

**Comment by saudet** [comment]
So, this only happens for binaries that you build? Then, yes, we should use
Docker for builds:
https://github.com/bytedeco/javacpp-presets/wiki/Build-Environments#linux-x86-and-x86_64

**Comment by acekillersg** [comment]
For my project, I only use caffe library including its dependencies like opencv, hdf5 and openblas. Yes, later I will try Docker to avoid these troubles. Thanks.

**Comment by saudet** [comment]
Are you having issues with the release binaries as well??

**Comment by acekillersg** [comment]
Actually I built binaries from source code on my own computer. I will try the released binaries later and report issues if any. Thanks.
