### ISSUE TITLE
Caffe: Check failed: registry.count(type) == 1 (0 vs. 1) Unknown solver type: SGD (known types: )

### ISSUE THREAD

**Issue by acekillersg** [bytedeco/javacpp-presets#428]
Hi @saudet , I tried the JavaCPP Presets 1.3 binary archive instead of building from source code, I found the old problem occurs again when I use Caffe module: the solver types haven't been registered as the following the message shows:
```
Jun 06, 2017 1:46:38 PM caffe$2 command
INFO: Use GPU with device ID 0
Jun 06, 2017 1:46:38 PM caffe$2 command
INFO: Starting Optimization
WARNING: Logging before InitGoogleLogging() is written to STDERR
F0606 13:46:39.010005 23693 solver_factory.hpp:76] Check failed: registry.count(type) == 1 (0 vs. 1) Unknown solver type: SGD (known types: )
*** Check failure stack trace: ***

Process finished with exit code 134 (interrupted by signal 6: SIGABRT)
```
Here is what I did:
```
1) download the JavaCPP Presets 1.3 binary archive, unzip and put the folder in /usr/local/lib
2) create a Maven project in Intellij Idea, and use the sample code caffe.java;
3) In Idea, open File-->Project Structure-->Modules-->Dependencies-->Add Jars or Directories-->Add "/usr/local/lib/JavaCPP-presets-bin/" to add all jars into project;
4) In Idea, open "Edit configurations" to produce a run configuration for caffe.java with program arguments like "train --solver=examples/mnist/lenet_solver.prototxt --gpu=0";
5) Run this configuration, then the errors occur.
```
I have also tested all other sample codes in other modules like openblas, hdf5, opencv, etc. They all work well. But If I build JavaCPP presets from source code instead of the one your provide, there are no errors.

I think you can also repeat this problem in another computer instead of the one you use to build from source code and generate the binary file. Would you please help to check and give me any hints on how to resolve this?

ps: "device_query" and "caffe test" are successful, only "caffe train" cannot work because it involves Solver which has not been registered successfully;
pps: some similar issue https://github.com/BVLC/caffe/issues/4010 and https://stackoverflow.com/questions/32416226/create-layer-error-at-layer-factory-hpp, it seems to be static library problem as layer or solver registration code is not included in static linking;
ppps: is it possible that the Caffe in JavaCPP Presets 1.3 binary is incompatible with CUDA 8.0 on my computer?

**Comment by saudet** [comment]
How is this related to #427?

**Comment by saudet** [comment]
According to that issue, it seems to be fixed in any case:
> I added it to tools/caffe.cpp for latest release

**Comment by acekillersg** [comment]
@saudet they are not related. #427 occurs using binaries built from source code on my own computer, and existing OpenBLAS library results in that issue. But here for this one, it's problem about Caffe. I mean, if we directly use the JavaCPP Presets binary, Caffe cannot work normally. The potential error is that: the layer/solver registration code in Caffe cannot be included if we use Caffe library in static linking way, which has been pointed out by https://github.com/BVLC/caffe/issues/4010 and https://stackoverflow.com/questions/32416226/create-layer-error-at-layer-factory-hpp. Would you please verify this issue?

**Comment by saudet** [comment]
What about the binaries at https://oss.sonatype.org/content/repositories/snapshots/org/bytedeco/javacpp-presets/caffe/master-1.3.3-SNAPSHOT/ ?

**Comment by acekillersg** [comment]
@saudet I downloaded the binaries from your link and put jar files of (opencv, hdf5, openblas, caffe, javacpp) modules into my class path. However, there is another error: 
```
INFO: Use GPU with device ID 0
Exception in thread "main" java.lang.UnsatisfiedLinkError: no jniopencv_core in java.library.path
```
But there are no such errors if I use V1.3 Presets binary as I did at beginning of this post.

**Comment by archenroot** [comment]
There are links for x86_64, look better....

**Comment by acekillersg** [comment]
@archenroot sorry, my fault. @saudet yes, now it is working now. May I know is there a timeline for release of official V1.3.3 JavaCPP and JavaCPP Presets?

**Comment by saudet** [comment]
Not sure when, but looks like Caffe 1.0 is out, so I might make a release of at least that...

**Comment by saudet** [comment]
I've updated the presets to support Caffe 1.0. Could you guys check that the new SNAPSHOT binaries still run correctly? If they are working fine, I'll make a release of those:
https://oss.sonatype.org/content/repositories/snapshots/org/bytedeco/javacpp-presets/caffe/1.0-1.3.3-SNAPSHOT/
Thanks!
