### ISSUE TITLE
Caffe preset for images classification 

### ISSUE THREAD

**Issue by waelHamdan** [bytedeco/javacpp-presets#43]
could I use the caffe presets for image classification?

**Comment by saudet** [comment]
Yes, but nice examples are hard to come by. We can do pretty much everything that we can do in C++ though, for example: https://github.com/BVLC/caffe/issues/499

If you find any code in C++ that you are having problems translating to Java, let me know! Thanks

**Comment by waelHamdan** [comment]
Thank you for your answer,

**Comment by saudet** [comment]
Have you figured out something in the end?

**Comment by waelHamdan** [comment]
Unfortunately not yet.
I asked for more help but still waiting, I very new to this.

**Comment by saudet** [comment]
Ok, let me know if you figure out anything! I'm new to Caffe myself, thanks.
