### ISSUE TITLE
Upload *-platform packages to sonartype

### ISSUE THREAD

**Issue by andreas-eberle** [bytedeco/javacpp-presets#430]
At the moment the *-platform artefacts aren't uploaded to sonatype.

@vb216:  @saudet said you would be the right one for this.

**Comment by vb216** [comment]
Yeah.. I'd been thinking of tackling that next, would help javacv too. I've been trying to finish up powerpc building in Travis and then we'd have the full set of architecture builds working.

I'm hoping that the new stages functionality in Travis will let us run the platform step as a separate stage after all the OS targets are built, but I'm not sure yet..

**Comment by saudet** [comment]
Thanks! FYI, we would just need to call `mvn -f platform -Djavacpp.platform= ...` after the other mvn command for each module. We probably don't need to build the parent one.

**Comment by vb216** [comment]
Oh cool, that makes life alot easier! Will wrap it up in the next PR coming
then
