### ISSUE TITLE
Incorrect checksum for freed object - object was probably modified after being freed

### ISSUE THREAD

**Issue by zugaldia** [bytedeco/javacpp-presets#432]
I have a method that computes the maximum values in an `opencv_core.UMat histogram` that looks like this:

```
public static HistogramPosition getMaxPosition(opencv_core.UMat histogram) {
  DoublePointer minVal = new DoublePointer(1);
  DoublePointer maxVal = new DoublePointer(1);
  opencv_core.Point minLoc = new opencv_core.Point(1);
  opencv_core.Point maxLoc = new opencv_core.Point(1);
  opencv_core.minMaxLoc(histogram, minVal, maxVal, minLoc, maxLoc, null);
  return new HistogramPosition(maxLoc.y(), maxVal.get(0));
}
```

where `HistogramPosition` is a simple POJO used to hold the values:

```
public class HistogramPosition {
  private int binIndex;
  private double binValue;

  public HistogramPosition(int binIndex, double binValue) {
    this.binIndex = binIndex;
    this.binValue = binValue;
  }

  public int getBinIndex() { return binIndex; }
  public double getBinValue() { return binValue; }
}
```

However, when I try accessing the values via `getBinIndex/getBinValue` I occasionally get the following native error:

```
java(19594,0x70000021a000) malloc: *** error for object 0x7fc6a966a258: incorrect checksum for freed object - object was probably modified after being freed.
*** set a breakpoint in malloc_error_break to debug
```

It looks like a race condition with the garbage collector. I'm using `org.bytedeco.javacpp-presets:opencv-platform:3.2.0-1.3` directly from Maven Central.

cc: @saudet

**Comment by saudet** [comment]
I'm pretty sure we can't access a UMat like that. Try to copy it to a Mat
first.

**Comment by saudet** [comment]
In any case, please post something I can use to reproduce this. I won't be able to fix something that isn't broken! Thanks

**Comment by zugaldia** [comment]
My bad - based on your feedback I redid the code to avoid `UMat` but I was still seeing the issue. Digging deeper I found that though the crash seemed to come from the method above, it was only _printed_ after the method had been executed. However, it was coming from the method that computed the histogram. That method had a `FloatPointer rangesPointer = new FloatPointer(size);` with the wrong `size`. Increasing the `size` value seemed to have fixed the issue. 

@saudet Thank you for the prompt feedback in any case.
