### ISSUE TITLE
Accelerate BLAS Preset for macOS

### ISSUE THREAD

**Issue by ibinti** [bytedeco/javacpp-presets#436]
I wonder if javacpp can bind macOS Frameworks. If so, please consider adding BLAS in Accelerate Framework.

**Comment by ibinti** [comment]
It should be doable as the macOS frameworks are basically a bundle of header files and respective dynamic libraries. And Accelerate BLAS are written in C, not Objective-C/C++ or swift.
On my macOS 10.12.5, the headers and *.dylib are located in /System/Library/Frameworks/Accelerate.framework/versions/A/Frameworks/vecLib.framework/Versions/A

**Comment by ibinti** [comment]
javacpp jni library should be written as framework in order to be more useful (at least to me).

**Comment by saudet** [comment]
We can use JavaCPP as a code generator as part of Xcode, that's fine.

**Comment by ibinti** [comment]
@saudet I am going to try it myself. Could you give me some more directions if possible?

**Comment by saudet** [comment]
Are you interested only in BLAS? If so, check the presets/openblas.java
file. There are bits about MKL. Try to do the same for Accelerate.

**Comment by ibinti** [comment]
BLAS and LAPACK presets seem working.
I checked BLAS function `cblas_dgemm` and the multiplication result is correct.
There is no issue finding jni library if I put javacpp-presets jars in the lib.
But if I try to use from mavenLocal, then it complains like:
```
java.lang.UnsatisfiedLinkError: no jniblas in java.library.path
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
        at java.lang.Runtime.loadLibrary0(Runtime.java:870)
        at java.lang.System.loadLibrary(System.java:1122)
        at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:976)
        at org.bytedeco.javacpp.Loader.load(Loader.java:777)
        at org.bytedeco.javacpp.Loader.load(Loader.java:684)
        at org.bytedeco.javacpp.accelerate.<clinit>(accelerate.java:10)
        at ExampleDGEMMrowmajor.main(ExampleDGEMMrowmajor.java:118)
```
What could be the reason?

**Comment by saudet** [comment]
Well then it's obviously not in the class path.

**Comment by ibinti** [comment]
Both accelerateblas-1.0.0-1.3.3-SNAPSHOT.jar and accelerateblas-1.0.0-1.3.3-SNAPSHOT-macosx-x86_64.jar are in the local maven repo. But strangely, preset jar does not find its accompanying jni jar.

**Comment by saudet** [comment]
Are you sure it's not SIP preventing your from loading things?

**Comment by ibinti** [comment]
It was indeed not in the class path, after all.
I simply missed the classifier `macosx-x86_64` in my gradle dependencies.
Now I think this issue can be closed.

**Comment by saudet** [comment]
Marking as duplicate of #444.
