### ISSUE TITLE
Opencv calcHist needs multi dimensional array for range

### ISSUE THREAD

**Issue by jcfrk101** [bytedeco/javacpp-presets#437]
I have tried to solve this several other ways, but it appears that the only solution would be correcting the interface. I keep getting the following 

OpenCV Error: Assertion failed (ranges[i] && ranges[i][0] < ranges[i][1]) in histPrepareImages, file /Users/saudet/projects/bytedeco/javacpp-presets/opencv/cppbuild/macosx-x86_64/opencv-3.0.0/modules/imgproc/src/histogram.cpp, line 190

This is how I am creating the histogram
` private static Mat getHistMat(Mat image){
			    int[] histSize = {256};
			    int[] channels = {0};
			    final float[] ranges = {0f,256f};
			    Mat hist=new Mat();
			    hist.rows(image.rows()).cols(image.cols());
			    Mat mask=new Mat();
			    mask.rows(image.rows()).cols(image.cols());
			    opencv_imgproc.calcHist(image, 1, channels, mask, hist, 2, histSize, ranges,true,false);
			    opencv_core.normalize(hist, hist, 0, 1, opencv_core.NORM_MINMAX, -1, new Mat());
			    return hist;
		    }`

**Comment by jcfrk101** [comment]
Resolved the issue by using a PointerPointer<FloatPointer> instead of float[][]. Not sure why the interface allows anything by PointerPointer since the calcHist method requires a multidimensional array for ranges. 

Sample of code that worked
` private static Mat getHistMat(Mat image){
			    int[] hist_size = {50,60};
			    int[] channels = {0,1};
			    IntPointer channels_pointer=new IntPointer(channels);
			    IntPointer hist_size_pointer=new IntPointer(hist_size);
			    final float[][] ranges = {{0f,180f},{0f,256f}};
			    PointerPointer<FloatPointer> range_pointer=new PointerPointer<FloatPointer>(ranges);
			    Mat hist=new Mat();
			    hist.rows(image.rows()).cols(image.cols());
			    Mat mask=new Mat();
			    mask.rows(image.rows()).cols(image.cols());
			    opencv_imgproc.calcHist(image, 1, channels_pointer, mask, hist, 2, hist_size_pointer, range_pointer,true,false);
			    opencv_core.normalize(hist, hist, 0, 1, opencv_core.NORM_MINMAX, -1, new Mat());
			    return hist;
		    }`

**Comment by saudet** [comment]
`float[][]` doesn't map to anything useful on the native side, so we need something like `PointerPointer`. We could create some additional overloads just for that, but I'm sure it would be worth it.

**Comment by saudet** [comment]
When called for only one channel, we can use `float[]` though.
