### ISSUE TITLE
Connection timeout error for some tar.gz packages due to restrict reason

### ISSUE THREAD

**Issue by Bahramudin** [bytedeco/javacpp-presets#438]
The problem with rebuilding the project from source due to the restriction of some URLs leading the build process to be failed. For example, 
`0curl: (7) Failed to connect to chromium.googlesource.com port 443: Timed out`
which cannot be accessed from some places, so if it is possible it will be better to redirect this kind of connection to some other servers. Thanks!!

**Comment by saudet** [comment]
By all means, please tell us about alternative sources if you know them and
we will put them in! Thanks

**Comment by Bahramudin** [comment]
The source when it was trying to download is` libvpx-v1.6.1.tar.gz`, but because the URL of this package is Google, so it has been restricted and cannot be used, so it makes the build process to be failed.

**Comment by saudet** [comment]
Yes, I understand. Do you have a working URL?

**Comment by Bahramudin** [comment]
@saudet In this time I don't have any URL, but it can be better that put all the necessary libs and packages in a can be accessed from anywhere servers, because in some country and places some of the URLs cannot be accessed, so it makes the build process to be failed.

**Comment by saudet** [comment]
Or you could use Travis CI.

**Comment by Bahramudin** [comment]
@saudet I have done every step as described [here](https://github.com/bytedeco/javacpp-presets/wiki/Build-Environments), but it was failed every time. So it makes me very confused. If you have any better way to build javacpp-presets, it will be nice!!!

**Comment by saudet** [comment]
Send a pull request, and it will get built by Travis CI.

**Comment by saudet** [comment]
I've changed the download site to GitHub:
https://github.com/bytedeco/javacpp-presets/commit/fa1fe067294f6c3a5c78d73c1fedf3af46353c47#diff-f0a16634b0085e43f858c2adb96676cd
Thanks for the feedback and enjoy!

**Comment by Bahramudin** [comment]
OK Thank you!! @saudet
