### ISSUE TITLE
Distributed training support in Mxnet preset?

### ISSUE THREAD

**Issue by acekillersg** [bytedeco/javacpp-presets#440]
Hi @saudet may I know whether the Mxnet preset support distributed training in current version?

**Comment by saudet** [comment]
Some things are, some things are not. Modify the flags you need, send a
pull request, and Travis CI will automatically compile new binaries for you!

**Comment by saudet** [comment]
FYI, it says we need to build MXNet with the `USE_DIST_KVSTORE=1` flag here:
http://mxnet.io/how_to/multi_devices.html#how-to-launch-a-job

So, if you are still interested, please add it to the cppbuild.sh script, and send a pull request to get new binaries! Thanks

**Comment by acekillersg** [comment]
Hi, dear Samuel,

Sure, I will firstly try it locally and if it works, then I will try to
submit pull request. Thanks.

Best Regards,
John
