### ISSUE TITLE
Trim video length with FrameGrabber and FrameRecorder on Android

### ISSUE THREAD

**Issue by 5eeman** [bytedeco/javacpp-presets#441]
I'm trying to trim video length with ffmpeg implementation of FrameGrabber and FrameRecorder, but getting corrupted file of smaller size then it's going to be. Seems like it's not recording changes between frames. Maybe there is other way to trim video from start time to end time, also updating trim progress. Here is code snippet:

                FrameGrabber grabber = new FFmpegFrameGrabber(mClip.getPath());
                grabber.start();
                grabber.setTimestamp(mClip.getClipStartMs()); // Write from specific moment

                File out = new File(mClip.getOutPutPath(params[0])); // Set destination to write
                FrameRecorder recorder = new FFmpegFrameRecorder(out, grabber.getImageWidth(), grabber.getImageHeight());

                recorder.setFormat(grabber.getFormat());
                recorder.setFrameRate(grabber.getFrameRate());
                recorder.setSampleRate(grabber.getSampleRate());
                recorder.setAspectRatio(grabber.getAspectRatio());
                recorder.setSampleFormat(grabber.getSampleFormat());

                recorder.setAudioCodec(grabber.getAudioCodec());
                recorder.setAudioBitrate(grabber.getAudioBitrate());
                recorder.setAudioChannels(grabber.getAudioChannels());

                recorder.setVideoCodec(grabber.getVideoCodec());
                recorder.setVideoBitrate(grabber.getVideoBitrate());

                recorder.start();

                Frame frame;
                Long timestamp;
                Long fullLength = mClip.getClipEndMs() - mClip.getClipStartMs();
                double percent = 0d, oldPercent = 0d;

                while ((frame = grabber.grabFrame()) != null && (timestamp = grabber.getTimestamp()) <= mClip.getClipEndMs()) {
                    Log.d(ASYNC_SAVE_TAG, "Started command : ffmpeg " + mClip.toString());

                    if (timestamp != 0d) {
                        oldPercent = percent;
                        percent = timestamp.doubleValue() / fullLength.doubleValue();
                        if (MathUtil.compare(percent, oldPercent) != 0) {
                            publishProgress(percent);
                        }
                    }

                    recorder.setTimestamp(grabber.getTimestamp() - mClip.getClipStartMs());
                    recorder.record(frame);
                }

                grabber.close();
                recorder.close();

**Comment by saudet** [comment]
The timestamp is in microseconds, are you using the right units?

**Comment by saudet** [comment]
I'm assuming that rescaling your values to microseconds fixed this issue, but please let me know if you are still having problems!

**Comment by saudet** [comment]
BTW, if the `ffmpeg` program is sufficient, with commit https://github.com/bytedeco/javacpp-presets/commit/13ffffd191fa48d9d9d1d8a64e0c4d64c9da1134 it now gets bundled and can be used easily from Java.
