### ISSUE TITLE
build ffmpeg with

### ISSUE THREAD

**Issue by mifritscher** [bytedeco/javacpp-presets#443]
Thanks for your work!
It would be nice to build the ffmpeg libraries with libfreetype so I can e.g. use the drawtext option :-)

Luckily, it works for now by simple exchanging the dlls with the statically built ones from ffmpeg.org ;-)

**Comment by saudet** [comment]
Duplicate of https://github.com/bytedeco/javacv/issues/254

Contributions are welcome!
