### ISSUE TITLE
is the mkl preset published to maven?

### ISSUE THREAD

**Issue by amuseoffire** [bytedeco/javacpp-presets#446]
This is not working for me:

`    <dependency>
            <groupId>org.bytedeco.javacpp-presets</groupId>
            <artifactId>mkl-platform</artifactId>
            <version>2017.2-1.3.3-SNAPSHOT</version>
        </dependency>`

and i can't find it here: https://mvnrepository.com/artifact/org.bytedeco.javacpp-presets?p=1

**Comment by saudet** [comment]
Make sure you have the SNAPSHOT repository somewhere in your pom.xml or settings.xml file. Something like this: https://github.com/bytedeco/javacpp-presets/blob/master/pom.xml#L118-L130

**Comment by amuseoffire** [comment]
thanks!

**Comment by saudet** [comment]
Now it has been released:
http://search.maven.org/#artifactdetails%7Corg.bytedeco.javacpp-presets%7Cmkl%7C2017.3-1.3%7Cjar

Enjoy!
