### ISSUE TITLE
building ffmpeg for android on mac, lame fails C preprocessor check

### ISSUE THREAD

**Issue by IFDeveloper** [bytedeco/javacpp-presets#45]
./cppbuild.sh -platform android-arm install ffmpeg
checking how to run the C preprocessor... /lib/cpp
configure: error: in `/Users/Phoenix/workspace/Frameworks/javacpp-presets/ffmpeg/cppbuild/android-arm/lame-3.99.5':
configure: error: C preprocessor "/lib/cpp" fails sanity check

**Comment by saudet** [comment]
This is weird. Does OpenCV compile fine?

**Comment by IFDeveloper** [comment]
Yeap, fine. Changing CPP flag makes some progress and again fails

**Comment by saudet** [comment]
Odd, I have no problems building for Android on Linux. Is the NDK that different on Mac OS X? BTW, if you don't need to encode in MP3, you can temporarily remove LAME from the build.

**Comment by zmingchun** [comment]
I also miss this error，even though I remove LAME ...

**Comment by zmingchun** [comment]
What's more，this is my log [javacpp-ffmpeg-lame-compiled-error-config.log](http://7xiuyx.com1.z0.glb.clouddn.com/codejavacpp-ffmpeg-lame-compiled-error-config.log)

**Comment by saudet** [comment]
@zmingchun It's still trying to build LAME, so you didn't remove it.

I'm not sure why this is happening, so let's mark this as a bug. If anyone finds out the solution, please let us know! For now the workaround is to build under Linux...

**Comment by zmingchun** [comment]
@saudet I build ffmpeg for IOS successful，use this shell file [build-ffmpeg-android.sh](http://7xiuyx.com1.z0.glb.clouddn.com/code/file/build-ffmpeg.sh)，use ` gas-preprocessor.pl` as  c processor ; But I didn't know  which one should as ` gas-preprocessor.pl` build for android.

**Comment by saudet** [comment]
Good! Could you propose the changes we should make to the `cppbuild.sh`
file? Thanks!

**Comment by IFDeveloper** [comment]
just updated to NDK r10e and all build went OK!!! possibly NDK r10d was missing some links. PLS mark this as SOLVED

**Comment by szitguy** [comment]
@IFDeveloper I use NDK r10e, but still not work

**Comment by saudet** [comment]
@szitguy What error do you get?

**Comment by szitguy** [comment]
@saudet 
configure: error: C preprocessor "/lib/cpp" fails sanity check
I had already installed XCode and Common Line Tools, but it still not work

**Comment by saudet** [comment]
@szitguy Well, you could get rid of LAME if you do not need it...

**Comment by kristofgiber** [comment]
Still no solutions to this other than removing LAME? I also have the latest NDK r10e on Mac and having the same error: 

configure: error: in `/Users/user/Code/git/javacpp-presets/ffmpeg/cppbuild/android-arm/lame-3.99.5':
configure: error: C preprocessor "/lib/cpp" fails sanity check
