### ISSUE TITLE
AVERROR(errno) is not defined

### ISSUE THREAD

**Issue by ishitatsuyuki** [bytedeco/javacpp-presets#454]
The [modern ffmpeg API](https://www.ffmpeg.org/doxygen/3.1/group__lavc__encdec.html) uses those macros especially `AVERROR(EAGAIN)` which is just a errno trick, but this preset doesn't seem to handle it. This makes it virtually impossible to use the new API.

**Comment by saudet** [comment]
We would have to pick up the errno constants from somewhere, but they are not part of FFmpeg. The header files differ depending on the operating system. What would you suggest to do?

**Comment by ishitatsuyuki** [comment]
The list used by FFmpeg is purely a subset, and we should implement the most vital ones like EAGAIN. If we can evaluate preprocessor we should get from it, else we would be just using a hardcoded enum.

I have collected all codes directly referenced by the source. Note that there may be other source of errno (e.g. system IO).
https://gist.github.com/7b84f62f9606ef375c94b30b25e004ff

**Comment by saudet** [comment]
We also need a list of constants that are available on all the platforms...

**Comment by saudet** [comment]
Or actually, we could simply implement them as JNI functions and they would return whatever constants are available as build time.

**Comment by ishitatsuyuki** [comment]
A sad thing is that BSD family including Mac uses a different value of EAGAIN. This means that we cannot hardcode it and must evaluate in some manner.

**Comment by saudet** [comment]
Declarations such as this at the bottom of `presets/avutil.java` appear to have the desired results:
```java
    public static native @MemberGetter @Name("AVERROR(EAGAIN)") int AVERROR_EAGAIN();
```
Would you mind sending a pull request for this? :)

**Comment by ishitatsuyuki** [comment]
Makes sense. Let me do that over the weekend.

**Comment by ishitatsuyuki** [comment]
Sorry, putting that statement at the bottom of **presets**/avutil.java doesn't seem to work. Is it somewhere else like InfoMap?

**Comment by saudet** [comment]
No, methods in avutil class itself.

**Comment by ishitatsuyuki** [comment]
Altering the generated files may cause maintenance burden. Is there any way to do this more systematically?

**Comment by saudet** [comment]
Not the generated one, the one in the presets subdirectory.

**Comment by ishitatsuyuki** [comment]
Putting the statement has no effect. I'm putting statements like this:

```
    public static native @MemberGetter @Name("AVERROR(EAGAIN)") int AVERROR_EAGAIN();
```

after `public void map` and before the class ending curly brace.

What result did you get?

**Comment by saudet** [comment]
What do you mean by effect? What does it return when you call it?

**Comment by ishitatsuyuki** [comment]
My bad. It actually works, but I didn't notice because generated JNI files gets automatically deleted.
