### ISSUE TITLE
AV_CH_LAYOUT_ defines are int instead of long

### ISSUE THREAD

**Issue by ishitatsuyuki** [bytedeco/javacpp-presets#455]
They're weakly typed in C relying on the integer type auto conversion (and this applies to Java as well).

However, inside Kotlin this creates a problem as conversion must be explicit and it gives you a bad feeling to manually cast a constant.

**Comment by saudet** [comment]
That could easily be fixed, would like to give it a try?

**Comment by ishitatsuyuki** [comment]
I have no experience with javacpp internals, can you give some hint?

**Comment by saudet** [comment]
There's already one specified on the line below, we could do the rest:
https://github.com/bytedeco/javacpp-presets/blob/master/ffmpeg/src/main/java/org/bytedeco/javacpp/presets/avutil.java#L58

**Comment by ishitatsuyuki** [comment]
Got it, will open a PR when I get to my computer.
