### ISSUE TITLE
java.lang.NoClassDefFoundError: org/bytedeco/javacpp/opencv_face$FaceRecognizer

### ISSUE THREAD

**Issue by thaermutlaq** [bytedeco/javacpp-presets#465]
Hi,
I'm trying to use javacpp in order to use fisherFaces classifier. I'm using Android studio, and all the time that I try to run my code I get the error that I mentioned in the title and in this screenshot.

<img width="933" alt="screen shot 2017-09-19 at 5 31 03" src="https://user-images.githubusercontent.com/25735569/30573400-58eae568-9cfc-11e7-8d48-c40a7e909d88.png">

I installed tha jars manually and here are two screenshots of the dependencies under my build.gradle and my libs tree. 

<img width="281" alt="screen shot 2017-09-19 at 5 31 20" src="https://user-images.githubusercontent.com/25735569/30573442-9772e682-9cfc-11e7-960c-3501a0368c23.png">
<img width="518" alt="screen shot 2017-09-19 at 5 32 32" src="https://user-images.githubusercontent.com/25735569/30573443-97a231d0-9cfc-11e7-8404-78d173d933f7.png">

Can you please help with this?

Thanks in advance

**Comment by saudet** [comment]
Could you also provide the list of files in your APK?

**Comment by thaermutlaq** [comment]
The code that I try to compile and run isn't an android APK. It's a regular PC terminal program.

**Comment by saudet** [comment]
Then don't use Android Studio.

**Comment by thaermutlaq** [comment]
Tried Eclipse and It worked! Thank you very much.
Actually my project Includes some code for android(as client side) and some code for PC (as a server side), and I didn't want to to use two different IDEs.
I can't see the reason why it doesn't work on Android Studio, but it's ok for now to switch between Eclipse and Android Studio when I want to debug.

**Comment by saudet** [comment]
It should work, but you need to make sure the module for opencv gets
included by Gradle, which is obviously not happening for your project. In
the worst case, just add all dependencies manually, it will work.
