### ISSUE TITLE
Update to OpenCV 3.3

### ISSUE THREAD

**Issue by ppong** [bytedeco/javacpp-presets#467]
OpenCV release 3.3 recently. (http://opencv.org/opencv-3-3.html). We would love to use some of the new changes in the opencv-contrib ximgproc package. Do you know when a new release might occur?

**Comment by saudet** [comment]
Sending a patch would certainly help :)

**Comment by Daniel-Alievsky** [comment]
I'm also interested in new version. No any info and prognoses?

**Comment by saudet** [comment]
I've upgraded the presets and SNAPSHOT artifacts are available here:
https://oss.sonatype.org/content/repositories/snapshots/org/bytedeco/javacpp-presets/opencv/3.3.0-1.3.4-SNAPSHOT/
Please let me know if there is anything missing!

**Comment by Daniel-Alievsky** [comment]
Do you know, when can we hope that it will appear as the stable version 3.3.0 on Maven Central?

**Comment by saudet** [comment]
I'm planning before next month, but 3.3.1 came out, so it won't be 3.3.0.

**Comment by Daniel-Alievsky** [comment]
Thank you! It will be great if it will be right away 3.3.1

**Comment by ben-manes** [comment]
@ppong and I tested our use-case and it works great.

Eclipse seems to get very confused by the snapshot version when resolving through Gradle. It will resolve the first time, and then forget it on a refresh. Also the snapshot repository stopped releasing new macosx builds, which we use locally and linux on the server. It would be nice if a formal release was made since the quirk might be due to its dynamic resolution.
```
"org.bytedeco:javacv:1.3.4-SNAPSHOT",
"org.bytedeco.javacpp-presets:opencv:3.4.0-1.3.4-20180107.061441-21:macosx-x86_64",
```

**Comment by saudet** [comment]
Working on it, but in the meantime, if you could let the Gradle team know you need better Maven compatibility, that would be great. They don't seem to care too much at the moment:
https://discuss.gradle.org/t/maven-metadata-with-classifiers-fails-to-resolve-for-snapshots/20071
https://github.com/gradle/gradle/issues/2882

**Comment by ben-manes** [comment]
I think Gradle does not understand the classifiers in snapshots, so it takes the globally latest which is only relevant to a single classifier.

```
<versioning>
<snapshot>
<timestamp>20180109.220324</timestamp>
<buildNumber>54</buildNumber>
</snapshot>
<lastUpdated>20180109220324</lastUpdated>
<snapshotVersions>
  ...
  <snapshotVersion>
    <classifier>macosx-x86_64</classifier>
    <extension>jar</extension>
    <value>3.4.0-1.3.4-20180109.132121-44</value>
    <updated>20180109132121</updated>
  </snapshotVersion>
</snapshotVersion>
```
```
compile "org.bytedeco.javacpp-presets:opencv:3.3.1-1.3.4-SNAPSHOT:${env.os}-${env.arch}
```
```
> Could not find opencv-macosx-x86_64.jar (org.bytedeco.javacpp-presets:opencv:3.4.0-1.3.4-SNAPSHOT).
  Searched in the following locations:
      https://oss.sonatype.org/content/repositories/snapshots/org/bytedeco/javacpp-presets/opencv/3.4.0-1.3.4-SNAPSHOT/opencv-3.4.0-1.3.4-20180109.220324-54-macosx-x86_64.jar
```

**Comment by ben-manes** [comment]
Can you open a Gradle issue? They moved from the discussion forum to Github issues instead. Its still difficult to get them to respond to such things, but they don't ignore them as flagrantly.

**Comment by ben-manes** [comment]
This seems to work for now. The javacv snapshot dependency confused Gradle and Eclipse.
```gradle
opencv: [
  dependencies.create("org.bytedeco:javacv:${versions.javacv}-SNAPSHOT") {
    exclude module: 'opencv'
  },
  "org.bytedeco.javacpp-presets:opencv:${versions.opencv}-${env.os == 'macosx' ? '20180109.132121-44' : '20180109.220324-54'}",
  "org.bytedeco.javacpp-presets:opencv:${versions.opencv}-${env.os == 'macosx' ? '20180109.132121-44' : '20180109.220324-54'}:${env.os}-${env.arch}",
],
```

But we'll eagerly be waiting for the next release. Thanks!

**Comment by saudet** [comment]
Version 1.4 has been released with binaries for OpenCV 3.4.0:
http://search.maven.org/#search%7Cga%7C1%7Cbytedeco%20opencv
Enjoy and thank you for your patience!

**Comment by ppong** [comment]
Thanks @saudet

**Comment by carlspring** [comment]
Hi,

Thanks for linking to [#2882](https://github.com/gradle/gradle/issues/2882). The more people that complain there, the better! Please, join in, if you're feeling the side-effects of this!

Thanks!

Martin
