### ISSUE TITLE
Help for ffmpeg optimize size configure build

### ISSUE THREAD

**Issue by farzadnone** [bytedeco/javacpp-presets#468]
Hi, i need only (only and only and only) create mp4 with series of bitmap(image). so ffmpeg is large size apk file. so, can i use ffmpeg (libavcodec.so) with command? how to create android small apk (~4mb or ~5mb) app with ffmpeg for this create simple mp4 with series of bitmap(image)? i have not linux. i have wiindows 8.1 x64. building ffmpeg is very complex :| please help me.

NOTE!
i need only create mp4 with series of bitmap.
-no need filter.
-no need complex converting.
-no need ffmpeg complex decode/encode. 
ONLY and ONLY create simple standard mp4 with bitmaps and play on all android devices without bug.

!@#$ ffmpeg(nested complx) / !@#$ android(low level) :| /!@#$ jcodec(simple) / !@#$ ringdroid(bug)

**saudet** please help me :(

**Comment by saudet** [comment]
The build should still work on Windows. If you have any problems with it,
let me know.

**Comment by farzadnone** [comment]
@saudet ty for reply. i am noob developer in ndk and no skill for building desire ffmpeg. so i need source of building minimal ffmpeg on windows. can i you give me useful guide source? i need ffmpeg only for generate standard mp4 video with bitmaps and mp3(audio). can i you build only this featured for me? i can use ndk with cpp. just i have not skill for building small ffmpeg for desire target. thank saudet. please help me. i need minimal ffmpeg for this target.

**Comment by saudet** [comment]
Yes, but
https://github.com/bytedeco/javacpp-presets/wiki/Build-Environments#windows-x86-and-x86_64
is more up-to-date.

**Comment by farzadnone** [comment]
@saudet Will I need to have Visual Studio?

**Comment by saudet** [comment]
Probably not, no.

**Comment by farzadnone** [comment]
hi @saudet . i solved and fix to build ffmpeg by vmware+ubuntu and success. but i need a request. please help me.

my request:

i'm building ffmpeg for android. my target is only create mp4 video with series of bitmap image and merge mp3 audio. i want use ffmpeg only only for this target. So i need optimized config for this target. i try find in google and find not bad config list. but i need full optimize config for reduce size of ffmpeg in android app. can you suggest me best config for this target?

i find this:
[Minimal configuration for mp4 files](http://ffmpeg.gusari.org/viewtopic.php?f=8&t=1663)
[how do i modify this ffmpeg build script for minimal binary size output](https://stackoverflow.com/questions/27832052/how-do-i-modify-this-ffmpeg-build-script-for-minimal-binary-size-output)

but is not complete optimized.

@saudet please suggest me full optimize config for my target.  thanks

**Comment by saudet** [comment]
Good! You could try to uncomment these lines in cppbuild.sh now:
https://github.com/bytedeco/javacpp-presets/blob/master/ffmpeg/cppbuild.sh#L13

**Comment by farzadnone** [comment]
@saudet nice, thank you man.
