### ISSUE TITLE
Request convert this javacv ffmpeg to ffmpeg c api for android jni

### ISSUE THREAD

**Issue by farzadnone** [bytedeco/javacpp-presets#472]
Hi, I build minimal ffmpeg shared library (*.so libs) via this config:

- android-ndk-r15b
- ffmpeg-3.3.4
- last_x264.tar_2

```
NDK=$HOME/Desktop/adt/android-ndk-r15b
PLATFORM=$NDK/platforms/android-24/arch-arm/
PREBUILT=$NDK/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64

GENERAL="\
--disable-all \
--enable-small \
--enable-cross-compile \
--extra-libs="-lgcc" \
--arch=arm \
--cc=$PREBUILT/bin/arm-linux-androideabi-gcc \
--cross-prefix=$PREBUILT/bin/arm-linux-androideabi- \
--nm=$PREBUILT/bin/arm-linux-androideabi-nm \
--extra-cflags="-I../x264/android/arm/include" \
--extra-ldflags="-L../x264/android/arm/lib" "


MODULES="\
--disable-network \
--enable-pthreads \
--enable-avcodec \
--enable-avformat \
--enable-swscale \
--enable-swresample \
--enable-avfilter \
--enable-libx264 \
--enable-gpl \
--enable-parser=bmp,mpegaudio \
--enable-demuxer=image2,bmp_pipe,mp3 \
--enable-decoder=bmp \
--enable-muxer=mp4 \
--enable-encoder=libx264 \
--enable-filter=format,scale \
--enable-protocol=file \
--enable-ffmpeg"

function build_ARMv7
{
  ./configure \
  --target-os=linux \
  --prefix=./android/armeabi-v7a \
  ${GENERAL} \
  --sysroot=$PLATFORM \
  --enable-shared \
  --disable-static \
  --extra-cflags="-DANDROID -fPIC -ffunction-sections -funwind-tables -fstack-protector -march=armv7-a -mfloat-abi=softfp -mfpu=vfpv3-d16 -fomit-frame-pointer -fstrict-aliasing -funswitch-loops -finline-limit=300" \
  --extra-ldflags="-Wl,-rpath-link=$PLATFORM/usr/lib -L$PLATFORM/usr/lib -nostdlib -lc -lm -ldl -llog" \
  ${MODULES} \
  --disable-doc \
  --enable-neon

  make clean
  make
  make install
}

build_ARMv7
echo Android ARMv7-a builds finished
```

Now i need create mp4 video with series of images and single mp3 audio. i used this javacv ffmpeg jar for this target. now i need convert this java code to C lang ffmpeg api for use in my jni file in my app.

FFmpegFrameGrabber audioGrabber = new FFmpegFrameGrabber(audioFile); //mp3 file
audioGrabber.start();

opencv_core.IplImage iplImage = cvLoadImage(finalImageFile); //jpg file

FFmpegFrameRecorder recorder = new FFmpegFrameRecorder(finalFile, 720, 720, audioGrabber.getAudioChannels());
recorder.setVideoCodec(avcodec.AV_CODEC_ID_MPEG4);
recorder.setAudioCodec(audioGrabber.getAudioCodec());
recorder.setFrameRate(1);
recorder.setVideoBitrate(128000);
recorder.setFormat("mp4");
recorder.setPixelFormat(avutil.AV_PIX_FMT_YUV420P);
recorder.setVideoQuality(0);
recorder.setSampleRate(audioGrabber.getSampleRate()); // 44100
recorder.setAudioBitrate(audioGrabber.getAudioBitrate());
//recorder.setAudioQuality(0);
recorder.setAudioChannels(audioGrabber.getAudioChannels()); // 2

OpenCVFrameConverter converter = new OpenCVFrameConverter() {
	@Override
	public Frame convert(Object o) {
		return null;
	}
	@Override
	public Object convert(Frame frame) {
		return null;
	}
};

recorder.start();

// record video
for (int i = 0; i < 61; i++) {
	Frame imgFrame = converter.convert(iplImage);
	recorder.record(imgFrame);
}

recorder.setTimestamp(0);

// record audio
Frame frame;
//long audioLength = audioGrabber.getLengthInTime();
while ((frame = audioGrabber.grabFrame()) != null) {
	long curTime = audioGrabber.getTimestamp(); //all 229041632
	if (curTime > 60000000)
		break;
	recorder.record(frame);
}
recorder.stop();
audioGrabber.stop();

Someone can write this to me in C language?
I do not have any familiarity with ffmpeg C api.
I also searched, but all resault are only ffmpeg commands line.(not found useful c api)
thanks.

**Comment by saudet** [comment]
This class isn't available in C.
