### ISSUE TITLE
Tesseract example causes JVM to crash in libtesseract.so

### ISSUE THREAD

**Issue by FloWi** [bytedeco/javacpp-presets#48]
I have this java-code from your example-page.
I set the TESSDATA_PREFIX=/usr/share/tesseract-ocr/tessdata to match my local ubuntu-installation of tesseract.

```java
import org.bytedeco.javacpp.*;
import static org.bytedeco.javacpp.lept.*;


public class TesseractSample {
    public static void main(String[] args) {
        BytePointer outText;

        tesseract.TessBaseAPI api = new tesseract.TessBaseAPI();
        // Initialize tesseract-ocr with English, without specifying tessdata path
        if (api.Init(null, "eng") != 0) {
            System.err.println("Could not initialize tesseract.");
            System.exit(1);
        }

        // Open input image with leptonica library
        PIX image = pixRead(args.length > 0 ? args[0] : TesseractSample.class.getResource("/newBoard.png").getFile());
        api.SetImage(image);
        // Get OCR result
        outText = api.GetUTF8Text();
        System.out.println("OCR output:\n" + outText.getString());

        // Destroy used object and release memory
        api.End();
        outText.deallocate();
        pixDestroy(image);
    }
}

```
It causes the JVM to crash.
```
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x000000304085203b, pid=27392, tid=139897653995264
#
# JRE version: Java(TM) SE Runtime Environment (8.0_40-b25) (build 1.8.0_40-b25)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.40-b25 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [libtesseract.so.3+0x25203b]  ERRCODE::error(char const*, TessErrorLogCode, char const*, ...) const+0x16b

```
You find the full log here: gist.github.com/FloWi/d632ed69315424348d1f

Any idea, what is wrong?
I'm completely lost in c++-land ;-)

**Comment by saudet** [comment]
Data for version "3.03" often doesn't work for Tesseract 3.03, so try with the ones labeled "3.02" here:
https://code.google.com/p/tesseract-ocr/downloads/list
That usually works better.

**Comment by FloWi** [comment]
Thanks for your help. I tried the example you provided.
But unfortunately I'm struggling with maven :-(

I searched hours to try to pass in the "TESSDATA_PREFIX" environment-variable from maven into the running sample. I don't get it. I even tried to add the exec-maven-plugin and configure it properly.
I learned, that I exec:java uses the same JVM to run. So I tried to pass in the parameter directly to maven like so:

```bash
mvn clean package exec:java -Dexec.mainClass=BasicExample -Dexec.args="test.png"
```
It doesn't work.
```
TESSDATA: null
Error opening data file /usr/share/tesseract/tessdata/eng.traineddata
Please make sure the TESSDATA_PREFIX environment variable is set to the parent directory of your "tessdata" directory.
Failed loading language 'eng'
Tesseract couldn't load any languages!
Could not initialize tesseract.
```

With exec:exec (which spawns a new jvm) it doesn't work either:
```
$ mvn package exec:exec -Dexec.mainClass=BasicExample  -Dexec.args="test.png"

[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.3.2:exec (default-cli) on project BasicExample: The parameters 'executable' for goal org.codehaus.mojo:exec-maven-plugin:1.3.2:exec are missing or invalid -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginParameterException
```

Here is the project I created (just the mavenized version of the example): https://github.com/FloWi/SampleTesseract.

Can someone help me out with some maven-knowledge? Any help is highly appreciated.

**Comment by saudet** [comment]
It looks like we can set it programmatically with `TessBaseAPIInit3`, at least:
https://code.google.com/p/tesseract-ocr/wiki/APIExample
Once you get this up and running, consider sending a pull request here:
https://github.com/bytedeco/sample-projects
Thanks!

**Comment by FloWi** [comment]
Will do when I have time. Thanks for pointing me in the right direction.

**Comment by pchundi** [comment]
I finally got it working with tesseract data from version 3.02, the error persists till the locale for numbers(LC_Numeric) is the same as overall locale. My localization settings:
```bash
pchundi@uvbox:~$ locale
LANG=en_US.UTF-8
LANGUAGE=en_US
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=en_US.UTF-8  -- must be same as language
LC_TIME=de_DE.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=de_DE.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=de_DE.UTF-8
LC_NAME=de_DE.UTF-8
LC_ADDRESS=de_DE.UTF-8
LC_TELEPHONE=de_DE.UTF-8
LC_MEASUREMENT=de_DE.UTF-8
LC_IDENTIFICATION=de_DE.UTF-8
LC_ALL=
```

@saudet : If you think it makes sense to have a SBT version of tesseract presets example ? I can generate a pull request.

**Comment by saudet** [comment]
A sample SBT project would great indeed! Please fork https://github.com/bytedeco/sample-projects, create a new directory, and send a pull request. Thanks!!
