### ISSUE TITLE
Deadlock on ffmpeg+x264 for windows encode with tune=zerolatency

### ISSUE THREAD

**Issue by n-kai-cj** [bytedeco/javacpp-presets#480]
Hello guys,

I'm using a _javacpp-1.3_ and _ffmpeg+x264_ for Windows x64 and facing deadlock problem.

I'd like to encode in real-time, so set a `-tune zerolatency` that is a x264 option.
Option setting source code below: 
> av_opt_set(avctx.priv_data(), "tune", "zerolatency", 0)

Actually I don't know about _x264_ in defails, but this option apparently enables x264 to encode a frame in thread parallel.

Encoding frame and extracting avpkt source code below: 
> avcodec_send_frame(avctx, frame)
> avcodec_receive_packet(avctx, avpkt)

**After encoding for a while, the encoding loop is stopped in `avcodec_send_frame()`.
Without x264 _zerolatency_ option, that problem doesn't occur.**
I doubted this problem would be a bug on official _ffmpeg+x264_ at first, but I didn't face the same problem by using below command.
> $ ffmpeg.exe -i input -c:v libx264 -tune zerolatency output

I tried some cases and found, official _ffmpeg+x264_ is using a win32 thread, on the other hand _ffmpeg+x264_ in _javacpp_ is built with `./configure --disable-win32thread` so it's using a pthread by default.
I guess my problem will be resolved if _ffmpeg+x264_ in _javacpp_ is built without `--disable-win32thread`.

I have two questions.
- Why _ffmpeg+x264_ in _javacpp_ disables win32thread ?
- If there is not a particular reason, can you rebuild it ?

Thank you.

**Comment by saudet** [comment]
Simply because it didn't use to build with that option. If they've fixed
it, sure, that's fine. Please send a pull request and let's see if there
are any build issues remaining.

**Comment by n-kai-cj** [comment]
Thank you for your quick response, saudet.

I'm really sorry, I'm not used to github and don't understand to send a pull request.
Diff info can be shown instead of a pull request, but is it ok ?

```
ffmpeg/cppbuild.sh

@@ -561,7 +561,7 @@
         cd ../openh264-$OPENH264_VERSION
         make -j $MAKEJ DESTDIR=./ PREFIX=.. AR=ar ARCH=x86 USE_ASM=No libraries install-static
         cd ../$X264
-        ./configure --prefix=$INSTALL_PATH --enable-static --enable-pic --disable-opencl --disable-win32thread --host=i686-w64-mingw32
+        ./configure --prefix=$INSTALL_PATH --enable-static --enable-pic --disable-opencl --host=i686-w64-mingw32
         make -j $MAKEJ
         make install
         cd ../x265-$X265
@@ -609,7 +609,7 @@
         cd ../openh264-$OPENH264_VERSION
         make -j $MAKEJ DESTDIR=./ PREFIX=.. AR=ar ARCH=x86_64 USE_ASM=No libraries install-static
         cd ../$X264
-        ./configure --prefix=$INSTALL_PATH --enable-static --enable-pic --disable-opencl --disable-win32thread --host=x86_64-w64-mingw32
+        ./configure --prefix=$INSTALL_PATH --enable-static --enable-pic --disable-opencl --host=x86_64-w64-mingw32
         make -j $MAKEJ
         make install
         cd ../x265-$X265
```

**Comment by saudet** [comment]
You'll need to send a pull request to be able to test it.

**Comment by n-kai-cj** [comment]
@saudet , please check this #481 .
This is for my first time to use a pull request, so tell me if anything wrong.
