### ISSUE TITLE
Problem on opening a video

### ISSUE THREAD

**Issue by iwnfubb** [bytedeco/javacpp-presets#482]
Hi, 
I have problem to get a frame from a video #
`VideoCapture capture =  new VideoCapture("video.mp4");`
`boolean isOK = capture.isOpened()`
isOpened() returns always `false`

I tried it with opencv 3.3.0 and opencv_ffmpeg330_64, and it works
Platform: Window7 64 bit
hier is my `gradle.build` dependencies
` compile group: 'org.bytedeco', name: 'javacpp', version: '1.3.3'`
 `compile group: 'org.bytedeco.javacpp-presets', name: 'opencv' + '-platform', version: '3.2.0' + '-1.3'`
  `compile group: 'org.bytedeco.javacpp-presets', name: 'ffmpeg' + '-platform', version: '3.2.1' + '-1.3'`

can someone please tell me where is the problem ?
Thank you

**Comment by saudet** [comment]
Please try to use FFmpegFrameGrabber instead.

**Comment by iwnfubb** [comment]
Thank you for feedback , 
I used  FFmpegFrameGrabber as you say, but it works not correctly 
`FFmpegFrameGrabber grabber = new FFmpegFrameGrabber("video.mp4");`
`int frameNumber = 0;`
`Frame frame = null;`
                `while ((frame = grabber.grabFrame()) != null) {`
                    `grabber.setFrameNumber(frameNumber++);`
                    `if (frame.imageHeight != 0 && frame.imageWidth != 0) {`
                        `Mat mat = Java2DFrameUtils.toMat(frame);`
                        `mat.copyTo(currentFrame);`
                    `}`
                `}`
some frames are just ignored, is there any problem with my code ?

**Comment by saudet** [comment]
What do you mean by ignored? What happens?

**Comment by iwnfubb** [comment]
i mean some frames return null

**Comment by saudet** [comment]
Null images? Those are probably audio frames...

**Comment by iwnfubb** [comment]
after debugging I got some frame with 
keyframe = false
imageWidth = 0
imageHeight = 0
imageDepth = 0
imageChannels = 0
sampleRate = 0
audioChannels = 0
samples = 0
timestamp  = 0

those are not Null frame, so are they audio frames ?

**Comment by saudet** [comment]
samples == null? It's not an audio frame then. Maybe some other type of
frame that isn't returned properly...

**Comment by saudet** [comment]
Could you provide a sample video file to reproduce this issue? Thanks!

**Comment by iwnfubb** [comment]
hier is the video: https://drive.google.com/open?id=11Qz08i_StotKjm1ia9rvFseOr_EXd_c8. 
Please tell me if you have the same problem or not  👍

**Comment by saudet** [comment]
Thanks! No, it's not happening here. I get 276 frames, all with imageWidth = 1184 and imageHeight = 656. The content looks fine too.
