### ISSUE TITLE
skia .so for iOS 

### ISSUE THREAD

**Issue by radxe** [bytedeco/javacpp-presets#483]
hello, I can't build skia .so for iOS , because of the network reason, who can build skia .so for iOS , thank you very much!

I will use the skia .so for iOS with robovm, thanks in advance!

**Comment by saudet** [comment]
FYI, it was pretty straightforward to get OpenBLAS builds for iOS: https://github.com/bytedeco/javacpp-presets/commit/53e93263a9cafe36af0a7afd872233d3318b7819
Could you give it a try by yourself for Skia? If you encounter any issues, I will help you out!

**Comment by radxe** [comment]
Hello, @saudet , 
    to build skia need to access google related websites, it is blocked, so I can't build it.
    I use robovm (robovm.mobidevelop.com), I need skia for iOS (arm64) ,could you please to build it for me, 
   thank you very much!

**Comment by saudet** [comment]
@nornagon Would you like to give it a try? :)

**Comment by nornagon** [comment]
You definitely don't need any special access to build Skia, see https://skia.org/user/build. Looks like it might be easy to do though, I'll give it a shot.

**Comment by nornagon** [comment]
See #525.

**Comment by saudet** [comment]
Thanks to @nornagon binaries for Skia are now getting deployed here:
https://oss.sonatype.org/content/repositories/snapshots/org/bytedeco/javacpp-presets/skia/20170511-53d6729-1.4.1-SNAPSHOT/
But they are very small. Is this normal @nornagon ?

**Comment by nornagon** [comment]
I measured the iOS .so at 9MB, which is smaller than the OS X binary. I
haven’t tested the iOS binary but it might not include all the static libs

**Comment by saudet** [comment]
Right, so the SKIA library itself doesn't get bundled in the JAR file for some reason. Also, AFAIK, Java doesn't support shared objects on iOS yet. We probably need the static one...

**Comment by saudet** [comment]
I've fixed that in commit https://github.com/bytedeco/javacpp-presets/commit/ea35dc73a104ba8b3414ad08386b91dec580f225 and now we get 70 meg JAR files, wow...

**Comment by saudet** [comment]
I've been able to reduce the size of the binaries by using `extra_cflags=["-g0"]`. Now each archive is around 5 megs in size.

These binaries are now available as part of the release for version 1.4.1: 
http://search.maven.org/#search%7Cga%7C1%7Cskia
Enjoy!
