### ISSUE TITLE
bug, please help me

### ISSUE THREAD

**Issue by bigfanofcpp** [bytedeco/javacpp-presets#489]
Stack: [0x00007000050c3000,0x00007000051c3000],  sp=0x00007000051bdc00,  free space=1003k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [libsystem_c.dylib+0x1432]  strlen+0x12
C  [libtensorflow_cc.so+0x22790fa]  perftools::gputools::internal::DsoLoader::GetDsoHandle(tensorflow::StringPiece, void**, perftools::gputools::internal::DsoLoader::LoadKind)+0x11a
C  [libtensorflow_cc.so+0x2278f4c]  perftools::gputools::internal::DsoLoader::GetCublasDsoHandle(void**)+0xcc
C  [libtensorflow_cc.so+0x227b022]  std::__1::__function::__func<tensorflow::Status (*)(void**), std::__1::allocator<tensorflow::Status (*)(void**)>, tensorflow::Status (void**)>::operator()(void**&&)+0x12
C  [libtensorflow_cc.so+0x227a7cf]  perftools::gputools::internal::CachedDsoLoader::FetchHandleResult(std::__1::function<tensorflow::Status (void**)>)+0x2f
C  [libtensorflow_cc.so+0x227a6af]  perftools::gputools::internal::CachedDsoLoader::GetCublasDsoHandle()+0x6f
C  [libtensorflow_cc.so+0x22053c2]  perftools::gputools::initialize_cublas()+0xf2

====

    <dependencies>
        <dependency>
            <groupId>org.bytedeco.javacpp-presets</groupId>
            <artifactId>tensorflow-platform</artifactId>
            <version>1.0.1-1.3</version>
        </dependency>
    </dependencies>

====

public class Example {
    public static void main(String[] args) throws Exception {
        final Session session = new Session(new SessionOptions());
        GraphDef def = new GraphDef();
        tensorflow.ReadBinaryProto(Env.Default(),
                "somedir/trained_model.proto", def);
        Status s = session.Create(def);
        if (!s.ok()) {
            throw new RuntimeException(s.error_message().getString());
        }
    }
}

====

OS is mac 10.13.1

**Comment by bigfanofcpp** [comment]
OS: mac 10.13.1

**Comment by saudet** [comment]
That's a known issue with TensorFlow on Mac. The workaround is here: https://github.com/bytedeco/javacpp-presets/issues/396#issuecomment-289182416

Or you can try the latest SNAPSHOT version...
