### ISSUE TITLE
1.4.0-1.3.4-SNAPSHOT not found, please help me

### ISSUE THREAD

**Issue by bigfanofcpp** [bytedeco/javacpp-presets#490]
<dependencies>
    <dependency>
        <groupId>org.bytedeco.javacpp-presets</groupId>
        <artifactId>tensorflow-platform</artifactId>
        <version>1.4.0-1.3.4-SNAPSHOT</version>
    </dependency>
</dependencies>

It is error version and not found, please help me

**Comment by bigfanofcpp** [comment]
<dependencies>
        <dependency>
            <groupId>org.bytedeco.javacpp-presets</groupId>
            <artifactId>tensorflow-platform</artifactId>
            <version>1.4.0-1.3.4-SNAPSHOT</version>
        </dependency>
    </dependencies>

**Comment by saudet** [comment]
Make sure to follow the instructions here: http://bytedeco.org/builds/
