### ISSUE TITLE
1.4.0-1.3.4-SNAPSHOT problem

### ISSUE THREAD

**Issue by bigfanofcpp** [bytedeco/javacpp-presets#491]
offical example src/main/java/ExampleTrainer.java

...
Output a = Const(root, Tensor.create(new float[] {3.f, 2.f, -1.f, 0.f}, new TensorShape(2, 2)));
...

compile error

====

    @Namespace("tensorflow")
    public static class TensorShape extends tensorflow.TensorShapeBase {
        public TensorShape() {
            super((Pointer)null);
            this.allocate();
        }

        public TensorShape(long size) {
            super((Pointer)null);
            this.allocateArray(size);
        }

        public TensorShape(Pointer p) {
            super(p);
        }

**Comment by saudet** [comment]
It looks like we need to use TensorShapeBase these days. Please try with that.

**Comment by bigfanofcpp** [comment]
or InsertDim ??

**Comment by saudet** [comment]
Yes, those functions still seem to work too!

**Comment by saudet** [comment]
It looks like we need to inherit the constructors:
> ```cpp
> class TensorShape : public TensorShapeBase<TensorShape> {
>  public:
>   using TensorShapeBase<TensorShape>::TensorShapeBase;
> ```

**Comment by saudet** [comment]
I've fixed that in the commit above. Thanks for reporting!

**Comment by saudet** [comment]
I've made a release that includes the fix:
http://repo1.maven.org/maven2/org/bytedeco/javacpp-presets/tensorflow/1.4.0-1.3/
http://repo1.maven.org/maven2/org/bytedeco/javacpp-presets/tensorflow-platform/1.4.0-1.3/
Thanks for reporting!
