### ISSUE TITLE
How load checkpoint(.ckpt) file

### ISSUE THREAD

**Issue by bigfanofcpp** [bytedeco/javacpp-presets#494]
How load checkpint(.ckpt) file by javacpp-presets(tensorflow)?

thanks.

**Comment by saudet** [comment]
We can do it from C++ this way apparently: https://stackoverflow.com/a/43639305/523744

This requires the definition of `MetaGraphDef` and `SaverDef`, so I've included those files in the commit above. If you're having problems using them, please let me know!

**Comment by saudet** [comment]
I've made a release that includes the additions:
http://repo1.maven.org/maven2/org/bytedeco/javacpp-presets/tensorflow/1.4.0-1.3/
http://repo1.maven.org/maven2/org/bytedeco/javacpp-presets/tensorflow-platform/1.4.0-1.3/
Thanks for your interest!

**Comment by saudet** [comment]
There appears to be a better interface for that these days in `checkpoint_reader.h` so I've also included it in the latest commit above. Enjoy!
