### ISSUE TITLE
Can we get jar built by Travis CI ?

### ISSUE THREAD

**Issue by n-kai-cj** [bytedeco/javacpp-presets#497]
I'd like a new snapshot of javacpp presets.
But I don't have a build environment for all platforms, so I have no choice but to wait a new release.

By the way, Travis CI seems to build for all platforms.
Then my question is wether we can get jar files built by Travis CI? or do you know any other ways to get jar files for all platforms?

**Comment by saudet** [comment]
Yes, of course, details here: http://bytedeco.org/builds/

If you're not using Maven, we can still browse the files here:
https://oss.sonatype.org/content/repositories/snapshots/org/bytedeco/javacpp-presets/

**Comment by n-kai-cj** [comment]
Great! Thank you.
Can we refer that repository on top page of javacpp presets?

**Comment by saudet** [comment]
What about a link to http://bytedeco.org/builds/ ?

**Comment by n-kai-cj** [comment]
It's also ok.
Or, I'd appreciate it if you would add the link to `README.md`

**Comment by saudet** [comment]
I've added a new "nexus" badge that links to that page here:
https://github.com/bytedeco/javacpp-presets#javacpp-presets
Looks good? Thanks for the feedback!

**Comment by n-kai-cj** [comment]
Yes! That's great, really thank you!
