### ISSUE TITLE
Large Jar File Size

### ISSUE THREAD

**Issue by zchacker** [bytedeco/javacpp-presets#500]
Hi , i have an desktop application that use ffmpeg via javacpp i make this for video conference for education purposes and everything is fine now .
i use java web start , so i try to make it small size file to start fast. 

what i did is re-build it via cppbuild.sh and enabled H264 & AAC codecs 
using this configuration.

DISABLE="--disable-iconv --disable-libxcb --disable-opencl --disable-sdl2 --disable-bzlib --disable-lzma --disable-linux-perf --disable-everything"

ENABLE="--enable-shared --enable-gpl --enable-runtime-cpudetect --enable-libx264 --enable-encoder=libx264 --enable-encoder=aac --enable-decoder=h264 --enable-decoder=aac --enable-parser=h264 --enable-parser=aac --enable-muxer=mp4 --enable-muxer=flv --enable-demuxer=mov --enable-demuxer=flv --enable-protocol=rtmp"

the generated JAR files is about 3.5MB , i tried to use upx to compress .dll files but it's not working fine and cause error !

can you suggest to me a good solutions if i can reduce size to 2-1MB because the whole room will be more than 6MB and this is not well

**Comment by saudet** [comment]
What is the error message?

**Comment by saudet** [comment]
In any case, BigBlueButton maintains such builds in their own fork. I think this is the latest branch:
https://github.com/bigbluebutton/javacpp-presets/tree/min-build-1.2-svc2
Please try to use that. That would be my recommendation.

@ritzalam If we could merge this somehow with the main repository it would be great!

**Comment by ritzalam** [comment]
I'd love to. But we're way behind the current version of javacpp-presets. When we get to upgrade to the latest I will send a PR.
