### ISSUE TITLE
Build for windows-x86 not working

### ISSUE THREAD

**Issue by zchacker** [bytedeco/javacpp-presets#503]
Hi, i try to build ffmpeg for windows 32 bit 
when run this command in mingw32 console and work fine, this is command 
bash cppbuild.sh -platform windows-x86 install ffmpeg 

but when i run this command : 
mvn install -Djavacpp.platform=windows-x86 -Djavacpp.cppbuild.skip=true --projects ffmpeg

it's stop and give me this error : 

```
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/6.2.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot find -lpostproc
collect2.exe: error: ld returned 1 exit status
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 34.777 s
[INFO] Finished at: 2018-01-01T01:37:22+03:00
[INFO] Final Memory: 38M/837M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.bytedeco:javacpp:1.3.4-SNAPSHOT:build (javacpp.compiler) on project ffmpeg: Execution javacpp.compiler of goal org.bytedeco:javacpp:1.3.4-SNAPSHOT:build failed: Process exited with an error: 1 -> [Help 1]


what the problem i have and how to solve it
```

**Comment by saudet** [comment]
It's just saying it can't find the postproc library. You can remove
everything related to it if you don't need it.

**Comment by zchacker** [comment]
how to remove it from my project ?

**Comment by saudet** [comment]
With a text editor ... ? What's the issue?

**Comment by zchacker** [comment]
i mean which file should i edit it to remove postproc library.

**Comment by saudet** [comment]
Files that have the word "postproc" in it:
https://github.com/bytedeco/javacpp-presets/search?utf8=%E2%9C%93&q=postproc&type=
