### ISSUE TITLE
javacpp-presets(tensorflow 1.4.0) tensorflow.SetDefaultDevice not working

### ISSUE THREAD

**Issue by andyguo007** [bytedeco/javacpp-presets#504]
Hi,

Thanks for releasing tensorflow to 1.4.0 in the maven repository. I have two Titan X GPUs. With 1.4.0, tensorflow.SetDefaultDevice("/gpu:1") or tensorflow.SetDefaultDevice("/device:GPU:1") doesn't seem to work. It is always using /gpu:0. While with tensorflow 1.0.1, there is no such problem. Wondering if there is something wrong with the new release. Thanks.

**Comment by saudet** [comment]
TensorFlow added dependencies on the CUDA libraries somewhere around 1.2.0, so I will be releasing separate binaries for GPU. For now, as per https://github.com/bytedeco/javacpp-presets/issues/396#issuecomment-352980020, SNAPSHOT artifacts are available though:
```xml
        <dependency>
            <groupId>org.bytedeco.javacpp-presets</groupId>
            <artifactId>tensorflow</artifactId>
            <version>1.4.0-1.3.4-SNAPSHOT</version>
            <classifier>linux-x86_64-gpu</classifier>
        </dependency>
```

**Comment by andyguo007** [comment]
Thanks a lot for the quick response! I am using gradle to pull the binaries from maven repository. Did you release all the related binaries to maven repository? When I am doing this "compile group: 'org.bytedeco.javacpp-presets', name: 'tensorflow', version: '1.4.0-1.3.4-SNAPSHOT', classifier: 'linux-x86_64-gpu'" in gradle, it gives me the following error:

Could not find tensorflow-linux-x86_64-gpu.jar (org.bytedeco.javacpp-presets:tensorflow:1.4.0-1.3).
  Searched in the following locations:
      https://repo1.maven.org/maven2/org/bytedeco/javacpp-presets/tensorflow/1.4.0-1.3/tensorflow-1.4.0-1.3-linux-x86_64-gpu.jar

Thanks!

**Comment by saudet** [comment]
No, it's not released.

**Comment by saudet** [comment]
Looks like binaries for 1.4.0 have already been erased by the SNAPSHOT repo though, but they are available for 1.4.1:
https://oss.sonatype.org/content/repositories/snapshots/org/bytedeco/javacpp-presets/tensorflow/1.4.1-1.3.4-SNAPSHOT/

**Comment by andyguo007** [comment]
Thanks.  There is no platform specific binaries in https://oss.sonatype.org/content/repositories/snapshots/org/bytedeco/javacpp-presets/tensorflow-platform/1.4.1-1.3.4-SNAPSHOT/, causing the following error:

Could not find tensorflow-android-arm.jar (org.bytedeco.javacpp-presets:tensorflow:1.4.1-1.3.4-SNAPSHOT).
  Searched in the following locations:
      https://oss.sonatype.org/content/repositories/snapshots/org/bytedeco/javacpp-presets/tensorflow/1.4.1-1.3.4-SNAPSHOT/tensorflow-1.4.1-1.3.4-20180102.094002-69-android-arm.jar

**Comment by saudet** [comment]
Just exclude it from your build.

**Comment by andyguo007** [comment]
@saudet are you building tensorflow with libcublas.so.9.0 instead of libcublas.so.8.0?

There is an error when I am trying to use it:

Caused by: java.lang.UnsatisfiedLinkError: /linux-x86_64-gpu/libjnitensorflow.so: libcublas.so.9.0: cannot open shared object file: No such file or directory

Thanks.

**Comment by saudet** [comment]
Yes, install CUDA 9.0.

**Comment by saudet** [comment]
And the newly released artifacts for 1.5.0-rc1 need CUDA 9.1:
http://search.maven.org/#search%7Cga%7C1%7Cbytedeco%20tensorflow
Enjoy!

**Comment by andyguo007** [comment]
Thanks. Do you have the timeline on the official release of 1.5.0?

**Comment by saudet** [comment]
Please ask upstream!

**Comment by saudet** [comment]
And 1.5.0 has been released:
http://repo2.maven.org/maven2/org/bytedeco/javacpp-presets/tensorflow/1.5.0-1.4/
Enjoy!

**Comment by andyguo007** [comment]
That's great. Thanks.
