### ISSUE TITLE
Is it possible to add Axpy layer to caffe

### ISSUE THREAD

**Issue by gunther82** [bytedeco/javacpp-presets#507]
I'm testing the latest caffe implementation included in the presets 1.4 with a network that contains an Axpy layer and I get the error message
`Unknown layer type: Axpy`

It seems that it is a layer normally not included in caffe. Is it possible to add this layer to the caffe implementation of Javacv, as suggested [here](https://github.com/hujie-frank/SENet/issues/35)?
This would be very appreciated, thanks!

**Comment by saudet** [comment]
Yes, of course. Please send a pull request with that patch applied as part
of the cppbuild.sh script.

**Comment by gunther82** [comment]
Sorry, I was unclear also in this case. I was asking if you could please add this layer to caffe.
I tried several times to compile opecv, openblas and caffe on my Mac, but I was always unsuccessful.  
I know it is a lot to ask, but I couldn't do it with my current programming environment.

**Comment by saudet** [comment]
You don't need to build it yourself. If you send a PR, Travis CI will automatically create new builds for you.

**Comment by saudet** [comment]
Included in the release for version 1.4.1! Thanks for the contribution.
