### ISSUE TITLE
FFmpegFrameGrabber.start() fails

### ISSUE THREAD

**Issue by Inumanoj** [bytedeco/javacpp-presets#51]
For some reason, my program crashes when FrameGrabber.start() is invoked.

I'm not sure what I'm doing wrong, I'm new android programming. I've searched for similar cases. Haven't found one posted on the web yet which is similar to mine.

Any help would be greatly appreciated.

This is the code I've implemented.

        @Override
	protected void onCreate(Bundle savedInstanceState) {
		// TODO Auto-generated method stub
		super.onCreate(savedInstanceState);
		setContentView(R.layout.activity_ffile);
		//VideoView display = (VideoView)findViewById(R.id.videoView1);
		
		Intent intent = getIntent();
		FilePath = intent.getStringExtra("path");
	    //display.setVideoPath(FilePath);
		FFmpegFrameGrabber vidcap = new FFmpegFrameGrabber(FilePath);
		Log.i(camera.TAG, "inited");
		
		try {
			vidcap.start();
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

Once start() is invoked, exception is raised during runtime and the app crashes. The library:
* I extracted all the .so files from ffmpeg-arm-android.jar and opencv-arm-android.jar into libs/armeabi. 
* Copied javacv and javacpp into libs/ 

05-07 10:50:52.045: E/AndroidRuntime(31417): FATAL EXCEPTION: main
05-07 10:50:52.045: E/AndroidRuntime(31417): Process: test.trackerproto, PID: 31417
05-07 10:50:52.045: E/AndroidRuntime(31417): java.lang.NoClassDefFoundError: org.bytedeco.javacpp.avcodec
05-07 10:50:52.045: E/AndroidRuntime(31417): 	at org.bytedeco.javacv.FFmpegFrameGrabber.start(FFmpegFrameGrabber.java:340)
05-07 10:50:52.045: E/AndroidRuntime(31417): 	at test.trackerproto.Saved_process.onCreate(Saved_process.java:31)
05-07 10:50:52.045: E/AndroidRuntime(31417): 	at android.app.Activity.performCreate(Activity.java:5248)
05-07 10:50:52.045: E/AndroidRuntime(31417): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1110)
05-07 10:50:52.045: E/AndroidRuntime(31417): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2162)
05-07 10:50:52.045: E/AndroidRuntime(31417): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2257)
05-07 10:50:52.045: E/AndroidRuntime(31417): 	at android.app.ActivityThread.access$800(ActivityThread.java:139)
05-07 10:50:52.045: E/AndroidRuntime(31417): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1210)
05-07 10:50:52.045: E/AndroidRuntime(31417): 	at android.os.Handler.dispatchMessage(Handler.java:102)
05-07 10:50:52.045: E/AndroidRuntime(31417): 	at android.os.Looper.loop(Looper.java:136)
05-07 10:50:52.045: E/AndroidRuntime(31417): 	at android.app.ActivityThread.main(ActivityThread.java:5086)
05-07 10:50:52.045: E/AndroidRuntime(31417): 	at java.lang.reflect.Method.invokeNative(Native Method)
05-07 10:50:52.045: E/AndroidRuntime(31417): 	at java.lang.reflect.Method.invoke(Method.java:515)
05-07 10:50:52.045: E/AndroidRuntime(31417): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
05-07 10:50:52.045: E/AndroidRuntime(31417): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
05-07 10:50:52.045: E/AndroidRuntime(31417): 	at dalvik.system.NativeStart.main(Native Method)

I tried executing through libraries installed by maven and I get a exception at initialization of  FFmpegFrameGrabber. This is the logcat for MAVEN LIBS

05-07 11:14:29.690: E/AndroidRuntime(4112): FATAL EXCEPTION: main
05-07 11:14:29.690: E/AndroidRuntime(4112): Process: test.trackerproto, PID: 4112
05-07 11:14:29.690: E/AndroidRuntime(4112): java.lang.NoClassDefFoundError: org.bytedeco.javacv.FFmpegFrameGrabber
05-07 11:14:29.690: E/AndroidRuntime(4112): 	at test.trackerproto.Saved_process.onCreate(Saved_process.java:28)
05-07 11:14:29.690: E/AndroidRuntime(4112): 	at android.app.Activity.performCreate(Activity.java:5248)
05-07 11:14:29.690: E/AndroidRuntime(4112): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1110)
05-07 11:14:29.690: E/AndroidRuntime(4112): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2162)
05-07 11:14:29.690: E/AndroidRuntime(4112): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2257)
05-07 11:14:29.690: E/AndroidRuntime(4112): 	at android.app.ActivityThread.access$800(ActivityThread.java:139)
05-07 11:14:29.690: E/AndroidRuntime(4112): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1210)

I use eclipse kepler, win 8.1, javacv 0.11 and maven complier plugin 3.1

I am not sure what I did wrong! I am new at this, if I missed out on any information or presented things in wrong format, please forgive me and let me know, so that I learn. Thanks in advance for the help!

**Comment by saudet** [comment]
Have you also copied `opencv.jar` and `ffmpeg.jar` in the `libs` directory? If not, that would be the cause of the issue.

**Comment by Inumanoj** [comment]
I feel like such an idiot! Thanks a lot Sam!!!!
