### ISSUE TITLE
Deallocation of heap-pointers vs Java Garbage Collection

### ISSUE THREAD

**Issue by beligum** [bytedeco/javacpp-presets#512]
Hi Samuel,

A quick question, but maybe interesting for others too, so I'm making it an issue:
Is there any relationship between a newly allocated c++ object in Java, say eg. `BytePointer outputPointer = new BytePointer(1024);` which - if i'm not mistaken - allocates a 1K buffer in C and the garbage collection system in Java?

I assume the newly allocated object is the responsibility of the coder and should be deallocated (or auto-closed) somewhere later explicitly, like any other C malloc (let's ignore shared pointers for the sake of this example). But since this (Java-) object will also influence the Java GC somehow, I'm wondering how the JavaCPP library is written and if the GC can interfere with this somehow?

Just being curious...

b.

**Comment by saudet** [comment]
>        // Pointer objects allocated in Java get deallocated once they become unreachable,
>        // but C++ destructors can still be called in a timely fashion with Pointer.deallocate()

- https://github.com/bytedeco/javacpp/

Does that answer your question?

**Comment by beligum** [comment]
Yes, it does, more or less. Could you roughly point me to the relevant piece of code in the library where this is implemented?
I'm interested in the matter for debug reasons, we're having major memory leaks in a webserver and I'd like to exclude it coming from JavaCPP (or at least be able to breakpoint it).

**Comment by saudet** [comment]
It's all in the Pointer class. We can set a logger or set
org.bytedeco.javacpp.logger.debug=true to get debug messages:
http://bytedeco.org/javacpp/apidocs/org/bytedeco/javacpp/tools/Logger.html

**Comment by beligum** [comment]
Awesome, thanks Samuel.

**Comment by saudet** [comment]
Have you figured out what the issue was?

**Comment by beligum** [comment]
Not yet. I've put it back on my agenda to revise the entire memory model as I'm still integrating other pieces of the puzzle in our project. I figured it's better to dig into the memory leak when everything is more or less stable...
