### ISSUE TITLE
Upgraded to 1.4 and Caffe said it is in CPU only mode

### ISSUE THREAD

**Issue by bdmccord** [bytedeco/javacpp-presets#518]
After upgrading all of my dependencies to 1.4 I am now getting an error that seems to indicate that caffe was compiled in CPU only mode. I get the following error:

`Cannot use GPU in CPU-only Caffe: check mode.`

Upon reviewing the issues here I found a comment which led me to try adding a classifier value to the caffe dependency as below:

`<classifier>linux-x86_64-gpu</classifier>`

This originally changed nothing, until I upgraded my system to cuda 9.1.  However it seems to have fixed it when I have cuda-9.1 installed.  In short, it seems like something has changed in the build process such that caffe now defaults to using cpu-only mode binaries.  Should this be more explicit in the documentation?

**Comment by saudet** [comment]
It's documented at http://bytedeco.org/news/2018/01/17/java-for-systems/
but I guess we should update the README.md files of OpenCV, Caffe, and
TensorFlow, yes.

**Comment by bdmccord** [comment]
Yes I guess that does explain the behavior I experienced pretty well.  Personally, I didn't even to think to look there, but I did read the entire README.  Thanks!

**Comment by saudet** [comment]
Done! Thanks for the feedback
