### ISSUE TITLE
opencv_cuda... libraries missing in binary archive

### ISSUE THREAD

**Issue by daKenpachi** [bytedeco/javacpp-presets#519]
Hi,

I´m using the opencv module of javacpp.presets 1.4. I did the manual installation without any problems with eclipse on windows x86-64 and already have some image processing running (canny and hough lines).
Now I wanted to try the cuda-equivalent of these algorithmes, but the opencv-windows-x86_64.jar is missing some dlls for that:
`
Exception in thread "Thread-1" java.lang.UnsatisfiedLinkError: no jniopencv_cudaarithm in java.library.path
...
Caused by: java.lang.UnsatisfiedLinkError: no opencv_cudaarithm340 in java.library.path
...
`

I noticed that none of the other platform jars contain these libs, so it would be great if you could deliver that in near future =)

**Comment by saudet** [comment]
Duplicate of issue #518.

Check the updated README.md file for instructions!
