### ISSUE TITLE
liquidfun Preset doesn't work on Windows x64

### ISSUE THREAD

**Issue by soylomass** [bytedeco/javacpp-presets#524]
I've set up a gradle project with liquidfun javacpp preset, and when I run it the following exception appears:

> Exception in thread "main" java.lang.UnsatisfiedLinkError: Platform "windows-x86_64" not supported by class org.bytedeco.javacpp.liquidfun
	at org.bytedeco.javacpp.Loader.load(Loader.java:891)
	at org.bytedeco.javacpp.Loader.load(Loader.java:854)
	at org.bytedeco.javacpp.liquidfun.<clinit>(liquidfun.java:10)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at org.bytedeco.javacpp.Loader.load(Loader.java:913)
	at org.bytedeco.javacpp.Loader.load(Loader.java:854)

What could be the problem?

**Comment by saudet** [comment]
> Platform "windows-x86_64" not supported

Contributions are welcome!

**Comment by saudet** [comment]
If you would like to contribute a build for Windows, but are encountering any issues doing it, please let me know, and I will help! Thanks

**Comment by saudet** [comment]
@floybix Would you like to give it a try? :)

**Comment by floybix** [comment]
Don't have Windows myself I'm afraid.

**Comment by saudet** [comment]
No need to, we can leave AppVeyor do the builds for us if you send a PR. :)

**Comment by saudet** [comment]
@nornagon What about you, would you like to give it a try?

**Comment by saudet** [comment]
Marking as duplicate of #536
