### ISSUE TITLE
Google cpu_features for the "Systems" preset

### ISSUE THREAD

**Issue by Neiko2002** [bytedeco/javacpp-presets#526]
It might be useful to get https://github.com/google/cpu_features into the "Systems" preset, to check for  AVX and other capabilities. This is not a feature request or bug report, but rather an information ticket about the new small library from Google https://opensource.googleblog.com/2018/02/cpu-features-library.html

with best regards
Neiko

**Comment by saudet** [comment]
Done! Including build for linux-ppc64le. Please give it a try with the snapshots: http://bytedeco.org/builds/

**Comment by saudet** [comment]
Now included in version 1.5. Enjoy!
