### ISSUE TITLE
java.lang.NoClassDefFoundError: Could not initialize class org.bytedeco.javacpp.avutil 

### ISSUE THREAD

**Issue by Krupiceva** [bytedeco/javacpp-presets#527]
I get this error when I try to grab first frame from video. Below is my simplified code sample that i try to use.
```java
        private void handleExport() {
                FFmpegFrameGrabber g = new FFmpegFrameGrabber(aviLocation.getText());
                try {
                        g.start();
                        Frame frame = g.grab();
                        Java2DFrameConverter cnvrt = new Java2DFrameConverter();
                        BufferedImage bImage = cnvrt.convert(frame);
                        String path = exportLocation.getText() + "\\img" + ".jpg";
                        File file = new File(path);
                        ImageIO.write(bImage, "jpg", file);
                } catch (Exception e) {
                        e.printStackTrace();
                }
        }
```

Please be aware that I'm beginner, i try to read all other threads with this question but can not find solutions. 
I don't use maven, I manually add javacv.jar, javacpp.jar i ffmpeg.jar from javacv-platform-1.4-bin.zip to my project and than add them to build path in eclipse. 
Do I have to add some other jars maybe?

I'm using it on Windows 10 with eclipse and JavaFX.

**Comment by saudet** [comment]
You'll need to add ALL the JAR files, not just three of them.
