### ISSUE TITLE
[FFMPEG] decode DATA STREAM

### ISSUE THREAD

**Issue by Tatsukyo** [bytedeco/javacpp-presets#532]
Hi @saudet 

I have a video with 3 streams this:

> Program 1 
>     Stream #0:0[0x7d0]: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p(top first), 1920x1080 [SAR 1:1 DAR 16:9], 30 fps, 60 tbr, 90k tbn, 60 tbc
>     Stream #0:1[0x7d1]: Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp, 90 kb/s
>     Stream #0:2[0x7d2]: Data: klv (KLVA / 0x41564C4B)

Can we decode data stream? if yes how? 

I can decode Video / audio Streams but i can't with the data Stream

Currently what i'm doing is : 

I check if the video contains data Stream

```
if (pFormatCtx.streams(i).codecpar().codec_type() == AVMEDIA_TYPE_DATA && dataStream < 0)
{
	dataStream = i;
}
```

if it contains i try to find context and codec:

```
avcodec_parameters_to_context(pCodecCtxData, pFormatCtx.streams(dataStream).codecpar());	
// Find the decoder for the data stream
System.out.println(pCodecCtxData.codec_id());
pCodecData = avcodec_find_decoder(pCodecCtxData.codec_id());	if (pCodecData == null)
{
	System.err.println("Unsupported codec!");
	System.exit(-1); // Codec not found
}

// Open data codec
if (avcodec_open2(pCodecCtxData, pCodecData, (PointerPointer) null) < 0)
{
	System.exit(-1); // Could not open codec 
}
```

and finally in the while(av_read_frame)
i use this to decode:

avcodec_send_packet(pCodecCtxData, packet);

```
if (avcodec_receive_frame(pCodecCtxData, pDataFrame) >= 0)
{
	frameFinished[0] = 1;
}
if (frameFinished[0] != 0)
{
     //some lines
}
```

Does this seem good to you?

Currently i don't find codec (codec_id = 100356 from pCodecCtxData.codec_id())

So i just want to know if it's me or if we can't decode data Stream

**Comment by Hockenberry** [comment]
You need to write your own code to decode the data in a KLVA data packet. See for some directions [here](https://stackoverflow.com/questions/25701034/does-ffmpeg-supported-klv-metadata#29461404).

**Comment by saudet** [comment]
We can update FFmpegFrameGrabber to return raw packets like you did, but
we'll probably need something else to decode them, yes...

**Comment by Tatsukyo** [comment]
but like i did 

in the 
```
if (avcodec_receive_frame(pCodecCtxData, pDataFrame) >= 0)
{
	frameFinished[0] = 1;
}
if (frameFinished[0] != 0)
{
     //some lines
}
```

especially in the 
```
if (frameFinished[0] != 0)
{
     //some lines
}
```

pDataFrame.data() contains nothing i mean, a buffer of x size and each object of this buffer equals 0 

So without data i can't decode them 


I tried the extended_data but nothing too

**Comment by saudet** [comment]
`capacity == 0` just means the size is unknown. The data is still there.

**Comment by Tatsukyo** [comment]
Because we have no codec to decode KLV data,


I just want to know one thing, where is the data in the Packet?

in the data function? 
Always return the same value, 6

**Comment by saudet** [comment]
Should be the same as video and audio packets...

**Comment by Tatsukyo** [comment]
Just got brained by the packet.data().get() ...

get() return get(0)

was unexpected
