### ISSUE TITLE
use CPUs or multiple GPUs for tensorflow linux-x86_64-gpu 1.5

### ISSUE THREAD

**Issue by andyguo007** [bytedeco/javacpp-presets#533]
Hi,

I am using gpu version of tensorflow 1.5 (linux-x86_64-gpu). And I have two Titan X GPUs. Here are some thing I found confusing when running tensorflow:

use:
tensorflow.GraphDef def = new tensorflow.GraphDef();
tensorflow.SetDefaultDevice(device, def);

when "device" is "/cpu:0" or "/cpu:1" or ... etc., I found that GPU:0 is being used.

1) Does it mean that when using the gpu version, a gpu would definitely be used even when no gpu is appointed (when only cpus are appointed)?

2) If I have multiple sessions using "cpu:0" and "cpu:1" ... etc., are these sessions sharing one GPU in this case?

3) If there are ONLY two sessions appointed with "gpu:0" and "gpu:1" individually, are these two sessions running solely on it's own appointed GPU? 

Thanks a lot,
Andy

**Comment by saudet** [comment]
According to the documentation, that sounds like what it should be doing, yes:
> You will see that now a and b are assigned to cpu:0. Since a device was not explicitly specified for the MatMul operation, the TensorFlow runtime will choose one based on the operation and available devices (gpu:0 in this example) and automatically copy tensors between devices if required.

https://www.tensorflow.org/programmers_guide/using_gpu

It sounds like it will respect the GPU we specify, though:
> If you have more than one GPU in your system, the GPU with the lowest ID will be selected by default. If you would like to run on a different GPU, you will need to specify the preference explicitly:

**Comment by saudet** [comment]
It looks like if we set the "device count" to 0, it will in effect ignore any GPUs:
https://medium.com/@lisulimowicz/tensorflow-cpus-and-gpus-configuration-9c223436d4ef
However, the field isn't currently being mapped by the presets...

**Comment by saudet** [comment]
Also, `SetDefaultDevice()` will only work if the device has not already been set on the nodes of the graph. We can clear these settings as with the "--clear_devices" option of this script:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/tools/freeze_graph.py

**Comment by saudet** [comment]
Ok, now we should be able to do something like the following to disable the GPU:
```java
        ConfigProto configProto = new ConfigProto();
        configProto.mutable_device_count().put(new BytePointer("GPU"), 0);
        SessionOptions options = new SessionOptions();
        options.config(configProto);
        Session sess = new Session(options);
        Status s = sess.Create(def);
        ...
```
