### ISSUE TITLE
Error in MatVector  put method

### ISSUE THREAD

**Issue by sara-khayyat** [bytedeco/javacpp-presets#534]
<img width="910" alt="error" src="https://user-images.githubusercontent.com/34396091/36923646-fb8cbaf6-1e7c-11e8-8e78-faa79347bbdd.png">

**When i try to use EigenFaceRecognizer , I declare a variable of MatVector datatype and I use the put() method to add a Mat variable to it, and I face this error.**

How I can fix this problem?
Here I declare the MatVector variable
<img width="561" alt="- -" src="https://user-images.githubusercontent.com/34396091/36923375-3430e3d8-1e7c-11e8-86a6-f92e62764a71.png">

here is the error line 
<img width="399" alt="errorline" src="https://user-images.githubusercontent.com/34396091/36923710-2f596d52-1e7d-11e8-99b0-34c737e0682b.png">

**Comment by saudet** [comment]
Maybe what you want to call is push_back()?
