### ISSUE TITLE
Question about using in android

### ISSUE THREAD

**Issue by Hosseinyzr** [bytedeco/javacpp-presets#535]
Hi , Thank u for your Presets. I Have questions about it...
I have .so libraries of ffmpeg(libavcodec.so , libavfilter.so,libavformat.so,libavutil.so,libpostproc.so,libswresample.so,libswscale.so,libx264.so,libx264.so.155).
now I want to use ffmpeg in android project (with android studio).
1-would you please help me and tell how to do?
I think I should Use your wrappers and these so files an use wrappers to execute commands.am i right?
2-is there any way to do things in command formats?
Thnak You.

**Comment by saudet** [comment]
Please take a look at https://github.com/bytedeco/sample-projects

If you have questions remaining after that, let me know.
