### ISSUE TITLE
[FFmpeg] Custom IO Context

### ISSUE THREAD

**Issue by Tatsukyo** [bytedeco/javacpp-presets#537]
Hi,

i face an issue,
Currently i have a runnable class which create IO Context, init everything and read the video.

so i can create a bunch of thread which will read each a video with his own IO Context

but the problem is it doesnt work.

With just one thread it works, but with at least 2 threads a deadlock appear 

so i tried to debug this and i may have found the issue but i'm not sure (currently i have a solution but I would like to use an other way ...)

it's look like when i create at least 2 threads 

`mReadCallback = new ReadCallback(mSrcChannel);`
```
mAvioContext = avio_alloc_context(
new BytePointer(av_malloc(4096)),
4096,
0,
null,
mReadCallback,
null,
null);
```

both of them is instanced, both of them have an address but 

it's look like the ReadCallBack is the same in both thread,

used a
`printf("readCallBack =%s,this)`
and their address is the same

is it normally or it's me who fail somewhere

**Comment by saudet** [comment]
Yes, that's a limitation of JavaCPP. Just use the same callback for all the
threads.

**Comment by saudet** [comment]
There are examples of that in FFmpegFrameGrabber and FFmpegFrameRecorder:
https://github.com/bytedeco/javacv/blob/master/src/main/java/org/bytedeco/javacv/FFmpegFrameGrabber.java#L250
https://github.com/bytedeco/javacv/blob/master/src/main/java/org/bytedeco/javacv/FFmpegFrameRecorder.java#L291
