### ISSUE TITLE
Can't translate ffmpeg command into javacv

### ISSUE THREAD

**Issue by fcinfo** [bytedeco/javacpp-presets#538]
I can run under command successfuly:
ffmpeg -hwaccel qsv -c:v h264_qsv -rtsp_transport tcp -i rtsp://admin:12345@192.168.6.201 -f flv -vcodec h264_qsv rtmp://193.169.100.222/live/stream1

what to do translate it into javacv ?

**Comment by saudet** [comment]
If you're facing any issues in particular, please also provide the error message you get! Thanks

**Comment by fcinfo** [comment]
I'm sorry. I can use FfmpegFrameRecorder.setVideoCodecName(“h264_qsv”) to specify encoder,
I don't know how to set accelerators and decoders for FfmpegFrameGrabber，I use
 grabber.setOption(“hwaccel”，“qsv”)；
grabber.setOption(“c:v”，“h264_qsv”)；
but I didn't find the accelerator and decoder used in decoding.

**Comment by saudet** [comment]
We will need to add calls to `avcodec_find_decoder_by_name()` along those to `avcodec_find_decoder()` in `FFmpegFrameGrabber`, and also add similar fields as with `FrameRecorder` but to `FrameGrabber` to be able to specify the names of the codecs.

Please let me know if you are having issues making the modifications and I will help! Thanks

**Comment by fcinfo** [comment]
It's great.Thanks！
Are there any plans to release the next release?

**Comment by saudet** [comment]
Are you having any issues making the modifications yourself?

**Comment by fcinfo** [comment]
The instance of AVCodec can be find by the method AvCodec.avcodec_find_decoder_by_name()，but I don't know how to use this instance,the method grabber.setVideoCodec only need int.

**Comment by saudet** [comment]
Right, so we need to add `setVideoCodecName()` and `setAudioCodecName()` for that.

**Comment by fcinfo** [comment]
After I modified the code, the decoder can work well, But the encoder(h264_qsv) cannot work:
[h264_qsv @ 0000000044b225e0] More than one of: { constant qscale, lookahead, VCM } requested, only one of them can be used at a time.
I don't know how to set the three parameters above?

**Comment by saudet** [comment]
Me neither, someone will need to read documentation, study the code, ask the developers of FFmpeg, etc...

**Comment by fcinfo** [comment]
grabber.setPixelFormat(avutil.AV_PIX_FMT_YUV420P);
All the colors of video are lost, It's only going to be avutil.AV_PIX_FMT_BGR24.
why?

**Comment by saudet** [comment]
You'll needto use something that supports that pixel format for display to see the colors.

**Comment by fcinfo** [comment]
Hi:
    I have modified some code to realize the required functions, but the modified code is limited to FFmpeg part, and I am not sure whether it is in accordance with your logic, so I have emailed you the revised code, please check it.
    Thanks.

**Comment by saudet** [comment]
That's great! Could please send a pull request instead? Thank you!
https://github.com/bytedeco/javacv/pulls

**Comment by saudet** [comment]
Thanks for pull https://github.com/bytedeco/javacv/pull/948!

**Comment by saudet** [comment]
BTW, if the `ffmpeg` program is sufficient, with commit https://github.com/bytedeco/javacpp-presets/commit/13ffffd191fa48d9d9d1d8a64e0c4d64c9da1134 it now gets bundled and can be used easily from Java.
