### ISSUE TITLE
FFMPEG 10-Bit Color Per Channel (HDR10) Support

### ISSUE THREAD

**Issue by smccombie** [bytedeco/javacpp-presets#541]
it appears that for ffmpeg, the file: cppbuild.sh can take a flag to enable 10-bit color support for libx265.  I'm requesting if possible a quick change to enable 10-bit color and HDR support (12-bit color would be a nice option as well).  Those appear to be HIGH_BIT_DEPTH (for 10-bit) & MAIN12 (for 12-bit [dolby vision hdr for example]).  I believe this feature is urgent due to the large number of TVs and monitors that now come equipped with HDR capabilities and full support in the Windows 10 operating system.  Only libx265 needs to be recompiled, everything else with ffmpeg's build should be fine.  Thank you for your time, the following is a reference for anyone who needs any additional information:
http://www.gregwessels.com/dev/2017/10/27/ffmpeg-x265.html

**Comment by saudet** [comment]
Sounds good! Could you send a pull request with the changes? Thanks!

**Comment by saudet** [comment]
Thanks to @renderdude, support for that has been added with pull #619!

**Comment by saudet** [comment]
Support now included in version 1.4.4, enjoy!
