### ISSUE TITLE
how to create a 2-D array tensorflow.Tensor

### ISSUE THREAD

**Issue by zhengdi1992** [bytedeco/javacpp-presets#544]
just like the sample:
int[][] twoD = new int[2][];
twoD[0] = new int[1];
twoD[1] = new int[2];
Tensor<Integer> x = Tensor.create(twoD, Integer.class);

but how to use it in javacpp.tensorflow.Tensor ? 
it only support like that:
        public static Tensor create(int[]    data, TensorShape shape) ;

can required int[][] ?2-D ?3-D? or more

**Comment by saudet** [comment]
We just need to give the data in row major format, as shown in 
https://github.com/bytedeco/javacpp-presets/tree/master/tensorflow#the-srcmainjavaexampletrainerjava-source-file:
```java
// a = [3 2; -1 0]
Output a = Const(root, Tensor.create(new float[] {3.f, 2.f, -1.f, 0.f}, new TensorShape(2, 2)));
```
The helpers are a bit rough though... Anyway, it's usually more efficient to let TensorFlow allocate memory, and then to set the elements, for example, in 3D:
```java
Tensor x = new Tensor(DT_INT32, new TensorShape(size1, size2, size3));
IntIndexer xIdx = x.createIndexer();
xIdx.put(x, y, z, value);
// ...
```

**Comment by zhengdi1992** [comment]
thx a lot.
