### ISSUE TITLE
Build on Raspberry Pi 3 B+ fails on FFmpeg

### ISSUE THREAD

**Issue by pwierzchon** [bytedeco/javacpp-presets#545]
Hi, I want to compile javacpp-presets on Raspbery Pi 3 B+ with the new Raspbian Stretch. I follow your instructions which worked perfectly for build on the previous RPi model (https://github.com/bytedeco/javacpp-presets/wiki/Build-Environments), but this time it fails on FFmpeg giving the following stack trace:

> patching file configure
> Hunk #1 succeeded at 5955 (offset 1 line).
> gcc is unable to create an executable file.
> If gcc is a cross-compiler, use the --enable-cross-compile option.
> Only do this if you know what cross compiling means.
> C compiler test failed.
> 
> If you think configure made a mistake, make sure you are using the latest
> version from Git.  If the latest version fails, report the problem to the
> ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.freenode.net.
> Include the log file "ffbuild/config.log" produced by configure as this will help
> solve the problem.
> [INFO] ------------------------------------------------------------------------
> [INFO] Reactor Summary:
> [INFO]
> [INFO] JavaCPP Presets 1.4.2-SNAPSHOT ..................... SUCCESS [  3.177 s]
> [INFO] JavaCPP Presets for OpenCV 3.4.1-1.4.2-SNAPSHOT .... SUCCESS [  02:42 h]
> [INFO] JavaCPP Presets for FFmpeg 3.4.2-1.4.2-SNAPSHOT .... FAILURE [20:58 min]
> [INFO] JavaCPP Presets for FlyCapture 2.11.3.121-1.4.2-SNAPSHOT SKIPPED
> [INFO] JavaCPP Presets for libdc1394 2.2.5-1.4.2-SNAPSHOT . SKIPPED
> [INFO] JavaCPP Presets for libfreenect 0.5.3-1.4.2-SNAPSHOT SKIPPED
> [INFO] JavaCPP Presets for ARToolKitPlus 2.3.1-1.4.2-SNAPSHOT SKIPPED
> [INFO] JavaCPP Presets for Chilitags master-1.4.2-SNAPSHOT  SKIPPED
> [INFO] JavaCPP Presets for flandmark 1.07-1.4.2-SNAPSHOT .. SKIPPED
> [INFO] JavaCPP Presets for OpenBLAS 0.2.20-1.4.2-SNAPSHOT . SKIPPED
> [INFO] JavaCPP Presets for ARPACK-NG 20171109-1d912ad-1.4.2-SNAPSHOT SKIPPED
> [INFO] JavaCPP Presets for CMINPACK 1.3.6-1.4.2-SNAPSHOT .. SKIPPED
> [INFO] JavaCPP Presets for FFTW 3.3.7-1.4.2-SNAPSHOT ...... SKIPPED
> [INFO] JavaCPP Presets for GSL 2.4-1.4.2-SNAPSHOT ......... SKIPPED
> [INFO] JavaCPP Presets for Leptonica 1.75.3-1.4.2-SNAPSHOT  SKIPPED
> [INFO] JavaCPP Presets for Tesseract 3.05.01-1.4.2-SNAPSHOT SKIPPED
> [INFO] JavaCPP Presets for Systems 1.4.2-SNAPSHOT ......... SKIPPED
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time: 03:03 h
> [INFO] Finished at: 2018-04-03T08:41:17Z
> [INFO] ------------------------------------------------------------------------
> [ERROR] Failed to execute goal org.bytedeco:javacpp:1.4.2-SNAPSHOT:build (javacpp.cppbuild.install) on project ffmpeg: Execution javacpp.cppbuild.install of goal org.bytedeco:javacpp:1.4.2-SNAPSHOT:build failed: Process exited with an error: 1 -> [Help 1]
> [ERROR]
> [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
> [ERROR] Re-run Maven using the -X switch to enable full debug logging.
> [ERROR]
> [ERROR] For more information about the errors and possible solutions, please read the following articles:
> [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
> [ERROR]
> [ERROR] After correcting the problems, you can resume the build with the command
> [ERROR]   mvn <goals> -rf :ffmpeg

Any ideas how to fix that?

**Comment by saudet** [comment]
@vb216 What would we need to support that model?

**Comment by vb216** [comment]
@pwierzchon did it compile ok using Stretch distro on other Pi models / recently? Or has it never worked on Stretch?

I'm guessing maybe different gcc version shipped nowadays, or one in the setup instructions isn't available any more (assuming its never worked on Stretch).

Hopefully shouldn't be too tricky to resolve, will grab latest raspbian distro and give it a try locally.

**Comment by pwierzchon** [comment]
It compiled ok with Stretch distro 4-5 months ago. Now my company gave me a new Pi and asked me to set up the environment using new Stretch.

**Comment by vb216** [comment]
pull #548 should fix this

If you want it quickly, you can manually modify ./ffmpeg/cppbuild.sh to bring it in line - just needs an extra lib path added as I guess in latest Stretch they moved some things around

**Comment by saudet** [comment]
Thanks @vb216!

**Comment by vb216** [comment]
Clue is in the message itself, you need to download flycapture (you have to accept some license stuff to be able to access it) and place it in ./javacpp-presets/downloads directory, then you can resume the build from that step, it'll find the flycapture source and carry on

**Comment by saudet** [comment]
Right, just skip any module you don't need. BTW, the precompiled binaries
should work. Why not use those?
