### ISSUE TITLE
how to get MIME type from grabber

### ISSUE THREAD

**Issue by palak18j** [bytedeco/javacpp-presets#546]
I need to obtain mime information from grabber -e.g. "video/avc"
using MediaExtractor I do it like
MediaFormat format = extractor.getTrackFormat(trackIndex);
String mime = format.getString(MediaFormat.KEY_MIME); 
where the mime returned in my case is -"video/avc"
How to achieve the same using FFmpegFrameGrabber ?
grabber.getMetadata("mime") returns null; Am I giving correct key(here mime)?whereas contentResolver returns file-format and not mime type(contentresolvedObject.getType(uri))

**Comment by saudet** [comment]
No, it doesn't look like FFmpeg supports that when opening a file. We can use ` av_guess_format()` for that though: https://stackoverflow.com/questions/45589437/libavformat-get-formats-mime-type-in-c

For example, 
```java
AVOutputFormat f = av_guess_format(null, "file.mp4", null);
System.out.println(f.mime_type().getString());
```
prints out "video/mp4".
