### ISSUE TITLE
Unable to resolve jar dependencies using make system

### ISSUE THREAD

**Issue by palak18j** [bytedeco/javacpp-presets#554]
I used the jars in my project and did compilation using gradle system and it worked, but when I compile the same project using make compile system, specifying jars in the Android.mk file, It compiles but thows errors at run time,
Caused by: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.qualcomm.touch2track-BDKEmDwdQfuN6Pqc7Aa6Rw==/base.apk"],nativeLibraryDirectories=[/data/app/com.qualcomm.touch2track-BDKEmDwdQfuN6Pqc7Aa6Rw==/lib/arm, /system/fake-libs, /data/app/com.qualcomm.touch2track-BDKEmDwdQfuN6Pqc7Aa6Rw==/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]] couldn't find "libgcc.so"
                                                                              
Upon extraction of a jar(ffmpeg) I could see the pom.xml file which mentions this library in <compiler option> tag,
How to resolve these dependencies during make compilation instead of gradle as these dependencies does not seem to be resolved upon compilation using mm?Is there a way out?

**Comment by saudet** [comment]
AFAIK, that has been fixed. Please try again with version 1.4.1.

**Comment by saudet** [comment]
Sorry, I read that wrong. So it works with Gradle, but you do not want to use dependency management, so you will need to do it on your own, unfortunately. This means adding all the relevant JAR files manually, yes. You can see which ones are included by Gradle by using ` gradle app:dependencies`, for example:
https://developer.android.com/studio/build/dependencies.html#view-dependency-tree

**Comment by palak18j** [comment]
Hey, there are 67 jars in number that I see in dependency tree. Not sure if all of these are relevant to jars, Is it not possible for either provide jars free of any such dependencies that is resolved by gradle or some way by which I could rebuild jars after ridding away from any dependencies?

**Comment by saudet** [comment]
We can exclude some dependencies with Gradle, yes, if that is what you meant?

**Comment by palak18j** [comment]
no I don't mean to exclude any dependency, just want to understand how I can get rid of the dependencies that are mentioned in pom.xml in maven within for e.g. ffmpeg.jar has compiler option that mentions . All works fine when I use your jars with gradle compilation. Problem comes when I compile using another compiler such as make system, It is not able to resolve the dependencies(it has gives a maven folder within apk but does not resolve) and app crashes on run time. 
You told in previous response that I ll have to see the dependency tree to see what all jars gradle adds upon compilation, I see 67 jars added by it(lint.jar, etc) and have no idea if all of those are necessary for resolving dependencies.
I see <compilerOption>-static-libgcc</compilerOption>
                <compilerOption>-static-libstdc++</compilerOption> in pom.xml within maven folder of the  META_INF within your jars.
Can you provide jars free from any dependencies that gradle must be resolving ? Or what if I extract your jars and again create without those pom files?

**Comment by saudet** [comment]
You could just add all the JAR files. You'll be sure not to miss anything then :)
