### ISSUE TITLE
LLVM: Missing bindings for creating new 'CatchPad' instructions.

### ISSUE THREAD

**Issue by RobertStanforth** [bytedeco/javacpp-presets#558]
The LLVM presets (great utility btw) lacks bindings for the following functions relating to the new 'CatchPad' style of exception handling:

LLVMBuildCatchPad
LLVMBuildCatchSwitch
LLVMBuildCatchRet
LLVMBuildCleanupPad
LLVMBuildCleanupRet

Would it be possible to implement these?

**Comment by saudet** [comment]
I'm sure they can! BTW, contributions are welcome.
