### ISSUE TITLE
Loaded runtime CuDNN library: 7005 (compatibility version 7000) but source was compiled with 7101 (compatibility version 7100)

### ISSUE THREAD

**Issue by andyguo007** [bytedeco/javacpp-presets#565]
Hi,

When I am using tensorflow 1.7.0-1.4.1, the following error happens: 
Loaded runtime CuDNN library: 7005 (compatibility version 7000) but source was compiled with 7101 (compatibility version 7100)

I have cuDNN 7.0.5 and CUDA 9.1 installed. And I see that in the cppbuild.sh TF_CUDNN_VERSION=7. Is tensorflow built with cuDNN 7.0.5 or 7.1?

Thanks.
Andy

**Comment by saudet** [comment]
cuDNN 7.1, because that's what the Docker images use:
https://hub.docker.com/r/nvidia/cuda/
https://github.com/bytedeco/javacpp-presets/blob/master/ci/install-travis.sh#L36
