### ISSUE TITLE
question : face Recognizer 

### ISSUE THREAD

**Issue by WaleedJubeh** [bytedeco/javacpp-presets#570]
hello developers ...
i saw this sample of face Recognizer in this link 
[FaceRecognizerInVideo](https://github.com/bytedeco/javacv/blob/master/samples/FaceRecognizerInVideo.java)
I don't want to make face recognizer in a video file .. 
i need to make it in my web camera (ex: laptop camera) ...
so what is the change in the code to do that ?
*************************************/
Another Question: i have a IP cameras connected to DVR so how to connect to them in the code ...
" same the first issue  just i want to choose ip camera not my camera " 

hope to  get solutions ...

**Comment by saudet** [comment]
For these sources, we can still use `OpenCVFrameGrabber` with a number like 0 for your webcam and `FFmpegFrameGrabber` with URL for your IP camera.

**Comment by WaleedJubeh** [comment]
i have already putted 0 in OpenCVFrameGrabber  
but its gives me this exception 

>OpenCV(3.4.1) Error: Assertion failed (!empty()) in cv::CascadeClassifier::detectMultiScale, file C:\projects\javacpp-presets\opencv\cppbuild\windows-x86_64\opencv-3.4.1\modules\objdetect\src\cascadedetect.cpp, line 1698
Exception in thread "main" java.lang.RuntimeException: OpenCV(3.4.1) C:\projects\javacpp-presets\opencv\cppbuild\windows-x86_64\opencv-3.4.1\modules\objdetect\src\cascadedetect.cpp:1698: error: (-215) !empty() in function cv::CascadeClassifier::detectMultiScale
at org.bytedeco.javacpp.opencv_objdetect$CascadeClassifier.detectMultiScale(Native Method)
at facereco.FaceRecognizerInVideo.main(FaceRecognizerInVideo.java:62)`


this happen when reach this line :
`           face_cascade.detectMultiScale(videoMatGray, faces);
`
any help

**Comment by saudet** [comment]
That's not related to your camera. You'll need to train the classifier first:
https://docs.opencv.org/3.4.1/da/d60/tutorial_face_main.html
