### ISSUE TITLE
openblas for ios failing with libopenblas.a

### ISSUE THREAD

**Issue by johanvos** [bytedeco/javacpp-presets#571]
When bundling an application with the accelerate framework, Nd4j and the blas calls work fine. When bundling with libopenblas.a, there are incorrect results. For example, the resulting NDArray only contains 0 elements.
   INDArray unin = Nd4j.create(1, 2);
            unin.putScalar(0, 0d);
            unin.putScalar(1, 1d);
            INDArray unw = Nd4j.create(2,3);
            unw.putScalar(0, 1d);
            unw.putScalar(1, 2d);
            unw.putScalar(2, 1d);
            unw.putScalar(3, 3d);
            unw.putScalar(4, 1d);
            unw.putScalar(5, 4d);
            INDArray unret = Nd4j.createUninitialized(1,3);
            unin.mmuli(unw,unret);
            
            System.out.println("UNIN = "+unin);
            System.out.println("UNW = "+unw);
            System.out.println("UNRET = "+unret);

**Comment by saudet** [comment]
Does this happen with `ios-arm64` or `ios-x86_64`, or both?

**Comment by johanvos** [comment]
This exact test fails with ios-x86_64
The results of a complex mnist app on ios-arm64 were incorrect, but I didn't check this particular test so in theory that might be caused by something else.

**Comment by saudet** [comment]
It's strange that Xcode would have problems with x86 assembly. In any case, the optimized kernels for ARM64 were already disabled as the assembler just doesn't work with the optimized kernels, so that should be OK.

**Comment by saudet** [comment]
I've made the changes in the latest commit disabling optimizations in assembly language. Let me know if you have the chance to try it out with version 0.3.0-1.4.2-SNAPSHOT. Thanks!

**Comment by saudet** [comment]
The changes are included in version 1.4.2. Thanks for reporting and let me know if you still see any issues related to that!
