### ISSUE TITLE
where is the tesseract 4 jar file

### ISSUE THREAD

**Issue by mossaudi** [bytedeco/javacpp-presets#572]
please, where is the version 4 jar file ?
this give me error
<dependency>
            <groupId>org.bytedeco.javacpp-presets</groupId>
            <artifactId>tesseract-platform</artifactId>
            <version>4.0.0-beta.1-1.4.2-SNAPSHOT</version>
        </dependency>

**Comment by saudet** [comment]
It's on the snapshot repository: http://bytedeco.org/builds/
