### ISSUE TITLE
Mac OSX issue loading DLL from openblas when using version 1.4.2-SNAPSHOT

### ISSUE THREAD

**Issue by C0deAttack** [bytedeco/javacpp-presets#573]
Loading a Keras model in Deeplearning4J using org.bytedeco.javacpp-presets:openblas:0.3.0-1.4.2-SNAPSHOT results in the following error:

```Caused by: java.lang.UnsatisfiedLinkError: /Users/mldemovm/.javacpp/cache/openblas-0.3.0-1.4.2-20180612.214127-97-macosx-x86_64.jar/org/bytedeco/javacpp/macosx-x86_64/libjniopenblas.dylib: dlopen(/Users/mldemovm/.javacpp/cache/openblas-0.3.0-1.4.2-20180612.214127-97-macosx-x86_64.jar/org/bytedeco/javacpp/macosx-x86_64/libjniopenblas.dylib, 1): Library not loaded: /usr/local/opt/gcc/lib/gcc/8/libquadmath.0.dylib
  Referenced from: /Users/mldemovm/.javacpp/cache/openblas-0.3.0-1.4.2-20180612.214127-97-macosx-x86_64.jar/org/bytedeco/javacpp/macosx-x86_64/./libopenblas.dylib
  Reason: image not found
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1938)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1821)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1204)
	... 30 more
```

If the dependency version is changed to 0.2.20-1.4.1 the model is loaded without error.
A Gist showing the pom.xml file in my test application can be seen [here](https://gist.github.com/C0deAttack/89a070c2130287a2cc68c5e0776b97fb).

I've checked this issue is present on Mac OS Yosemite and High Sierra.

**Comment by saudet** [comment]
This was an issue only with OpenBLAS 0.3.0. For some reason 0.2.20 failed to use GFortran for linking, so the problem didn't show up then. Gone back to GCC, so should be fixed now. Thanks for reporting!
