### ISSUE TITLE
9.2 on Maven

### ISSUE THREAD

**Issue by maximusgrey** [bytedeco/javacpp-presets#576]
I cannot find the new 9.2 version on the Maven repository ( https://mvnrepository.com/artifact/org.bytedeco.javacpp-presets/cuda), is this the correct location or has it not jet been updated there?

**Comment by saudet** [comment]
It's available in the snapshots: http://bytedeco.org/builds/

**Comment by maximusgrey** [comment]
Perfect, Thank you very much!
