### ISSUE TITLE
Build failure in llvm module on macOS High Sierra 10.13.5

### ISSUE THREAD

**Issue by sameerajayasoma** [bytedeco/javacpp-presets#577]
I am getting the following build failure when building the llvm module on macOS High Sierra 10.13.5.  Please let me know how to get this solved. I have xcode installed in my machine. 

[INFO] clang++ -I/Users/sameera/work/wso2/clones/llvm-java/javacpp-presets/llvm/cppbuild/macosx-x86_64/include/ -I/Library/Java/JavaVirtualMachines/jdk1.8.0_151.jdk/Contents/Home/include -I/Library/Java/JavaVirtualMachines/jdk1.8.0_151.jdk/Contents/Home/include/darwin /Users/sameera/work/wso2/clones/llvm-java/javacpp-presets/llvm/target/classes/org/bytedeco/javacpp/jniLLVM.cpp /Users/sameera/work/wso2/clones/llvm-java/javacpp-presets/llvm/target/classes/jnijavacpp.cpp -march=x86-64 -m64 -O3 -std=c++11 -Wl,-rpath,@loader_path/. -Wall -fPIC -dynamiclib -undefined dynamic_lookup -o libjniLLVM.dylib -L/Users/sameera/work/wso2/clones/llvm-java/javacpp-presets/llvm/cppbuild/macosx-x86_64/lib/ -Wl,-rpath,/Users/sameera/work/wso2/clones/llvm-java/javacpp-presets/llvm/cppbuild/macosx-x86_64/lib/ -lLLVM -lLTO -framework JavaVM
/Users/sameera/work/wso2/clones/llvm-java/javacpp-presets/llvm/target/classes/org/bytedeco/javacpp/jniLLVM.cpp:74:10: fatal error: 'exception' file not found
#include <exception>
         ^~~~~~~~~~~
1 error generated.
/Users/sameera/work/wso2/clones/llvm-java/javacpp-presets/llvm/target/classes/jnijavacpp.cpp:72:10: fatal error: 'exception' file not found
#include <exception>
         ^~~~~~~~~~~
1 error generated.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 58:52 min
[INFO] Finished at: 2018-06-22T10:54:09-07:00
[INFO] Final Memory: 23M/416M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.bytedeco:javacpp:1.4.2-SNAPSHOT:build (javacpp.compiler) on project llvm: Execution javacpp.compiler of goal org.bytedeco:javacpp:1.4.2-SNAPSHOT:build failed: Process exited with an error: 1 -> [Help 1]
[ERROR]

**Comment by saudet** [comment]
That's a standard C++ header file. Your installation of Xcode is just
corrupted. Reinstall it!
