### ISSUE TITLE
Broken Tensorflow jar in Sonatype Snapshots

### ISSUE THREAD

**Issue by wumo** [bytedeco/javacpp-presets#579]
Today's tensorflow jar is:

tensorflow-1.9.0-rc1-1.4.2-20180628.175809-25.jar | Thu Jun 28 17:58:09 UTC 2018 | 610529
-- | -- | --

which is half size of previous jar:

tensorflow-1.9.0-rc1-1.4.2-20180627.063735-21.jar | Wed Jun 27 06:37:47 UTC 2018 | 1517673
-- | -- | --

And many Ops are missing. (e.g `Placeholder`, `Variable`)

**Comment by saudet** [comment]
That's a transient issue that happens when deploying for Android before the
rest... Should be fixed by now.

**Comment by wumo** [comment]
@saudet  yep. fixed.
