### ISSUE TITLE
mkl-dnn does not fallback to mkl-ml for non-AVX512-BW processors

### ISSUE THREAD

**Issue by blueberry** [bytedeco/javacpp-presets#597]
I'm following this tutorial from the official JavaCPP MKL-DNN guide: https://github.com/bytedeco/javacpp-presets/tree/master/mkl-dnn

At some point, there is a constructor call `convolution_forward.primitive_desc` that, according to the guide comment, should fail if int8 convolution is not supported.

According to the MKL-DNN documentation, int8 is supported on processors that support AVX512-BW.
 
I'm running this on a i7-4790k, which does **not** support AVX512-BW, but, according to the same documentation, in this case, the implementation should use a fallback provided by MKL-ML library, if it is present. JavaCPP MKL-DNN jar **does** contain `mklml`-related native libraries, so I guess that the falback should be used.

However, in my case, the fallback is **not** used, and I am not able to run the code from the tutorial.

Either I'm wrong about how this fallback should work, or there is some problem with how JavaCPP MKL-DNN is packaged, that causes the mklml to not be recognized as available...

**Comment by saudet** [comment]
Yes, that's correct, it works fine for me at least. Which platform are you
on?

**Comment by blueberry** [comment]
Arch Linux.

Actually, id does work for me too, with a change:

instead
```java
convolution_forward.primitive_desc conv_prim_desc = new convolution_forward.primitive_desc(
                conv_desc, conv_attr, cpu_engine);
```
, which throws an exception `mkl_unimplemented`, I had to leave out `conv_attr`, for the code to work:

```java
convolution_forward.primitive_desc conv_prim_desc = new convolution_forward.primitive_desc(
                conv_desc, conv_attr, cpu_engine);
```

Also, if i change `u8` to `f32`, the code is roughly 8 times faster, but the same `conv_attr` had to be left out for it to work. Otherwise, it throws the same exception.

**Comment by blueberry** [comment]
I'm not sure what you mean. This is from the following JavaCPP version published at https://github.com/bytedeco/javacpp-presets/tree/master/mkl-dnn

I don't know what the speed should be in raw C++, and I don't think it would be different, as the speed difference is probably because the fallback engine is used. I've just mentioned that to point out that the original code does not work for me even if we leave out `u8` data and make everything `f32`...

**Comment by saudet** [comment]
Strange, I've just tried it again here (Fedora 27) and I get a "Simple-net-int8 example passed!". I wonder if there is a debug mode on that thing...

**Comment by blueberry** [comment]
Interestingly, when I run that from the main, it does work and print that example passed.

I'm running this from Clojure's interactive REPL, so I'll have to check whether I mistyped something (probably not, since everything else work) or there is some thread pool executor or classloader gotcha there...

**Comment by blueberry** [comment]
Sorry for the false alarm. I had a wrong number in my code ops_alpha should be 0.0f, and I mistakenly typed 1.0f. Now it works!

Thanks for the help!
