### ISSUE TITLE
Static linking of MKL library

### ISSUE THREAD

**Issue by alois-bissuel** [bytedeco/javacpp-presets#601]
I successfully used the mkl preset. Thanks for the very good work!

Now I would like to use this preset on a server where MKL is not installed.  From what I understood, the MKL is not bundled in the jar available on Maven Central for licensing issue. 

Is there a way to do it, preferably without meddling in javacpp source code? 

Below is my unsuccessful (and maybe clumsy) attempt at doing it on macos (though my compilation target is Linux):

I have seen that the compilation flags were taken from https://github.com/bytedeco/javacpp/blob/master/src/main/resources/org/bytedeco/javacpp/properties/macosx-x86_64.properties

I thus added a "static" field in the "compiler" property in [mkl/src/main/java/org/bytedeco/javacpp/presets/mkl_rt.java](https://github.com/bytedeco/javacpp-presets/blob/master/mkl/src/main/java/org/bytedeco/javacpp/presets/mkl_rt.java)

I called maven trying to pass the "static" property as follows:
`mvn install -Dplatform.compiler.static="-static" --projects mkl`

But maven tells me just before calling clang++ that the static property was not found:
`[WARNING] Could not get the property named "platform.compiler.static"`

I am taking the right path?

**Comment by saudet** [comment]
We just need remove the `<copyLibs>false</copyLibs>` line here and it should get bundled properly:
https://github.com/bytedeco/javacpp-presets/blob/master/mkl/pom.xml#L59

**Comment by saudet** [comment]
Please let me know if this isn't working properly though, thanks!

**Comment by alois-bissuel** [comment]
Thanks a lot for the quick answer. It worked on my mac, and I am now trying on Linux.

**Comment by saudet** [comment]
BTW, the new license actually permits redistributing the libraries, so they are now being bundled! Enjoy
