### ISSUE TITLE
Tensorflow C++ Python API: undefined symbol: tensorflow::AddControlInput

### ISSUE THREAD

**Issue by wumo** [bytedeco/javacpp-presets#602]
when using `AddControlInput` (commit e61ec03e1f76c07276b6e52df7dae9f25d7e9256) in Ubuntu 16.04, it results in the following error:
```
/usr/lib/jvm/jdk1.8.0_181/bin/java: symbol lookup error: /home/wumo/.javacpp/cache/tensorflow-1.10.0-1.4.3-20180817.021425-14-linux-x86_64.jar/org/bytedeco/javacpp/linux-x86_64/libjnitensorflow.so: undefined symbol: _ZN10tensorflow15AddControlInputEP8TF_GraphP12TF_OperationS3_
```
while in windows 10, there is no such error.

**Comment by saudet** [comment]
We probably need to enable Python support for the Bazel build as well...

**Comment by saudet** [comment]
Ok, I've enabled the Python API for the build with Bazel as well. That symbol is now appears in the list, but I haven't tested it...

**Comment by wumo** [comment]
It worked. thx @saudet .
