### ISSUE TITLE
Is there any release for jdk 6?

### ISSUE THREAD

**Issue by MJ-DEV91** [bytedeco/javacpp-presets#624]
Hi. I have to use jdk6 in my production environment. Is there any release for jdk6?

**Comment by saudet** [comment]
The last release that supports JDK 6 is version 1.0:
http://bytedeco.org/news/2015/10/25/moving-to-java-se-7/
Please try it out and let me know if that isn't enough for your needs! Thanks

**Comment by MJ-DEV91** [comment]
Really thanks. Is there any maven repository for tesseract-platform (jdk6)?

**Comment by saudet** [comment]
You'll need to add the dependencies of the platforms you need manually:
https://search.maven.org/search?q=g:org.bytedeco.javacpp-presets%20AND%20a:tesseract&core=gav

**Comment by MJ-DEV91** [comment]
Now I face with this error:

`actual_tessdata_num_entries_ <= TESSDATA_NUM_ENTRIES:Error:Assert failed:in file tessdatamanager.cpp, line 53`

**Comment by saudet** [comment]
You'll need to use an old version of the data as well.

**Comment by MJ-DEV91** [comment]
Im really sorry, where can I find the proper data?

**Comment by MJ-DEV91** [comment]
I put the data version 3.02 and it worked. Thanks for your support.
