### ISSUE TITLE
macosx-x86_64 is missing in MKL 2019.0-1.4.3-SNAPSHOT ?

### ISSUE THREAD

**Issue by tzolov** [bytedeco/javacpp-presets#625]
The `macosx-x86_64` is available in the `MKL` `2019.0-1.4.3-SNAPSHOT` build:
https://oss.sonatype.org/content/repositories/snapshots/org/bytedeco/javacpp-presets/mkl/2019.0-1.4.3-SNAPSHOT/

Is this accidental or intentional?

**Comment by saudet** [comment]
Not really, the Nexus server there isn't configured optimally for us. :)
It's been released now anyway: https://github.com/deeplearning4j/deeplearning4j/pull/6587

**Comment by tzolov** [comment]
Sorry i meant that it is NOT available (missed the not in my original message). Still i fully understands how many tricks the maven releasing infrastructure can bring ;)
