### ISSUE TITLE
Cant build latest code from source on Ubuntu 12 server

### ISSUE THREAD

**Issue by icarusfire** [bytedeco/javacpp-presets#63]
I followed this instructions on a Mac and it worked fine:

http://stackoverflow.com/questions/30925074/javacpp-liblept-4-dylib-library-not-loaded

But when I trey the same on an Ubuntu server in the same way, after running command "mvn install -pl .,leptonica,tesseract" I got errors below:

First this one:

[WARNING]
[WARNING] Some problems were encountered while building the effective model for org.bytedeco.javacpp-presets:opencv:jar:3.0.0-1.0-SNAPSHOT
[WARNING] 'version' contains an expression but should be a constant. @ org.bytedeco.javacpp-presets:opencv:3.0.0-${project.parent.version}, /usr/share/javacppfiles/javacpp-presets-master/opencv/pom.xml, line 14, column 12
[WARNING]
[WARNING] Some problems were encountered while building the effective model for org.bytedeco.javacpp-presets:ffmpeg:jar:2.7-1.0-SNAPSHOT
[WARNING] 'version' contains an expression but should be a constant. @ org.bytedeco.javacpp-presets:ffmpeg:2.7-${project.parent.version}, /usr/share/javacppfiles/javacpp-presets-master/ffmpeg/pom.xml, line 14, column 12
[WARNING]..

..
..
..

INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] JavaCPP Presets ................................... SUCCESS [0.857s]
[INFO] JavaCPP Presets for Leptonica ..................... FAILURE [12.358s]
[INFO] JavaCPP Presets for Tesseract ..................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 14.267s
[INFO] Finished at: Fri Jun 26 19:30:26 EDT 2015
[INFO] Final Memory: 21M/75M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:2.3:copy-dependencies (copy-dependencies) on project leptonica: Execution copy-dependencies of goal org.apache.maven.plugins:maven-dependency-plugin:2.3:copy-dependencies failed: Plugin org.apache.maven.plugins:maven-dependency-plugin:2.3 or one of its dependencies could not be resolved: Failed to collect dependencies for org.apache.maven.plugins:maven-dependency-plugin:jar:2.3 (): Failed to read artifact descriptor for org.apache.maven:maven-settings:jar:2.0.5: Could not transfer artifact org.apache.maven:maven-settings:pom:2.0.5 from/to central (http://repo.maven.apache.org/maven2): Connection reset -> [Help 1]

And then when i tried to re run again, I got this error:

[INFO] Parsing /usr/share/javacppfiles/javacpp-presets-master/leptonica/cppbuild/linux-x86_64/include/leptonica/allheaders.h
[INFO] Successfully executed JavaCPP Builder
[INFO]
[INFO] --- maven-dependency-plugin:2.3:copy-dependencies (copy-dependencies) @ leptonica ---
[INFO] javacpp-1.0-SNAPSHOT.jar already exists in destination.
[INFO]
[INFO] --- maven-resources-plugin:2.4:resources (default-resources) @ leptonica ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /usr/share/javacppfiles/javacpp-presets-master/leptonica/src/main/resources
[INFO]
[INFO] --- maven-compiler-plugin:2.3:compile (default-compile) @ leptonica ---
[INFO] Compiling 1 source file to /usr/share/javacppfiles/javacpp-presets-master/leptonica/target/classes
[INFO]
[INFO] --- javacpp:1.0-SNAPSHOT:build (process-classes) @ leptonica ---
[INFO] Executing JavaCPP Builder
[INFO] Generating /usr/share/javacppfiles/javacpp-presets-master/leptonica/target/classes/org/bytedeco/javacpp/jnilept.cpp
[INFO] Compiling /usr/share/javacppfiles/javacpp-presets-master/leptonica/target/classes/org/bytedeco/javacpp/linux-x86_64/libjnilept.so
[INFO] g++ -I/usr/share/javacppfiles/javacpp-presets-master/leptonica/cppbuild/linux-x86_64/include/ -I/usr/lib/jvm/java-8-oracle/include -I/usr/lib/jvm/java-8-oracle/include/linux /usr/share/javacppfiles/javacpp-presets-master/leptonica/target/classes/org/bytedeco/javacpp/jnilept.cpp -Wl,-rpath,$ORIGIN/ -march=x86-64 -m64 -Wall -O3 -fPIC -shared -s -o /usr/share/javacppfiles/javacpp-presets-master/leptonica/target/classes/org/bytedeco/javacpp/linux-x86_64/libjnilept.so -L/usr/share/javacppfiles/javacpp-presets-master/leptonica/cppbuild/linux-x86_64/lib/ -Wl,-rpath,/usr/share/javacppfiles/javacpp-presets-master/leptonica/cppbuild/linux-x86_64/lib/ -llept
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.6/README.Bugs> for instructions.

**Comment by saudet** [comment]
That's an old version of GCC... It works fine in the case of Android so, I'm not sure what is wrong. Could you ask the GCC team about that? Thanks

**Comment by icarusfire** [comment]
tnx! but what is gcc? and who is gcc team?

**Comment by saudet** [comment]
I'll just copy/paste what you copy/pasted:
See file:///usr/share/doc/gcc-4.6/README.Bugs for instructions.

**Comment by icarusfire** [comment]
ok I will, but it was the second error, first I got this:

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:2.3:copy-dependencies (copy-dependencies) on project leptonica: Execution copy-dependencies of goal org.apache.maven.plugins:maven-dependency-plugin:2.3:copy-dependencies failed: Plugin org.apache.maven.plugins:maven-dependency-plugin:2.3 or one of its dependencies could not be resolved: Failed to collect dependencies for org.apache.maven.plugins:maven-dependency-plugin:jar:2.3 (): Failed to read artifact descriptor for org.apache.maven:maven-settings:jar:2.0.5: Could not transfer artifact org.apache.maven:maven-settings:pom:2.0.5 from/to central (http://repo.maven.apache.org/maven2): Connection reset -> [Help 1]

**Comment by icarusfire** [comment]
and when I run the code agaon without fixing this problem gcc crashed, which I believe is a separete issue

**Comment by saudet** [comment]
Yes, GCC crashed, so try a different compiler if you can.

**Comment by icarusfire** [comment]
ok so you say this error below is a GCC problem?, this happened way before GCC crash

ERROR] Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:2.3:copy-dependencies (copy-dependencies) on project leptonica: Execution copy-dependencies of goal org.apache.maven.plugins:maven-dependency-plugin:2.3:copy-dependencies failed: Plugin org.apache.maven.plugins:maven-dependency-plugin:2.3 or one of its dependencies could not be resolved: Failed to collect dependencies for org.apache.maven.plugins:maven-dependency-plugin:jar:2.3 (): Failed to read artifact descriptor for org.apache.maven:maven-settings:jar:2.0.5: Could not transfer artifact org.apache.maven:maven-settings:pom:2.0.5 from/to central (http://repo.maven.apache.o

**Comment by saudet** [comment]
So if you're worried about that, contact the Maven team. There no mention of JavaCPP anywhere in any of those errors. I cannot help you.

**Comment by icarusfire** [comment]
using gcc 4.9 and rebooting the server solved the problem

**Comment by saudet** [comment]
Great!
