### ISSUE TITLE
Record a JAVA SE APP

### ISSUE THREAD

**Issue by Tatsukyo** [bytedeco/javacpp-presets#639]
Hi @saudet

Currently trying to create a mp4 file from a java SE app which contains NO sound.

At the current time, i'm have just a basic JFrame which contains 2 JButtons and 1 Label which work as a timer to see if the video is working.

I tried with JAVACV which works pretty good but it's coming with too much dependencies since i'm just using FFmpeg (and potentially openCV).

Right now i'm just trying to init my "Recorder" as a mp4 recorder:
```
private void initRecorder()
{
	avcodec_register_all();
	av_register_all();
	mVideoHeight = mPanel.getHeight();
	mVideoWidth = mPanel.getWidth();

	mFormatContext = new AVFormatContext(null);
	mOutputFormat = av_guess_format(mFileExtension, null, null);
	avformat_alloc_output_context2(mFormatContext, null, mFileExtension, null);

	mFormatContext.oformat(mOutputFormat);
	mFormatContext.filename().putString("C:\\Users\\A874966\\Desktop\\TestRecordFrame.mp4");
	mFormatContext.max_delay(-1);
	mInputVideoStream = null;
	mVideoCodec = avcodec_find_encoder(AV_CODEC_ID_MPEG4);
	mOutputFormat.video_codec(AV_CODEC_ID_MPEG4);
	AVRational lFramerate = av_d2q(mFramerate, 1001000);
	AVRational lSupportedFramerate = mVideoCodec.supported_framerates();
	if (lSupportedFramerate != null)
	{
		int idx = av_find_nearest_q_idx(lFramerate, lSupportedFramerate);
		lFramerate = lSupportedFramerate.position(idx);
	}
	mInputVideoStream = avformat_new_stream(mFormatContext, null);
	mVideoCodecContext = avcodec_alloc_context3(mVideoCodec);
	mVideoCodecContext.codec_id(mOutputFormat.video_codec());
	mVideoCodecContext.codec_type(AVMEDIA_TYPE_VIDEO);
	mVideoCodecContext.bit_rate(mBitrate);
	/* resolution must be a multiple of two. Scale height to maintain the aspect ratio. */
	if (mVideoWidth % 2 == 1)
	{
		int roundedWidth = mVideoWidth + 1;
		mVideoHeight = (roundedWidth * mVideoHeight + mVideoWidth / 2) / mVideoWidth;
		mVideoWidth = roundedWidth;
	}
	mVideoCodecContext.width(mVideoWidth);
	mVideoCodecContext.height(mVideoHeight);
	AVRational time_base = av_inv_q(lFramerate);
	mVideoCodecContext.time_base(time_base);
	mInputVideoStream.time_base(time_base);
	mInputVideoStream.avg_frame_rate(lFramerate);
	mVideoCodecContext.pix_fmt(AV_PIX_FMT_YUV420P);
	if ((mOutputFormat.flags() & AVFMT_GLOBALHEADER) != 0)
	{
		mVideoCodecContext.flags(mVideoCodecContext.flags() | AV_CODEC_FLAG_GLOBAL_HEADER);
	}
	if ((mVideoCodec.capabilities() & AV_CODEC_CAP_EXPERIMENTAL) != 0)
	{
		mVideoCodecContext.strict_std_compliance(AVCodecContext.FF_COMPLIANCE_EXPERIMENTAL);
	}
	avcodec_open2(mVideoCodecContext, mVideoCodec, (AVDictionary) null);
	mPictureFrame = av_frame_alloc();
	mTmpPictureFrame = av_frame_alloc();
	mPictureFrame.pts(0);
	mPicturePointer = new BytePointer(av_malloc(av_image_get_buffer_size(mVideoCodecContext.pix_fmt(), mVideoCodecContext.width(), mVideoCodecContext.height(), 1)));
	avcodec_parameters_from_context(mInputVideoStream.codecpar(), mVideoCodecContext);
}
```

and stoping with
```
private void stopRecording() throws Exception
{
	if (mFormatContext != null)
	{
		try
		{
			System.out.println(av_write_frame(mFormatContext, mVideoPacket));
		}
		finally
		{
			closeRecorder();
		}
	}
}
```

i got a fatal error, and looking at the pid.log it's the av_write_frame which crash the JVM

Am I missing something? is my init false?

If it can help u i'm using the ffmpeg-platform
version:3.4.1-1.4

Thank u in advance

**Comment by saudet** [comment]
Have you tried to use FFmpegFrameRecorder instead?

**Comment by Tatsukyo** [comment]
Holy fck u are so reactfull,

Yes i used it and it worked. but javacv is coming with too much dependencies

**Comment by saudet** [comment]
Just asking simple questions, that doesn't take too much time :)

We don't need to use JavaCV, just copy `FFmpegFrameRecorder.java`, modify it a bit, and put it wherever you need it.

**Comment by Tatsukyo** [comment]
Well i tried it too,

Sadly FFmpegFrameRecorder extends FrameRecorder which contains a method 
Record which take a Frame as Parameter and obviously Frame is a class of JavaCV,

i tried, i failed :c

**Comment by saudet** [comment]
Just remove any references to FrameRecorder or Frame, that will work.

**Comment by Tatsukyo** [comment]
Hey look like 
replacing av_write_frame by av_interleaved_write_frame do not crash but there is no file,

I suppose the file will be at the mFormatContext.filename().putString("C:\\Users\\A874966\\Desktop\\TestRecordFrame.mp4");

but there is nothing...

is it av_interleaved_write_frame which write the file?

**Comment by saudet** [comment]
You said that FFmpegFrameRecorder works, so just do the same as in FFmpegFrameRecorder and it will work.
