### ISSUE TITLE
Problem running on centos 64bit vm

### ISSUE THREAD

**Issue by chaksoham** [bytedeco/javacpp-presets#640]
Getting error while running in centos 64bit vm. We had deployed in a centos system after creating jar of our project (maven build ). When running the tesseract module we get error in opening the tessdata/eng.traineddata. Though the file is present inside the jar.

**Comment by saudet** [comment]
Yes, it's not included. Include it in your application, along with whatever
other languages you might need.

**Comment by chaksoham** [comment]
> Yes, it's not included. Include it in your application, along with whatever other languages you might need.

It's included the path it tries to locate is correct but gives an error.

**Comment by saudet** [comment]
You'll also need to make sure to use version of the data that is compatible
with the version of Tesseract you are using.
