### ISSUE TITLE
What is correct byte order for Java direct byte buffer while creating Mat?

### ISSUE THREAD

**Issue by Daniel-Alievsky** [bytedeco/javacpp-presets#646]
Sorry for trivial question, I didn't find answer... Here is a simple function:
```
    public static ByteBuffer toByteBuffer(opencv_core.UMat u) {
        final long size = sizeOfInBytes(u);
        final ByteBuffer byteBuffer = ByteBuffer.allocateDirect((int) size);
        byteBuffer.order(ByteOrder.nativeOrder());
        final opencv_core.Mat m = new opencv_core.Mat(
            u.rows(), u.cols(), u.type(), new BytePointer(byteBuffer.duplicate()));
        u.copyTo(m);
        return byteBuffer;
    }
```
Or something like this. My task is to create correct Mat on the base of Java byte buffer - in this example, to copy there some UMat.
Do I understand correctly that I **must** set byte order of the byte buffer to ByteOrder.nativeOrder()? ByteBuffer.allocateDirect (according Java specification) always creates byte buffer with BIG_ENDIAN, and, on my Intel computer, if actual matrix is floating-point or int-32, the results of copying are incorrect.
When I've set native byte order (ByteOrder.nativeOrder(), i.e. LITTLE_ENDIAN on my computer), all works fine, but can I be sure that it will be correct on any platform? Does OpenCV Mat always use native byte order (ByteOrder.nativeOrder()) for storing non-byte elements?

**Comment by saudet** [comment]
Yes, OpenCV uses the native order of the machine, that's not related to
JavaCPP, although it does the same with IntPointer, FloatPointer, etc.

**Comment by Daniel-Alievsky** [comment]
Thank you!
