### ISSUE TITLE
Huge size of the java bindings for Leptonica

### ISSUE THREAD

**Issue by maximumspatium** [bytedeco/javacpp-presets#65]
Hello Samuel,

**Issue description:**

Tesseract has the binary dependency on Leptonica that currently counts about 2500 functions. Tesseract utilizes only 118 Leptonica functions.
Unfortunately, Leptonica has been designed as a huge monolithic library incorporating several independent image processing technologies. When Tesseract's dependencies are being resolved, the whole Leptonica library will be loaded into RAM but only 4,8% of its code will be actually used!

Moreover, the way Tesseract external API is designed, we have to go through Leptonica in order to be able to get Tesseract data in and out. Therefore, we need to have a java bindings for Leptonica which adds another 5,3 MB unused code laid out in RAM.

**Proposed solution:**

Add another JNI wrapper called "leptonica-min" that provides java bindings for the Leptonica functions used by the Tesseract external API. This (tiny) wrapper should be shipped together with the Leptonica preset.

Projects relying on Tesseract only could link to "leptonica-min" and thus save a significant amount of memory (5MB!!!). Projects relying on further Leptonica functionality could link to the full Leptonica wrapper instead provided in the same JAR.

**Question:**
What do you think of the above mentioned solution?

Best regards
Maxim

**Comment by saudet** [comment]
Sounds good! And if it's small enough, it could even be bundled with Tesseract, and we could save some more hassle that way. ;)

Is there already a "min" config readily available for Leptonica?

**Comment by maximumspatium** [comment]
> Is there already a "min" config readily available for Leptonica?

No, but I'm currently working on such a config. One thing I ain't quite sure about is which file to strip in order to achieve this goal. Leptonica presets contains two files: "presets/lept.java" and "lept.java". The former seems to be the main config as described in the Wiki's "Create new presets". The latter seems to be machine-generated. Its purpose is opaque to me...

Will it be enough to strip Java files? Or should I strip Leptonica's main header - "allheaders.h" - instead?

Thank you in advance!
Best regards
Maxim

**Comment by saudet** [comment]
You're going to need to modify Leptonica itself. The Java files are auto-generated yes, so we can do that after.

**Comment by saudet** [comment]
Hi there, any progress?

**Comment by saudet** [comment]
In my opinion, the effort required to save a few megs here is not worth it, so I'm closing this, but if you would still like to spend some time on this, please let me know! Thanks
