### ISSUE TITLE
Using BytePointer

### ISSUE THREAD

**Issue by icarusfire** [bytedeco/javacpp-presets#66]
I think this is a question rather than a issue.

I try to use Bytearray or inputstream as source of my image file. But pixRead() method accepts either a filepath or a BytePointer. So I tried something like this to convert my file to BytePointer:

     BytePointer b=new BytePointer();
     b.put (file.getBytes(), 0, (int)file.getBytes().length);
     lept.PIX image = pixRead(b);
But I got this error below;
    
    java.lang.UnsatisfiedLinkError:org.bytedeco.javacpp.BytePointer.put([BII)Lorg/bytedeco/javacpp/BytePointer;
	org.bytedeco.javacpp.BytePointer.put(Native Method)

How can I achieve this?

Thanks

**Comment by saudet** [comment]
`pixRead()` doesn't support loading from memory. You're going to need to use [`pixReadMem()`](http://bytedeco.org/javacpp-presets/leptonica/apidocs/org/bytedeco/javacpp/lept.html#pixReadMem-byte:A-long-) for that, and it conveniently supports `byte[]` as argument so no need to mess around with `BytePointer`. Enjoy! :)
