### ISSUE TITLE
Is there a guarantee that newly created Mat/UMat are zero-filled?

### ISSUE THREAD

**Issue by Daniel-Alievsky** [bytedeco/javacpp-presets#661]
Maybe it is a very simple question. Can you consult me: can be I sure that newly created matrix (Mat or UMat) is always filled by zeroes? 
`new opencv_core.UMat(height, width, source.type())`
(or Mat) - is it possible that the result will contain some random noise? (For Java arrays it is impossible: JVM guarantees that all new objects are zero-filled.)

If there is no such a guarantee, we of course, sometimes _must_ fill the new matrix by a direct call of put(zeroScalar) method. But in this case it makes sense to write about this in comments to the constructor.

**Comment by saudet** [comment]
There are constructors with a `Scalar s` parameter for that:
http://bytedeco.org/javacpp-presets/opencv/apidocs/org/bytedeco/javacpp/opencv_core.Mat.html#constructor.summary
If you wish to update something about this documentation, please file an issue upstream!

**Comment by Daniel-Alievsky** [comment]
Yes, I know, but constructor with Scalar works in 100 times slower. I hoped that there is a guarantee that simply created Mat/UMat are always zero (I didn't see any random data in it).

"Please file an issue" - I didn't understand, what should I do exactly?

**Comment by saudet** [comment]
Ask the developers of OpenCV to provide something that isn't 100 times slower, and also ask them to update their documentation if you're not satisfied with it. I'm not the one you should be talking about this!

**Comment by saudet** [comment]
That applies to all subclasses of [Pointer](http://bytedeco.org/javacpp/apidocs/org/bytedeco/javacpp/Pointer.html) in general. We could add a note about that in the documentation there. Please send a pull request!

**Comment by saudet** [comment]
BTW, there is a specialized factory method to create and initialize to zeros, so it should be efficient:
http://bytedeco.org/javacpp-presets/opencv/apidocs/org/bytedeco/javacpp/opencv_core.UMat.html#zeros-int-int-int-

**Comment by Daniel-Alievsky** [comment]
Yes, thank you. But actually they work with the same speed. Obviously, both methods fill the matrix by scalar value.
