### ISSUE TITLE
Couldn't get the expected result from drawContours function?

### ISSUE THREAD

**Issue by abbracadabra** [bytedeco/javacpp-presets#662]
Javacpp-opencv drawContours function produce different result than in python.  

I couldn't add images here.So could you checkout the same question i posted on [stackoverflow](https://stackoverflow.com/questions/53844313/javacpp-opencv-drawcontours-produce-different-result-than-in-python) that includes screenshots?
```
public static void main(String[] args){
    Mat im = imread("7KXY.png");
    cvtColor(im, im, CV_BGR2GRAY);
    threshold(im,im, 230, 255, THRESH_BINARY_INV);

    MatVector contours = new MatVector();
    Mat hierarchy = new Mat();
    findContours(im, contours,hierarchy,RETR_TREE  ,CHAIN_APPROX_SIMPLE);

    im = new Mat(im.rows(),im.cols(),CV_8UC1);
    drawContours(im, contours, -1, new Scalar(255), 1, 8, hierarchy, 2, new Point(0,0));
    imwrite( "ccc.jpg", im);
}
```

Below is code in python to use drawContours function

```
im = cv2.imread(r'7KXY.png')
im = cv2.cvtColor(im, cv2.COLOR_BGR2GRAY)
thresh,im = cv2.threshold(im, 230, 255, cv2.THRESH_BINARY_INV)

im2, contours, hierarchy = cv2.findContours(im, cv2.RETR_TREE , cv2.CHAIN_APPROX_SIMPLE)

im = np.zeros(im.shape).astype(dtype='uint8')
cv2.drawContours(im, contours, -1, (255), 1,8, hierarchy, 2,(0,0))
cv2.imwrite(r"asd.jpg",im)
```

My maven pom 
```
        <dependency>
            <groupId>org.bytedeco</groupId>
            <artifactId>javacv-platform</artifactId>
            <version>1.4.3</version>
        </dependency>
```

**Comment by abbracadabra** [comment]
So it worked after i downloaded opencv-***.jar and it's dll native library directly.   I still don't why it soesn't work   in javacv

**Comment by saudet** [comment]
Looks like there is a bug somewhere, looking into this.

BTW, the JavaCPP Presets also bundle the official Java API of OpenCV, so we can use those classes too.

**Comment by saudet** [comment]
Ah, I see what the issue is. `new Scalar(255)` creates an array of `Scalar` objects with undefined color, so that's not going to work:
http://bytedeco.org/javacpp-presets/opencv/apidocs/org/bytedeco/javacpp/opencv_core.Scalar.html#Scalar-long-
You'll need to call `new Scalar(255.0)` to have it do what you expect:
http://bytedeco.org/javacpp-presets/opencv/apidocs/org/bytedeco/javacpp/opencv_core.Scalar.html#Scalar-double-

**Comment by abbracadabra** [comment]
> Ah, I see what the issue is. `new Scalar(255)` creates an array of `Scalar` objects with undefined color, so that's not going to work:
> http://bytedeco.org/javacpp-presets/opencv/apidocs/org/bytedeco/javacpp/opencv_core.Scalar.html#Scalar-long-
> You'll need to call `new Scalar(255.0)` to have it do what you expect:
> http://bytedeco.org/javacpp-presets/opencv/apidocs/org/bytedeco/javacpp/opencv_core.Scalar.html#Scalar-double-

After changing to ```new Scalar(255.0)```,the contour did show up.But there are still some weird random dotted stripes.

**Comment by saudet** [comment]
That's just because you're not initializing the new `Mat` to anything.
