### ISSUE TITLE
How to read PDF files

### ISSUE THREAD

**Issue by icarusfire** [bytedeco/javacpp-presets#67]
When I try to ocr pdf files I get this error:

    Error in pixReadMem: Unknown format: no pix returned
    Error in pixGetDimensions: pix not defined
    ....

I read that Tesseract dont directly have pdf support and ghost script is needed, but only adding the dependency didn't help. Do I really have to first seperatly convert pdf to a png and THEN use the Javacpp? Or is there a better way?

Thanks

**Comment by saudet** [comment]
AFAIK, Leptonica and Tesseract don't support PDF as input at all. You're going to need to convert it do something else before, e.g.: http://kiirani.com/2013/03/22/tesseract-pdf.html
