### ISSUE TITLE
pixRead and pixDestroy missing

### ISSUE THREAD

**Issue by Azim-D3Tm** [bytedeco/javacpp-presets#671]
Ok, so i tried to follow example in the readme and it doesnt work, becouse there are no such methods as pixRead or pixDestroy
(tesseract)

**Comment by saudet** [comment]
They are part of Leptonica:
http://bytedeco.org/javacpp-presets/leptonica/apidocs/org/bytedeco/javacpp/lept.html#pixRead-java.lang.String-
http://bytedeco.org/javacpp-presets/leptonica/apidocs/org/bytedeco/javacpp/lept.html#pixDestroy-org.bytedeco.javacpp.lept.PIX-

**Comment by Azim-D3Tm** [comment]
Then why dont u update the readme to contain the **working** example?

**Comment by saudet** [comment]
It's working just fine for me. Send your fix as a pull request!

**Comment by saudet** [comment]
Or if you're still not able to make it work on your end, please provide more details (your platform, version of Java, your IDE or the commands you use to build, the exact error message you get, etc). Thanks
