### ISSUE TITLE
Do you have tutoiral of llvm？

### ISSUE THREAD

**Issue by SongBiu** [bytedeco/javacpp-presets#687]
How can I get the tutorial of llvm using java？

**Comment by saudet** [comment]
It's basically just the C API of LLVM. Here's one, for example:
https://pauladamsmith.com/blog/2015/01/how-to-get-started-with-llvm-c-api.html

**Comment by SongBiu** [comment]
thannks

**Comment by saudet** [comment]
Please let me know if you encounter any issues translating those examples in C to Java! Thanks
