### ISSUE TITLE
TensorFlow Scope.WithOpName missing for TensorFlow 1.13.0-rc1 

### ISSUE THREAD

**Issue by LBRIANMCGANN** [bytedeco/javacpp-presets#689]
Build with lastest commit 5a1020f  Feb 9, 2019 for macOS is missing WithOpName method for Scope class.

**Comment by saudet** [comment]
I see, they've changed the declaration in C++ a bit. Fixed in commit 0e8176b0b2417f350436f6b7cdbb1d4e8df46d9e.

Please let me know if you see anything else missing, and thanks for reporting!

**Comment by LBRIANMCGANN** [comment]
Thanks. Things work well now. Great project!
