### ISSUE TITLE
somebody is working at new version called clandmark ?

### ISSUE THREAD

**Issue by henriquem** [bytedeco/javacpp-presets#69]
Hello Guys,

I would like to know if is coming soon the version upgraded called clandmark in java ?

check out:
GitHub: https://github.com/uricamic/clandmark
website: http://cmp.felk.cvut.cz/~uricamic/clandmark/  

very exciting !

Cheers

**Comment by saudet** [comment]
I guess that would be something of interest to Jarek, so I'll him answer :)

**Comment by henriquem** [comment]
it will be nice!
We are anxiously waiting

**Comment by lloydmeta** [comment]
Just noticed that FLandmark was officially replaced by CLandmark according to the Flandmark website http://cmp.felk.cvut.cz/~uricamic/flandmark/

Looking at CLandmark, it looks quite nice, supporting more landmarks than Flandmark. 

If there's something I can help with to get this going, please let me know. I'm a beginner but I'm willing to pitch in !

**Comment by saudet** [comment]
@lloydmeta Start by checking out this guide here:
https://github.com/bytedeco/javacpp-presets/wiki/Create-New-Presets
CLankmark looks pretty easy to map, but let me know if you encounter errors you can't resolve! Thanks :)

**Comment by lloydmeta** [comment]
@saudet thanks, I'll take a look at that guide.

@jpsacha: you mentioned [here](https://github.com/uricamic/clandmark/issues/4#issuecomment-170260287) that you were already looking into it and I see you were assigned to this issue; is there something you can point me to that I can work off of? Any helpful info at all would help.

**Comment by omainegra** [comment]
Any news on this? It has been more than a year since the last comment.

**Comment by saudet** [comment]
No, I don't believe so. Would you like to give it a try? I can help you with any issues that you encounter.

**Comment by omainegra** [comment]
@saudet Definitely, I'll let you know if I need further assistance.

**Comment by lloydmeta** [comment]
Yeah, no I haven't made any progress. Turned out to be a tad more time consuming than I had anticipated :D

**Comment by saudet** [comment]
Something like flandmark/clandmark has been integrated in the opencv_face module of OpenCV 3.4.0: 
https://docs.opencv.org/master/d2/d42/tutorial_face_landmark_detection_in_an_image.html
Maybe we can consider flandmark/clandmark obsolete and close this issue?

**Comment by saudet** [comment]
I'll close this now that we can use the landmark functionality from OpenCV through the presets for `opencv_face` as of the release of version 1.4.1, but please let me know if there is anything OpenCV can't do that we can with CLandmark! Thanks
