### ISSUE TITLE
tensorflow 1.12 compatible CUDA cuDNN versions?

### ISSUE THREAD

**Issue by andyguo007** [bytedeco/javacpp-presets#695]
hi,

What are the versions of CUDA and cuDNN versions being used for tensorflow 1.12?

Thanks,
Andy

**Comment by saudet** [comment]
We can find that out by looking in the README.md file of that version:
https://github.com/bytedeco/javacpp-presets/tree/1.4.4/tensorflow
```xml
            <artifactId>cuda</artifactId>
            <version>10.0-7.4-1.4.4</version>
```
This means CUDA 10.0 and cuDNN 7.4.

**Comment by saudet** [comment]
BTW, if you need a different version, it's always possible to modify `cppbuild.sh` and rebuild from source.

**Comment by andyguo007** [comment]
Thanks!
