### ISSUE TITLE
tensorflow create string feed_dict

### ISSUE THREAD

**Issue by zhengdi1992** [bytedeco/javacpp-presets#699]

**Comment by zhengdi1992** [comment]
how to create Tensor with type of DT_STRING..
my python script can work fine as fellow:


`mock_input=np.array(["香蕉 苹果 西瓜"])
result1_,result2_,result3_ = sess.run([result1,result2,result3], feed_dict={features: mock_input})
`

for use the same .pb file..in javacpp tensorflow..
`tensorflow.Tensor mockInput = new tensorflow.Tensor(tensorflow.DT_STRING, new TensorShape(1,1));
StringArray inputArr = mockInput.createStringArray();
inputArr.position(0).put("香蕉 苹果 西瓜");
String[] inputNames = new String[]{"input1:0"};
tensorflow.Tensor[] inputTensors = new tensorflow.Tensor[]{mockInput};
StringTensorPairVector inputs = new StringTensorPairVector(inputNames, inputTensors);
`
.....
`
s = session.Run(inputs, outputTensorNames, targetTensorNames, outputs);
`
I get the error message is `input must be a vector, got shape: [1,1]`

I want to know if my input data was only one string, the op desc of mockInput shape is (?, 1),
at this time how to build the input Tensor in java code by javacpp tensorflow. 
thanks a lot for your help. :)


i has try some code but the same error.. :(
` tensorflow.Tensor mockInput = Tensor.create(new String[]{"香蕉 苹果 西瓜"}, new TensorShape(1, 1));`

`tensorflow.Tensor mockInput = new tensorflow.Tensor(tensorflow.DT_STRING, new TensorShape(1,1));
StringArray inputArr = mockInput.createStringArray();StringArray item = new StringArray();item.put("香蕉 苹果 西瓜");inputArr.put(item);`

**Comment by saudet** [comment]
A vector has typically only 1 dimension so try with new TensorShape(1).

**Comment by saudet** [comment]
That might not call the right constructor though, also try with new TensorShape(new long[]{1}).

**Comment by saudet** [comment]
Let me know if you have any other issues concerning this! Thanks

**Comment by zhengdi1992** [comment]
thanks a lot..
