### ISSUE TITLE
For android unable to get all .so files for Opencv and ffmpeg

### ISSUE THREAD

**Issue by Himanshu4003** [bytedeco/javacpp-presets#70]
I am following this instruction  [javacpp-presets build ](https://github.com/bytedeco/javacpp-presets#build-instructions).

Now when i run following command .

ANDROID_NDK=/home/ubbvand2/Himanshu/adt-bundle-linux-x86_64-20140321/sdk/ndk-bundle/ bash cppbuild.sh -platform android-arm install '/home/ubbvand2/Himanshu/JavaCpp/javacpp-presets/ffmpeg'

It works file and i get following libs 

libavcodec.so,libavdevice.so,libavfilter.so,libavformat.so,libavutil.so,libpostproc.so,libswresample.so,libswscale.so.

While from this gradle build compile group: 'org.bytedeco.javacpp-presets', name: 'ffmpeg', version: '2.6.1-0.11', classifier: 'android-arm' i am getting 16 so file double of my generated from builds steps and i can see that another 8 so file are same name just they have libjni .

Can you point me how to generate missing libjni so files ?

**Comment by saudet** [comment]
We need to run `mvn install` for that...

**Comment by Himanshu4003** [comment]
i just try it and get following error 

Command: mvn install --projects .,opencv,ffmpeg

[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.bytedeco.javacpp-presets:opencv:jar:3.0.0-1.0-SNAPSHOT
[WARNING] 'version' contains an expression but should be a constant. @ org.bytedeco.javacpp-presets:opencv:3.0.0-${project.parent.version}, /home/ubbvand2/Himanshu/JavaCpp/javacpp-presets/opencv/pom.xml, line 14, column 12
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.bytedeco.javacpp-presets:ffmpeg:jar:2.7-1.0-SNAPSHOT
[WARNING] 'version' contains an expression but should be a constant. @ org.bytedeco.javacpp-presets:ffmpeg:2.7-${project.parent.version}, /home/ubbvand2/Himanshu/JavaCpp/javacpp-presets/ffmpeg/pom.xml, line 14, column 12
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.bytedeco.javacpp-presets:flycapture:jar:2.7.3.19-1.0-SNAPSHOT
[WARNING] 'version' contains an expression but should be a constant. @ org.bytedeco.javacpp-presets:flycapture:2.7.3.19-${project.parent.version}, /home/ubbvand2/Himanshu/JavaCpp/javacpp-presets/flycapture/pom.xml, line 14, column 12
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.bytedeco.javacpp-presets:libdc1394:jar:2.2.3-1.0-SNAPSHOT
[WARNING] 'version' contains an expression but should be a constant. @ org.bytedeco.javacpp-presets:libdc1394:2.2.3-${project.parent.version}, /home/ubbvand2/Himanshu/JavaCpp/javacpp-presets/libdc1394/pom.xml, line 14, column 12
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.bytedeco.javacpp-presets:libfreenect:jar:0.5.2-1.0-SNAPSHOT
[WARNING] 'version' contains an expression but should be a constant. @ org.bytedeco.javacpp-presets:libfreenect:0.5.2-${project.parent.version}, /home/ubbvand2/Himanshu/JavaCpp/javacpp-presets/libfreenect/pom.xml, line 14, column 12
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.bytedeco.javacpp-presets:videoinput:jar:0.200-1.0-SNAPSHOT
[WARNING] 'version' contains an expression but should be a constant. @ org.bytedeco.javacpp-presets:videoinput:0.200-${project.parent.version}, /home/ubbvand2/Himanshu/JavaCpp/javacpp-presets/videoinput/pom.xml, line 14, column 12
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.bytedeco.javacpp-presets:artoolkitplus:jar:2.3.1-1.0-SNAPSHOT
[WARNING] 'version' contains an expression but should be a constant. @ org.bytedeco.javacpp-presets:artoolkitplus:2.3.1-${project.parent.version}, /home/ubbvand2/Himanshu/JavaCpp/javacpp-presets/artoolkitplus/pom.xml, line 14, column 12
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.bytedeco.javacpp-presets:flandmark:jar:1.07-1.0-SNAPSHOT
[WARNING] 'version' contains an expression but should be a constant. @ org.bytedeco.javacpp-presets:flandmark:1.07-${project.parent.version}, /home/ubbvand2/Himanshu/JavaCpp/javacpp-presets/flandmark/pom.xml, line 14, column 12
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.bytedeco.javacpp-presets:fftw:jar:3.3.4-1.0-SNAPSHOT
[WARNING] 'version' contains an expression but should be a constant. @ org.bytedeco.javacpp-presets:fftw:3.3.4-${project.parent.version}, /home/ubbvand2/Himanshu/JavaCpp/javacpp-presets/fftw/pom.xml, line 14, column 12
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.bytedeco.javacpp-presets:gsl:jar:1.16-1.0-SNAPSHOT
[WARNING] 'version' contains an expression but should be a constant. @ org.bytedeco.javacpp-presets:gsl:1.16-${project.parent.version}, /home/ubbvand2/Himanshu/JavaCpp/javacpp-presets/gsl/pom.xml, line 14, column 12
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.bytedeco.javacpp-presets:llvm:jar:3.6.1-1.0-SNAPSHOT
[WARNING] 'version' contains an expression but should be a constant. @ org.bytedeco.javacpp-presets:llvm:3.6.1-${project.parent.version}, /home/ubbvand2/Himanshu/JavaCpp/javacpp-presets/llvm/pom.xml, line 14, column 12
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.bytedeco.javacpp-presets:leptonica:jar:1.72-1.0-SNAPSHOT
[WARNING] 'version' contains an expression but should be a constant. @ org.bytedeco.javacpp-presets:leptonica:1.72-${project.parent.version}, /home/ubbvand2/Himanshu/JavaCpp/javacpp-presets/leptonica/pom.xml, line 14, column 12
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.bytedeco.javacpp-presets:tesseract:jar:3.03-rc1-1.0-SNAPSHOT
[WARNING] 'version' contains an expression but should be a constant. @ org.bytedeco.javacpp-presets:tesseract:3.03-rc1-${project.parent.version}, /home/ubbvand2/Himanshu/JavaCpp/javacpp-presets/tesseract/pom.xml, line 14, column 12
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.bytedeco.javacpp-presets:caffe:jar:master-1.0-SNAPSHOT
[WARNING] 'version' contains an expression but should be a constant. @ org.bytedeco.javacpp-presets:caffe:master-${project.parent.version}, /home/ubbvand2/Himanshu/JavaCpp/javacpp-presets/caffe/pom.xml, line 14, column 12
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.bytedeco.javacpp-presets:cuda:jar:7.0-1.0-SNAPSHOT
[WARNING] 'version' contains an expression but should be a constant. @ org.bytedeco.javacpp-presets:cuda:7.0-${project.parent.version}, /home/ubbvand2/Himanshu/JavaCpp/javacpp-presets/cuda/pom.xml, line 14, column 12
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO] Inspecting build with total of 16 modules...
[INFO] Not installing Nexus Staging features:
[INFO]  * Preexisting staging related goal bindings found in 16 modules.
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] JavaCPP Presets
[INFO] JavaCPP Presets for OpenCV
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building JavaCPP Presets 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-install-plugin:2.3:install (default-install) @ javacpp-presets ---
[INFO] Installing /home/ubbvand2/Himanshu/JavaCpp/javacpp-presets/pom.xml to /root/.m2/repository/org/bytedeco/javacpp-presets/1.0-SNAPSHOT/javacpp-presets-1.0-SNAPSHOT.pom
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building JavaCPP Presets for OpenCV 3.0.0-1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for org.bytedeco:javacpp:jar:1.0-SNAPSHOT is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] JavaCPP Presets ................................... SUCCESS [0.224s]
[INFO] JavaCPP Presets for OpenCV ........................ FAILURE [0.201s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.219s
[INFO] Finished at: Thu Jul 09 19:24:45 IST 2015
[INFO] Final Memory: 12M/148M
[INFO] ------------------------------------------------------------------------
[ERROR] Plugin org.bytedeco:javacpp:1.0-SNAPSHOT or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.bytedeco:javacpp:jar:1.0-SNAPSHOT: Could not find artifact org.bytedeco:javacpp:pom:1.0-SNAPSHOT -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginResolutionException


i have check both .pom file of ffmpeg and opencv and they have 

in Opencv 

<parent>
    <groupId>org.bytedeco</groupId>
    <artifactId>javacpp-presets</artifactId>
    <version>1.0-SNAPSHOT</version>
  </parent>

in ffmpeg 

<parent>
    <groupId>org.bytedeco</groupId>
    <artifactId>javacpp-presets</artifactId>
    <version>1.0-SNAPSHOT</version>
  </parent>

**Comment by saudet** [comment]
Please run  `mvn install` on the javacpp module first!
