### ISSUE TITLE
Tesseract inconsistent results

### ISSUE THREAD

**Issue by luke-rogers** [bytedeco/javacpp-presets#702]
Tesseract version - 4.0.0-1.4.4
Using engine mode 0 as latest doesnt support `tessedit_char_whitelist`

When using tesseract previous image results have side effects.

For example if I read _Image 1_ alone I get the correct results.
However If I read _Image 2_ and then read _Image 1_, the read of _Image 1_ is not correct and different from when I just read _Image 1_ alone.

The tesseract documentation details the following
> Try to turn off the adaptive classifier by setting the config variable classify_enable_learning to 0, or to clear the adaptive data with the method ClearAdaptiveClassifier().

Sample service code
```java
public String performOcr(File target) {
        tesseract.TessBaseAPI api = new tesseract.TessBaseAPI();
        if (api.Init(getTessDataPath(), "eng", 0) != 0) {
            throw new RuntimeException("Unable to initialize tesseract");
        }
        // not supported without oem 0
        api.SetVariable("tessedit_char_whitelist", "abcABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789.,-");
        api.SetVariable("load_system_dawg", "false");
        api.SetVariable("load_freq_dawg", "false");
        api.SetVariable("classify_enable_learning ", "0");

        // Open input image with leptonica library
        lept.PIX image = pixRead(target.getAbsolutePath());
        api.SetImage(image);
        api.SetSourceResolution(300);

        // Get OCR result
        BytePointer resultPointer = api.GetUTF8Text();
        String result = resultPointer.getString();
        LOGGER.info(result);

        // Destroy used object and release memory
        api.ClearAdaptiveClassifier();
        api.End();
        resultPointer.deallocate();
        pixDestroy(image);

        return result;
    }
```

Sample test code
```java
@Test
public void output_test() throws IOException {
        UkDrivingLicenceOcrService service1 = new UkDrivingLicenceOcrService(new TesseractService());
        final UkDrivingLicence read1 = service1.read(new MockMultipartFile("licence-1.jpg", getClass().getResourceAsStream("/licence-1.jpg")));
        System.out.println(read1);

        final UkDrivingLicence read2 = service1.read(new MockMultipartFile("license-2.jpg", getClass().getResourceAsStream("/license-2.jpg")));
        System.out.println(read2);
    }
```

Further details

- https://github.com/tesseract-ocr/tesseract/wiki/FAQ#there-are-inconsistent-results-from-tesseract-when-the-same-tessbaseapi-object-is-used-for-decoding-multiple-images
- https://groups.google.com/forum/#!topic/tesseract-ocr/ByGJhocI9qQ

Not sure if this is the correct place for this issue or if it should be in the tesseract project itsself.

**Comment by saudet** [comment]
Can you reproduce this issue in C++? If so, this should be reported upstream, yes.

**Comment by luke-rogers** [comment]
I am not familiar with C++ but can give it a go.

**Comment by saudet** [comment]
Have you tried to turn off the adaptive classifier? That sounds like the first thing I would try :)

**Comment by saudet** [comment]
I see that you tried, but you've got an extra space in the name here that won't work:
```java
api.SetVariable("classify_enable_learning ", "0");
```

**Comment by luke-rogers** [comment]
Good spot, although still doesnt work without the space at the end.
Tried both `classify_enable_learning` and `classify_enable_adaptive_matcher` which seem to make no difference.

I am creating a new instance of the `TessBaseAPI` for every call. Not sure what else I can really do.
