### ISSUE TITLE
How to get TessBaseAPI.PrintVariables to work?

### ISSUE THREAD

**Issue by schmitzCatz** [bytedeco/javacpp-presets#704]
Hi,

As you can see from the titel, I have problems to get TessBaseAPI.PrintVariavles to work, since this method need a FILE* pointer which I do not have ;-(. Can anybody point me in the right direction to work with file pointer's within the javacpp Environment?

I appreciate the help. Thank you.

**Comment by saudet** [comment]
There is also `TessBaseAPIPrintVariables()`, is this sufficient?

**Comment by schmitzCatz** [comment]
Yap that will do, thank you!
