### ISSUE TITLE
Missing MKL VML DLL

### ISSUE THREAD

**Issue by kinnally** [bytedeco/javacpp-presets#705]
When calling org.bytedeco.javacpp.mkl_rt.vdAdd(...), I get this error:

Intel MKL FATAL ERROR: cannot load mkl_vml_avx2.dll or mkl_vml_def.dll

I could probably manually install MKL, and add that to my path, but since mkl_rt is already in a jar, it might make sense to also add the various vml dlls to a jar (at least mkl_vml_avx, amkl_vml_avx2, and mkl_vml_avx512). It would also be good if the right one was used for the machine that the user is on.

**Comment by kinnally** [comment]
These are my pom dependencies:
<dependencies>
    <dependency>
      <groupId>org.bytedeco.javacpp-presets</groupId>
      <artifactId>mkl-platform</artifactId>
      <version>2019.1-1.4.4</version>
    </dependency>

    
    <dependency>
      <groupId>org.bytedeco.javacpp-presets</groupId>
      <artifactId>mkl</artifactId>
      <version>2019.1-1.4.4</version>
      <classifier>linux-x86-redist</classifier>
    </dependency>
    <dependency>
      <groupId>org.bytedeco.javacpp-presets</groupId>
      <artifactId>mkl</artifactId>
      <version>2019.1-1.4.4</version>
      <classifier>linux-x86_64-redist</classifier>
    </dependency>
    <dependency>
      <groupId>org.bytedeco.javacpp-presets</groupId>
      <artifactId>mkl</artifactId>
      <version>2019.1-1.4.4</version>
      <classifier>macosx-x86_64-redist</classifier>
    </dependency>
    <dependency>
      <groupId>org.bytedeco.javacpp-presets</groupId>
      <artifactId>mkl</artifactId>
      <version>2019.1-1.4.4</version>
      <classifier>windows-x86-redist</classifier>
    </dependency>
    <dependency>
      <groupId>org.bytedeco.javacpp-presets</groupId>
      <artifactId>mkl</artifactId>
      <version>2019.1-1.4.4</version>
      <classifier>windows-x86_64-redist</classifier>
    </dependency>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <scope>test</scope>
    </dependency>

  </dependencies>

**Comment by saudet** [comment]
Done! Let me know if there's anything else missing. MKL already loads the right ones by itself at runtime.

**Comment by kinnally** [comment]
Awesome - thank you for adding this so quickly!

I'm not certain at the moment, but I think that should be everything for my intended use. I'm also interested in using VSL (the fast random number generators and stats tools), which also uses the VML dll, along with mkl_rt.dll - I can't say for sure, but I don't think there are other dlls required for that.
