### ISSUE TITLE
ffmpeg fails because libmfx is missing

### ISSUE THREAD

**Issue by johntwill** [bytedeco/javacpp-presets#707]
It looks like libmfx is part of some seperate mediasdk from intel?  How do I install that and get the config to see it?

**Comment by saudet** [comment]
You don't need to, it gets bundled. What error message are you getting?

**Comment by johntwill** [comment]
require libmfx mfx/mfxvideo.h MFXInit -lmfx
check_lib libmfx mfx/mfxvideo.h MFXInit -lmfx
check_func_headers mfx/mfxvideo.h MFXInit -lmfx
test_ld cc -lmfx
test_cc
BEGIN /tmp/ffconf.PaoMzgxu/test.c
    1	#include <mfx/mfxvideo.h>
    2	#include <stdint.h>
    3	long check_MFXInit(void) { return (long) MFXInit; }
    4	int main(void) { int ret = 0;
    5	 ret |= ((intptr_t)check_MFXInit) & 0xFFFF;
    6	return ret; }
END /tmp/ffconf.PaoMzgxu/test.c
gcc -m64 -D_ISOC99_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_POSIX_C_SOURCE=200112 -D_XOPEN_SOURCE=600 -DPIC -I ../include/freetype2/ -I../include/ -std=c11 -fomit-frame-pointer -fPIC -I/home/x/git/javacpp-presets/ffmpeg/cppbuild/linux-x86_64/include -pthread -I/home/x/git/javacpp-presets/ffmpeg/cppbuild/linux-x86_64/include -c -o /tmp/ffconf.PaoMzgxu/test.o /tmp/ffconf.PaoMzgxu/test.c
gcc -m64 -L../lib/ -Wl,--as-needed -Wl,-z,noexecstack -o /tmp/ffconf.PaoMzgxu/test /tmp/ffconf.PaoMzgxu/test.o -lmfx -lstdc++ -lpthread -ldl -lz -lm -lva-drm -lva-x11 -lva
../lib//libmfx.a(libmfx_la-main.o): In function `MFXClose':
main.cpp:(.text+0x12ca): undefined reference to `mfx_deallocate_va'
../lib//libmfx.a(libmfx_la-main.o): In function `init_internal_hwctx(_mfxSession*)':
main.cpp:(.text+0x1fa6): undefined reference to `mfx_allocate_va'
collect2: error: ld returned 1 exit status
ERROR: libmfx not found

**Comment by saudet** [comment]
I see, you're trying to build from source. Follow these instructions, and everything will work fine:
https://github.com/bytedeco/javacpp-presets/wiki/Build-Environments

**Comment by johntwill** [comment]
Thanks!  So ffmpeg builds inside the docker environment, but I had to get and use  a newer version of maven.  I'm new to docker... how do I copy out the results of the build to the host machine?

btw, opencv also worked but flycapture failed

**Comment by saudet** [comment]
We can use "docker cp", we can also mount external volumes to have it share
directories with the host, such as ~/.m2.

**Comment by saudet** [comment]
If you don't need some of them like flycapture, just skip them.
