### ISSUE TITLE
[hwaccel]How to enable hardware acceleration in ffmpeg of javacv

### ISSUE THREAD

**Issue by Cesareans** [bytedeco/javacpp-presets#708]

**Comment by saudet** [comment]
Duplicate of https://github.com/bytedeco/javacv/issues/1154 and https://github.com/bytedeco/javacv/issues/1163

Call something like `setOption("hwaccel", "cuvid")`, `setOption("hwaccel", "h264_videotoolbox")`, etc.

**Comment by Cesareans** [comment]
Thks, I just tried and the effect seems awesome. But there are another problem that are if i can use CUDA or  other to give javacv full GPU acceleration.

**Comment by saudet** [comment]
If you need encoding, we can use "h264_cuvid", for example, see issue https://github.com/bytedeco/javacv/issues/1154.

**Comment by Cesareans** [comment]
Actually i need both encoding and decoding. Can i still use "h264_cuvid" for codec of both are not ".h264", "vp8" in encoding for example.

**Comment by saudet** [comment]
All details about what is supported are here:
https://trac.ffmpeg.org/wiki/HWAccelIntro

**Comment by Cesareans** [comment]
Oh, i see. And the last problem, is recorder.setVideoCodec(avcodec.AV_CODEC_ID_H264) the same with grab.setVideoCodecName("h264_cuvid");

**Comment by saudet** [comment]
`setVideoCodecName()` overrides `setVideoCodec()`, so we don't need to set the latter, but you can leave it there if that's convenient.
