### ISSUE TITLE
Does tensorflow 1.12 come with tftrt (tensorflow-tensorrt)?

### ISSUE THREAD

**Issue by andyguo007** [bytedeco/javacpp-presets#709]
hi,
When I tried to load a frozen graph (optimised with python tftrt API), there was an exception:

java.lang.RuntimeException: Op type not registered 'TRTEngineOp' in binary running on ***. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing (e.g.) `tf.contrib.resampler` should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed.

Any idea?

Thanks,
Andy

**Comment by saudet** [comment]
Not yet, no, but this is something that is planned, yes. If you are willing to help with this, it would be great!

**Comment by andyguo007** [comment]
would love to, but not familiar with C++ at all.

**Comment by saudet** [comment]
The updated build for TensorFlow 1.14.0-rc0 should now include support for TensorRT.
Could you give it a try with the snapshots? http://bytedeco.org/builds/

**Comment by saudet** [comment]
TensorFlow 1.14.0 included in version 1.5.1 should now work with these models. Please let me know if it still doesn't work though. Thanks!
