### ISSUE TITLE
Using Bytedeco along with Proguard on Android

### ISSUE THREAD

**Issue by Anriod** [bytedeco/javacpp-presets#710]
I'm using SNAPSHOTS for openblas and opencv on android alongside DL4J. I'm trying to compile a release apk with Proguard to shrink the dependencies as currently it comes to around 135 MB. However the META-INF/versions/9/module-info.class seems to be leading to errors. Something like this - 
```
Warning: class [META-INF/versions/9/module-info.class] unexpectedly contains class [module-info]
Note: duplicate definition of program class [module-info]
Note: there were 20 duplicate class definitions.
      (http://proguard.sourceforge.net/manual/troubleshooting.html#duplicateclass)
Warning: there were 21 classes in incorrectly named files.
         You should make sure all file names correspond to their class names.
         The directory hierarchies must correspond to the package hierarchies.
```
This is true for all bytedeco dependencies. I realize this is probably a Proguard issue but the documentation on this is very sparse and no solutions seem to work. Is there anything that can be done on this side of things?

**Comment by saudet** [comment]
That's actually an issue with Android Studio. It's fixed with recent
versions.

**Comment by Anriod** [comment]
I'm using Android Studio 3.3.2

**Comment by saudet** [comment]
Ok, so it's just ProGuard complaining about duplicate files? Just exclude it, or pick one of them, see issue https://github.com/bytedeco/javacv/issues/353 for some example on how to do that.

**Comment by Anriod** [comment]
@saudet As per  bytedeco/javacv#353 I tried to using pickFirst or exclude flags to avoid this - 
```
packagingOptions {
        pickFirst 'META-INF/versions/9/module-info.class'
        exclude 'META-INF/DEPENDENCIES'
        exclude 'META-INF/DEPENDENCIES.txt'
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/LICENSE.txt'
        exclude 'META-INF/license.txt'
        exclude 'META-INF/NOTICE'
        exclude 'META-INF/NOTICE.txt'
        exclude 'META-INF/notice.txt'
        exclude 'META-INF/INDEX.LIST'
    }
```
This leads to no change. Also apart from duplicate classes , it complains about - 
```
Warning: there were 21 classes in incorrectly named files.
         You should make sure all file names correspond to their class names.
         The directory hierarchies must correspond to the package hierarchies.
```

**Comment by saudet** [comment]
It's only a warning, just ignore it until ProGuard fixes this. If this is a problem for you though, please report that issue upstream.

**Comment by Anriod** [comment]
It seems to be the thing preventing a successful build.  I'll take it up with them. Thanks for your time and effort.
