### ISSUE TITLE
cpython call python class instance many time with build only once

### ISSUE THREAD

**Issue by zhengdi1992** [bytedeco/javacpp-presets#713]
as the python script...named model.py
```
#!/usr/bin/python
# -*- coding: utf-8 -*-

class Model:

    def __init__(self, name):
        print("init.....")
        self.name = name
        self.info = [1,2,3] 

    def predict(self, param):
        print("predict....")
        print(param)
        print(self.info)
```
do you have any more example for exec python script...? as this case, i want to init the model only once, and call predict method for many times in java env...

i hava try like this:
```
PyObject pName = python.PyUnicode_DecodeFSDefault("myclass");
PyObject pModule = PyImport_Import(pName);   // keep the instance for build once
PyObject initFunc = python.PyObject_GetAttrString(pModule, "__init__");
PyObject_CallObject(initFunc, initArgs);

PyObject predictFunc = python.PyObject_GetAttrString(pModule, "__init__");
...
pValue = PyObject_CallObject(predictFunc, predictArgs);
```
and find `ModuleNotFoundError: No module named 'myclass'`
maybe i should change the `$PYTHONPATH`, can i use the api `python.PySys_SetPath(path)`
to do this job? but i'm confused to know how to build the `path`
`CharPointer path = new CharPointer("")` was not work it out..

perhaps any other best practice？i have already choose a folly try...

**Comment by saudet** [comment]
We can set the `PYTHONPATH` environment variable or call `PySys_SetPath()`, among other options, yes, but I found that modifying directly the `PySys_GetObject("path")` list is easier. There is an example of that in the sample usage for NumPy:
https://github.com/bytedeco/javacpp-presets/tree/master/numpy#the-matmuljava-source-file
Let me know if that doesn't work for you though.

**Comment by zhengdi1992** [comment]
cool, it works..
but `PyList_Insert(PySys_GetObject("path"), 0, PyUnicode_FromString(path));
` is local change or global change？

i have build a platform for python script run...
if the api was global affect , will it cause many module conflicts , of cause i should manage everyone's script file namespace..

**Comment by zhengdi1992** [comment]
and another question..the param cpp --> python is immutable？and how easy and better get the string result from python..

i simple the case like that
```
Pointer program = Py_DecodeLocale(TestCPython.class.getSimpleName(), null);
Py_SetProgramName(program);  /* optional but recommended */
Py_Initialize();
String path = cachePackage().getAbsolutePath();
PyList_Insert(PySys_GetObject("path"), 0, PyUnicode_FromString(path));
PyObject pName = PyUnicode_FromString("test");
PyObject pModule = PyImport_Import(pName);
PyObject runFn = PyObject_GetAttrString(pModule, "run");
PyObject runArgs = PyTuple_New(1);
PyTuple_SetItem(runArgs, 0, PyBytes_FromString("hello-cpython"));
PyObject result = PyObject_Call(runFn, runArgs, PyDict_New());
System.out.println(PyBytes_AsString(result).getString());
```
and python script was:
```
#!/usr/bin/python
# -*- coding: utf-8 -*-

def run(strParam):
    return strParam                //can works fine and print hello-cpython
#    return strParam[1]         //can not get the result fine PyBytes_AsString(result) return null ?
#    return str('hello-cpython') // the same error with return strParam[1] ...
```

**Comment by saudet** [comment]
`sys.path` is a runtime variable, it doesn't change anything on the system:
https://docs.python.org/3/library/sys.html#sys.path

A `String` object in Java is immutable, yes, so it cannot share memory with other objects.
Use `BytePointer`, `CharPointer`, and `IntPointer` to share character buffers with Python.

**Comment by zhengdi1992** [comment]
so in that case python script:
`#    return str('hello-cpython') // the same error with return strParam[1] ...`
can not get the String result by this api ?
`PyBytes_AsString(result).getString()`
there PyObject result see as BytePointer ?

**Comment by saudet** [comment]
Sure, it works just the same as it would in C:
https://docs.python.org/3/c-api/bytes.html#c.PyBytes_AsString
You probably don't have an object of the right type, check TypeError.

**Comment by zhengdi1992** [comment]
can i get the std stream like the error stream`PyErr_Print()`? for get the  print in python script
`print('hello')` in console..

**Comment by saudet** [comment]
I don't know, is there a function in the C API for that?

**Comment by zhengdi1992** [comment]
i can't find so.. :(
i just want to find a easy way for debug...
like your sample
```
PyRun_SimpleStringFlags("from time import time,ctime\n"
                              + "print('Today is', ctime(time()))\n", null);
```
this can get the `Today is xxx` in terminal console...

but in that case:
`PyObject_Call(runFn, runArgs, PyDict_New());`

```
#!/usr/bin/python
# -*- coding: utf-8 -*-

#import io, sys
#sys.stdout = io.StringIO()

def run(strParam):
    print('test info ')
    #sys.stderr.write(sys.stdout.getvalue())
    return str('hello-cpython')
```
can not get the `test info` in console.. even if redirect it to `sys.stderr` and get nothing from `PyErr_Print()`?

**Comment by zhengdi1992** [comment]
it works by 
`PyBytes_AsString(PyUnicode_AsUTF8String(result)).getString()`
you're right the unicode type for python...but maybe directly return `strParam` from the method param  was string..than `PyBytes_AsString` can works well.
