### ISSUE TITLE
Fatal error ffmpeg transcoding

### ISSUE THREAD

**Issue by ray-morehead** [bytedeco/javacpp-presets#714]
Copying the official transcoding example from the ffmpeg site.  There is a method 

avfilter_graph_create_filter(&buffersink_ctx, buffersink, "out",
                NULL, NULL, filter_graph);

This populates the filter_graph with an output filter of null.  This should not happen.  Later the program tests for null values (fatal error) and also tests for filter->src, which of course crashes since the filter is null.  see line 316
[transcoder.txt](https://github.com/bytedeco/javacpp-presets/files/3084702/transcoder.txt)

**Comment by saudet** [comment]
Could you propose a patch and send a pull request to fix this issue?

**Comment by ray-morehead** [comment]
no clue

**Comment by saudet** [comment]
Well, it's working fine in FFmpegFrameFilter, so just do like that:
https://github.com/bytedeco/javacv/blob/master/src/main/java/org/bytedeco/javacv/FFmpegFrameFilter.java
