### ISSUE TITLE
I need someone to help me with custom presets

### ISSUE THREAD

**Issue by ConeyLiu** [bytedeco/javacpp-presets#72]
I need someone to help me to solve the problem which describe as follow.when I call "mvn clean packages --project *" ,there is a error ,declare as follow:

```
home/lxy/git/javacpp-presets_bak/videoabstraction1/target/classes/org/bytedeco/javacpp/jniCtracker.cpp:1185:20: 错误： ‘operator=’在‘ptr->CTracker::tracks = * ptr0’中没有匹配
/home/lxy/git/javacpp-presets_bak/videoabstraction1/target/classes/org/bytedeco/javacpp/jniCtracker.cpp:1185:20: 附注： 备选是：
/usr/include/c++/4.6/bits/vector.tcc:161:5: 附注： std::vector<_Tp, _Alloc>& std::vector<_Tp, _Alloc>::operator=(const std::vector<_Tp, _Alloc>&) [with _Tp = CTrack*, _Alloc = std::allocator<CTrack*>]
/usr/include/c++/4.6/bits/vector.tcc:161:5: 附注：   no known conversion for argument 1 from ‘char’ to ‘const std::vector<CTrack*>&’
/home/lxy/git/javacpp-presets_bak/videoabstraction1/target/classes/org/bytedeco/javacpp/jniCtracker.cpp: 在函数‘void Java_org_bytedeco_javacpp_Ctracker_00024CTracker_Update(JNIEnv*, jobject, jobject, jint, jint)’中:
/home/lxy/git/javacpp-presets_bak/videoabstraction1/target/classes/org/bytedeco/javacpp/jniCtracker.cpp:1222:38: 错误： 对‘CTracker::Update(char&, jint&, jint&)’的调用没有匹配的函数
/home/lxy/git/javacpp-presets_bak/videoabstraction1/target/classes/org/bytedeco/javacpp/jniCtracker.cpp:1222:38: 附注： 备选是：
/home/lxy/git/javacpp-presets_bak/videoabstraction1/cppbuild/linux-x86_64/include/Ctracker.h:48:10: 附注： void CTracker::Update(std::vector<PPoint_>&, int, int)
/home/lxy/git/javacpp-presets_bak/videoabstraction1/cppbuild/linux-x86_64/include/Ctracker.h:48:10: 附注：   no known conversion for argument 1 from ‘char’ to ‘std::vector<PPoint_>&’
/home/lxy/git/javacpp-presets_bak/videoabstraction1/target/classes/org/bytedeco/javacpp/jniCtracker.cpp: 在函数‘_jobject* Java_org_bytedeco_javacpp_Ctracker_00024CTrack_trace__Lorg_bytedeco_javacpp_Pointer_2(JNIEnv*, jobject, jobject)’中:
/home/lxy/git/javacpp-presets_bak/videoabstraction1/target/classes/org/bytedeco/javacpp/jniCtracker.cpp:1627:19: 错误： ‘operator=’在‘ptr->CTrack::trace = * ptr0’中没有匹配
/home/lxy/git/javacpp-presets_bak/videoabstraction1/target/classes/org/bytedeco/javacpp/jniCtracker.cpp:1627:19: 附注： 备选是：
/usr/include/c++/4.6/bits/vector.tcc:161:5: 附注： std::vector<_Tp, _Alloc>& std::vector<_Tp, _Alloc>::operator=(const std::vector<_Tp, _Alloc>&) [with _Tp = PPoint_, _Alloc = std::allocator<PPoint_>]
/usr/include/c++/4.6/bits/vector.tcc:161:5: 附注：   no known conversion for argument 1 from ‘char’ to ‘const std::vector<PPoint_>&’
```

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
Here is the head file :

``` cpp
  class CTrack
{
public:
    //vector<Point2d> trace;
    vector<PPoint_> trace;
    static size_t NextTrackID;
    int frame_begin;
    int track_del_flag;
    int frame_end;
    size_t track_id;
    size_t skipped_frames;
    Point2d prediction;
    TKalmanFilter* KF;
    CTrack(Point2f p, float dt, float Accel_noise_mag);
    ~CTrack();
};


class CTracker
{
public:
    float dt;
    float Accel_noise_mag;
    double dist_thres;
    int maximum_allowed_skipped_frames;
    int max_trace_length;
    FILE *fp_11;
    vector<CTrack*> tracks;
    void Update(vector<PPoint_>& detections,int frame_number_,int end_flag);
    void find_each_track_begin_number(int frame_number_);
    CTracker(float _dt, float _Accel_noise_mag, double _dist_thres=60, int _maximum_allowed_skipped_frames=30,int _max_trace_length=10);
    ~CTracker(void);
};
```

////////////////////////////////////////////////////////////////////////////////////////
follow is my presets file:

``` java
       public void map(InfoMap infoMap) {
        infoMap.put(new Info("PPoint_").cast().pointerTypes("Pointer"));
        infoMap.put(new Info("vector<PPoint_>").pointerTypes("Pointer"));
        infoMap.put(new Info("vector<PPoint_>").cast().pointerTypes("PPoint_Vector").define());

        infoMap.put(new Info("size_t").cast().pointerTypes("Pointer"));
        infoMap.put(new Info("Point2d").cast().pointerTypes("Pointer"));

        infoMap.put(new Info("TKalmanFilter").cast().pointerTypes("Pointer"));
        infoMap.put(new Info("TKalmanFilter*").cast().valueTypes("TKalmanFilter"));

        infoMap.put(new Info("Point2f").cast().pointerTypes("Pointer"));

        infoMap.put(new Info("FILE").cast().pointerTypes("Pointer"));
        infoMap.put(new Info("FILE *").cast().valueTypes("FILE"));

        infoMap.put(new Info("CTrack*").cast().valueTypes("CTrack"));
        infoMap.put(new Info("vector<CTrack*>").pointerTypes("Pointer"));
        infoMap.put(new Info("vector<CTrack*>").cast().pointerTypes("CTrackVector").define());
```

**Comment by saudet** [comment]
What happens if you use just this line alone?
```java
infoMap.put(new Info("std::vector<CTrack*>").cast().pointerTypes("CTrackVector").define());
```
And make sure to have `@Properties(inherit=opencv_core.class, ...)` as well.

**Comment by lxy765705425** [comment]
now I change the presets file as follow :
 public void map(InfoMap infoMap) {
        infoMap.put(new Info("PPoint_").cast().valueTypes("PPoint"));     // presets the headfile PPoint
       // infoMap.put(new Info("std::vector<PPoint_>").pointerTypes("Pointer"));
        infoMap.put(new Info("std::vector<PPoint_>").cast().pointerTypes("PPointVector").define());

        infoMap.put(new Info("size_t").cast().pointerTypes("Pointer"));
        infoMap.put(new Info("Point2d").cast().pointerTypes("Pointer"));

        infoMap.put(new Info("TKalmanFilter").cast().pointerTypes("Pointer"));
        infoMap.put(new Info("TKalmanFilter*").cast().valueTypes("TKalmanFilter"));

        infoMap.put(new Info("Point2f").cast().pointerTypes("Pointer"));

        infoMap.put(new Info("FILE").cast().pointerTypes("Pointer"));
        infoMap.put(new Info("FILE *").cast().valueTypes("FILE"));

        infoMap.put(new Info("CTrack*").cast().valueTypes("CTrack"));
        //infoMap.put(new Info("CTrack*").cast().pointerTypes("Pointer"));
        //infoMap.put(new Info("vector<CTrack*>").pointerTypes("Pointer"));
        infoMap.put(new Info("std::vector<CTrack*>").cast().pointerTypes("CTrackVector").define());
    }


and the error : 
/home/lxy/git/javacpp-presets_bak/videoabstraction1/target/classes/org/bytedeco/javacpp/jniCtracker.cpp: in function ‘_jobject* Java_org_bytedeco_javacpp_Ctracker_00024PPointVector_get(JNIEnv*, jobject, jlong)’中:
/home/lxy/git/javacpp-presets_bak/videoabstraction1/target/classes/org/bytedeco/javacpp/jniCtracker.cpp:1792:31: error： When the assignment is not 'PPoint_' convert 'jobject {aka _jobject *}
'/home/lxy/git/javacpp-presets_bak/videoabstraction1/target/classes/org/bytedeco/javacpp/jniCtracker.cpp: in function ‘_jobject* Java_org_bytedeco_javacpp_Ctracker_00024PPointVector_put__JLorg_bytedeco_javacpp_PPoint_2(JNIEnv*, jobject, jlong, jobject)’中:
/home/lxy/git/javacpp-presets_bak/videoabstraction1/target/classes/org/bytedeco/javacpp/jniCtracker.cpp:1841:28: error： ‘operator=’在‘ptr->std::vector<_Tp, _Alloc>::operator[] [with _Tp = PPoint_, _Alloc = std::allocator<PPoint_>, std::vector<_Tp, _Alloc>::reference = PPoint_&, std::vector<_Tp, _Alloc>::size_type = long unsigned int](((size_t)arg0)) = ptr1’中没有匹配
/home/lxy/git/javacpp-presets_bak/videoabstraction1/target/classes/org/bytedeco/javacpp/jniCtracker.cpp:1841:28: 附注： 备选是：
/home/lxy/git/javacpp-presets_bak/videoabstraction1/cppbuild/linux-x86_64/include/PPoint.h:6:8: 附注： PPoint_& PPoint_::operator=(const PPoint_&)
/home/lxy/git/javacpp-presets_bak/videoabstraction1/cppbuild/linux-x86_64/include/PPoint.h:6:8: 附注：   no known conversion for argument 1 from ‘jobject {aka _jobject*}’ to ‘const PPoint_&’

**Comment by lxy765705425** [comment]
the "@Properties(inherit=opencv_core.class)", if I should put the opecn_core.java in the package of presets?

**Comment by saudet** [comment]
Not really, try to use the `flandmark` module as template:
https://github.com/bytedeco/javacpp-presets/tree/master/flandmark

**Comment by lxy765705425** [comment]
I will try it,thanks a lot

**Comment by saudet** [comment]
Are you still having issues getting this working? Let me know! Thanks
