### ISSUE TITLE
JavaCPP Presets Tesseract compile failure

### ISSUE THREAD

**Issue by GraemeWellington** [bytedeco/javacpp-presets#720]
I have followed the procedure for installing JavaCPP on Windows 10 64bit [https://github.com/bytedeco/javacpp-presets/wiki/Build-Environments#windows-x86-and-x86_64]
The pre-requisites completed successfully.
I then ran the following:
mvn clean install -Djavacpp.platform=windows-x86_64 --projects .,leptonica,tesseract
Results:
JavaCPP Presets SUCCESS
Leptonica SUCCESS
Tesseract FAILED
I then ran mvn with -X to get debug log which is attached.
The log after the failure references MojoExecutor but I am not sure where to go from here.
Any help appreciated.
[JavaCPP-Presetes-Tesseract.txt](https://github.com/bytedeco/javacpp-presets/files/3100880/JavaCPP-Presetes-Tesseract.txt)

**Comment by saudet** [comment]
Looks like your installation of Python is broken: Reinstall it!

**Comment by GraemeWellington** [comment]
Thanks suadet - problem solved - in record time!

Was 'MojoExecutor' an indication that there was something wrong with Python?

I uninstalled all Python versions and installed 2.7 and 3.6 and changed the existing environment path entry to C:\python27

Is it necessary to start from the very beginning of the wiki install procedure for Build-Environments#windows-x86-and-x86_64?

Thanks again.

**Comment by saudet** [comment]
Great!
> ImportError: No module named site

That's a Python error.

On Windows, no need to follow the guide for platforms other than Windows, no.
