### ISSUE TITLE
More efficient way to get floats out of Mat object?

### ISSUE THREAD

**Issue by jeroenarens** [bytedeco/javacpp-presets#73]
At the moment, I have the following code to extract floats out of a Mat object
```java
FloatBuffer floats = matObject.getFloatBuffer();
Point[] points = new Point[4];
for(int i=0;i<points.length;i++){
      points[i] = new Point((int)floats.get(2*i),(int)floats.get(2*i+1));
}
```
I am now wondering if there exists a more efficient way to get a float out of a Mat image than first converting it to a float buffer.
I am using the javacpp-opencv version 2.4.10-0.10

Thanks in advance

Jeroen

**Comment by saudet** [comment]
More or less, indexers are backed by buffers:
http://bytedeco.org/news/2014/12/23/third-release/
But under Android, an non-direct indexer backed by an array would be best.
