### ISSUE TITLE
Want Tesseract 4.0.0 Alpha native api

### ISSUE THREAD

**Issue by vipulpatel2103** [bytedeco/javacpp-presets#734]
As JavaCpp provides a wrapper for native API, it's really hard to identify which version of libraries are being used internally.
My requirement is to use Tess 4.0.0 Alpha and doesn't know which version of JavaCpp supports that tesseract version.
This is not an issue but question how to change libs version and any other version of JavaCpp that support.

**Comment by saudet** [comment]
No it's not hard. Look in the cppbuild.sh script files to see where the sources come from.

**Comment by saudet** [comment]
And if it's not exactly what you need, just change the URL(s) and run the build(s).

**Comment by usheth** [comment]
This does not work because the patches only work with 4.1.0-rc. Is there another way around this?

**Comment by saudet** [comment]
Previous versions are there too, just use one of those.

**Comment by saudet** [comment]
https://github.com/bytedeco/javacpp-presets/tree/1.5/tesseract
https://github.com/bytedeco/javacpp-presets/tree/1.4.4/tesseract
https://github.com/bytedeco/javacpp-presets/tree/1.4.3/tesseract
https://github.com/bytedeco/javacpp-presets/tree/1.4.2/tesseract
https://github.com/bytedeco/javacpp-presets/tree/1.4.1/tesseract
https://github.com/bytedeco/javacpp-presets/tree/1.4/tesseract
