### ISSUE TITLE
Memory Leak using cvCvtColor

### ISSUE THREAD

**Issue by nestoracunablanco** [bytedeco/javacpp-presets#739]
The following code produces a memory leak in the version 1.4.4:

```
public static IplImage blackGrayImage(IplImage image){
	IplImage grayImage = cvCreateImage(cvGetSize(image), IPL_DEPTH_8U, 1);
	cvCvtColor(image, grayImage, CV_BGR2GRAY);
	IplImage returnImage = grayImage.clone();
	grayImage.release();
	return returnImage;
}

```
A while loop with this method inside shows how the memory grows, throwing finally one OutOfMemoryError.

Changing to the Mat interface and using "cvtColor" instead solves the problem, however.

**Comment by saudet** [comment]
That's normal, you forgot to call cvReleaseImage().

**Comment by nestoracunablanco** [comment]
I have also a version with cvReleaseImage() and it produces the same result.

**Comment by saudet** [comment]
Ok, so let's take a look at that version too!

**Comment by nestoracunablanco** [comment]
Ok, I tested it... and you are right. What's exactly the difference between cvReleaseImage and IplImage.release()? 

Thanks in advance.

**Comment by saudet** [comment]
http://bytedeco.org/javacpp-presets/opencv/apidocs/org/bytedeco/opencv/opencv_core/AbstractIplImage.html#create-org.bytedeco.opencv.opencv_core.CvSize-int-int-
http://bytedeco.org/javacpp-presets/opencv/apidocs/org/bytedeco/opencv/opencv_core/AbstractIplImage.html#release--
