### ISSUE TITLE
MKL-DNN version: 1.0-rc vs 0.20-rc

### ISSUE THREAD

**Issue by blueberry** [bytedeco/javacpp-presets#740]
Hi,

As I understand, Intel now has a plan to release MKL-DNN 1.0 soon (during summer), and in the meanwhile they release 0.xx versions to give the users a time to switch from their older codebases.

javacpp-presets currently follows 0.xx versions, and I was unable to find 1.0-rc. I guess that the support will be switched to 1.0 once it is released, but in the meantime, is there a plan to introduce the support for 1.0? Or 0.xx will be the only line followed until its development is officially abandoned by Intel?

**Comment by saudet** [comment]
Will probably happen in pull #741.

**Comment by saudet** [comment]
Progress now being tracked in pull #741.

**Comment by saudet** [comment]
Actually merged to the `mkl-dnn` branch with pull #765.
