### ISSUE TITLE
no method submat on Mat Class ?

### ISSUE THREAD

**Issue by govi2010** [bytedeco/javacpp-presets#746]
I am using this in android. 

I want to draw small image on center of bigger image.

I know we can do that using submat method on opencv.Mat class.

**Comment by saudet** [comment]
We can call `operator()` for that, but since that's not a valid method name in Java, it's named `apply()`:
http://bytedeco.org/javacpp-presets/opencv/apidocs/org/bytedeco/opencv/opencv_core/Mat.html#apply-org.bytedeco.opencv.opencv_core.Range-org.bytedeco.opencv.opencv_core.Range-

**Comment by govi2010** [comment]
I used apply method but it did not worked for me.

**Comment by saudet** [comment]
Not all functions support submatrices like that, so make sure to make a copy.
