### ISSUE TITLE
How Java Object to PyObject in numpy

### ISSUE THREAD

**Issue by penetest** [bytedeco/javacpp-presets#748]

**Comment by saudet** [comment]
Could you clarify your question? What are you trying to do?

**Comment by penetest** [comment]
@saudet Hi,I have a need: Java passes arguments to python and extracts the results from python
   Like this:   
          Java object :   class Datas {
                                 int a;
                                 List b;
                                 long c;
                                  ....
                         }
 void funprocess(Datas datas ) throws StageException {
        System.setProperty("org.bytedeco.openblas.load", "mkl");

        Py_Initialize();
        String path = null;
        try {
            path = cachePackage().getAbsolutePath();
        } catch (IOException e) {
            e.printStackTrace();
        }
        PyList_Insert(PySys_GetObject("path"), 0, PyUnicode_FromString(path));
        if (_import_array() < 0) {
            System.err.println("numpy.core.multiarray failed to import");
            PyErr_Print();
            System.exit(-1);
        }
        PyObject globals = PyModule_GetDict(PyImport_AddModule("__main__"));

        **PyDict_SetItemString(globals, "x", datas );**
       #### PyDict_SetItemString(PyObject , char*, PyObject ), but datas is java object,I do not know how to do that make datas change to PyObject ,I  need your help.
  
        PyRun_StringFlags("import numpy as np ;b = x.b; y = np.array(b);y.shape", Py_single_input, globals, globals, null);

        PyArrayObject y = new PyArrayObject(PyDict_GetItemString(globals, "y"));
  
    }
  }

**Comment by saudet** [comment]
That's basically the example here, and it works fine for me:
https://github.com/bytedeco/javacpp-presets/blob/master/numpy/samples/MatMul.java
Could you provide the error message that you get when running that example?

**Comment by penetest** [comment]
@saudet Hi，I mean how to convert a java data value into a PyObject, for example:
                                    int k = 2, 
                                  how to convert k to PyObject?

 I hope you give some examples.

**Comment by saudet** [comment]
That would be `PyLong_FromLong()`, as documented here: https://docs.python.org/3/c-api/long.html

**Comment by penetest** [comment]
Tanks！
