### ISSUE TITLE
GpuMat get put

### ISSUE THREAD

**Issue by StarlightNL** [bytedeco/javacpp-presets#757]
Hello,

I am trying to use this library because of the gpu support with Java but I am stuck on some code.
In the opencv library there are .get(row,col) and .put(row, col, data) functions. How can I get and put data in a GpuMat or do I need to convert it to a normal Mat?
Here are some code examples of what I am trying to do.

- Getting a value from a depthmap that is captured using VideoCapture with realsense.
Function used `public double[] get(int row, int col)`
```
int distance;
distance = (int) depthMat.get(y,x)[0];
```

- Putting data in a Mat for offsetting a mat
Function used  `public int put(int row, int col, double... data)`
```
public static Mat translateImg(Mat img, int offsetx, int offsety){
    Mat trans_mat = new Mat(2, 3, CvType.CV_64FC1 );
    int row = 0, col = 0;
    trans_mat.put(row ,col, 1,0,offsetx, 0,1,offsety);
    warpAffine(img,img,trans_mat,img.size());
    return img;
}
```

**Comment by saudet** [comment]
Use indexers for that:
http://bytedeco.org/news/2014/12/23/third-release/

**Comment by saudet** [comment]
If you have any additional questions, feel free to ask! Thanks

**Comment by saudet** [comment]
And then these constructors can be used to transfer data between Mat and GpuMat:
http://bytedeco.org/javacpp-presets/opencv/apidocs/org/bytedeco/opencv/opencv_core/GpuMat.html#GpuMat-org.bytedeco.opencv.opencv_core.Mat-
http://bytedeco.org/javacpp-presets/opencv/apidocs/org/bytedeco/opencv/opencv_core/Mat.html#Mat-org.bytedeco.opencv.opencv_core.GpuMat-
But there are other `copyTo()`, etc functions as well.

**Comment by StarlightNL** [comment]
Thank you for telling me. I didn't know converting from both formats is that easy. I used convertTo but the method you suggest is easier and cleaner as well. 

I do have some problems trying to run my program due to the fact that it says it is not compiled with cuda. How can I compile it with cuda with the stable branch or is it easier to use the snapshot build? Do I need to ask that in a new issue?

**Comment by saudet** [comment]
You'll need to add a few more artifacts to get the CUDA-enabled binaries:
https://github.com/bytedeco/javacpp-presets/tree/1.5.1/opencv#the-pomxml-build-file

**Comment by StarlightNL** [comment]
I added the artifacts but it seems that there are no arm64 artifacts for cuda and opencv-gpu. The goal is to run this on a Jetson TX2.

**Comment by saudet** [comment]
Not yet, no, but it's possible to build from source. See issue #735.
