### ISSUE TITLE
Caffe: NullPointerException   org.bytedeco.javacpp.caffe$FloatLayerSharedVector.get

### ISSUE THREAD

**Issue by beatlevic** [bytedeco/javacpp-presets#76]
With the latest 1.0 presets for Caffe, I'm running into a NullPointerException after I fetch the layers of a FloatNet and try to get the layer at index 0. The FloatLayerSharedVector size correctly shows the number of layers I have, i.e. 24.

This did not happen under version 0.11. 

Any ideas?

**Comment by saudet** [comment]
It's been fixed in recent commits, see https://github.com/bytedeco/javacpp/issues/25.

**Comment by beatlevic** [comment]
Thank you, I'll checkout the latest version.

**Comment by beatlevic** [comment]
Actually, I'm going to wait for the version to bump, as I'm using the mvnrepository to pull in my dependencies (with Leiningen).

**Comment by saudet** [comment]
Fix released in version 1.1. Thank for reporting!
