### ISSUE TITLE
Android Utils missing from org.bytedeco.opencv

### ISSUE THREAD

**Issue by nofurylion** [bytedeco/javacpp-presets#760]
Hi,
Build target : Android 21+
Language : Kotlin
My gradle :
```
implementation group: 'org.bytedeco', name: 'opencv', version: '4.1.0-1.5.1'
implementation group: 'org.bytedeco', name: 'opencv', version: '4.1.0-1.5.1', classifier: "android-arm"
```

When using `Utils.bitmapToMat(param1, param2)`, the only available Utils are from package `org.opencv.android`.  I cant find Utils from package `org.bytedeco.opencv.android` .

This lead to error since param2 will require `org.opencv.core.Mat` instead of `org.bytedeco.opencv.opencv_core.Mat`

I've tried rough casting it like `param2 as org.opencv.core.Mat` but it lead to error "unable to cast".

Are there any alternative way to convert bitmap to mat easily? 
and also why package `org.opencv.*` still exist in the library? Is that how wrappers work?
![Screenshot_2019-07-13_17-53-25](https://user-images.githubusercontent.com/23353377/61170730-f45ea980-a597-11e9-819a-72990968ce0a.png)

_Originally posted by @nofurylion in https://github.com/bytedeco/javacpp-presets/issues/549#issuecomment-511112920_

**Comment by saudet** [comment]
We can convert between Mat objects of the two APIs with OpenCVFrameConverter.ToMat and OpenCVFrameConverter.ToOrgOpenCvCoreMat. See this unit test for an example:
https://github.com/bytedeco/javacv/blob/master/platform/src/test/java/org/bytedeco/javacv/FrameConverterTest.java#L211
