### ISSUE TITLE
How about LLVM Cpp Bindings ?

### ISSUE THREAD

**Issue by lfkdsk** [bytedeco/javacpp-presets#767]
Have we considered provide LLVM Cpp Bindings?

**Comment by saudet** [comment]
Duplicate of #594

**Comment by saudet** [comment]
To answer your question, yes, one of the main goals I want to achieve is to be able to parse the C++ API for LLVM and Clang. If you would like to participate, that would be great! Please tell us more about what interests you in one of the already opened threads. Thanks
