### ISSUE TITLE
javacpp-presets build FFmpeg  on windows-x86_64  failure! 

### ISSUE THREAD

**Issue by JinLike** [bytedeco/javacpp-presets#771]
I am in accordance with the https://github.com/bytedeco/javacpp-presets/wiki/Building-on-Windows#installation-recipe-for-visual-studiuo-2015-and-windows-10
OS: windows 7 SP1
VS 2015
msys64
jdk 11.0.4     
but  i used  ubuntu  build javacpp-presets Linux-x86_64 successful 

libtool:   error: object name conflicts in archive: .libs/libmp3lame.lax/liblam
vectorroutines.a//c/javacpp-presets-1.5.1/ffmpeg/cppbuild/windows-x86_64/lame-3
100/libmp3lame/../libmp3lame/vector/.libs/liblamevectorroutines.a
make[3]: *** [Makefile:550: libmp3lame.la] Error 1
make[3]: Leaving directory '/c/javacpp-presets-1.5.1/ffmpeg/cppbuild/windows-x8
_64/lame-3.100/libmp3lame'
make[2]: *** [Makefile:613: all-recursive] Error 1
make[2]: Leaving directory '/c/javacpp-presets-1.5.1/ffmpeg/cppbuild/windows-x8
_64/lame-3.100/libmp3lame'
make[1]: *** [Makefile:452: all-recursive] Error 1
make[1]: Leaving directory '/c/javacpp-presets-1.5.1/ffmpeg/cppbuild/windows-x8
_64/lame-3.100'
make: *** [Makefile:381: all] Error 2
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  02:17 min
[INFO] Finished at: 2019-07-29T14:25:09+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.bytedeco:javacpp:1.5.1:build (javacpp-cppbui
d-install) on project ffmpeg: Execution javacpp-cppbuild-install of goal org.by
edeco:javacpp:1.5.1:build failed: Process exited with an error: 2 -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swi
ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please re
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecuti
nException

(⊙o⊙)… 

 -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
Rebuild javacpp 
[ERROR] Errors:
[ERROR]   AdapterTest.setUpClass:98 ? IO Cannot run program "cl" (in directory "C:\msys6...
[ERROR]   BufferTest.setUpClass:82 ? IO Cannot run program "cl" (in directory "C:\msys64...
[ERROR]   BuilderTest.testExtensions:76 ? IO Cannot run program "cl" (in directory "C:\m...
[ERROR]   EnumTest.setUpClass:88 ? IO Cannot run program "cl" (in directory "C:\msys64\h...
[ERROR]   IndexerTest.setUpClass:60 ? IO Cannot run program "cl" (in directory "C:\msys6...
[ERROR]   PointerTest.setUpClass:68 ? IO Cannot run program "cl" (in directory "C:\msys6...

https://github.com/bytedeco/javacpp-presets/wiki/Build-Environments

**Comment by JinLike** [comment]
I am in accordance with the https://github.com/bytedeco/javacpp-presets/wiki/Building-on-Windows#installation-recipe-for-visual-studiuo-2015-and-windows-10 
OS: windows 7 SP1   
VS 2015   
msys64 
jdk 11.0.4

**Comment by saudet** [comment]
Try this instead:
https://github.com/bytedeco/javacpp-presets/wiki/Build-Environments#windows-x86-and-x86_64

**Comment by JinLike** [comment]
> 试试这个：[https](https://github.com/bytedeco/javacpp-presets/wiki/Build-Environments#windows-x86-and-x86_64)：
> [//github.com/bytedeco/javacpp-presets/wiki/Build-Environments #windows-x86-and-x86_64](https://github.com/bytedeco/javacpp-presets/wiki/Build-Environments#windows-x86-and-x86_64)

Thank you. I'll try

**Comment by saudet** [comment]
> [ERROR] AdapterTest.setUpClass:98 ? IO Cannot run program "cl" (in directory "C:\msys6...

Indeed, you're missing the `cl.exe` C++ compiler. To get that one, you'll need to install Visual Studio and set up the environment properly as described on the wiki page above.
