### ISSUE TITLE
InvalidModuleDescriptorException for org.bytedeco.teeseract.presets module version 1.5.1

### ISSUE THREAD

**Issue by dwiebusch** [bytedeco/javacpp-presets#772]
There seems to be a typo in the tesseract module-info.java file (version 1.5.1) causing modularized java builds to fail. More specifically, in line 5 in the module-info.java file, tesseract is written with a double 'e' instead of a double 's':

    exports org.bytedeco.teeseract.presets;

When compiling the modile via maven, this leads to an error reading the module:

    Error: Error reading module ~/.m2/repository/org/bytedeco/tesseract/4.1.0-1.5.1/tesseract-4.1.0-1.5.1.jar

When trying to run with eclipse the typo is listed in the error message:

    Error occurred during initialization of boot layer
    java.lang.module.FindException: Error reading module: ~/.m2/repository/org/bytedeco/tesseract/4.1.0-1.5.1/tesseract-4.1.0-1.5.1.jar
    Caused by: java.lang.module.InvalidModuleDescriptorException: Package org.bytedeco.teeseract.presets not found in module

**Comment by saudet** [comment]
Fixed! Please give it a try with the snapshots when the builds are done in a few hours:
http://bytedeco.org/builds/

**Comment by dwiebusch** [comment]
The problem is solved in the new version, thanks!
