### ISSUE TITLE
Ops generated helpers missing from tensorflow

### ISSUE THREAD

**Issue by jxtps** [bytedeco/javacpp-presets#773]
If I include `"org.bytedeco" % "tensorflow-platform" % "1.14.0-1.5.1"` I get the following in org.tensorflow.op: 

![image](https://user-images.githubusercontent.com/90846/62089889-9ed4fe80-b21f-11e9-9395-ba422f189b38.png)

However, if I include `"org.tensorflow" % "tensorflow" % "1.14.0"` I get this: 

![image](https://user-images.githubusercontent.com/90846/62089928-c1ffae00-b21f-11e9-8208-e4b3b7adec6f.png)

Seems like they ran some preprocessor to generate a bunch of helper classes that make it more convenient to use the various Ops.

**Comment by saudet** [comment]
Fixed! Please give it a try with the snapshots when the builds are done in a few hours:
http://bytedeco.org/builds/

**Comment by jxtps** [comment]
The Ops are indeed there now, thanks!
