### ISSUE TITLE
javaCV FFMPEG terminate called after throwing an instance of 'JavaCPP_exception'

### ISSUE THREAD

**Issue by tom0512** [bytedeco/javacpp-presets#776]
@saudet 

ten thread read rtsp video ;
 running after ten minute throw exception ;
and then program stop ;
jdk = 11;

terminate called after throwing an instance of 'JavaCPP_exception'
what():  java.lang.NullPointerException

**Comment by tom0512** [comment]
public class VideoServiceImpl implements VideoService {

    protected final Logger logger = LoggerFactory.getLogger(this.getClass());

    public static final int FRAME_READ_TIMEOUT = 60000; // 60S

    // public static final int FRAME_PIC_FMT = AV_PIX_FMT_YUVJ420P; //AV_PIX_FMT_BGR24;
    public static final int FRAME_PIC_FMT = AV_PIX_FMT_BGR24; //AV_PIX_FMT_BGR24;

    @Autowired
    VideoPushService videoPushService;

    @Autowired
    TaskRuntimeService taskRuntimeService;


    public void safeReadStreamFromRTSP(VideoTaskModel model) {
        try {
            readStreamFromRTSP(model);
        } catch (Throwable e) {
            // e.printStackTrace();
        }
    }

    public void readStreamFromRTSP(VideoTaskModel model) throws Exception {
        final AtomicLong lastFrameTime = new AtomicLong(System.currentTimeMillis());
        Long frameStartTime = System.currentTimeMillis(), picRate = model.getPicRate() - 100L, validCheckTime = System.currentTimeMillis();
        // av_log_set_level(AV_LOG_DEBUG);
        // av_log_set_level(AV_LOG_ERROR);

        AVIOInterruptCB.Callback_Pointer cp = new AVIOInterruptCB.Callback_Pointer() {
            @Override
            public int call(Pointer pointer) {
                if ((lastFrameTime.get() + FRAME_READ_TIMEOUT) < System.currentTimeMillis()) {
                    return 1;
                }
                return 0;
            }
        };
        AVIOInterruptCB cb = new AVIOInterruptCB();
        cb.callback(cp);

        AVFormatContext pFormatCtx = null;
        AVCodecContext pCodecCtx = null;
        AVCodec pCodec = null;
        AVPacket packet = null;
        AVDictionary optionsDict = null;
        AVFrame pFrame = null;
        int[] frameFinished = new int[1];
        int videoStream;
        AVFrame pFrameRGB = null;
        BytePointer buffer = null;
        try {
            pFormatCtx = avformat_alloc_context();
            pFormatCtx.interrupt_callback(cb);
            pFormatCtx.max_analyze_duration(50 * AV_TIME_BASE);
            pFormatCtx.probesize(500 * 1024);// 500K
            optionsDict = new AVDictionary(null);
            av_dict_set(optionsDict, "rtsp_transport", "tcp", 0);
            av_dict_set(optionsDict, "buffer_size", "20480000", 0);
            av_dict_set(optionsDict, "stimeout", "2000000", 0);//2000000 20S
            av_dict_set(optionsDict, "max_delay", "5000000", 0);

            packet = new AVPacket();

            // av_register_all();
            int c = avformat_open_input(pFormatCtx, model.getRtspUrl(), null, optionsDict);

            if (c != 0) {
                throw new Exception("" + model.getRtspUrl());
            }


            int e = avformat_find_stream_info(pFormatCtx, (PointerPointer<Pointer>) null);
            logger.info("" + model.getRtspUrl() + " e = " + e);
            if (e < 0) {
                throw new Exception("" + model.getRtspUrl());
            }

            av_dump_format(pFormatCtx, 0, model.getRtspUrl(), 0); 

            videoStream = -1;
            for (int i = 0; i < pFormatCtx.nb_streams(); i++) {
                if (pFormatCtx.streams(i).codecpar().codec_type() == avutil.AVMEDIA_TYPE_VIDEO) {
                    videoStream = i;
                    break;
                }
            }
            if (videoStream == -1) {
                throw new Exception("");
            }

            pCodecCtx = avcodec_alloc_context3(null);
            avcodec_parameters_to_context(pCodecCtx, pFormatCtx.streams(videoStream).codecpar());

            pCodec = avcodec_find_decoder(pCodecCtx.codec_id());
            if (pCodec == null) {
                throw new Exception("");
            }

            // if (avcodec_open2(pCodecCtx, pCodec, optionsDict) < 0) {
            if (avcodec_open2(pCodecCtx, pCodec, (PointerPointer) null) < 0) {
                throw new Exception("");
            }

            pFrame = av_frame_alloc();

            pFrameRGB = av_frame_alloc();
            if (pFrameRGB == null) {
                throw new Exception("");
            }
            pFrameRGB.width(pCodecCtx.width());
            pFrameRGB.height(pCodecCtx.height());
            pFrameRGB.format(FRAME_PIC_FMT);

            int numBytes = av_image_get_buffer_size(FRAME_PIC_FMT, pCodecCtx.width(), pCodecCtx.height(), 1);
            buffer = new BytePointer(av_malloc(numBytes));

            SwsContext sws_ctx = sws_getContext(pCodecCtx.width(), pCodecCtx.height(), pCodecCtx.pix_fmt(), pCodecCtx.width(), pCodecCtx.height()
                    , FRAME_PIC_FMT, SWS_BICUBIC, null, null, (DoublePointer) null);
            if (sws_ctx == null) {
                throw new Exception("");
            }

            av_image_fill_arrays(pFrameRGB.data(), pFrameRGB.linesize(), buffer, FRAME_PIC_FMT, pCodecCtx.width(), pCodecCtx.height(), 1);

            lastFrameTime.set(System.currentTimeMillis()); // 
            int ret1 = -1, ret2 = -1;
            while (av_read_frame(pFormatCtx, packet) >= 0) {
                if ((System.currentTimeMillis() - frameStartTime) > picRate && packet.stream_index() == videoStream) {
                    // int let = avcodec_decode_video2(pCodecCtx, pFrame, frameFinished, packet);
                    ret1 = avcodec_send_packet(pCodecCtx, packet);
                    ret2 = avcodec_receive_frame(pCodecCtx, pFrame);
                    // if (ret2 >= 0 && frameFinished != null && frameFinished[0] != 0 && !pFrame.isNull() && pFrame.key_frame() == 1 && pFrame.pict_type() == AV_PICTURE_TYPE_I) {
                    if (ret2 >= 0 && !pFrame.isNull() && pFrame.key_frame() == 1 && pFrame.pict_type() == AV_PICTURE_TYPE_I) {
                        sws_scale(sws_ctx, pFrame.data(), pFrame.linesize(), 0, pCodecCtx.height(), pFrameRGB.data(), pFrameRGB.linesize());
                        frameStartTime = System.currentTimeMillis();
                    }
                }
                av_packet_unref(packet); 
                lastFrameTime.set(System.currentTimeMillis()); // 
            }
        } catch (Throwable e) {
            e.printStackTrace();
        } finally {
            if (buffer != null) {
                av_free(buffer);
            }
            if (pFrameRGB != null) {
                av_frame_free(pFrameRGB);
            }
            if (pFrame != null) {
                av_frame_free(pFrame);
            }
            if (pCodecCtx != null) {
                avcodec_close(pCodecCtx);
                avcodec_free_context(pCodecCtx);
            }
            if (pFormatCtx != null) {
                avformat_close_input(pFormatCtx);
            }
            if (optionsDict != null) {
                av_dict_free(optionsDict);
            }

        }
    }


}

**Comment by tom0512** [comment]
![image](https://user-images.githubusercontent.com/53565719/62299309-49128780-b4a7-11e9-97b5-7ca715990324.png)

**Comment by saudet** [comment]
Please update your JDK and try again.

**Comment by saudet** [comment]
JavaCPP_exception just wraps a Java exception thrown for your code. Use a try-catch block in your callback implementation to deal with it.

**Comment by saudet** [comment]
Your callback might also get garbage collected. Keep it in a field to make sure this doesn't happen.

**Comment by SageLam** [comment]
> Your callback might also get garbage collected. Keep it in a field to make sure this doesn't happen.

hello, i use the these callbacks to read data  by javacv ffmpeg , but it always terminate called after throwing an instance of 'JavaCPP_exception'
what(): java.lang.RuntimeException. Could you please help me ? I don't know why it would throw exception.

Read_packet_Pointer_BytePointer_int reader = new Read_packet_Pointer_BytePointer_int() {
               @Override
               public int call(Pointer pointer, BytePointer buf, int bufSize) {
                    try {
                         byte[] data = null;
                         int read = 0;
                         while (true) {
                              data = sipCameraInfo.getCameraBroadcastQueue().poll();
                              if (data != null && data.length > 0) {
                                   read = data.length;
                                   break;
                              }
                              else {
                                   Thread.currentThread().sleep(50);
                              }
                         }

                         buf.position(0);
                         buf.put(data, 0, read);
                         return read;
                    }
                    catch (Exception ex) {
                         logger.error(ex.getMessage(), ex);
                         return -1;
                    }
               }
          };

          Seek_Pointer_long_int seeker = new Seek_Pointer_long_int() {
               @Override
               public long call(Pointer pointer, long offset, int whence) {
                    return -1;
               }
          };

**Comment by saudet** [comment]
@SageLam That's an exception thrown from your code. Check its stack trace.

**Comment by SageLam** [comment]
> @SageLam That's an exception thrown from your code. Check its stack trace.

Thanks for reply. But I have try catch in the callback.And the code shouldn't throw runtime exception.Could you please tell me how to check its stack trace.I just can only see only this error:Error getting method ID of java/lang/RuntimeException/<init>
terminate called after throwing an instance of 'JavaCPP_exception'
  what():  java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException

**Comment by saudet** [comment]
It looks like you might be running with a different version of JavaCPP than you're building with. Make sure they are both the same version.

**Comment by SageLam** [comment]
> It looks like you might be running with a different version of JavaCPP than you're building with. Make sure they are both the same version.

I use this in pom.xml:
        <dependency>
            <groupId>org.bytedeco</groupId>
            <artifactId>ffmpeg-platform</artifactId>
            <version>4.1.3-1.5.1</version>
        </dependency>

and confirm that ffmpeg is 4.1.3-1.5.1 and javacpp is 1.5.1. It is so wired because it throws exception randomly.Sometimes it throws in few minutes.Sometimes in several hours.

**Comment by saudet** [comment]
Ah, ok, so you're encountering some memory corruption. You'll need to pinpoint the source of where memory gets corrupted. If it never happens without your callback, then it's something wrong with your callback.

**Comment by SageLam** [comment]
> Ah, ok, so you're encountering some memory corruption. You'll need to pinpoint the source of where memory gets corrupted. If it never happens without your callback, then it's something wrong with your callback.

I test on my pc and the server.Both throws the same exception.I should simplify my callback to check if still happens. If you have any other suggestion ,please tell me . thanks.

**Comment by SageLam** [comment]
> Ah, ok, so you're encountering some memory corruption. You'll need to pinpoint the source of where memory gets corrupted. If it never happens without your callback, then it's something wrong with your callback.

Hi,I have got the stack trace:
Exception in thread "Thread-22" java.lang.RuntimeException: java.lang.RuntimeException: java.lang.StackOverflowError
        at org.bytedeco.ffmpeg.avformat.Read_packet_Pointer_BytePointer_int.call(Native Method)
        at org.bytedeco.ffmpeg.avformat.Read_packet_Pointer_BytePointer_int.call(Native Method)
        at org.bytedeco.ffmpeg.avformat.Read_packet_Pointer_BytePointer_int.call(Native Method)
       ...
       at org.bytedeco.ffmpeg.avformat.Read_packet_Pointer_BytePointer_int.call(Native Method)
        at org.bytedeco.ffmpeg.avformat.Read_packet_Pointer_BytePointer_int.call(Native Method)
        at org.bytedeco.ffmpeg.avformat.Read_packet_Pointer_BytePointer_int.call(Native Method)
        at org.bytedeco.ffmpeg.global.avformat.av_read_frame(Native Method)
        at com.iwhalecloud.ivs.camera.thread.CameraBroadcastThread.readPacket(CameraBroadcastThread.java:345)
        at com.iwhalecloud.ivs.camera.thread.CameraBroadcastThread.run(CameraBroadcastThread.java:78)
        at java.lang.Thread.run(Thread.java:748)

I think it went into a loop . And this is the generated cpp method:

JNIEXPORT jint JNICALL Java_org_bytedeco_ffmpeg_avformat_Read_1packet_1Pointer_1BytePointer_1int_call(JNIEnv* env, jobject obj, jobject arg0, jobject arg1, jint arg2) {
    JavaCPP_org_bytedeco_ffmpeg_avformat_Read_1packet_1Pointer_1BytePointer_1int* ptr = (JavaCPP_org_bytedeco_ffmpeg_avformat_Read_1packet_1Pointer_1BytePointer_1int*)jlong_to_ptr(env->GetLongField(obj, JavaCPP_addressFID));
    if (ptr == NULL) {
        env->ThrowNew(JavaCPP_getClass(env, 6), "This pointer address is NULL.");
        return 0;
    }
    if (ptr->ptr == NULL) {
        env->ThrowNew(JavaCPP_getClass(env, 6), "This function pointer address is NULL.");
        return 0;
    }
    jlong position = env->GetLongField(obj, JavaCPP_positionFID);
    ptr += position;
    char* ptr0 = arg0 == NULL ? NULL : (char*)jlong_to_ptr(env->GetLongField(arg0, JavaCPP_addressFID));
    jlong position0 = arg0 == NULL ? 0 : env->GetLongField(arg0, JavaCPP_positionFID);
    ptr0 += position0;
    signed char* ptr1 = arg1 == NULL ? NULL : (signed char*)jlong_to_ptr(env->GetLongField(arg1, JavaCPP_addressFID));
    jlong position1 = arg1 == NULL ? 0 : env->GetLongField(arg1, JavaCPP_positionFID);
    ptr1 += position1;
    jint rarg = 0;
    jthrowable exc = NULL;
    try {
        int rval = (*ptr->ptr)(ptr0, (uint8_t*)ptr1, arg2);
        rarg = (jint)rval;
    } catch (...) {
        exc = JavaCPP_handleException(env, 8);
    }

    if (exc != NULL) {
        env->Throw(exc);
    }
    return rarg;
}

Maybe ptr just point to itself so it runs in a loop until StackOverflowError.Can you help how to fix this?

**Comment by saudet** [comment]
You said it doesn't always do that, so the answer is the same: You have memory corruption happening somewhere. You'll need to find where it happens.

**Comment by saudet** [comment]
BTW, since you're posting here on this issue, I'm assuming that you read the answer above and that your are keeping a reference of your callback in a field.

**Comment by xiaobo-lab** [comment]
> Sorry I don't keep a reference of callback so it has been gc. Thanks.



> > Ah, ok, so you're encountering some memory corruption. You'll need to pinpoint the source of where memory gets corrupted. If it never happens without your callback, then it's something wrong with your callback.
> 
> Hi,I have got the stack trace: Exception in thread "Thread-22" java.lang.RuntimeException: java.lang.RuntimeException: java.lang.StackOverflowError at org.bytedeco.ffmpeg.avformat.Read_packet_Pointer_BytePointer_int.call(Native Method) at org.bytedeco.ffmpeg.avformat.Read_packet_Pointer_BytePointer_int.call(Native Method) at org.bytedeco.ffmpeg.avformat.Read_packet_Pointer_BytePointer_int.call(Native Method) ... at org.bytedeco.ffmpeg.avformat.Read_packet_Pointer_BytePointer_int.call(Native Method) at org.bytedeco.ffmpeg.avformat.Read_packet_Pointer_BytePointer_int.call(Native Method) at org.bytedeco.ffmpeg.avformat.Read_packet_Pointer_BytePointer_int.call(Native Method) at org.bytedeco.ffmpeg.global.avformat.av_read_frame(Native Method) at com.iwhalecloud.ivs.camera.thread.CameraBroadcastThread.readPacket(CameraBroadcastThread.java:345) at com.iwhalecloud.ivs.camera.thread.CameraBroadcastThread.run(CameraBroadcastThread.java:78) at java.lang.Thread.run(Thread.java:748)
> 
> I think it went into a loop . And this is the generated cpp method:
> 
> JNIEXPORT jint JNICALL Java_org_bytedeco_ffmpeg_avformat_Read_1packet_1Pointer_1BytePointer_1int_call(JNIEnv* env, jobject obj, jobject arg0, jobject arg1, jint arg2) { JavaCPP_org_bytedeco_ffmpeg_avformat_Read_1packet_1Pointer_1BytePointer_1int* ptr = (JavaCPP_org_bytedeco_ffmpeg_avformat_Read_1packet_1Pointer_1BytePointer_1int*)jlong_to_ptr(env->GetLongField(obj, JavaCPP_addressFID)); if (ptr == NULL) { env->ThrowNew(JavaCPP_getClass(env, 6), "This pointer address is NULL."); return 0; } if (ptr->ptr == NULL) { env->ThrowNew(JavaCPP_getClass(env, 6), "This function pointer address is NULL."); return 0; } jlong position = env->GetLongField(obj, JavaCPP_positionFID); ptr += position; char* ptr0 = arg0 == NULL ? NULL : (char*)jlong_to_ptr(env->GetLongField(arg0, JavaCPP_addressFID)); jlong position0 = arg0 == NULL ? 0 : env->GetLongField(arg0, JavaCPP_positionFID); ptr0 += position0; signed char* ptr1 = arg1 == NULL ? NULL : (signed char*)jlong_to_ptr(env->GetLongField(arg1, JavaCPP_addressFID)); jlong position1 = arg1 == NULL ? 0 : env->GetLongField(arg1, JavaCPP_positionFID); ptr1 += position1; jint rarg = 0; jthrowable exc = NULL; try { int rval = (_ptr->ptr)(ptr0, (uint8_t_)ptr1, arg2); rarg = (jint)rval; } catch (...) { exc = JavaCPP_handleException(env, 8); }
> 
> ```
> if (exc != NULL) {
>     env->Throw(exc);
> }
> return rarg;
> ```
> 
> }
> 
> Maybe ptr just point to itself so it runs in a loop until StackOverflowError.Can you help how to fix this?

can you please tell me how to check this stack trace? i have same problem.thanks!
