### ISSUE TITLE
Dependency doesnt exist!

### ISSUE THREAD

**Issue by QuikkHakk** [bytedeco/javacpp-presets#781]
I copied the dependencies of your example but it doesnt exist!
I also looked for it on your maven page but couldn't find there either.

<dependency>
     <groupId>org.bytedeco</groupId>
    <artifactId>llvm-platform</artifactId>
    <version>8.0.1-1.5.2-SNAPSHOT</version>
</dependency>

Thanks :)

**Comment by QuikkHakk** [comment]
Ok, it works without the SNAPSHOT, you may want to update the example :)

**Comment by saudet** [comment]
The repository for snapshots is different: http://bytedeco.org/builds/
