### ISSUE TITLE
How to build openblas.jar without removing the symbol（not stripped）

### ISSUE THREAD

**Issue by 0x0916** [bytedeco/javacpp-presets#783]
I want to use a "not stripped" version of openblas.jar, but the current build are all stripped.

```
# file libjniopenblas_nolapack.so 
libjniopenblas_nolapack.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=8b905d64d437550bd8aa7abb062fdc3a418bee22, stripped
```

Does any one know how to get the not stripped version? or how to build it by myself?

**Comment by saudet** [comment]
Yes, you'll need rebuild by yourself, and the instructions are here:
https://github.com/bytedeco/javacpp-presets#build-instructions

**Comment by 0x0916** [comment]
> Yes, you'll need rebuild by yourself, and the instructions are here:
> https://github.com/bytedeco/javacpp-presets#build-instructions

@saudet Thank you for your reply, I read the all wiki and still don't know how to change the cppbuild.sh to build openblas with not stripped(`libjniopenblas_nolapack.so`).

I am new to maven and java. Can you give me some more guidance? Thank you very much!

**Comment by saudet** [comment]
Like this: https://github.com/xianyi/OpenBLAS#debug-version

**Comment by 0x0916** [comment]
@saudet I change the following:
```
diff --git a/openblas/cppbuild.sh b/openblas/cppbuild.sh
index 9e39491..0e53f8e 100755
--- a/openblas/cppbuild.sh
+++ b/openblas/cppbuild.sh
@@ -110,7 +110,7 @@ case $PLATFORM in
         ;;
 esac
 
-make -j $MAKEJ libs netlib shared "CROSS_SUFFIX=$CROSS_SUFFIX" "CC=$CC" "FC=$FC" "HOSTCC=$HOSTCC" BINARY=$BINARY COMMON_PROF= F_COMPILER=GFORTRAN
+make -j $MAKEJ  DEBUG=1 libs netlib shared "CROSS_SUFFIX=$CROSS_SUFFIX" "CC=$CC" "FC=$FC" "HOSTCC=$HOSTCC" BINARY=$BINARY COMMON_PROF= F_COMPILER=GFORTRAN
 make install "PREFIX=$INSTALL_PATH"
 export LDFLAGS=
```

and it does not works:
```
# file *
libgcc_s.so.1:     ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=179f202998e429aa1215907f6d4c5c1bb9c90136, stripped
libgfortran.so.3:  ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=a3354af57028230b310acc089b41e9010e9d05a3, stripped
libjniopenblas.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=4eb25f84ba061b5126d891d7734d99bb523b0fdc, stripped
libopenblas.so.0:  ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=b8aac5ee1ccdd1fb78a366854b3bb71542cff5bf, not stripped
libquadmath.so.0:  ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=983ea503e3ddf7a973e90f9b627862df40dc9666, stripped

```

except `libopenblas.so.0`, other files are all stripped.

**Comment by saudet** [comment]
The other files are copied from the system. Where the debug info is depends on your distribution.

**Comment by 0x0916** [comment]
> The other files are copied from the system. Where the debug info is depends on your distribution.
This one （`libjniopenblas.so` ） is not copied.

**Comment by saudet** [comment]
You'll need to add 
`@Platform(compiler="debug", ...)` for that one.

**Comment by saudet** [comment]
For example, on this line: https://github.com/bytedeco/javacpp-presets/blob/master/openblas/src/main/java/org/bytedeco/openblas/presets/openblas_nolapack.java#L43
