### ISSUE TITLE
Windows DL4J on Eclipse - Missing jniopenblas in java.library.path

### ISSUE THREAD

**Issue by Siandfrance** [bytedeco/javacpp-presets#784]
Hi, I installed DL4J according to the [Quick Start Guide](https://deeplearning4j.org/docs/latest/deeplearning4j-quickstart) and [this blog post](https://electronsfree.blogspot.com/2016/10/how-to-setup-dl4j-project-with-eclipse.html) 
but when I tried to fit a model that receives two inputs x, y and outputs (x > y) (Code in _NeuralNetworkFit.java_). I had an UsatisfiedLinkError (see _NeuralNetworkFit.log_)

So I followed the [Debugging UnsatisfiedLinkError](https://github.com/bytedeco/javacpp-presets/wiki/Debugging-UnsatisfiedLinkError-on-Windows#using-dependency-walker) (see _UnsatisfiedLinkError.java_ and _UnsatisfiedLinkError.log_). 

When I look at .javacpp/cache, there is no jniopenblas.dll (if I delete .javacpp/cache and I run _UnsatisfiedLinkError.java_, this folder is empty) I think that is the issue, but I don't know how to solve it. Can anyone help me?

Code and log file [here](https://github.com/bytedeco/javacpp-presets/files/3545847/sources.zip).

**Comment by saudet** [comment]
Could you try with https://github.com/deeplearning4j/dl4j-examples/?

**Comment by Siandfrance** [comment]
I imported dl4j-example as an eclipse project, but some import don't work
![image](https://user-images.githubusercontent.com/48362835/63772333-2bcfae00-c8d9-11e9-9991-7d79dbd3e912.png)

**Comment by Siandfrance** [comment]
Oh! I forgot to say that I am using Eclipse without Maven/Gradle.

**Comment by Siandfrance** [comment]
I'll try with Maven, to see if I have the same issue.

**Comment by Siandfrance** [comment]
[The libraries](https://github.com/woolfel/robottag/tree/master/lib), from [the tutorial](https://electronsfree.blogspot.com/2016/10/how-to-setup-dl4j-project-with-eclipse.html) "How setup DL4J for eclipse", are outdated (last updated in 2017).
So I will learn to use maven and install DL4j the "intended way".

Thanks for looking at this issue !^^
