### ISSUE TITLE
Failed to execute goal org.bytedeco:javacpp:1.5.2-SNAPSHOT

### ISSUE THREAD

**Issue by lishoahua** [bytedeco/javacpp-presets#785]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:27 min
[INFO] Finished at: 2019-08-30T16:11:44+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.bytedeco:javacpp:1.5.2-SNAPSHOT:build (javacpp-cppbuild-install) on project ffmpeg: Execution javacpp-cppbuild-install of goal org.bytedeco:javacpp:1.5.2-SNAPSHOT:build failed: Process exited with an error: 1 -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException

**Comment by saudet** [comment]
Build instructions are here: https://github.com/bytedeco/javacpp-presets#build-instructions

Let me know if you have any additional questions though! Thanks
