### ISSUE TITLE
How can I transcode mp3 to aac?

### ISSUE THREAD

**Issue by DTHeaven** [bytedeco/javacpp-presets#79]
I want to decode mp3 and write the audio data to mp4, how can I do.
Use recordSamples(Buffer... samples) ?
How can I get correct buffer form AVFrame?

Btw, is there any way to use AVAudioFifo?
Thanks.

**Comment by saudet** [comment]
> I want to decode mp3 and write the audio data to mp4, how can I do.
> Use recordSamples(Buffer... samples) ?
> How can I get correct buffer form AVFrame?

There's an example here: https://github.com/bytedeco/javacv/issues/169

> Btw, is there any way to use AVAudioFifo?

Sure, we can add "fifo.h" and "audio_fifo.h" to the include list of header files. Let me know if you try it out! Thanks

**Comment by saudet** [comment]
Added in the newly released version 1.1. Thanks for reporting!
