### ISSUE TITLE
JavaCPP Presets For CUDA » 10.1-7.6-1.5.1 not avaliable in maven repository

### ISSUE THREAD

**Issue by lightway82** [bytedeco/javacpp-presets#790]
Version is present on maven central web-site catalog, but not avaliable to download by maven because there is no such version present in repository( find screenshots for referense above) 

![image](https://user-images.githubusercontent.com/17110240/64471696-39005e80-d15d-11e9-89fb-5a0a0111411b.png)

![image](https://user-images.githubusercontent.com/17110240/64471599-5123ae00-d15c-11e9-8684-8861fb85a46a.png)

**Comment by saudet** [comment]
Yes, the names changed a bit:
http://bytedeco.org/news/2019/04/11/beyond-java-and-cpp/
