### ISSUE TITLE
What do these do?

### ISSUE THREAD

**Issue by peardox** [bytedeco/javacpp-presets#800]
Project tends to OOM without them, I'm blindly applying them simply cos it stops the OOM

-D"org.bytedeco.javacpp.maxbytes"=8G -D"org.bytedeco.javacpp.maxphysicalbytes"=10G

**Comment by saudet** [comment]
http://bytedeco.org/javacpp/apidocs/org/bytedeco/javacpp/Pointer.html#maxBytes
