### ISSUE TITLE
language files

### ISSUE THREAD

**Issue by Ginso** [bytedeco/javacpp-presets#802]
Hello,
sorry if this looks like a stuid question, but somehow i don't understand the setup.
i added the dependency to my pom.xml but i seem to miss some language file:
when i run TessBaseAPI.Init() i get the error:

Could not initialize tesseract.
Error opening data file \Program Files\Java\jre1.8.0_191\bin\tessdata/eng.traineddata
Please make sure the TESSDATA_PREFIX environment variable is set to the parent directory of your "tessdata" directory.
Failed loading language 'eng'
Tesseract couldn't load any languages!

do i have to do anyhting else?
i tried saving https://github.com/tesseract-ocr/tessdata/blob/master/eng.traineddata into the specified folder, but it didn't change anything

**Comment by saudet** [comment]
Try something like this:
```
git clone https://github.com/tesseract-ocr/tessdata
export TESSDATA_PREFIX=tessdata
```
