### ISSUE TITLE
Off topic nd4j Question

### ISSUE THREAD

**Issue by peardox** [bytedeco/javacpp-presets#803]
Off topic - sorry but you'll know the answer

I've got bad copies of libnd4jcpu.so and libjnind4jcpu.so for arm -trying the aarch64 first. I built the former after some messing around but the latter is compaining that...

 Could not find artifact org.bytedeco.javacpp-presets:openblas:jar:linux-aarch64:0.2.20-1.4.1 in central (https://repo.maven.apache.org/maven2)

Thing is I've got versions of JavaCPP-Presets (1.4.1 - SNAPSHOT) all over my drive

Maven is complaining it can't find openblas.jar

Any way I can point nd4j at the copy(s) I already have?

**Comment by saudet** [comment]
Don't try to use old versions like that. Use 1.5.2-SNAPSHOT.

**Comment by peardox** [comment]
I meant 1.5.2-SNAPSHOT

Still can't build libjnind4jcpu.so for arm - everything's archived / out of fate / missing (specifically https://deeplearning4j.org/buildinglocally)

**Comment by saudet** [comment]
Make sure to set the platform manually, it doesn't "detect" it for other platform than x86:
```bash
mvn clean install -Dmaven.test.skip -Djavacpp.platform=linux-armhf
```

**Comment by saudet** [comment]
I'm assuming this answered your question, but let me know if you continue to have problems with that! Thanks
