### ISSUE TITLE
Artifacts are published with pom files containing ${revision} as version

### ISSUE THREAD

**Issue by agolovenko** [bytedeco/javacpp-presets#807]
Artifacts are published with pom files containing `${revision}` as version.

Normally it's OK but if one starts using [maven CI fliendly versions](https://maven.apache.org/maven-ci-friendly.html) in his project with `bytedeco` dependencies, the build can break:

Consider setting revision like this, which is valid: `mvn -Drevision=v0-3-gd5f13e59 clean package`

This revision value will propagate to `bytedeco` dependency and cascade to `${project.version}`, causing a snowball of unresolved dependencies:

```
[DEBUG]             org.bytedeco:opencv-platform:jar:4.1.0-1.5.1:compile
[DEBUG]                org.bytedeco:openblas-platform:jar:0.3.6-1.5.1:compile
[DEBUG]                   org.bytedeco:openblas:jar:android-arm:v0-3-gd5f13e59:compile
[DEBUG]                   org.bytedeco:openblas:jar:android-arm64:v0-3-gd5f13e59:compile
[DEBUG]                   org.bytedeco:openblas:jar:android-x86:v0-3-gd5f13e59:compile
[DEBUG]                   org.bytedeco:openblas:jar:android-x86_64:v0-3-gd5f13e59:compile
[DEBUG]                   org.bytedeco:openblas:jar:ios-arm64:v0-3-gd5f13e59:compile
[DEBUG]                   org.bytedeco:openblas:jar:ios-x86_64:v0-3-gd5f13e59:compile
[DEBUG]                   org.bytedeco:openblas:jar:linux-x86:v0-3-gd5f13e59:compile
[DEBUG]                   org.bytedeco:openblas:jar:linux-x86_64:v0-3-gd5f13e59:compile
[DEBUG]                   org.bytedeco:openblas:jar:linux-armhf:v0-3-gd5f13e59:compile
[DEBUG]                   org.bytedeco:openblas:jar:linux-arm64:v0-3-gd5f13e59:compile
[DEBUG]                   org.bytedeco:openblas:jar:linux-ppc64le:v0-3-gd5f13e59:compile
[DEBUG]                   org.bytedeco:openblas:jar:windows-x86:v0-3-gd5f13e59:compile
[DEBUG]                   org.bytedeco:openblas:jar:windows-x86_64:v0-3-gd5f13e59:compile
[DEBUG]                org.bytedeco:opencv:jar:android-arm:v0-3-gd5f13e59:compile
[DEBUG]                org.bytedeco:opencv:jar:android-arm64:v0-3-gd5f13e59:compile
[DEBUG]                org.bytedeco:opencv:jar:android-x86:v0-3-gd5f13e59:compile
[DEBUG]                org.bytedeco:opencv:jar:android-x86_64:v0-3-gd5f13e59:compile
[DEBUG]                org.bytedeco:opencv:jar:ios-arm64:v0-3-gd5f13e59:compile
[DEBUG]                org.bytedeco:opencv:jar:ios-x86_64:v0-3-gd5f13e59:compile
[DEBUG]                org.bytedeco:opencv:jar:linux-x86:v0-3-gd5f13e59:compile
[DEBUG]                org.bytedeco:opencv:jar:linux-x86_64:v0-3-gd5f13e59:compile
[DEBUG]                org.bytedeco:opencv:jar:linux-armhf:v0-3-gd5f13e59:compile
[DEBUG]                org.bytedeco:opencv:jar:linux-arm64:v0-3-gd5f13e59:compile
[DEBUG]                org.bytedeco:opencv:jar:linux-ppc64le:v0-3-gd5f13e59:compile
[DEBUG]                org.bytedeco:opencv:jar:macosx-x86_64:v0-3-gd5f13e59:compile
```

The solution to this one would be to start using [flatten maven plugin](https://www.mojohaus.org/flatten-maven-plugin/) in builds. This plugin resolves properties and substitutes them to values before publishing artifacts.

**Comment by saudet** [comment]
That sounds reasonable. Could you send a pull request to that effect?

**Comment by saudet** [comment]
Actually, let's remove `${revision}` entirely. It was meant to shut up Maven complaining about `'version' contains an expression but should be a constant`, but `${project.parent.version}` *is* a constant in that context, so it should allow it. I've reverted those changes from commit fd11a9cd79764d30646ccbe513138a748f700e0e in the last commit, and we'll just live with the warning messages for now. Thanks for reporting!

**Comment by agolovenko** [comment]
Thanks, @saudet! If you decide at some point to use `flatten maven plugin`, feel free to ping me for PR!

**Comment by saudet** [comment]
Version 1.5.2 has been released without this issue. Thanks again for reporting!
