### ISSUE TITLE
Adding other native libs to platform jars

### ISSUE THREAD

**Issue by b005t3r** [bytedeco/javacpp-presets#809]
I'm trying to build a customized ffmpeg, relying on additional *.so files and my question is how do I include those files in the resulting jar file (ffmpeg-linux-x86_64.jar)? I can't find the place where these are listed. I'd also want to include additional executables (currently only ffmpeg and ffprobe are included) - how do I do that?

**Comment by saudet** [comment]
You'll need to create more "presets":
https://github.com/bytedeco/javacpp-presets/wiki/Create-New-Presets
If this is only about ffmpeg, just use the existing ones as templates:
https://github.com/bytedeco/javacpp-presets/tree/master/ffmpeg/src/main/java/org/bytedeco/ffmpeg
