### ISSUE TITLE
FFMpeg function pointer to av_log_default_callback

### ISSUE THREAD

**Issue by edwinRNDR** [bytedeco/javacpp-presets#812]
The FFMPEG bindings appear to miss a mechanism for restoring the default logger using `av_log_set_callback`. `av_log_default_callback` can be called but not used in places where function pointer arguments are taken.

**Comment by saudet** [comment]
I've added a fix for this in commit https://github.com/bytedeco/javacpp-presets/commit/adf432105258e9e23b07ca2a718de6b158db40eb. Thanks for reporting!

**Comment by saudet** [comment]
Fix released with version 1.5.6. Enjoy!
