### ISSUE TITLE
Libfreenect2 preset troubles

### ISSUE THREAD

**Issue by poqudrof** [bytedeco/javacpp-presets#82]
Hello, 

I try to create a [preset for libfreenect2](https://github.com/poqudrof/javacpp-presets/tree/master/libfreenect2), I have some trouble as it is my first time with JavaCPP. 

My problem for now it this templated virtual class : 

``` c++ 
namespace libfreenect2
{

template<typename PacketT> class PacketProcessor {
public:
  virtual ~PacketProcessor() {}

  virtual bool ready() { return true; }
  virtual void process(const PacketT &packet) = 0;
};
``` 

I figured the virtual part, but I have trouble to work with the template part... Here is part of my solution : 

``` java 
      @Namespace("libfreenect2") public static class PacketProcessor extends Pointer {
        static {   Loader.load(); }
        public PacketProcessor() {  super(); }
        public PacketProcessor(Pointer p) {       super(p);    }
        @Virtual public native boolean ready();
        @Virtual public native void process(@Const @ByRef org.bytedeco.javacpp.freenect2.DepthPacket packet);
    }
```

If you have a **simple** (or not) solution, we could update the [JavaCPP readme](https://github.com/bytedeco/javacpp/blob/master/README.md) which lacks the template part. 

Cheers, 

Jeremy.

**Comment by saudet** [comment]
We're going to need a separate doc for the `Parser`. Want to contribute? :) I like to think of the presets themselves as doc anyway. There's some templates in OpenCV, Caffe, and Tesseract for example:
https://github.com/bytedeco/javacpp-presets/blob/master/opencv/src/main/java/org/bytedeco/javacpp/presets/opencv_core.java
https://github.com/bytedeco/javacpp-presets/blob/master/caffe/src/main/java/org/bytedeco/javacpp/presets/caffe.java
https://github.com/bytedeco/javacpp-presets/blob/master/tesseract/src/main/java/org/bytedeco/javacpp/presets/tesseract.java

**Comment by poqudrof** [comment]
So, I will try to find my c++ skills back and make some examples. I will make them following the javacpp-presets compiling process which seems really neat.

**Comment by saudet** [comment]
I didn't try it, but something like
```java
infoMap.put(new Info("libfreenect2::PacketProcessor<libfreenect2::DepthPacket>").pointerTypes("DepthPacketProcessor").define())
```
etc for other class templates and types of packets, should work with the `Parser`.

**Comment by poqudrof** [comment]
It works fine  thanks !  

I have another issue, this time with "Enums", enums are types in C++, and not in Java with JavaCPP. However it is referenced as a type in C++ code and it causes some troubles... 

``` c++ 
class Frame {
public:
    enum Type
    {
        Color = 1,
        Ir = 2,
        Depth = 4
    };
}
typedef std::map<Frame::Type, Frame*> FrameMap;
```

``` java
infoMap.put(new Info("std::map<libfreenect2::Frame::Type,libfreenect2::Frame*>").pointerTypes("FrameMap").define());
```

With this I have code that tries to find the type  "Type" coming from the enum. I tried to force the enum as integer : 

``` java 
    infoMap.put(new Info("libfreenect2::Frame::Type").pointerTypes("int"));
``` 

Then, my C++ compiler is not happy at all with the types (as it should be). 
>  invalid conversion from ‘jint {aka int}’ to ‘libfreenect2::Frame::Type

It is better to force the cast ? Then how ? The best would be to create the type in Java, but it would not cast as integer that easily...

**Comment by saudet** [comment]
Yes, we have to force the cast... The `Parser` isn't that sophisticated and this is one place where it falls short, but it's not a very common corner case, and we can work around easily enough with a hack like this:
```java
infoMap.put(new Info("Frame::Type").valueTypes("@Cast(\"Frame::Type\") int"));
infoMap.put(new Info("std::map<Frame::Type,Frame*>").pointerTypes("FrameMap").define());
```

**Comment by saudet** [comment]
So, any luck with that so far? Any other issues?

**Comment by poqudrof** [comment]
Hello,  
I suspended this work for a few weeks as I have a  "hacky" version working, base on video4linux loopback : https://github.com/jfrey-xx/libfreenect2/tree/wip-k22v4l/examples/k22v4l 

I plan to continue the integration with JavaCPP, but it is not my main focus for now. 
I started to follow the CMake tutorial, to have a full suite CMake - C++ - JavaCPP - Java.
https://github.com/poqudrof/javacpp-tutorial-cpp .

**Comment by saudet** [comment]
Ok, no problem! Let me know when you make some progress or encounter a roadblock so I can help.

About CMake, are you trying to use it on top of the build scripts and Maven in some way?

**Comment by saudet** [comment]
FYI, the above mentioned issue should be fixed in this commit: https://github.com/bytedeco/javacpp/commit/45daaa690059ca65a12fdbc965beb8f0aebb6dbc

**Comment by saudet** [comment]
Hi there, are you still having issues with this?

**Comment by poqudrof** [comment]
Nope, I might get back to it to finish it, but not for now. We can close this :)

**Comment by saudet** [comment]
Done here: https://github.com/bytedeco/javacpp-presets/pull/340
