### ISSUE TITLE
No timecode.h in avutil

### ISSUE THREAD

**Issue by nanguantong** [bytedeco/javacpp-presets#822]
Hi, there is no timecode in avutil of ffmpeg, i want to use the av_timecode_init_from_string.

**Comment by saudet** [comment]
We should be able to just add it to the list here:
https://github.com/bytedeco/javacpp-presets/blob/master/ffmpeg/src/main/java/org/bytedeco/ffmpeg/presets/avutil.java#L42
Could you try that and send a pull request?

**Comment by nanguantong** [comment]
Hi,  the javacpp ffmpeg  do not implement the timecode in segment.c  ?

segment.c:
`av_dict_set(&s->metadata, "timecode",  av_timecode_make_string(&tc, buf, 0), 0);`
I set  0:0:0:0 to the timecode of metadata that is always 0:0:0:0， why？

**Comment by saudet** [comment]
Included in version 1.5.3. Thanks for reporting!
