### ISSUE TITLE
Cannot access slices of a 3d matrix

### ISSUE THREAD

**Issue by turekg** [bytedeco/javacpp-presets#824]
I am trying to get slices of a 3D image. In C++ this is done by passing an array of the ranges like:

Range ranges[3];
ranges[0] = Range::all();
ranges[1] = Range::all();
ranges[2] = Range(x,x+1) //within a for loop.
Mat 2dmat = 3dmat(ranges).clone();

But I can't see how to do this with import org.bytedeco.opencv.opencv_core.Mat;
The  method apply in the above mentioned class says it takes an array of Ranges, but it actually does not:
```
   /**\overload
    @param ranges Array of selected ranges along each array dimension.
    */
    public native @ByVal @Name("operator ()") Mat apply( @Const Range ranges );
```

**Comment by turekg** [comment]
Ah, I figured it out, the argument is a list of ranges.

**Comment by saudet** [comment]
`Range` is a `Pointer`, which provides functionality to access native arrays, so something like this will do what you need:
```java
Range ranges = new Range(3);
ranges.position(0).put(Range.all());
ranges.position(1).put(Range.all());
ranges.position(2).put(new Range(x,x+1));
Mat 2dmat = 3dmat(ranges.position(0)).clone();
```
