### ISSUE TITLE
gsl-platform 2.6-1.5.2 on sbt

### ISSUE THREAD

**Issue by yukoba** [bytedeco/javacpp-presets#825]
I can use gsl-platform 2.5-1.5.1 on sbt, but I cannot use 2.6-1.5.2 on sbt.

I just did these.
```
libraryDependencies += "org.bytedeco" % "gsl-platform" % "2.6-1.5.2"
libraryDependencies += "org.bytedeco" % "mkl-platform-redist" % "2019.5-1.5.2"
```

The test code is https://github.com/yukoba/GslTest .
The error message is https://gist.github.com/yukoba/74cdb483624517d13edf27ce660a0b7f .

I used sbt 1.2 to avoid this problem https://github.com/bytedeco/javacpp-presets/issues/823 .

**Comment by saudet** [comment]
Looks like a duplicate of https://github.com/sbt/sbt/issues/5046

**Comment by yukoba** [comment]
https://github.com/sbt/sbt/issues/5046 says it does not happen on sbt 1.2.
But my problem happens on sbt 1.2.
Is it the same?

**Comment by saudet** [comment]
It fails the same with and without Coursier? Did you make sure to delete
Ivy's cache? It sometimes gets corrupted

**Comment by yukoba** [comment]
You're right. I can compile with these.

1. Delete Ivy's cache ```.ivy2/cache/```.
2. Use sbt 1.3.4.
3. Add ```ThisBuild / useCoursier := false``` to build.sbt.

I could move all my sbt projects from JavaCPP 1.5.1 to 1.5.2.
I checked both Windows 10 and Ubuntu 18.04.
Thank you! I will close this issue.
