### ISSUE TITLE
[TensorFlow] On Windows it takes 2 minutes to initialize

### ISSUE THREAD

**Issue by yukoba** [bytedeco/javacpp-presets#842]
On Windows 10, it takes 2 minutes to initialize TensorFlow.
This only happens on Windows 10. This does not happen on Ubuntu 18.04.

I used VisualVM and I saw `Loader` uses a lot of time.

If I use `-Dorg.bytedeco.javacpp.logger.debug=true`, I saw many many symbolic link creation errors on Windows 10. I think it comes from https://github.com/bytedeco/javacpp/blob/1.5.2/src/main/java/org/bytedeco/javacpp/Loader.java#L536 .

Shouldn't you copy the files on Windows? Sorry if I am saying a wrong thing.

I am using tensorflow-platform 1.15.0-1.5.2.

**Comment by saudet** [comment]
It might not be related to Windows, but the Java class loader, see https://github.com/bytedeco/javacpp/issues/287. This issue has been fixed in the snapshots. Could you give it a try with 1.5.3-SNAPSHOT to make sure it doesn't happen there? See http://bytedeco.org/builds/ Thanks!

**Comment by yukoba** [comment]
Wow! It is fixed in 1.5.3-SNAPSHOT.
I will close this issue.

**Comment by zaleslaw** [comment]
@saudet the same issue on windows with 1.5.5. 
I run ExampleTrainer and it takes 10 minutes for execution (3 minutes for init)

**Comment by saudet** [comment]
That's for CUDA, right? It's probably just JIT compiling kernels...

**Comment by zaleslaw** [comment]
I have installed cuda 10.0 but I thought that it used cpu device by default. Can I disable that compilation and should it re-run such compilation for every run if trainerExample?

**Comment by saudet** [comment]
As long as you don't include any dependencies with `-gpu` in their names, it's going to run on CPU by default. Just make sure you don't have any of those, and confirm what it's loading by setting `org.bytedeco.javacpp.logger.debug` to `true` and by checking the messages that it outputs to the console.

**Comment by zaleslaw** [comment]
Thanks, continue my experiments and return

сб, 26 дек. 2020 г., 14:57 Samuel Audet <notifications@github.com>:

**Comment by saudet** [comment]
@zaleslaw I think I've (re)fixed this with commit https://github.com/bytedeco/javacpp/commit/2ee94b8317ec8e5009950384e3114f546ab094b5. Please try it again!

**Comment by zaleslaw** [comment]
Hi, @saudet could you please say me, is it available in snapshot or release? or I should build it from sources?

**Comment by zaleslaw** [comment]
@saudet thanks, looks like it was delivered in updated snapshot.
Now it takes a few seconds on my machine.
