### ISSUE TITLE
Multithreaded loading caffe model HDF5 error

### ISSUE THREAD

**Issue by dayong0325** [bytedeco/javacpp-presets#852]
When I started multiple threads to load caffe model, I sometimes reported an hdf5 error, and sometimes it loaded successfully，The current version in use is 1.5.2，The operating system is Red Hat Enterprise Linux Server release 7.6 (Maipo)

[hdf5-error2.txt](https://github.com/bytedeco/javacpp-presets/files/4296873/hdf5-error2.txt)
[hdf5-error3.txt](https://github.com/bytedeco/javacpp-presets/files/4296874/hdf5-error3.txt)
[model.zip](https://github.com/bytedeco/javacpp-presets/files/4296875/model.zip)
[hdf5-error.txt](https://github.com/bytedeco/javacpp-presets/files/4296876/hdf5-error.txt)
[hdf5-error1.txt](https://github.com/bytedeco/javacpp-presets/files/4296878/hdf5-error1.txt)

import org.bytedeco.caffe.Caffe;
import org.bytedeco.caffe.FloatNet;
import org.bytedeco.caffe.global.caffe;
/**
 * Created by Administrator on 2020/1/17.
 */
public class Test {
    public static void main(String[] args) throws Exception {
        int threadNum = Integer.parseInt(args[0]);

        String pnetModel = "/tmp/vehicle/22/det1.prototxt";
        String pnetWeights = "/tmp/vehicle/22/det1.caffemodel";

        String rnetModel = "/tmp/vehicle/22/det2.prototxt";
        String rnetWeights = "/tmp/vehicle/22/det2.caffemodel";

        String onetModel = "/tmp/vehicle/22/det3.prototxt";
        String onetWeights = "/tmp/vehicle/22/det3.caffemodel";

        Thread[] ts = new Thread[threadNum];
        for(int i = 0; i < threadNum; i++){
            ts[i] = new Thread(()->{
                Caffe.SetDevice(0);
                Caffe.set_mode(Caffe.GPU);
                FloatNet pnet = new FloatNet(pnetModel, caffe.TEST);
                pnet.CopyTrainedLayersFrom(pnetWeights);

                FloatNet rnet = new FloatNet(rnetModel, caffe.TEST);
                rnet.CopyTrainedLayersFrom(rnetWeights);

                FloatNet onet = new FloatNet(onetModel, caffe.TEST);
                onet.CopyTrainedLayersFrom(onetWeights);
            });
        }

        for(int i =0; i < threadNum; i++){
            ts[i].join();
        }
        for(int i =0; i < threadNum; i++){
            ts[i].start();
        }
    }
}

**Comment by saudet** [comment]
It doesn't sound like HDF5 is thread-safe:
https://support.hdfgroup.org/HDF5/faq/threadsafe.html
We probably need to synchronize those calls.
