### ISSUE TITLE
How to use arm64-v8a architecture version on Android

### ISSUE THREAD

**Issue by duck123456** [bytedeco/javacpp-presets#855]
splits {
        abi {
            enable true
            reset()
            include 'x86', 'armeabi', 'armeabi-v7a','arm64-v8a'
            universalApk false
        }
    }

    compile group: 'org.bytedeco', name: 'javacv', version: '1.4.3'
    compile group: 'org.bytedeco.javacpp-presets', name: 'opencv', version: '3.4.3-1.4.3', classifier: 'android-arm'
    compile group: 'org.bytedeco.javacpp-presets', name: 'opencv', version: '3.4.3-1.4.3', classifier: 'android-x86'
    compile group: 'org.bytedeco.javacpp-presets', name: 'ffmpeg', version: '4.0.2-1.4.3', classifier: 'android-arm'
    compile group: 'org.bytedeco.javacpp-presets', name: 'ffmpeg', version: '4.0.2-1.4.3', classifier: 'android-x86'

The crash occurred when I used include 'x86', 'armeabi', 'armeabi-v7a','arm64-v8a' .
The conflict is 'arm64-v8a'. How do I solve this, I need to use arm64-v8a
Thanks

**Comment by saudet** [comment]
The binaries for that platform are in artifacts with `android-arm64` as classifier: https://github.com/bytedeco/javacpp-presets/wiki/Reducing-the-Number-of-Dependencies#including-binaries-only-for-mobile-platforms

**Comment by duck123456** [comment]
> The binaries for that platform are in artifacts with `android-arm64` as classifier: https://github.com/bytedeco/javacpp-presets/wiki/Reducing-the-Number-of-Dependencies#including-binaries-only-for-mobile-platforms

Thanks! you are right

**Comment by saudet** [comment]
There is also now a plugin for Gradle to exclude by platform names:
https://github.com/bytedeco/gradle-javacpp#the-platform-plugin
If you try it out and find anything missing, please let me know!
