### ISSUE TITLE
Can't build tensorrt on Windows x86_64

### ISSUE THREAD

**Issue by StaticDefault** [bytedeco/javacpp-presets#858]
# bash cppbuild.sh -platform windows-x86_64 -extension "-gpu" install tensorrt
Detected platform "windows-x86_64"
Building for platform "windows-x86_64" with extension "-gpu"
Installing "tensorrt"
/d/javacpp/javacpp-presets/tensorrt/cppbuild /d/javacpp/javacpp-presets
Error: Platform "windows-x86_64" is not supported
/d/javacpp/javacpp-presets

How to build tensorrt for windows x86_64? I think tensorrt's headfile and interface are same on Windows and Linux.

**Comment by saudet** [comment]
It's not currently supported, but it might just be a question of adding the right paths to these files for  `@Platform(value = "windows", ...)`:
https://github.com/bytedeco/javacpp-presets/blob/master/tensorrt/cppbuild.sh
https://github.com/bytedeco/javacpp-presets/blob/master/tensorrt/src/main/java/org/bytedeco/tensorrt/presets/nvinfer.java

**Comment by StaticDefault** [comment]
thx for your reply.

i have one more question. 

if i add win tensorrt header file path and win platform string  to nvinfer.java and remove the condition statement in cppbuild.sh.
can i build on windows?

**Comment by saudet** [comment]
If the `cppbuild.sh` script fails, the build is going to fail. Please read the following page:
https://github.com/bytedeco/javacpp-presets/wiki/Create-New-Presets

**Comment by StaticDefault** [comment]
thank you! i added new windows preset to tensorrt module. 

now, i can use tensorrt on windows!

**Comment by saudet** [comment]
Please send a pull request with your modifications!

**Comment by StaticDefault** [comment]
ok! i will send pr tomorrow(because, i want clean my code)
