### ISSUE TITLE
scipy module, how get the result to the Java call

### ISSUE THREAD

**Issue by dayong0325** [bytedeco/javacpp-presets#861]
I need to pass the Java variables to python  then get result to java, 
example：
String iou_matrix = ....

PyRun_StringFlags("from scipy.optimize import linear_sum_assignment\n"
                + "matched_indices = linear_assignment(iou_matrix)\n"
                + "print(matched_indices)\n",Py_file_input, globals, globals, null);

String matched_indices = ....

**Comment by saudet** [comment]
We have to use the C API of NumPy:
https://docs.scipy.org/doc/numpy/reference/c-api.html

There's an example of this here:
https://github.com/bytedeco/javacpp-presets/tree/master/numpy#the-matmuljava-source-file
