### ISSUE TITLE
opencv-platform-4.1.2-1.5.2: SIGSEGV in libopencv_core.4.1.dylib

### ISSUE THREAD

**Issue by turekg** [bytedeco/javacpp-presets#865]
Hello, I am having this problem with a SIGSEV crash that is happening on one MacPro and not on another. As far as we can see we have the same OS versions (10.15.4) and java versions (8.0_241-b07) The  problem is not happening in java, but OpenCV support group has declined to help . The header of the resulting log file (attached) says:
```
A fatal error has been detected by the Java Runtime Environment:
#
SIGSEGV (0xb) at pc=0x0000000194ba8b33, pid=811, tid=0x000000000000981f

#
JRE version: Java(TM) SE Runtime Environment (8.0_241-b07) (build 1.8.0_241-b07) Java VM: Java HotSpot(TM) 64-Bit Server VM (25.241-b07 mixed mode bsd-amd64 compressed oops)
Problematic frame: C [libopencv_core.4.1.dylib+0x2edb33] cv::va_intel::convertFromVASurface(void*, unsigned int, cv::Size_<int>, cv::_OutputArray const&)+0x4e533
#
```
and I cannot produce a core dump. Any idea how I can debug this? To make things a bit more challenging it all works great in on my machine, it's a colleague's that is problematic, so at best I can remote access his machine. Any ideas where to look would be greatly appreciated. Cheers Gaby

[hs_err_pid811.log](https://github.com/bytedeco/javacpp-presets/files/4443822/hs_err_pid811.log)

**Comment by saudet** [comment]
Please try with OpenCV 4.3.0: http://bytedeco.org/builds/

**Comment by turekg** [comment]
Will do and report back thanx

**Comment by turekg** [comment]
Yes! That seems to have solved the problem. Thanx!
