### ISSUE TITLE
[mkl-dnn] MKL-DNN project changed name (again)

### ISSUE THREAD

**Issue by blueberry** [bytedeco/javacpp-presets#868]
Hi, the Intel MKL-DNN, aka DNNL, is now officially named oneDNN, and this time they changed the GitHub project address. The old address now forwards to https://github.com/oneapi-src/oneDNN

They claim that, so far, DNNL api should continue to work, so I guess this requires "only" changes in javacpp-preset project name and appropriate package updates...

**Comment by saudet** [comment]
The library itself is still named DNNL, so we don't need to change anything. It's just the project name that changed.

**Comment by blueberry** [comment]
Thank you. I must have misunderstood their readme.

**Comment by saudet** [comment]
Well, who knows, maybe they'll decide to release `libonednn.so.2` or something :)
We'll see when that happens.
