### ISSUE TITLE
no jnilept in java.library.path under Debian7

### ISSUE THREAD

**Issue by oelleo** [bytedeco/javacpp-presets#87]
Hello,

I found this error when I tried to initialize JavaCpp Tesseract under my debian7 64bits
``` no jnilept in java.library.path ```
Do you know what can I do to solve this ?

**Comment by oelleo** [comment]
I also the following error  on a debian 8 i686 (32bits)

Error: Illegal min or max specification!
"Fatal error encountered!" == NULL:Error:Assert failed:in file globaloc.cpp, line 75
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0xa6eb4d75, pid=27000, tid=3065731904
#
# JRE version: Java(TM) SE Runtime Environment (7.0_72-b14) (build 1.7.0_72-b14)
# Java VM: Java HotSpot(TM) Client VM (24.72-b04 mixed mode linux-x86 )
# Problematic frame:
# C  [libtesseract.so.3+0x228d75]  ERRCODE::error(char const*, TessErrorLogCode, char const*, ...) const+0xc5
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /var/lib/jenkins/workspace/ocr/hs_err_pid27000.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.sun.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

which crashes my JVM...

**Comment by saudet** [comment]
Could you try to run BasicExample.java with the pom.xml file from the
README file? Let me know if that works or not.
Thanks

**Comment by oelleo** [comment]
For my first error (jnilept not in java path) I tried your solution from stackoverflow (http://stackoverflow.com/questions/30925074/javacpp-liblept-4-dylib-library-not-loaded)

And after building again my project I ended with my second error. I'll try to run your BasicExample and come back to you !

**Comment by oelleo** [comment]
Actually I found a solution from this link (http://stackoverflow.com/questions/23579290/tesseract-error-illegal-min-or-max-specification?ref=driverlayer.com/web)

I needed to change my locale LC_NUMERIC from "fr_FR.UTF-8" to "C"
`export LC_NUMERIC="C"`

It seems to be because in my country we use colon instead of dot for decimal (?)

I'll try to include that in my code but maybe you can add it somewhere in yours to prevent this problem in the future ?

**Comment by oelleo** [comment]
adding this `Locale.setDefault(Locale.Category.FORMAT, Locale.ENGLISH);` before initializing tesseract worked for me !

**Comment by saudet** [comment]
Ok, so this is an issue with Tesseract?

**Comment by oelleo** [comment]
Indeed, it seems to be.

**Comment by saudet** [comment]
Maybe they've fixed that in 3.04. I've just updated the presets in this commit: https://github.com/bytedeco/javacpp-presets/commit/d7cfc3d084f9e4cf6d1a83e2417902680caa9550
Could you try it out and let me know if that fixes this issue? Thanks!

**Comment by oelleo** [comment]
Hi, I just tried and the problem isn't solved, I still must change the LC_NUMERIC to "C" in order to avoid the ```Error: Illegal min or max specification!
"Fatal error encountered!" == NULL:Error:Assert failed:in file globaloc.cpp, line 75```

**Comment by saudet** [comment]
Ok, thanks for testing. So, please report that upstream here: 
https://github.com/tesseract-ocr/tesseract/issues
Thanks!

**Comment by oelleo** [comment]
Thanks to you for your quick replies !

**Comment by oelleo** [comment]
Hi,
I found a patch here (https://code.google.com/p/tesseract-ocr/issues/detail?id=910) that correct the error "Illegal min or max specification" and the need to manually change the local  LC_NUMERIC.

It seems that this patch is not applied in Tesseract 3.04 but maybe you can add it to your project ? 
It would be very nice because changing the locale environnement is not a solution that I can use in a production environnement?

**Comment by saudet** [comment]
Sure! Check how patches are applied in cppbuild.sh for opencv, ffmpeg, etc
and replicate something like that for Tesseract. Since it's for all
platforms, we might as well apply it right after the extraction though. And
send a pull request with the changes. Sounds good?
