### ISSUE TITLE
Can you call scipy in multiple threads?

### ISSUE THREAD

**Issue by dayong0325** [bytedeco/javacpp-presets#870]
I synchronize those calls. PyRun_StringFlags holding the lock always

**Comment by saudet** [comment]
We still need to acquire the GIL before making calls in a given thread.

**Comment by saudet** [comment]
All the information we need is available here: https://docs.python.org/3/c-api/init.html

We can also use this file as a template: https://github.com/eclipse/deeplearning4j/blob/master/rl4j/rl4j-gym/src/main/java/org/deeplearning4j/rl4j/mdp/gym/GymEnv.java

**Comment by dayong0325** [comment]
Thanks for your reply very much, the problem of calling has been solved, I just want to call scipy.linear_sum_assignment function with multiple threads, but using GIL this way affects the performance, is there any way without locking?

**Comment by saudet** [comment]
No, that's a limitation of CPython, but there are workarounds, for example,
you could try to use multiprocessing:
https://docs.python.org/3/library/multiprocessing.html
