### ISSUE TITLE
windows-x86_64 snapshot is missing

### ISSUE THREAD

**Issue by yukoba** [bytedeco/javacpp-presets#875]
There is windows-x86, but the windows-x86_64 snapshot is missing now.
For example,
https://oss.sonatype.org/content/repositories/snapshots/org/bytedeco/llvm/10.0.0-1.5.4-SNAPSHOT/
I think all the projects are missing.

https://oss.sonatype.org/content/repositories/snapshots/org/bytedeco/llvm/10.0.0-1.5.4-SNAPSHOT/maven-metadata.xml
maven-metadata is not updated too.

**Comment by saudet** [comment]
That's normal, not everything is available all the time: http://bytedeco.org/builds/

**Comment by yukoba** [comment]
I'm not understanding.

I created this ```pom.xml``` file.
```xml
<project>
    <modelVersion>4.0.0</modelVersion>
    <groupId>org.bytedeco.opencv</groupId>
    <artifactId>stitching</artifactId>
    <version>1.5.4-SNAPSHOT</version>
    <properties>
        <exec.mainClass>Stitching</exec.mainClass>
    </properties>
    <dependencies>
        <dependency>
            <groupId>org.bytedeco</groupId>
            <artifactId>llvm-platform</artifactId>
            <version>10.0.0-1.5.4-SNAPSHOT</version>
        </dependency>
    </dependencies>
    <repositories>
        <repository>
            <id>sonatype-nexus-snapshots</id>
            <url>https://oss.sonatype.org/content/repositories/snapshots</url>
        </repository>
    </repositories>
    <pluginRepositories>
        <pluginRepository>
            <id>sonatype-nexus-snapshots</id>
            <url>https://oss.sonatype.org/content/repositories/snapshots</url>
        </pluginRepository>
    </pluginRepositories>
</project>
```

But ```mvn -U compile``` returns,

```
[ERROR] Failed to execute goal on project stitching: Could not resolve dependencies for project org.bytedeco.opencv:stitching:jar:1.5.4-SNAPSHOT: Could not find artifact org.bytedeco:llvm:jar:windows-x86_64:10.0.0-1.5.4-20200421.130605-25 in sonatype-nexus-snapshots (https://oss.sonatype.org/content/repositories/snapshots) -> [Help 1]
```

What should I do?

**Comment by saudet** [comment]
If you need Windows, wait until the build gets done: https://ci.appveyor.com/project/Bytedeco/javacpp-presets/

**Comment by yukoba** [comment]
OK. So my pull request is a reason. 😅
I'm using sbt and sbt cannot use ```javacpp.platform``` and sbt-javacpp cannot use SNAPSHOT because of this method https://github.com/bytedeco/sbt-javacpp/blob/master/src/main/scala/org/bytedeco/sbt/javacpp/Plugin.scala#L62 .
I think you should change it ```case _ => version```.

**Comment by saudet** [comment]
Please send a pull request!
