### ISSUE TITLE
Questions, can't find the answers

### ISSUE THREAD

**Issue by stemrobotics** [bytedeco/javacpp-presets#876]
I am very new to Javacv and using maven and have two questions I can't find answers to:

1) In  opencv.jar there are what appears to be duplicate APIs, the org.bytedeco.opencv name space and the org.opencv name space. What is going on here?  Which of these sets of classes should you use? Why are there two sets of APIs?

2) I used maven to download the javacv-platform artifact to my windows pc and got all of the jars for the other platforms downloaded as well. I don't understand how to use the -D option to set a variable to subset the download to only windows in an Eclipse environment. I am running the program under Eclipse.

**Comment by saudet** [comment]
Please read the following and let me know if you still have any questions after that:
- http://bytedeco.org/faq/
- https://github.com/bytedeco/javacpp-presets/wiki/Reducing-the-Number-of-Dependencies

**Comment by stemrobotics** [comment]
Thanks for the reply. I have read the material on your site  and  looked at the source code. There is a lot there that is over my head...but I think I get the drift. I want to write Java programs on Windows using OpenCV and Javacv looks like the way to go. But I still don't get why there are two APIs in opencv.jar?  It appears there is the JavaCPP API and what appears to be the original opencv API. Why both? I only expected to see the JavaCPP API. How do these two APIs relate? What is the correct way to use them?

Also, where does the name PRESETS as used on your projects come from?

**Comment by saudet** [comment]
No need to use the official API if you don't need it. It's just there because the authors of OpenCV don't see the value in JavaCPP and decided to come up with something inferior, but because it's official, people want to use it, so we can also use it with JavaCV.

A name is just a name. There's no other reason to give something a name other than to be able to more easily refer to that thing that didn't previously have a name. If you have a better name in mind, let me know.

**Comment by saudet** [comment]
And about Eclipse IDE, it's pretty buggy when it comes to importing Maven artifacts, so if you're having problems with that, be sure to switch to using Maven instead.

**Comment by saudet** [comment]
> And about Eclipse IDE, it's pretty buggy when it comes to importing Maven artifacts, so if you're having problems with that, be sure to switch to using Maven instead.

Or Gradle, there's Gradle JavaCPP too these days: https://github.com/bytedeco/gradle-javacpp
