### ISSUE TITLE
ClassNotFoundException when calling cudaDeviceReset in a subproject

### ISSUE THREAD

**Issue by fcunilim** [bytedeco/javacpp-presets#877]
In Eclipse Java, I have the following situation:

```
Project1
+- Project2
   +- Project3
```

Project1, Project2 and Project3 are regular Java projects that have been created through File > New Java project, then converted to Maven projects through a right-click in Project Explorer > Maven > Convert to Maven. Project1 contains my application entrypoint (static main method). Project1 code calls Project2 code, which in turns calls Project3 code:

```
// Project1
public class Project1Class {
    public static void main(String[] args)
    {
        Project2Class.foo();
        System.out.println("Done");
    }
}
// Project2
public class Project2Class {
    public static void foo()
    {
        Project3Class.bar();
    }
}
// Project3
public class Project3Class {
    public static void bar()
    {
       cudaDeviceReset();
    }
}

```
Project3 uses the following CUDA Maven dependency:

```
<dependency>
  <groupId>org.bytedeco</groupId>
  <artifactId>cuda-platform-redist</artifactId>
  <version>10.2-7.6-1.5.3</version>
</dependency>
```

My problem is the following:

When running or debugging Project1, I can see that Project1, Project2 and Project3 'target/classes' folders are in the classpath, as expected, Maven dependencies for Project1 and Project2 also are in the classpath, **but the Maven dependencies of Project3 are missing**. As a result, native libraries cannot be loaded, and I get an exception:

```
java.lang.ClassNotFoundException: org.bytedeco.cuda.global.cudart
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
 [wrapped] java.lang.NoClassDefFoundError: org/bytedeco/cuda/global/cudart
	[...]
	at Project1.main()
```

If I move the cuda-platform-redist dependency declaration from Project3 to Project2, then the Maven dependency indeed ends up in the classpath, and calling cudaDeviceReset() succeeds.

I tried with Eclipse 2019-09 and 2020-03, same result.

It seems Eclipse does not add Maven dependencies that reside in indirect dependencies. How can I tell it to add Maven dependencies in the classpath for all dependencies, i.e. both direct and indirect?
Ideally I don't want to declare the dependency in Project2, because it's got nothing to do there.

**Comment by fcunilim** [comment]
Nevermind, I figured it out. Project2's pom.xml missed an explicit Project3 dependency.
What was very misleading is that Eclipse does propagate Project2's Maven dependencies in the classpath even if you don't specify a pom.xml dependency. This is very odd, strange and disturbing.

**Comment by saudet** [comment]
You're talking about M2Eclipse? Yes, that's pretty buggy. It's best to avoid it.
