### ISSUE TITLE
Could not parse "opencv2/hal/defs.h": File does not exist

### ISSUE THREAD

**Issue by Refikcanmalli** [bytedeco/javacpp-presets#88]
I was building opencv from source and maven install showed me this error
 
tried with both MAC OSX and Ubuntu 14.04 platforms same result.

1) git clone https://github.com/bytedeco/javacpp-presets.git
2) cd javacpp-presets
3) ANDROID_NDK=PATH_TO_NDK bash cppbuild.sh -platform android-arm  install  opencv 
4) mvn install --projects .,opencv

failure on step 4 
Result
<img width="570" alt="screenshot" src="https://cloud.githubusercontent.com/assets/7341604/9831242/1a4238a6-5957-11e5-9c20-a9a793c8b376.png">

**Comment by saudet** [comment]
We also need to specify the platform for Maven, something like 
```
mvn install --projects .,opencv -Dplatform=android-arm -Dplatform.root=/path/to/android-ndk/ -Dplatform.compiler=/path/to/arm-linux-androideabi-g++
```
as per the comments in the `pom.xml` file.
