### ISSUE TITLE
missing x64 .so files

### ISSUE THREAD

**Issue by robmr88** [bytedeco/javacpp-presets#883]
Hi, I'm working on a project that already had bytedeco integrated when it was assigned to me. I can see that the project has some .so files int hea armeabi-v7a and x86 jni folders but it's missing the x64 files. Can anyone give me a hand on how to make the 64 bit .so files? 
Thanks

<img width="662" alt="Screenshot at May 12 10-41-06" src="https://user-images.githubusercontent.com/60899275/81661914-21d8e580-943d-11ea-84e5-7fe3b1a3ea09.png">

**Comment by saudet** [comment]
You'll need to upgrade to a newer version that comes with a build for those.

**Comment by robmr88** [comment]
I understand. So If i add the .so files by hand that won't do it ?
If i change the version do I have to change all the .so files ? 
Sorry for all the questions , it's just that I don't understand what version the developer before me used and also I don't understand very well bytedeco, it's the first time that I have to use it in a project. Thank you

<img width="640" alt="Screenshot at May 12 14-46-21" src="https://user-images.githubusercontent.com/60899275/81692911-65444b80-945f-11ea-8577-92fa1732e1e4.png">

**Comment by saudet** [comment]
If you have the files, you can add them manually, sure. What is the issue exactly?

**Comment by robmr88** [comment]
the old integration doen't seem to support 64 bit processors and crashes. So I was trying to understand how they integrated bytedeco and update it

**Comment by saudet** [comment]
Right, so like I said you'll need to get a version that does have the builds you need:
https://search.maven.org/search?q=bytedeco%20opencv
https://search.maven.org/search?q=bytedeco%20ffmpeg

**Comment by robmr88** [comment]
Thank you

**Comment by robmr88** [comment]
just one more thing, could you tell me in which version was the android 64 bit support introduced? Right now the project has the very first version of the libraries, if I add the .so file from the 1.5.3 versions a lot of errors appear. Maybe I could have an easier update process if I start with the first version that has 64 bit support.

<img width="352" alt="Screenshot at May 12 17-37-02" src="https://user-images.githubusercontent.com/60899275/81714301-389c2e00-9477-11ea-839c-93124c9ed4c7.png">

**Comment by saudet** [comment]
According to the change log, that would be 1.4.1:
https://github.com/bytedeco/javacpp-presets/blob/master/CHANGELOG.md
