### ISSUE TITLE
when to release 1.5.4?

### ISSUE THREAD

**Issue by ericxsun** [bytedeco/javacpp-presets#885]
especially DNNL 1.4

**Comment by saudet** [comment]
It's already available as snapshots: http://bytedeco.org/builds/

**Comment by ericxsun** [comment]
> It's already available as snapshots: http://bytedeco.org/builds/

Thanks a lot.

There are some difference between release([4.3.0-1.5.3](https://repo1.maven.org/maven2/org/bytedeco/opencv/4.3.0-1.5.3/)) and snapshots([4.3.0-1.5.4-SHANSHOT](https://oss.sonatype.org/content/repositories/snapshots/org/bytedeco/opencv/4.3.0-1.5.4-SNAPSHOT/)): only gpu side was published in 1.5.4-SNAPSHOT, no cpu.

xxx-1.5.4-SNAPSHOT
- opencv:  no cpu
- onnxruntime: no linux-x86_64

**Comment by saudet** [comment]
As mentioned on that page, that's just the server cleaning up files every 3
days or so. They should be back in 1 or 2 days.

**Comment by ericxsun** [comment]
> As mentioned on that page, that's just the server cleaning up files every 3 days or so. They should be back in 1 or 2 days.

okay, thanks very much

**Comment by blueberry** [comment]
Hi, @saudet

I understand that there are SNAPSHOTs available (I'm using that fo DNNL 1.5). However, releasing a non-shapshot library that depends on javacpp-dnnl requires that all dependencies be non-snapshot. That practically constrains the release schedule of all software that is using javacpp. 

Now, this is not something that you can solve generally :) OTOH, can you hint at an approximate data when we can expect the 1.5.4 release, or even consider doing the javacpp releases more often?

**Comment by saudet** [comment]
Well, if you're only interested in DNNL, we can make a release of just that
for 1.5.3...

**Comment by blueberry** [comment]
That would be great! Thank you.

**Comment by saudet** [comment]
Ok, could inquire about when they plan to release  1.5.1 or 1.6? If it's like next week, we'll wait a bit.

**Comment by blueberry** [comment]
According to their timeline, the next release is expected in about a month. https://github.com/oneapi-src/oneDNN/milestones

**Comment by saudet** [comment]
Thanks! And you're OK without 1.5.1?

**Comment by blueberry** [comment]
Yes. As far as I can see at their github home, 1.5. is the latest release, and is also the one I am using through javacpp.
In general, I'm very satisfied with how javacpp tracks their releases (pretty fast). The only thing that might be easier is if the releases could be also tracked in the current release of javacpp (for example, javacpp dnnl 1.5-1.5.3 in addition to the usual 1.5-1.5.4-SNAPSHOT). 
And it's not that I find javacpp shapshots lacking (they always worked amazingly well for me), it's only the problem that maven won't let me releasing my libraries that depend on these snapshots, so I have to wait to the official javacpp release.

Thank you!

**Comment by saudet** [comment]
Ok, I've released 1.5-1.5.3: https://repo1.maven.org/maven2/org/bytedeco/dnnl/1.5-1.5.3/ Enjoy!

**Comment by blueberry** [comment]
Thank you!
