### ISSUE TITLE
java.lang.NoClassDefFoundError: org.bytedeco.ffmpeg.global.avutil javacv 1.5.3

### ISSUE THREAD

**Issue by Thomas-Markhorst** [bytedeco/javacpp-presets#886]
I want to load frames from an mp4 file, so I want to use FFmpegFrameGrabber. So I added the following to my build.gradle file:
`androidTestImplementation group: 'org.bytedeco', name: 'javacv', version: '1.5.3'`
When I ran that it gave
`java.lang.NoClassDefFoundError: org.bytedeco.ffmpeg.global.avutil
at java.lang.Class.classForName(Native Method)
at java.lang.Class.forName(Class.java:453)
at org.bytedeco.javacpp.Loader.load(Loader.java:1176)
at org.bytedeco.javacpp.Loader.load(Loader.java:1109)
at org.bytedeco.ffmpeg.avformat.Read_packet_Pointer_BytePointer_int.<clinit>(Read_packet_Pointer_BytePointer_int.java:45)
at org.bytedeco.javacv.FFmpegFrameGrabber.<clinit>(FFmpegFrameGrabber.java:345)`

So I added the javacpp dependency:
`androidTestImplementation group: 'org.bytedeco', name: 'javacpp', version: '1.5.3'`

But it still gives the same error. If possible I prefer to just use Gradle for the dependency and not add javacv as a .jar to my libraries.

I'm using this for tests performing on an android tablet.

**Comment by Thomas-Markhorst** [comment]
I also added:
`androidTestImplementation group: 'org.bytedeco', name: 'ffmpeg', version: '1.5.3'`
to be sure although I think FFmpeg is already included in javacv.

**Comment by saudet** [comment]
Make sure you're using `javacv-platform`, not just `javacv`.

**Comment by Thomas-Markhorst** [comment]
When I did that, it installed dependencies for all platforms (I only need Android 64 bit) and it slows down my gradle build a lot. That's one thing I need to change.
Then when running the code it gave me the error that my android API has a wrong version so it cannot install the application, I'm running api 29. It does not specify something else though so that makes debugging difficult. Is this a known issue to you?

**Comment by saudet** [comment]
Follow this guide:
https://github.com/bytedeco/javacpp-presets/wiki/Reducing-the-Number-of-Dependencies

**Comment by saudet** [comment]
What is the error message that you get? I'm not aware of any issues with API 29, no.

**Comment by saudet** [comment]
Please also give it a try with the new platform plugin from Gradle JavaCPP:
https://github.com/bytedeco/gradle-javacpp#the-platform-plugin

**Comment by saudet** [comment]
I'm assuming that everything is working as expected now, but please let me know if you have more questions. Thanks!
