### ISSUE TITLE
Errors when working with certain data sizes

### ISSUE THREAD

**Issue by tobq** [bytedeco/javacpp-presets#888]
I'm running: Windows - JDK 14 - org.bytedeco:fftw-platform:3.3.8-1.5.3

When I change the length of the input data array, I get errors - seemingly randomly.
```Javascript

   public static void main(String[] args) {
        Loader.load(org.bytedeco.fftw.global.fftw3.class);
        fftw3.fftw_plan plan;
        var data = new double[]{0, 1, 2, 4, 5, 7, 7, 9, 2, 23, 3, 2, 2, 2, 2, 2, 1, 3, 3, 3, 3, 312, 32, 3, 2, 9};
        var sampleCount = data.length;
        var result = new DoublePointer(sampleCount);
        try (var signal = new DoublePointer(sampleCount)) {
            System.out.println("sampleCount = " + sampleCount);
            signal.put(data);
            plan = fftw_plan_dft_1d(
                    sampleCount, // TODO: investigate why N BE DIFFERENT TO INPUT SIZE?
                    signal,
                    result,
                    FFTW_FORWARD,
                    (int) FFTW_ESTIMATE
            );
        }
        fftw_execute(plan);
        fftw_destroy_plan(plan);
    }

```

I've read that FFT only works with sizes that are powers of 2, but also read FFTW specifically didn't have this limitation

----
Full error:

`> Process 'command 'C:/Program Files/Java/jdk-14.0.1/bin/java.exe'' finished with non-zero exit value -1073740940`

**Comment by saudet** [comment]
You'll need to execute FFTW's functions within the try { } block.

**Comment by tobq** [comment]
@saudet but why would this error be happening, only with certain sizes of data? The library is supposed to support all isn't it?

**Comment by tobq** [comment]
@saudet That fixed it - I realised that you'd obviously want the input `signal` during `execute`...

**Comment by tobq** [comment]
I'm still confused about how it works with some array sizes though, maybe some internal caching going on

**Comment by saudet** [comment]
Deallocating memory doesn't necessarily make it unavailable to the process. Sometimes we can still access it, that's normal.

**Comment by tobq** [comment]
@saudet False positive. Running this results in an error still:

`    public static void main(String[] args) {
        Loader.load(org.bytedeco.fftw.global.fftw3.class);
        fftw3.fftw_plan plan;
        var data = new double[]{0, 1, 2, 4, 5, 7, 7, 9, 2, 23, 3, 2, 2, 2, 2, 2, 1, 3, 3, 3, 3, 312, 32, 3, 2, 9};
        var sampleCount = data.length;
        var result = new DoublePointer(sampleCount);
        try (var signal = new DoublePointer(sampleCount)) {
            System.out.println("sampleCount = " + sampleCount);
            signal.put(data);
            plan = fftw_plan_dft_1d(
                    sampleCount, // TODO: investigate why N would BE DIFFERENT TO INPUT SIZE?
                    signal,
                    result,
                    FFTW_FORWARD,
                    (int) FFTW_ESTIMATE
            );
            fftw_execute(plan);
        }
        fftw_destroy_plan(plan);
    }`

**Comment by saudet** [comment]
You'll need to put `fftw_destroy_plan()` as well in the `try { }` block.

**Comment by tobq** [comment]
I think I'll stop trying to hack javas try-resourcing and cpp resource management together...

**Comment by tobq** [comment]
This issue persists....
```Java
    public static void main(String[] args) {
        var data = new double[]{
                1, 2, 3, 4, 5, 2, 5, 5, 1, 1, 2, 3, 4, 5, 2, 5, 5, 1,
                1, 2, 3, 4, 5, 2, 5, 5, 1, 1, 2, 3, 4, 5, 2, 5, 5, 1,
                1, 2, 3, 4, 5, 2, 5, 5, 1, 1, 2, 3, 4, 5, 2, 5, 5, 1,
                1, 2, 3, 4, 5, 2, 5, 5, 1, 1, 2, 3, 4, 5, 2, 5, 5, 1,
                1, 2, 3, 4, 5, 2, 5, 5, 1, 1, 2, 3, 4, 5, 2, 5,
                1, 2, 3, 4, 5, 2, 5, 5, 1, 1, 2, 3, 4, 5, 2, 5, 5, 1,
                1, 2, 3, 4, 5, 2, 5, 5, 1, 1, 2, 3, 4, 5, 2, 5, 5, 1,
                1, 2, 3, 4, 5, 2, 5, 5, 1, 1, 2, 3, 4, 5, 2, 5, 5, 1,
                1, 2, 3, 4, 5, 2, 5, 5, 1, 1, 2, 3, 4, 5, 2, 5, 5, 1,
                1, 2, 3, 4, 5, 2, 5, 5, 1, 1, 2, 3, 4, 5, 2, 5,
                1, 2, 3, 4, 5, 2, 5, 5, 1, 1, 2, 3, 4, 5, 2, 5, 5, 1,
                1, 2, 3, 4, 5, 2, 5, 5, 1, 1, 2, 3, 4, 5, 2, 5, 5, 1,
                1, 2, 3, 4, 5, 2, 5, 5, 1, 1, 2, 3, 4, 5, 2, 5, 5, 1,
                1, 2, 3, 4, 5, 2, 5, 5, 1, 1, 2, 3, 4, 5, 2, 5, 5, 1,
                1, 2, 3, 4, 5, 2, 5, 5, 1, 1, 2, 3, 4, 5, 2, 5,
                1, 2, 3, 4, 5, 2, 5, 5, 1, 1, 2, 3, 4, 5, 2, 5, 5, 1,
                1, 2, 3, 4, 5, 2, 5, 5, 1, 1, 2, 3, 4, 5, 2, 5, 5, 1,
                1, 2, 3, 4, 5, 2, 5, 5, 1, 1, 2, 3, 4, 5, 2, 5, 5, 1,
                1, 2, 3, 4, 5, 2, 5, 5, 1, 1, 2, 3, 4, 5, 2, 5, 5, 1,
                1, 2, 3, 4, 5, 2, 5, 5, 1, 1, 2, 3, 4, 5, 2, 5,
                1, 2, 3, 4, 5, 2, 5, 5, 1, 1, 2, 3, 4, 5, 2, 5, 5, 1,
                1, 2, 3, 4, 5, 2, 5, 5, 1, 1, 2, 3, 4, 5, 2, 5, 5, 1,
                1, 2, 3, 4, 5, 2, 5, 5, 1, 1, 2, 3, 4, 5, 2, 5, 5, 1,
                1, 2, 3, 4, 5, 2, 5, 5, 1, 1, 2, 3, 4, 5, 2, 5, 5, 1,
                1, 2, 3, 4, 5, 2, 5, 5, 1, 1, 2, 3, 4, 5, 2, 5,
                1, 2, 3, 4, 5, 2, 5, 5, 1, 1, 2, 3, 4, 5, 2, 5, 5, 1,
                1, 2, 3, 4, 5, 2, 5, 5, 1, 1, 2, 3, 4, 5, 2, 5, 5, 1,
                1, 2, 3, 4, 5, 2, 5, 5, 1, 1, 2, 3, 4, 5, 2, 5, 5, 1,
                1, 2, 3, 4, 5, 2, 5, 5, 1, 1, 2, 3, 4, 5, 2, 5, 5, 1,
                1, 2, 3, 4, 5, 2, 5, 5, 1, 1, 2, 3, 4, 5, 2, 5,
                1, 2, 3, 4, 5, 2, 5, 5, 1, 1, 2, 3, 4, 5, 2, 5, 5, 1,
                1, 2, 3, 4, 5, 2, 5, 5, 1, 1, 2, 3, 4, 5, 2, 5, 5, 1,
                1, 2, 3, 4, 5, 2, 5, 5, 1, 1, 2, 3, 4, 5, 2, 5, 5, 1,
                1, 2, 3, 4, 5, 2, 5, 5, 1, 1, 2, 3, 4, 5, 2, 5, 5, 1,
                1, 2, 3, 4, 5, 2, 5, 5, 1, 1, 2, 3, 4, 5, 2, 5,
                1, 2, 3, 4, 5, 2, 5, 5, 1, 1, 2, 3, 4, 5, 2, 5, 5, 1,
                1, 2, 3, 4, 5, 2, 5, 5, 1, 1, 2, 3, 4, 5, 2, 5, 5, 1,
                1, 2, 3, 4, 5, 2, 5, 5, 1, 1, 2, 3, 4, 5, 2, 5, 5, 1,
                1, 2, 3, 4, 5, 2, 5, 5, 1, 1, 2, 3, 4, 5, 2, 5, 5, 1,
                1, 2, 3, 4, 5, 2, 5, 5, 1, 1, 2, 3, 4, 5, 2, 5,
                1, 2, 3, 4, 5, 2, 5, 5, 1, 1, 2, 3, 4, 5, 2, 5, 5, 1,
                1, 2, 3, 4, 5, 2, 5, 5, 1, 1, 2, 3, 4, 5, 2, 5, 5, 1,
                1, 2, 3, 4, 5, 2, 5, 5, 1, 1, 2, 3, 4, 5, 2, 5, 5, 1,
                1, 2, 3, 4, 5, 2, 5, 5, 1, 1, 2, 3, 4, 5, 2, 5, 5, 1,
                1, 2, 3, 4, 5, 2, 5, 5, 1, 1, 2, 3, 4, 5, 2, 5,
        };
        var sampleLength = data.length;

        Loader.load(org.bytedeco.fftw.global.fftw3.class);
        var result = new DoublePointer(sampleLength);
        var signal = new DoublePointer(sampleLength);
        signal.put(data);

        var plan = fftw_plan_dft_1d(sampleLength, signal, result, FFTW_FORWARD, (int) FFTW_ESTIMATE);
        fftw_execute(plan);
        fftw_destroy_plan(plan);
    }
```

**Comment by saudet** [comment]
Since you're not referencing either `result` or `signal` after `fftw_plan_dft_1d()`, they might get garbage collected before calling `fftw_execute()`. Make sure that doesn't happen.

**Comment by tobq** [comment]
I tried 

```Java
        ...
        fftw_destroy_plan(plan);
        var x = signal;
        var y = result;
```

Surely this is an issue with the API?

**Comment by tobq** [comment]
This doesn't seem to be a garbage collection issue. And there's no real logging to help with debug - very frustrating.

**Comment by saudet** [comment]
> This doesn't seem to be a garbage collection issue. And there's no real logging to help with debugging - very frustrating.

That's why documentation exists! It looks like `malloc()` from MSVC doesn't align memory well enough, it works fine with `fftw_malloc()`, I've tried it:

> The example code first allocates the input and output arrays. You can allocate them in any way that you like, but we recommend using fftw_malloc, which behaves like malloc except that it properly aligns the array when SIMD instructions (such as SSE and Altivec) are available (see [SIMD alignment and fftw_malloc](http://www.fftw.org/fftw3_doc/SIMD-alignment-and-fftw_005fmalloc.html#SIMD-alignment-and-fftw_005fmalloc)).

http://www.fftw.org/fftw3_doc/Complex-One_002dDimensional-DFTs.html

**Comment by tobq** [comment]
This problem persists, even when using fftw_malloc. I think maybe you should test this.

**Comment by saudet** [comment]
It looks like you are calling the function incorrectly. Did you try this?
```
fftw_plan_dft_1d(sampleLength / 2, signal, result, FFTW_FORWARD, (int) FFTW_MEASURE);
```

**Comment by tobq** [comment]
dividing the length by two ends in the same error...

**Comment by saudet** [comment]
Well, it works for me. There's probably something else that you're not doing correctly. Read the docs:
http://www.fftw.org/fftw3_doc/Complex-One_002dDimensional-DFTs.html

**Comment by saudet** [comment]
There's also good advice here:
http://www.fftw.org/faq/section3.html#segfault
Make sure the tests don't crash on your machine.
If they do, that's a problem with your hardware.

**Comment by tobq** [comment]
Thanks again

**Comment by tobq** [comment]
I've gotten this working, however it seems the use of fftw_malloc/fftw_free always results in a C++ error. Even when testing with [Example.java](https://github.com/bytedeco/javacpp-presets/tree/master/fftw#the-examplejava-source-file)

**Comment by saudet** [comment]
If you're talking about this code:
```java
var signalPointer = fftw_malloc(sampleLength);
var resultPointer = fftw_malloc(sampleLength);
```
Yeah, that's not going to work. You'll need to do something like this:
```java
var signalPointer = fftw_malloc(8 * sampleLength);
var resultPointer = fftw_malloc(8 * sampleLength);
```
