### ISSUE TITLE
Bug in processing bash script on windows

### ISSUE THREAD

**Issue by eix128** [bytedeco/javacpp-presets#895]

**Comment by saudet** [comment]
> D:\repo\javacpp-presets>bash cppbuild.sh -platform windows-x86_64 install llvm
> : invalid optione 3: set: -
> set: usage: set [-abefhkmnptuvxBCHP] [-o option-name] [--] [arg ...]
> cppbuild.sh: line 4: $'\r': command not found
> cppbuild.sh: line 11: $'\r': command not found
> cppbuild.sh: line 14: syntax error near unexpected token $'in\r'' 'ppbuild.sh: line 14: case $KERNEL in
> 
> I fixed it by using
> dos2unix javacpp.sh
> cd llvm
> dos2unix javacpp.sh
> 
> It should work without dos2unix

The script is already in Unix format and it runs just fine:
https://ci.appveyor.com/project/Bytedeco/javacpp-presets/builds/33500552/job/2n4fkcgy22qtv24t
