### ISSUE TITLE
It is possible not to use TESSDATA_PREFIX?

### ISSUE THREAD

**Issue by knowdbtech** [bytedeco/javacpp-presets#897]
It is possible not to use TESSDATA_PREFIX and embed it into jar?

In some environments with container, some times is not permitted to copy files to server. If I could to embed the tessdata into jar and tell to init where to find the tessdata or automatically the app look in the resources directory would perfect to run in a container.

**Comment by saudet** [comment]
Yes, that's what the argument to [`TessBaseApi.Init()`](http://bytedeco.org/javacpp-presets/tesseract/apidocs/org/bytedeco/tesseract/TessBaseAPI.html#Init-org.bytedeco.javacpp.BytePointer-org.bytedeco.javacpp.BytePointer-) is for.
