### ISSUE TITLE
presets for libgcc or libllvm?

### ISSUE THREAD

**Issue by zcaudate** [bytedeco/javacpp-presets#899]
I'd like to be able to package either one of these compilers into a javacpp preset. What's the best place to start?

**Comment by saudet** [comment]
LLVM is already available:
https://github.com/bytedeco/javacpp-presets/tree/master/llvm

**Comment by saudet** [comment]
If you'd like to work on something more, please start here:
https://github.com/bytedeco/helloworld
https://github.com/bytedeco/javacpp/wiki/Mapping-Recipes
https://github.com/bytedeco/javacpp-presets/wiki/Create-New-Presets
