### ISSUE TITLE
libpostal doesn't build on the latest version of MSYS2

### ISSUE THREAD

**Issue by kyrill007** [bytedeco/javacpp-presets#903]
It looks like **libpostal** refuses to gcc compile on the latest version (2020062) of MSYS - here is the error that I am getting:

C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build_trans_table-string_utils.o:C:\idexx\FOSS\javacpp-presets\libpostal\cppbuild\windows-x86_64\libpostal-1.1-alpha\src/klib/drand48.h:32: multiple definition of `_rand48_seed'; build_trans_table-transliteration_table_builder.o:C:\idexx\FOSS\javacpp-presets\libpostal\cppbuild\windows-x86_64\libpostal-1.1-alpha\src/klib/drand48.h:32: first defined here
collect2.exe: error: ld returned 1 exit status
make[2]: *** [Makefile:1078: build_trans_table.exe] Error 1

This error is present when I try to build libpostal _directly_ too (not through javacpp-presets). An experienced C developer, I think, should be able to resolve this issue rather quickly. Thank you, guys, in advance. You should be able to reproduce this error immediately if you install msys2-x86_64-20200629.exe.

**Comment by saudet** [comment]
Please report upstream!

If you don't need to use the latest version of mingw-w64 though, downgrade to a known good version and it will work:
https://github.com/bytedeco/javacpp-presets/blob/master/ci/install-windows.sh#L156

**Comment by kyrill007** [comment]
Eh... msys (regardless of its version) will pull the latest versions of dependencies. It is most certainly some kind of dependency problem, possibly, in how 32-bit and 64-bit gcc interaction is handled. It is not even clear to me where to report... To msys team? They will say to go libpostal. I've already reported it to libpostal, but they don't seem to care much about windows support. I've been very impressed with what you've done with your build scripts, so I thought, maybe, it will be easy for the bytedeco team to figure out (it should be a simple problem).

**Comment by saudet** [comment]
BTW, why do you need to build from source? If there is anything that you need fixed, just send a pull request here, and you'll be able to get new binaries from the CI servers automatically without breaking a sweat.

**Comment by lumen00000** [comment]
For a successful build, you need to remove "multiple definitions".
Comment out these lines in the `src/klib/drand48.h` file:
```
     // unsigned short _rand48_seed [3];
     // unsigned short _rand48_mult [3];
     // unsigned short _rand48_add;
```
Then run again

**Comment by saudet** [comment]
Thanks @lumen00000! I've applied this change in commit https://github.com/bytedeco/javacpp-presets/commit/1d22113736d75791dd447ca7dcff7fdb253f43e4.
