### ISSUE TITLE
ffmpeg-platform not updated in mvnrepository

### ISSUE THREAD

**Issue by nanguantong** [bytedeco/javacpp-presets#904]
Now the newest version is 4.2.2-1.5.3 in https://mvnrepository.com/artifact/org.bytedeco/ffmpeg-platform
But the ffmpeg that I need use has some bugs fixed in 4.3.1, so can you please update it ?

**Comment by nanguantong** [comment]
And

Could not find javacpp-android-arm.jar (org.bytedeco:javacpp:1.5.4-SNAPSHOT:20200712.064611-457).
Searched in the following locations:
    https://oss.sonatype.org/content/repositories/public/org/bytedeco/javacpp/1.5.4-SNAPSHOT/javacpp-1.5.4-20200712.064611-457-android-arm.jar

**Comment by saudet** [comment]
You'll need to wait a couple of days to be able to consume the snapshots
directly with Gradle like that. If you can't wait, please use Mave as
explained here: http://bytedeco.org/builds/

**Comment by nanguantong** [comment]
Yes，I just used the steps in http://bytedeco.org/builds/

in gradle:

repositories {
    maven { url 'https://oss.sonatype.org/content/repositories/snapshots' }
}

compile group: 'org.bytedeco', name: 'javacpp', version: '1.5.4-SNAPSHOT'
compile group: 'org.bytedeco', name: 'ffmpeg-platform', version: '4.3-1.5.4-SNAPSHOT'


but errors as following: 
      `Could not find javacpp-android-arm.jar (org.bytedeco:javacpp:1.5.4-SNAPSHOT:20200712.064611-457).`

**Comment by saudet** [comment]
No, that's no the right way, read http://bytedeco.org/builds/#other-options

**Comment by nanguantong** [comment]
Ok， I'll try it，thanks

**Comment by nanguantong** [comment]
In addition, when will the new version 1.5.4  be released?

**Comment by saudet** [comment]
Ok, the snapshots have finally been fixed. You can use Gradle as usual to try them out! Thanks

> In addition, when will the new version 1.5.4 be released?

Sometime before the end of year. It depends on how much help I get. :)
