### ISSUE TITLE
writing my presets,how to write my InfoMap?

### ISSUE THREAD

**Issue by wpzybyq** [bytedeco/javacpp-presets#905]
my .h file like this:class ClassA: public std::unordered_multimap<std::string,ClassB *, StructA, StructB>,how to write my InfoMap?
i add Info Like this: infoMap.put(new Info("std::unordered_multimap<std::string,ClassB *, StructA, StructB>").pointerTypes("String").define());,but get error info:std::unordered_multimapstd::string,ClassB*,StructA,StructB.java:[18,127] expected

**Comment by saudet** [comment]
Please start by reading this page: https://github.com/bytedeco/javacpp/wiki/Mapping-Recipes

**Comment by wpzybyq** [comment]
> Please start by reading this page: https://github.com/bytedeco/javacpp/wiki/Mapping-Recipes

yes,i hava saw this page.
as the below shotcut:
![image](https://user-images.githubusercontent.com/49703486/87306354-789c9180-c54a-11ea-9f31-b6eb4e2b38b1.png)
as i know,this page tell us how to map variable or method from c++ to java;
but my case is different,it is a class extends c++ containers, i don't know how to write my java configuration file.
please tell me how to do  it.thanks!

**Comment by saudet** [comment]
Try this:
https://github.com/bytedeco/javacpp/wiki/Mapping-Recipes#defining-wrappers-for-basic-c-containers

**Comment by wpzybyq** [comment]
@saudet 
yes,i have tried it.

infoMap.put(new Info("basic/containers").cppTypes("std::array", "std::bitset", "std::deque", "std::list", "std::map", "std::queue", "std::set", "std::stack", "std::vector", "std::valarray", "std::pair", "std::forward_list""std::priority_queue","std::unordered_map","std::unordered_multimap", "std::unordered_set"));

infoMap.put(new Info("std::unordered_multimap<std::string,ClassB *, StructA, StructB>").pointerTypes("StringClassBStructAStructB").define());

as i know,std::unordered_multimap<std::string,ClassB *, StructA, StructB> need to be mapped to StringClassBStructAStructB,
but get error as below:
[ERROR] std::unordered_multimap<std::string,ClassB *, StructA, StructB>.java:[12,17] '{' expected

below is my .h file info :
class ClassA: public std::unordered_multimap<std::string,ClassB *, StructA, StructB>

**Comment by wpzybyq** [comment]
What confuses me is，according to my configuration file,std::unordered_multimap<std::string,ClassB *, StructA, StructB> need to be mapped to StringClassBStructAStruct,i should get a java file named StringClassBStructAStructB.java,not std::unordered_multimap<std::string,ClassB *, StructA, StructB>.java

**Comment by saudet** [comment]
You'll need to remove spaces in the template parameters. The parser isn't too robust in that sense:
https://github.com/bytedeco/javacpp/wiki/Mapping-Recipes#creating-instances-of-c-templates

**Comment by wpzybyq** [comment]
i have removed whitespaces  between template arguments as below:
infoMap.put(new Info("std::unordered_multimap<std::string,ClassB*,StructA,StructB>").pointerTypes("StringClassBStructAStructB").define());

but also get error as below:
[ERROR] std::unordered_multimap<std::string,ClassB*,StructA,StructB>.java:[12,17] '{' expected.

**Comment by saudet** [comment]
You'll need to put the template parameters inside `< ... >`

**Comment by wpzybyq** [comment]
@saudet 
sorry,i just omitted the '<'.

in fact,i have removed whitespaces between template arguments as below:
infoMap.put(new Info("std::unordered_multimap<std::string,VariableValue *,MyHash,MyEqual>").pointerTypes("StringVariHashEqual").define());

and get error as below:
[ERROR] std::unordered_multimap<std::string,ClassB*,StructA,StructB>.java:[12,17] '{' expected.

also generate the std::unordered_multimap<std::string,ClassB*,StructA,StructB>.java file.

**Comment by saudet** [comment]
Well, you probably made a typo somewhere. It works with std::map right? If
you want me to debug your code, you'll need to give it to me...

**Comment by wpzybyq** [comment]
it also works with std::unordered_multimap in case of mapping variable.
if i want you to help me debug my code,i need to give you java configuration file,are there other files needed?

**Comment by saudet** [comment]
A simple header file that should work but doesn't work is probably the only thing I need to check this. Thanks

**Comment by wpzybyq** [comment]
@saudet 
[header_file.zip](https://github.com/bytedeco/javacpp-presets/files/4916963/header_file.zip)
line 71,72

**Comment by saudet** [comment]
Well, `VariableValue` isn't defined, but if I give it a C++ class like this:
```cpp
class VariableValue {
};
```
This this works just fine:
```java
infoMap.put(new Info("basic/containers").cppTypes("std::unordered_multimap"));
infoMap.put(new Info("std::unordered_multimap<std::string,modsecurity::VariableValue*,modsecurity::MyHash,modsecurity::MyEqual>").pointerTypes("MyMap").define());
```

**Comment by wpzybyq** [comment]
@saudet 
wow,it's ok!thank you very much!
