### ISSUE TITLE
OpenCV is not loading in new veriosn 

### ISSUE THREAD

**Issue by AKMANSoft** [bytedeco/javacpp-presets#909]
Im getting this error, im using windows, using OpenJDK version 11

Exception in thread "main" java.lang.UnsatisfiedLinkError: 'int org.bytedeco.openblas.global.openblas_nolapack.OPENBLAS_OS_LINUX()'
	at org.bytedeco.openblas.global.openblas_nolapack.OPENBLAS_OS_LINUX(Native Method)
	at org.bytedeco.openblas.global.openblas_nolapack.<clinit>(openblas_nolapack.java:19)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:398)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1190)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1139)
	at com.mi6.opencv.Main.main(Main.java:19)

<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>com.mi6</groupId>
		<artifactId>compare-parent</artifactId>
		<version>0.0.1-SNAPSHOT</version>
	</parent>

	<artifactId>compare</artifactId>
	<packaging>jar</packaging>

	<name>compare</name>
	<url>http://maven.apache.org</url>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<javacpp.version>1.5.4-SNAPSHOT</javacpp.version>
	</properties>

	<dependencies>
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>3.8.1</version>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>org.bytedeco</groupId>
			<artifactId>javacv</artifactId>
			<version>1.5.4-SNAPSHOT</version>
		</dependency>
		
		<dependency>
			<groupId>org.bytedeco</groupId>
			<artifactId>ffmpeg</artifactId>
			<version>4.3-${javacpp.version}</version>
			<classifier>windows-x86_64</classifier>
		</dependency>

		
		<dependency>
			<groupId>org.bytedeco</groupId>
			<artifactId>javacpp</artifactId>
			<version>${javacpp.version}</version>
			<classifier>windows-x86_64</classifier>
		</dependency>
		
		
		<dependency>
			<groupId>org.bytedeco</groupId>
			<artifactId>opencv</artifactId>
			<version>4.3.0-${javacpp.version}</version>
			<classifier>windows-x86_64</classifier>
		</dependency>

		
		<dependency>
			<groupId>org.bytedeco</groupId>
			<artifactId>openblas</artifactId>
			<version>0.3.9-${javacpp.version}</version>
			<classifier>windows-x86_64</classifier>
		</dependency>
		
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-api</artifactId>
			<version>1.7.30</version>
		</dependency>

		<dependency>
			<groupId>ch.qos.logback</groupId>
			<artifactId>logback-classic</artifactId>
			<version>1.2.3</version>
		</dependency>

	</dependencies>

	<repositories>
		<repository>
			<id>sonatype-nexus-snapshots</id>
			<url>https://oss.sonatype.org/content/repositories/snapshots</url>
		</repository>
	</repositories>
</project>

**Comment by saudet** [comment]
Please use `javacv-platform` as shown here: http://bytedeco.org/builds/

**Comment by saudet** [comment]
Actually, you're right. There was a bug in the latest update to 0.3.10. It's been fixed in commit https://github.com/bytedeco/javacpp-presets/commit/dedf9005a77526a98d922175f6bd09f47e2f7d6e. Thanks for reporting!

**Comment by AKMANSoft** [comment]
Just to mention in previous versions if I didn’t add the platform dependency and add classifier only in the main jar Pom it automatically download the platform jar, e.g

**Comment by saudet** [comment]
Nope, it still works the same: https://github.com/bytedeco/javacpp-presets/wiki/Reducing-the-Number-of-Dependencies
