### ISSUE TITLE
Qt-platform 5.15.0-1.5.4-SNAPSHOT is not published

### ISSUE THREAD

**Issue by DenisNovac** [bytedeco/javacpp-presets#910]
Hi everyone. I can't load 5.15.0-1.5.4-SNAPSHOT version of qt-platform (which is shown in tutorial https://github.com/bytedeco/javacpp-presets/tree/master/qt#the-pomxml-build-file)

 It seems that it wasn't published: https://mvnrepository.com/artifact/org.bytedeco/qt-platform

**Comment by saudet** [comment]
It's on the snapshot repository: http://bytedeco.org/builds/
