### ISSUE TITLE
header file dosn't have no-args constructor,cpp file compile error

### ISSUE THREAD

**Issue by wpzybyq** [bytedeco/javacpp-presets#914]
as header file dosn't have no-args constructor.
at the same time,generated java file need to have no-args constructor.
so cpp file compile error:error: no matching function for call to 
namespace::Class* rptr = new namespace::Class();

how can i fix it?thanks

**Comment by wpzybyq** [comment]
another question:
header file has variable define as below:
std::ostringstream m_requestBody;

but cpp file has compile error:
error: use of deleted function ‘std::__cxx11::basic_ostringstream<_CharT, _Traits, _Alloc>& std::__cxx11::basic_ostringstream<_CharT, _Traits, _Alloc>::operator=(const std::__cxx11::basic_ostringstream<_CharT, _Traits, _Alloc>&) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>]’

how can i fix it?thanks

**Comment by saudet** [comment]
If this is an abstract type, use Info.purify:
https://github.com/bytedeco/javacpp/wiki/Mapping-Recipes#dealing-with-abstract-classes-and-virtual-methods

**Comment by saudet** [comment]
As for deleted functions, use Info.skip or something else with Info.javaText:
https://github.com/bytedeco/javacpp/wiki/Mapping-Recipes#mapping-a-declaration-to-custom-code

**Comment by wpzybyq** [comment]
> If this is an abstract type, use Info.purify:
> https://github.com/bytedeco/javacpp/wiki/Mapping-Recipes#dealing-with-abstract-classes-and-virtual-methods

no,that's not an abstract type.
`VariableValue(const std::string *key,
        const std::string *value = nullptr)
        : m_key(*key),
        m_keyWithCollection(*key),
        m_collection(""),
        m_value(value != nullptr?*value:"")
    { }

    VariableValue(const std::string *collection,
        const std::string *key,
        const std::string *value)
        : m_key(*key),
        m_keyWithCollection(*collection + ":" + *key),
        m_collection(*collection),
        m_value(*value)
    { }

    explicit VariableValue(const VariableValue *o) :
        m_key(o->m_key),
        m_value(o->m_value),
        m_collection(o->m_collection),
        m_keyWithCollection(o->m_keyWithCollection)
    {
        for (auto &i : o->m_orign) {
            std::unique_ptr<VariableOrigin> origin(new VariableOrigin());
            origin->m_offset = i->m_offset;
            origin->m_length = i->m_length;
            m_orign.push_back(std::move(origin));
        }
    }`

the class just dosn't have no-args constructor,those classes have no-args constructor are ok.
so i guess no-args constructor in generated java class can not find matching function from c++ class.is it right?

**Comment by wpzybyq** [comment]
> As for deleted functions, use Info.skip or something else with Info.javaText:
> https://github.com/bytedeco/javacpp/wiki/Mapping-Recipes#mapping-a-declaration-to-custom-code
thanks.when i use Info.skip,it's ok.
if iwant to use Info.javaText,this member variable type is "std::ostringstream",how to write my Info.javaText?

**Comment by saudet** [comment]
Where is it trying to use the default constructor?

**Comment by wpzybyq** [comment]
> Where is it trying to use the default constructor?

just use infoMap.put(new Info("namespace::Class").purify(true)); can solve this error,thanks.

**Comment by saudet** [comment]
That disables all constructors though. You won't be able to create an instance of that class from Java.
