### ISSUE TITLE
does it support libjpeg-turbo to decode jpeg/jpg in opencv?

### ISSUE THREAD

**Issue by ericxsun** [bytedeco/javacpp-presets#916]
The opencv supports libjpeg-turbo to speedup decode image(jpeg) since opencv-3.4+ [support MR](https://github.com/opencv/opencv/pull/11497). And I've double checked opencv-4.3.0 also support it.

```py
>>> import cv2
>>> cv2.getBuildInformation()
'\nGeneral configuration for OpenCV 4.3.0 ....

>>> import re
>>> re.findall('.*jpeg.*', cv2.getBuildInformation())
['    3rdparty dependencies:       ittnotify libprotobuf zlib libjpeg-turbo libwebp libpng libtiff IlmImf quirc ippiw ippicv',
 '    JPEG:                        build-libjpeg-turbo (ver 2.0.4-62)']
```

So, I'm wondering, does it supported in javacpp-presets? And how to enable it?

Thanks a lot.

Addition:

version:
- javacpp: 1.5.3
- opencv: 4.3.0-1.5.3

When loading jpg with the following snippet, `imdecode` costs me much time, for large image especially

```scala
val bytes: Array[Byte] = .... // 

val mat = new Mat(bytes: _*)
val res = opencv_imgcodecs.imdecode(mat, opencv_imgcodecs.IMREAD_UNCHANGED)
```

**Comment by saudet** [comment]
That's what OpenCV uses by default, yes. You can confirm with getBuildInformation().

**Comment by ericxsun** [comment]
> That's what OpenCV uses by default, yes. You can confirm with getBuildInformation().

Yes, I got it. Thanks anymore.

```scala
JPEG:                        build-libjpeg-turbo (ver 2.0.4-62)
```
