### ISSUE TITLE
javacpp-preset - ffmpeg - "avcodec_open2() error -22: Could not open video codec" when loading VP8 (libvpx) codec

### ISSUE THREAD

**Issue by dandamian83** [bytedeco/javacpp-presets#92]
Steps to reproduce the Exception:
1) Cloned javacpp-presets 
$git clone https://github.com/bytedeco/javacpp.git
2)  Change directory cu javacpp-presets
$cd javacpp-presets
3) Built ffmpeg with libvpx support
$bash cppbuild.sh -platform android-arm install ffmpeg
4) Create the ffmpeg jars for Android
$mvn install -Pandroid-arm -Dplatform.root=$ANDROID_NDK --projects ffmpeg
5) Built opencv
$bash cppbuild.sh -platform android-arm install opencv
6) Create opencv jars for Android 
$mvn install -Pandroid-arm -Dplatform.root=$ANDROID_NDK --projects opencv
7) Cloned javacpp 
$git clone https://github.com/bytedeco/javacpp.git
7) Create javacpp.jar for Android
$mvn install -Pandroid-arm -Dplatform.root=$ANDROID_NDK
8) Added the jars: ffmpeg.jar, ffmpeg-android-arm.jar, opencv.jar, opencv-android-arm.jar, javacpp.jar and javacv.jar to my Android project.
9) After invoking the following lines of code
```java
mFFmpegRecorder = new FFmpegFrameRecorder(Constants.VIDEOS_FOLDER_PATH + --File.separator + mVideoFile, Constants.VIDEO_WIDTH, Constants.VIDEO_HEIGHT, 1);
mFFmpegRecorder.setVideoCodec(avcodec.AV_CODEC_ID_VP8);
[...]
try {
    mFFmpegRecorder.start();
} catch (FFmpegFrameRecorder.Exception e) {
    e.printStackTrace();
}
```

I get:
```
org.bytedeco.javacv.FrameRecorder$Exception: avcodec_open2() error -22: Could not open video codec.
```

Even though I've built ffmepg with the default configuration which includes libvpx support.

**Comment by saudet** [comment]
I've taken some time to hack FFmpeg's log functions and redirect them to Java (or Android's log). There's a new `FFmpegLogCallback` class in JavaCV. Call the static `set()` method somewhere during init and let me know what shows up in the log. Thanks!

**Comment by dandamian83** [comment]
Can you be more specific (than you are here
<https://github.com/bytedeco/javacv#build-instructions>) about how could I
build javacv from source?
Now, even though I've run mvn install in javacpp and javacpp-presets
folders I still get:

Downloaded:
https://repo.maven.apache.org/maven2/com/google/android/android/4.1.1.4/android-4.1.1.4.jar
(12645 KB at 585.3 KB/sec)
[INFO]
------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO]
------------------------------------------------------------------------
[INFO] Total time: 24.925 s
[INFO] Finished at: 2015-10-12T22:42:36+03:00
[INFO] Final Memory: 16M/173M
[INFO]
------------------------------------------------------------------------
[ERROR] Failed to execute goal on project javacv: Could not resolve
dependencies for project org.bytedeco:javacv:jar:1.1-SNAPSHOT: The
following artifacts could not be resolved:
org.bytedeco.javacpp-presets:flycapture:jar:2.7.3.19-1.1-SNAPSHOT,
org.bytedeco.javacpp-presets:libdc1394:jar:2.2.3-1.1-SNAPSHOT,
org.bytedeco.javacpp-presets:libfreenect:jar:0.5.2-1.1-SNAPSHOT,
org.bytedeco.javacpp-presets:videoinput:jar:0.200-1.1-SNAPSHOT,
org.bytedeco.javacpp-presets:artoolkitplus:jar:2.3.1-1.1-SNAPSHOT,
org.bytedeco.javacpp-presets:flandmark:jar:1.07-1.1-SNAPSHOT: Could not
find artifact
org.bytedeco.javacpp-presets:flycapture:jar:2.7.3.19-1.1-SNAPSHOT -> [Help
1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e
switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions,
please read the following articles:
[ERROR] [Help 1]
http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException


Should I build each preset by going into his folder and running it's
cppbuild scripts and after mvn install for android ?

After I build javacv I can proceed with the tests.

Thanks,

Dan

**Comment by saudet** [comment]
Run cppbuild.sh for the presets you are interested in, yes.

**Comment by saudet** [comment]
I've just added a new wiki page that should help you with that:
https://github.com/bytedeco/javacpp-presets/wiki/Build-Environments

**Comment by dandamian83** [comment]
Hello Samuel,

My problem wasn't about building javacpp-presets but more about building
javacv.
Anyway I commented out the decencies that were of no need to me like
(flycapture, libdc1394, libfreenect, videoinput, artoolkitplus and
flandmark), and then I got success building javacv.

But to my surprisez FFmpegLogCallback.class wasnt in the jar. After looking
more into it I noticed that the class didn't find it's parent LogCallback.

Thanks,

Dan

**Comment by saudet** [comment]
Yes, that's a new class in javacpp-presets. That's why I refered you to the
wiki to help you rebuild that...

**Comment by saudet** [comment]
Please try again with version 1.1, thanks!

**Comment by dandamian83** [comment]
Hello Samuel,

Long time no see! :)
I've just tried with javacv 1.1 and it works! At least I don't have the
codec not found error. Thanks!
Anyway, after downloading  javacv-1.1-bin.zip
<http://search.maven.org/remotecontent?filepath=org/bytedeco/javacv/1.1/javacv-1.1-bin.zip>,
I couldn't find ffmpeg-android-arm.jar in the distribution so I've compiled
it myself.

I've done the following:
1) Cloned javacpp because
git clone https://github.com/bytedeco/javacpp.git
2) build it
mvn install
3) cloned javacpp-presets
git clone https://github.com/bytedeco/javacpp-presets.git
4) compiled ffmpeg  (my $ANDROID_NDK is already defined)
...javacpp-presets: bash cppbuild.sh -platform android-arm install ffmpeg
5) build ffmpeg
mvn install -Pandroid-arm -Dplatform.root=$ANDROID_NDK --projects ffmpeg

at step 5 I think your documentation (
https://github.com/bytedeco/javacpp-presets) it's not too acurate, as you
are saying to run

$ mvn install --projects
.,opencv,ffmpeg,flycapture,libdc1394,libfreenect,videoinput,artoolkitplus,etc.


but the ideea is that you get some exceptions if you run simple
mvn install --projects ffmpeg or
mvn install --project ., ffmpeg

[ERROR] Failed to execute goal org.bytedeco:javacpp:1.2-SNAPSHOT:build
(generate-sources) on project ffmpeg: Failed to execute JavaCPP Builder:
Could not parse "libavutil/avutil.h": File does not exist -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e
switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions,
please read the following articles:
[ERROR] [Help 1]
http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException


Anyway, running
$ mvn install -Pandroid-arm -Dplatform.root=$ANDROID_NDK --projects ffmpeg
everything goes fine.

Hope this helps.

All the best,

Dan

**Comment by saudet** [comment]
The artifact for `android-arm` *is* in `javacv-1.1-bin.zip` though:
```
10562971  Defl:N 10517831   0% 10-25-2015 17:12 3ddce267  javacv-bin/ffmpeg-android-arm.jar
```
As mentioned in the README.md file, there's more platform-specific instructions here:
https://github.com/bytedeco/javacpp-presets/wiki/Build-Environments

Anyway, good to hear it's fixed! Thanks for testing

**Comment by dan-damian** [comment]
I guess I wasn't paying attention to what codec I had specified, but the error is still showing when I choose ```avcodec.AV_CODEC_ID_VP8```:

```W/System.err﹕ org.bytedeco.javacv.FrameRecorder$Exception: avcodec_open2() error -22: Could not open video codec.
W/System.err﹕ at org.bytedeco.javacv.FFmpegFrameRecorder.startUnsafe(FFmpegFrameRecorder.java:529)
W/System.err﹕ at org.bytedeco.javacv.FFmpegFrameRecorder.start(FFmpegFrameRecorder.java:288)```

I'm using: ffmpeg-android-arm.jar, javacpp.jar, opencv-android-arm.jar, ffmpeg.jar, javacv.jar, opencv.jar, all extracted from javacv-1.1-bin.zip and running everything on Android 5.1.1.

**Comment by saudet** [comment]
Could you check what you get in the log if you call `FFmpegLogCallback.set()` during init? Thanks!

**Comment by dan-damian** [comment]
I've added ```FFmpegLogCallback.set()``` and  bellow what the function added to my logs:
```11-30 12:13:46.045  13600-13681/myapp.xyz.myappvr I/System.out﹕ Output #0, mp4, to '/storage/emulated/0/DCIM/myapp/20151130_1213_92.mpeg':
11-30 12:13:46.052  13600-13681/myapp.xyz.myappvr I/System.out﹕ Stream #0:0
11-30 12:13:46.052  13600-13681/myapp.xyz.myappvr I/System.out﹕ : Video: vp8 (libvpx), yuv420p, 480x480, q=-1--1, 1196 kb/s
11-30 12:13:46.052  13600-13681/myapp.xyz.myappvr I/System.out﹕ ,
11-30 12:13:46.055  13600-13681/myapp.xyz.myappvr I/System.out﹕ 30 tbn,
11-30 12:13:46.055  13600-13681/myapp.xyz.myappvr I/System.out﹕ 30 tbc
11-30 12:13:46.055  13600-13681/myapp.xyz.myappvr I/System.out﹕ [ 11-30 12:13:46.057 13600:13681 I/System.out ]
    Stream #0:1
11-30 12:13:46.059  13600-13681/myapp.xyz.myappvr I/System.out﹕ : Audio: aac, 44100 Hz, mono, fltp, 64 kb/s
11-30 12:13:46.061  13600-13681/myapp.xyz.myappvr I/System.out﹕ [ 11-30 12:13:46.101 13600:13610 W/art      ]
    Suspending all threads took: 17.444ms
11-30 12:13:46.125  13600-13681/myapp.xyz.myappvr I/System.out﹕ [libvpx @ 0xaec46400] v1.4.0
11-30 12:13:46.161  13600-13681/myapp.xyz.myappvr W/System.err﹕ Error: [libvpx @ 0xaec46400] Failed to initialize encoder: Invalid parameter
11-30 12:13:46.168  13600-13681/myapp.xyz.myappvr W/System.err﹕ Error: [libvpx @ 0xaec46400]   Additional information: g_lag_in_frames out of range [..0]
11-30 12:13:46.200  13600-13681/myapp.xyz.myappvr W/System.err﹕ org.bytedeco.javacv.FrameRecorder$Exception: avcodec_open2() error -22: Could not open video codec.
11-30 12:13:46.200  13600-13681/myapp.xyz.myappvr W/System.err﹕ at org.bytedeco.javacv.FFmpegFrameRecorder.startUnsafe(FFmpegFrameRecorder.java:529)```

**Comment by saudet** [comment]
It sounds like a bug in FFmpeg or libvpx. Could you report that upstream? Thanks!
