### ISSUE TITLE
Introduction of IntVector in OpenCV causes backward incompatible change

### ISSUE THREAD

**Issue by frankier** [bytedeco/javacpp-presets#921]
The recent upgrade of OpenCV included a change to the mapping code for opencv_videoio which mapped std::vector<int> to a pointer subclass IntVector. See: https://github.com/bytedeco/javacpp-presets/blame/17a1f75ee9587151b40f58066bfad74561c5313d/opencv/src/main/java/org/bytedeco/opencv/presets/opencv_videoio.java#L54

This has caused a change in the OpenPose preset. Now get() on OpenPose.FloatArray requires an opencv_videoio.IntVector argument, whereas previously the StdVector overloading magic allowed passing a simple java int array which was previously the most convenient way of getting result data out from OpenPose. Here is a diff after rerunning the generation:

```
-        public native @ByRef @Name("operator []") FloatPointer get(@StdVector IntPointer indexes);
-        public native @ByRef @Name("operator []") FloatBuffer get(@StdVector IntBuffer indexes);
-        public native @ByRef @Name("operator []") float[] get(@StdVector int[] indexes);
+        public native @ByRef @Name("operator []") FloatPointer get(@Const @ByRef IntVector indexes);
```

I'm not sure what I can do about this. Can the mapping of IntVector in opencv_video be removed, or is it still needed? Is there some way I can avoid my mapping code seeing IntVector? Can I avoid including it? I have tried unmapping it in the OpenPose mapping code like so:

```
.put(new Info("std::vector<int>").pointerTypes())
```

But that caused a compilation error (/ by zero?!). Any ideas? Is there anything I can do to "opt-in" to certain mappings from dependencies to isolate against these types of changes in the future?

**Comment by saudet** [comment]
OpenCV often includes breaking changes, that's not unusable.
If you find a way to hack this a bit better though, contributions are welcome!

**Comment by frankier** [comment]
Ok. In that case I will probably just work around it by changing my code to make an opencv_videoio.IntVector since I'm really not sure how else I can work around this. I suppose the example code in the Openpose preset is broken now too. It feels to me like mapping code should at least be able to blacklist or ignore or undo other mapping code, since in some sense the std::vector<int> in Openpose has nothing to do with the one in opencv_video.

**Comment by saudet** [comment]
Well, let me see if I can fix this... In any case, it shouldn't affect OpenPose either way.

**Comment by frankier** [comment]
The plot thickens...

If I download the current nightly: OpenCV's opencv.videoio no longer has IntVector(?!)

```
$ cd /path/to/extracted/nightly/org/bytedeco/opencv/opencv_videoio
$ ls
CvCapture.class                    IVideoWriter.class
CvCaptureDefaultDeleter.class      VideoCapture.class
CvVideoWriter.class                VideoCapturePrivateAccessor.class
CvVideoWriterDefaultDeleter.class  VideoWriter.class
IVideoCapture.class
```

Oddly the the OpenPose preset is still using it though. I guess maybe when it gets rebuild against the new OpenCV video_io it won't any more? Not sure why it's gone on the nightlies but not master though.

**Comment by saudet** [comment]
Ah, I see what's going on. This affects all modules inheriting from opencv_video.
I've figured out how to make do without `IntVector`, like it was before. Thanks for reporting!

> Oddly the the OpenPose preset is still using it though. I guess maybe when it gets rebuild against the new OpenCV video_io it won't any more? Not sure why it's gone on the nightlies but not master though.

Yes, you'll need to wait for all the builds. That's just me testing things (mostly) locally.

**Comment by frankier** [comment]
I just tried the nightly version again and oddly the FloatArray in OpenPose preset is still looking for IntVector

```
Warning: Loader.putMemberOffset(): java.lang.ClassNotFoundException: org.bytedeco.opencv.opencv_videoio.IntVector
Warning: Loader.putMemberOffset(): java.lang.ClassNotFoundException: org.bytedeco.opencv.opencv_videoio.IntVector
<--SNIP-->
Error loading class org/bytedeco/opencv/opencv_videoio/IntVector.
Exception in thread "pool-3-thread-2" java.lang.NoClassDefFoundError: org/bytedeco/opencv/opencv_videoio/IntVector
	at org.bytedeco.openpose.FloatArray.getSize(Native Method)
```

But I've cleared by Maven cache to make sure I'm using the latest version, then verified I really am using the latest version. Finally I have checked the openpose/FloatArray.class in the fat jar I'm executing and it has reverted to how it was before IntVector was added to OpenCV videoio i.e. it contains no reference to IntVector and is instead using the `@StdVector` overloads.

Any idea why it's still looking for IntVector?

**Comment by saudet** [comment]
You probably have some old JAR files in your cache, yes. Make sure to run Maven with `mvn -U ...`.

**Comment by saudet** [comment]
Looks like Maven on Travis CI didn't pick it up actually, so I've restarted the build:
https://travis-ci.org/github/bytedeco/javacpp-presets/jobs/715061978

**Comment by saudet** [comment]
`mvn -U clean compile exec:java -Djavacpp.platform.host` now work for me without warnings.
