### ISSUE TITLE
DNNL 1.6.1 non-snapshot release?

### ISSUE THREAD

**Issue by blueberry** [bytedeco/javacpp-presets#936]
Hi Samuel,

This is a similar issue as in #885. Basically, I'd like to release a library that depends on DNNL 1.6.1, but I can't because javacpp's maven depenedency is a SNAPSHOT, caused by slower release cycle of javacpp core.

Can you please release DNNL 1.6.1-1.5.3 in not so distant future?

**Comment by saudet** [comment]
Most likely sometime next month... Before that though, please make sure that the snapshots are working alright.

**Comment by blueberry** [comment]
So far, they work all right.

**Comment by saudet** [comment]
Version 1.5.4 has been released with DNNL 1.6.2. Thank you for waiting!
