### ISSUE TITLE
OpenCV + ffmpeg issue

### ISSUE THREAD

**Issue by doktor-ziel** [bytedeco/javacpp-presets#941]
Dear Community!
I've create simple java app to create time lapse movie. You can find my code [here](https://github.com/doktor-ziel/time-lapse-creator).

I'm getting the following error:
```
[ERROR:0] global C:\projects\javacpp-presets\opencv\cppbuild\windows-x86_64\opencv-4.3.0\modules\videoio\src\cap.cpp (527) cv::VideoWriter::open VIDEOIO(CV_IMAGES): raised OpenCV exception:

OpenCV(4.3.0) C:\projects\javacpp-presets\opencv\cppbuild\windows-x86_64\opencv-4.3.0\modules\videoio\src\cap_images.cpp:253: error: (-5:Bad argument) CAP_IMAGES: can't find starting number (in the name of file): src/main/resources/video.avi in function 'cv::icvExtractPattern'
```
I observed earlier that this behaviour is caused by lack of ffmpeg dll. 

When I downloaded opencv library there is `opencv_videoio_ffmpeg440_64.dll`. I don't see such a file while using your library. I tried with `ffmpeg-platform` library but it didn't solve my issue. Is there any way to solve such a problem?

Any help will be appreciated.

Best regards
Doktor Ziel

**Comment by saudet** [comment]
OpenCV isn't built against FFmpeg because it doesn't provide anything that we can't do with JavaCV anyway, and because it forces FFmpeg's licensing issues on OpenCV, which is a problem for users sensitive to that. Please let me know if you're not able to do what you need to do with JavaCV though.

**Comment by saudet** [comment]
For starters, please take a look at the Demo class here as an example using FFmpegFrameRecorder:
https://github.com/bytedeco/javacv/#sample-usage

**Comment by n-kai-cj** [comment]
This may help you if you can accept MJPG or mp4 format.

```java
    public static void main(String[] args) throws IOException {
        Loader.load(opencv_java.class);

        // produces error as reporter said
        //VideoWriter videoWriter = new VideoWriter("outputPath.avi", VideoWriter.fourcc('F', 'M', 'P', '4'), 4, new Size(1280, 720), true);

        // works well!
        //VideoWriter videoWriter = new VideoWriter("outputPath.mp4", VideoWriter.fourcc('F', 'M', 'P', '4'), 4, new Size(1280, 720), true);

        // output error but works well
        VideoWriter videoWriter = new VideoWriter("outputPath.avi", VideoWriter.fourcc('M', 'J', 'P', 'G'), 4, new Size(1280, 720), true);

        Files.list(Paths.get("picts"))
                .peek(System.out::println)
                .map(p -> Imgcodecs.imread(p.toAbsolutePath().toString()))
                .forEach(videoWriter::write);
        videoWriter.release();
    }
```

**Comment by doktor-ziel** [comment]
Thanks for help, using JavaCV solved the problem
