### ISSUE TITLE
Why OpenCV needs OpenBLAS ?

### ISSUE THREAD

**Issue by n-kai-cj** [bytedeco/javacpp-presets#943]
I have questions.
1. Why javacpp+opencv doesn't work without openblas?
2. Is there any way to work javacpp+opencv without openblas?

**Comment by saudet** [comment]
Duplicate of https://github.com/bytedeco/javacv/issues/1329

**Comment by n-kai-cj** [comment]
Ah I understand. Thank you and sorry for duplicate.

**Comment by saudet** [comment]
The reason is that operations such as GEMM used by many algorithms are a lot faster with OpenBLAS/MKL:
https://jamesbowley.co.uk/build-opencv-4-0-0-with-cuda-10-0-and-intel-mkl-tbb-in-windows/
