### ISSUE TITLE
create-new-preset tutorial: zlib compilation error after parser

### ISSUE THREAD

**Issue by codywh29** [bytedeco/javacpp-presets#953]
Hi,

I'm trying to build a zlib preset using the latest version of javacpp and javacpp-presets (1.5.5-SNAPSHOT).

I am following the example from the Create-New-Presets (https://github.com/bytedeco/javacpp-presets/wiki/Create-New-Presets). 
A minor change to the zlib.java file were made.
@Platform(include = "<zlib.h>", link = "z@.1#") -> @Platform(include = {"<zconf.h>", "<zlib.h>"}, link = "z@.1#"),
Configuration code for reference:

````
package org.bytedeco.zlib.presets;

import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;
import org.bytedeco.javacpp.tools.*;

@Properties(
        value = {
                @Platform(include = {"<zconf.h>", "<zlib.h>"}, link = "z@.1#"),
//                @Platform(include = "<zlib.h>", link = "z@.1#"),
                @Platform(value = "windows", link = "zlib#")
        },
        target = "org.bytedeco.zlib",
        global = "org.bytedeco.zlib.global.zlib"
)
public class zlib implements InfoMapper {
    static { Loader.checkVersion("org.bytedeco", "zlib"); }

    public void map(InfoMap infoMap) {
        infoMap.put(new Info("ZEXTERN", "ZEXPORT", "z_const", "zlib_version").cppTypes().annotations())
                .put(new Info("FAR").cppText("#define FAR"))
                .put(new Info("OF").cppText("#define OF(args) args"))
                .put(new Info("Z_ARG").cppText("#define Z_ARG(args) args"))
                .put(new Info("Byte", "Bytef", "charf").cast().valueTypes("byte").pointerTypes("BytePointer"))
                .put(new Info("uInt", "uIntf").cast().valueTypes("int").pointerTypes("IntPointer"))
                .put(new Info("uLong", "uLongf", "z_crc_t", "z_off_t", "z_size_t").cast().valueTypes("long").pointerTypes("CLongPointer"))
                .put(new Info("z_off64_t").cast().valueTypes("long").pointerTypes("LongPointer"))
                .put(new Info("voidp", "voidpc", "voidpf").valueTypes("Pointer"))
                .put(new Info("gzFile_s").pointerTypes("gzFile"))
                .put(new Info("gzFile").valueTypes("gzFile"))
                .put(new Info("Z_LARGE64", "!defined(ZLIB_INTERNAL) && defined(Z_WANT64)").define(false))
                .put(new Info("inflateGetDictionary", "gzopen_w", "gzvprintf").skip());
    }
}
````

When running the command "mvn clean install --projects ,.zlib", it is able to parse zconf.h and zlib.h to start generating java files. It then throws an error when attempting to compile int.java. 
See Compilation Error attached. 
![compilation_error_javacpp_presets](https://user-images.githubusercontent.com/31327962/94721970-7822c400-030b-11eb-8ff3-e5a4f0c2a63e.PNG)

The generated int.java below:

```
package org.bytedeco.zlib;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static org.bytedeco.zlib.global.zlib.*;

@Properties(inherit = org.bytedeco.zlib.presets.zlib.class)
public class int extends FunctionPointer {
    static { Loader.load(); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public    int(Pointer p) { super(p); }
    protected int() { allocate(); }
    private native void allocate();
    public native Pointer call(Pointer opaque, @Cast("uInt") int items, @Cast("uInt") int size);
}
```

Has anyone ran into this issue following the tutorial or have any suggestions?

Thank you.

**Comment by saudet** [comment]
It works perfectly fine for me. I've created a branch here with the submodule:
```java
$ git clone https://github.com/bytedeco/javacpp-presets
$ cd javacpp-presets
$ git checkout zlib
$ mvn clean install --projects .,zlib
...
[INFO] --- maven-install-plugin:2.5.2:install (default-install) @ zlib ---
[INFO] Installing /tmp/javacpp-presets/zlib/target/zlib.jar to /home/saudet/.m2/repository/org/bytedeco/zlib/1.2.11-1.5.5-SNAPSHOT/zlib-1.2.11-1.5.5-SNAPSHOT.jar
[INFO] Installing /tmp/javacpp-presets/zlib/pom.xml to /home/saudet/.m2/repository/org/bytedeco/zlib/1.2.11-1.5.5-SNAPSHOT/zlib-1.2.11-1.5.5-SNAPSHOT.pom
[INFO] Installing /tmp/javacpp-presets/zlib/target/zlib-linux-x86_64.jar to /home/saudet/.m2/repository/org/bytedeco/zlib/1.2.11-1.5.5-SNAPSHOT/zlib-1.2.11-1.5.5-SNAPSHOT-linux-x86_64.jar
[INFO] Installing /tmp/javacpp-presets/zlib/target/zlib-sources.jar to /home/saudet/.m2/repository/org/bytedeco/zlib/1.2.11-1.5.5-SNAPSHOT/zlib-1.2.11-1.5.5-SNAPSHOT-sources.jar
[INFO] Installing /tmp/javacpp-presets/zlib/target/zlib-javadoc.jar to /home/saudet/.m2/repository/org/bytedeco/zlib/1.2.11-1.5.5-SNAPSHOT/zlib-1.2.11-1.5.5-SNAPSHOT-javadoc.jar
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] JavaCPP Presets 1.5.5-SNAPSHOT ..................... SUCCESS [  1.206 s]
[INFO] JavaCPP Presets for zlib 1.2.11-1.5.5-SNAPSHOT ..... SUCCESS [ 25.562 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 28.360 s
[INFO] Finished at: 2020-10-01T09:26:45+09:00
[INFO] ------------------------------------------------------------------------
```
What do you get?

**Comment by codywh29** [comment]
Thank you so much for the reply.

I was able to get to to compile successfully. I attempted to build from scratch following steps in the create-new-preset but I haven't identified where I went wrong.
I'll look into, post a comment and close the issue.

Again, thank you.

**Comment by saudet** [comment]
Ah, I see, you'd like to parse the zconf.h file as well. Let's add that one too then.

**Comment by saudet** [comment]
Hum, I'm not sure what you'd like to map from zconf.h. It's just a bunch of macros we can't use from Java, so we have to skip all that anyway. Could you elaborate on what you're trying to achieve?

**Comment by codywh29** [comment]
I attempting to add zconf.h file because it got rid of an error I was dealing with. I removed it in my recent attempts.
I am trying to understand how to create a new preset from scratch so I can work on creating my own for a larger project.

I'm still working through the differences between the two zlib projects. To clarify, the zlib project directory I built up vs the one provided in your git repo but I'm still getting an error when parsing the zlib.h file. See the image below. 
![image](https://user-images.githubusercontent.com/31327962/94856655-25b5d600-03e5-11eb-992b-0f472a7e95df.png)

**Comment by codywh29** [comment]
I've gotten a little further but I'm not exactly sure what is happening.

The global zlib.java files that are being generated by javacpp from zlib.h are identical but it looks like there's some difference/issue with InfoMap trying to create unnecessary java files? Note: the zlib.java files used for instantiating the InfoMapper are identical. See two directories below. 
This first one is generated from checking out the zlib branch and following your steps:
![image](https://user-images.githubusercontent.com/31327962/94863935-112b0b00-03f0-11eb-9fb5-df7c9dd0d78f.png)

This second one is cloning both the javacpp and javacpp-presets without checking out the zlib branch. Opting instead to "create a new zlib preset" from scratch. This was done following steps provided in the Create New Preset tutorial.
![image](https://user-images.githubusercontent.com/31327962/94864124-62d39580-03f0-11eb-89e7-779825ecd9ae.png)

It seems like it could be incorrectly reading zconf.h? The two functions that are different are int.java and IntPointer.java.

**Comment by codywh29** [comment]
I figured out the issue. There were some generated files from trying to parse through zconf.h that didn't properly generate and they were never cleaned out of the generated folder.

Were you able to build the maven project while including zconf.h? If I try to run the parser while including the zconf it produces obviously incorrect output files. int.java and IntPointer.java

**Comment by saudet** [comment]
No, it doesn't work with zconf.h, not without more Info to ignore all those
macros.
