### ISSUE TITLE
[Question] about while including dependency in maven Repository for javacpp

### ISSUE THREAD

**Issue by vijay180396** [bytedeco/javacpp-presets#957]
when including dependency in pom.xml
<dependencies>
        <dependency>
            <groupId>org.bytedeco</groupId>
            <artifactId>opencv-platform</artifactId>
            <version>4.1.0-1.5.1</version>
        </dependency>

        
        <dependency>
            <groupId>org.bytedeco</groupId>
            <artifactId>opencv</artifactId>
            <version>4.1.0-1.5.1</version>
            <classifier>linux-x86_64-gpu</classifier>
        </dependency>

        
        <dependency>
            <groupId>org.bytedeco</groupId>
            <artifactId>cuda-platform</artifactId>
            <version>10.1-7.6-1.5.1</version>
            <classifier>linux-x86_64-redist</classifier>
        </dependency>

**the above dependency working with GPUMAT HAD NO ISSUE**

but,when i try  for latest version of 4.4.0-1.5.4

<dependency>
            <groupId>org.bytedeco</groupId>
            <artifactId>opencv-platform</artifactId>
            <version>4.4.0-1.5.4</version>
        </dependency>

        ;
        <dependency>
            <groupId>org.bytedeco</groupId>
            <artifactId>opencv-platform-gpu</artifactId>
            <version>4.4.0-1.5.4</version>
        </dependency>

it gives these error
Exception in thread "main" java.lang.RuntimeException: OpenCV(4.4.0) /home/travis/build/javacpp-presets/opencv/cppbuild/linux-x86_64-gpu/opencv-4.4.0/modules/core/src/cuda/gpu_mat.cu:116: error: (-217:Gpu API call) CUDA driver version is insufficient for CUDA runtime version in function 'allocate'

	at org.bytedeco.opencv.opencv_core.GpuMat.upload(Native Method)
	at Testjar.main(Testjar.java:7)

please tell how to add latest version of javacpp-preset

**Comment by saudet** [comment]
You'll need to upgrade to CUDA 11.

**Comment by vijay180396** [comment]
i add cuda dependency version 11.0-8.0-1.5.4


 <dependency>
           <groupId>org.bytedeco</groupId>
           <artifactId>opencv-platform</artifactId>
           <version>4.4.0-1.5.4</version>
       </dependency>

       <dependency>
           <groupId>org.bytedeco</groupId>
           <artifactId>opencv-platform-gpu</artifactId>
           <version>4.4.0-1.5.4</version>
       </dependency>

       <dependency>
           <groupId>org.bytedeco</groupId>
           <artifactId>opencv</artifactId>
           <version>4.4.0-1.5.4</version>
       </dependency>

<dependency>
           <groupId>org.bytedeco</groupId>
           <artifactId>cuda</artifactId>
           <version>11.0-8.0-1.5.4</version>
       </dependency>
i am getting same error.
Exception in thread "main" java.lang.RuntimeException: OpenCV(4.4.0) C:/projects/javacpp-presets/opencv/cppbuild/windows-x86_64-gpu/opencv-4.4.0/modules/core/src/cuda/gpu_mat.cu:116: error: (-217:Gpu API call) CUDA driver version is insufficient for CUDA runtime version in function '<unnamed>::DefaultAllocator::allocate'

	at org.bytedeco.opencv.opencv_core.GpuMat.upload(Native Method)
	at ExampleImageStitching.main(ExampleImageStitching.java:76)

what i am doing wrong?

**Comment by saudet** [comment]
That's fine for CUDA's runtime, but you will need to update your video driver.
That requires admin permission so we can't do that with Maven.

**Comment by vijay180396** [comment]
ok then,i need to download cuda 11 toolkit.
and i also need to set environment path right.

**Comment by saudet** [comment]
No, just the video driver: https://www.nvidia.com/Download/

**Comment by vijay180396** [comment]
thank you!

**Comment by vijay180396** [comment]
I have updated my drive.
My driver => GeForce GTX 1050 Ti.Whether it capable for 10.2 or 11.0 cuda toolkit.

**Comment by vijay180396** [comment]
after update my driver.
it works! thanks.
