### ISSUE TITLE
Include Fast Line Detector

### ISSUE THREAD

**Issue by calvertdw** [bytedeco/javacpp-presets#958]
A fast line detector implementation is available in opencv_contrib -> opencv2/ximgproc/fast_line_detector.hpp

This issue is a feature request to include that.

**Comment by saudet** [comment]
Done in commit https://github.com/bytedeco/javacpp-presets/commit/f69b146172e3ac33017b41f0261b6d910e6cd969! Please give it a try with the snapshots: http://bytedeco.org/builds/

**Comment by calvertdw** [comment]
That was fast. Thank you! We'll give it a shot.

**Comment by Daniel-Alievsky** [comment]
Will it be probably available in the next stable version 1.5.5?

**Comment by supergrecko** [comment]
> Will it be probably available in the next stable version 1.5.5?

Yeah, but you can start using it today through the snapshot builds Samuel linked above

**Comment by saudet** [comment]
Version 1.5.5 has been released with all those features included! Enjoy and thanks for reporting
