### ISSUE TITLE
how to add ffmpeg thrid libraries 

### ISSUE THREAD

**Issue by clickear** [bytedeco/javacpp-presets#960]
i want to build glew and glfw to ffmpeg-platform, so i build it from source on mac;

1.  i build the source to $INSTALL_PATH/lib

2, i add  --extra-libs="-lstdc++ -ldl -lz -lm glfw GLEW " to build

3.1 `bash cppbuild.sh install ffmpeg -extension=-gltransition`

3.2 `mvn install -Djavacpp.platform=macosx-x86_64 -Djavacpp.platform.extension="-gltransition" -Djavacpp.cppbuild.skip=true --projects ffmpeg ` 

4 i use it, found error 
java.lang.UnsatisfiedLinkError: no jniavutil in java.library.path
macosx-x86_64-gltransition/libjniavutil.dylib, 1): Library not loaded: /usr/local/lib/libavutil.56.dylib
  Reason: image not found
4.1 
on the path 

> .javacpp/cache/ffmpeg-4.3.1-1.5.5-SNAPSHOT-macosx-x86_64-gltransition.jar/org/bytedeco/ffmpeg/macosx-x86_64-gltransition

,
`otool -L libjniavutil.dylib`
libjniavutil.dylib:
	libjniavutil.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/local/lib/libavutil.56.dylib (compatibility version 56.0.0, current version 56.58.100)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 400.9.4)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.250.1)

i dont know why it link to /usr/local/lib/libavutil.56.dylib  instead of \@rpath/libavutil.56.dylib

**Comment by saudet** [comment]
You'll need to remove `-Djavacpp.cppbuild.skip=true`.

**Comment by clickear** [comment]
> You'll need to remove `-Djavacpp.cppbuild.skip=true`.

this is my first step. **bash cppbuild.sh install ffmpeg -extension=-gltransition**

i found it maybe a error on add 
`@Platform(value = "mac", extension = {"-gpl","-gltransition"},preload = {"glfw","GLEW"}, link= {"glfw","GLEW"})` to a` org.bytedeco.ffmpeg.presets.avutil.class`
when javacpp found a libraries for preload, it first found in /usr/local/lib. i dont know why it not found in cppbuild path.

**Comment by saudet** [comment]
If you set the linkpath to "/usr/local/lib", it will look there, yes, that's normal.

**Comment by clickear** [comment]
> If you set the linkpath to "/usr/local/lib", it will look there, yes, that's normal.

but i not set the linkpath to /usr/local/lib. java defualt linkpath is `/usr/local/lib` ?

**Comment by saudet** [comment]
No, but it's being set somehow because it successfully finds your version of GLEW there, right? How did you manage that?

**Comment by saudet** [comment]
Make sure to set the "org.bytedeco.javacpp.logger.debug" system property to "true" and you'll get information about what gets loaded exactly and how displayed on the console. It's probably failing to load your version of `libavutil.56.dylib` for some reason.
