### ISSUE TITLE
Warning: Version of org.bytedeco:openblas could not be found.seems to be a very serious warning how to resolve.

### ISSUE THREAD

**Issue by xwaeaewcrhomesysplug** [bytedeco/javacpp-presets#972]
It will make the cblas totally not working if I am not wrong.

eg code>

```
import static org.bytedeco.openblas.global.openblas.*;

public class Test {

    /* Main program */
    public static void main(String[] args) {
        blas_set_num_threads(8);
        System.out.println("vendor = " + blas_get_vendor() + ", num_threads = " + blas_get_num_threads());
        /* Locals */
        double[] A = {1,  1,  1,  2,  3,  4,  3,  5,  2, 4};
        double[] B = {-10, -3, 12, 14, 14, 12, 16, 16, 18, 16};
		cblas_ddot(10,new org.bytedeco.javacpp.DoublePointer(A),1,new org.bytedeco.javacpp.DoublePointer(B),1);
		for(double obj:B){System.out.println(obj);}
    }
}
```

console out>
Warning: Version of org.bytedeco:openblas could not be found.
vendor = 2, num_threads = 8
-10.0
-3.0
12.0
14.0
14.0
12.0
16.0
16.0
18.0
16.0

Did the B changed?

But here is the catch I tested the array argument input in another openblas func>
```
import static org.bytedeco.openblas.global.openblas.*;

public class Test {

    /* Main program */
    public static void main(String[] args) {
        blas_set_num_threads(8);
        System.out.println("vendor = " + blas_get_vendor() + ", num_threads = " + blas_get_num_threads());
        /* Locals */
        double[] A = {1,  1,  1,  2,  3,  4,  3,  5,  2, 4};
        double[] B = {-10, -3, 12, 14, 14, 12, 16, 16, 18, 16};
        cblas_daxpy(10,1f,A,1,B,1);
		for(double obj:B){System.out.println(obj);}
    }
}
```

Console out>
Warning: Version of org.bytedeco:openblas could not be found.
vendor = 2, num_threads = 8
-9.0
-2.0
13.0
16.0
17.0
16.0
19.0
21.0
20.0
20.0

Thus I conclude that array input is supported.but..

Another script removed boilerplate,show main point>
```
double[] A = {1,  1,  1,  2,  3,  4,  3,  5,  2, 4};
        double[] B = {-10, -3, 12, 14, 14, 12, 16, 16, 18, 16};
		cblas_ddot(10,A,1,B,1);
		for(double obj:B){System.out.println(obj);}

```
Should work right?but...
Console out>
Warning: Version of org.bytedeco:openblas could not be found.
vendor = 2, num_threads = 8
-10.0
-3.0
12.0
14.0
14.0
12.0
16.0
16.0
18.0
16.0

Now my brain is blown.Someone has any insights on this?
Does the Openblas warning directly effects the behaviour?
Why the xxpointer class as argument has no effect?

BTW,i did test all A output it is the same,and as the official Blas docs said,Y=aX+Y.
They take it literally change Y.and as shown one of them did work.

**Comment by saudet** [comment]
If you're sure that you have the compatible versions installed, you can ignore the warning. Which versions are you trying to use?

**Comment by xwaeaewcrhomesysplug** [comment]
for javacpp>
javacpp-1.5.4
javacpp-1.5.4 windows86_64
These should be right
openblas-0.3.10-1.5.4
openblas-0.3.10-1.5.4-windows-x86_64
These should also be right,no need intel mkl,just the openblas to work now as baseline.

**Comment by saudet** [comment]
`new DoublePointer(double[])` copies the content of the array. It's not possible to pin the memory of Java arrays, so for output data, we need to copy back from them, for example, by using `DoublePointer.get()` after the call.

**Comment by xwaeaewcrhomesysplug** [comment]
sadly it does not seems to work.

 public static void main(String[] args) {
        blas_set_num_threads(8);
        System.out.println("vendor = " + blas_get_vendor() + ", num_threads = " + blas_get_num_threads());/* Locals */
        double[] A = {1,  1,  1,  2,  3,  4,  3,  5,  2, 4};
        double[] B = {-10, -3, 12, 14, 14, 12, 16, 16, 18, 16};
		org.bytedeco.javacpp.DoublePointer obj=new org.bytedeco.javacpp.DoublePointer(B);
		cblas_ddot(1,new org.bytedeco.javacpp.DoublePointer(A),1,obj,1);
		obj.get(B);
		for(double temp:B){System.out.println(temp);}
    }
usage log>
Warning: Version of org.bytedeco:openblas could not be found.
vendor = 2, num_threads = 8
-10.0
-3.0
12.0
14.0
14.0
12.0
16.0
16.0
18.0
16.0

**Comment by saudet** [comment]
That's an input array, it's not supposed to change.
