### ISSUE TITLE
macos 10.15.4 can not build

### ISSUE THREAD

**Issue by jiatongwu** [bytedeco/javacpp-presets#976]
[INFO] Installing /Users/macos/bitbucket/rtsp/javacpp-presets/pom.xml to /Users/macos/.m2/repository/org/bytedeco/javacpp-presets/1.5.4/javacpp-presets-1.5.4.pom
[INFO] 
[INFO] -----------------------< org.bytedeco:openblas >------------------------
[INFO] Building JavaCPP Presets for OpenBLAS 0.3.10-1.5.4                [2/43]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ openblas ---
[INFO] 
[INFO] --- javacpp:1.5.4:build (javacpp-cppbuild-clean) @ openblas ---
[INFO] Detected platform "macosx-x86_64"
[INFO] Building platform "macosx-x86_64"
[INFO] bash /Users/macos/bitbucket/rtsp/javacpp-presets/openblas/../cppbuild.sh clean openblas 
Detected platform "macosx-x86_64"
Building platform "macosx-x86_64"
Cleaning "openblas"
[INFO] 
[INFO] --- javacpp:1.5.4:build (javacpp-validate) @ openblas ---
[INFO] Detected platform "macosx-x86_64"
[INFO] Building platform "macosx-x86_64"
[INFO] 
[INFO] --- javacpp:1.5.4:build (javacpp-cppbuild-install) @ openblas ---
[INFO] Detected platform "macosx-x86_64"
[INFO] Building platform "macosx-x86_64"
[INFO] bash /Users/macos/bitbucket/rtsp/javacpp-presets/openblas/../cppbuild.sh install openblas -platform=macosx-x86_64 -extension= 
Detected platform "macosx-x86_64"
Building platform "macosx-x86_64"
Installing "openblas"
~/bitbucket/rtsp/javacpp-presets/openblas/cppbuild ~/bitbucket/rtsp/javacpp-presets
Decompressing archives...
patching file exports/Makefile
Hunk #1 succeeded at 120 (offset 4 lines).
patching file Makefile.install
patching file exports/Makefile
Hunk #1 succeeded at 120 (offset 4 lines).
patching file Makefile.install
ls: /usr/local/bin/gcc-?: No such file or directory
ls: /usr/local/bin/gfortran-?: No such file or directory
C Compiler () is something wrong.
1 at ./c_check line 30.
make: *** [config.h] Error 2
Makefile.system:222: Makefile.conf: No such file or directory
Makefile.system:1187: Makefile.: No such file or directory
make: *** No rule to make target `Makefile.'.  Stop.

**Comment by saudet** [comment]
https://github.com/bytedeco/javacpp-presets/wiki/Build-Environments#mac-os-x-x86_64
