### ISSUE TITLE
Tesseract crashes after many sequential executions

### ISSUE THREAD

**Issue by patrick-frank-bsi** [bytedeco/javacpp-presets#977]
Tesseract crashes with with NPE in api.AnalyseLayout() when I run it sequentially on many images.

Currently at application startup, I instantiate one TessBaseApi with Init() and at the end of the application lifecycle I destroy that instance with End().

Is that the intended usage or should I create a new instance for each image to be ocr'd?

And if I need to create a new instance for each image, how can I do that efficiently? Can I do that with a call to End() and a subsequent call to Init()?

**Comment by saudet** [comment]
You can reuse it, that's fine, but it's not thread-safe, so if you are using threads, you won't be able to reuse the same instance.

**Comment by saudet** [comment]
Also make sure to read the documentation and be mindful of its warnings:
http://bytedeco.org/javacpp-presets/tesseract/apidocs/org/bytedeco/tesseract/TessBaseAPI.html#AnalyseLayout--

**Comment by saudet** [comment]
Duplicate of #996
