### ISSUE TITLE
How can I remove libvpx? I don't need it. And I can't download it.

### ISSUE THREAD

**Issue by szitguy** [bytedeco/javacpp-presets#98]
Downloading https://chromium.googlesource.com/webm/libvpx/+archive/v1.4.0.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:01:15 --:--:--     0curl: (7) Failed to connect to 2404:6800:4008:c01::52: No route to host

**Comment by saudet** [comment]
Just modify the `cppbuild.sh` file and remove ares related to libvpx.

**Comment by szitguy** [comment]
OK, it works, thank you
