### ISSUE TITLE
It seems javaCPP ONNX is not supported in windows

### ISSUE THREAD

**Issue by oneengineer** [bytedeco/javacpp-presets#983]
the maven library:
<dependency>
    <groupId>org.bytedeco</groupId>
    <artifactId>onnx-platform</artifactId>
    <version>1.7.0-1.5.4</version>
</dependency>

I got error when trying to run example code.

`Exception in thread "main" java.lang.UnsatisfiedLinkError: Platform "windows-x86_64" not supported by class org.bytedeco.onnx.MessageLite`

**Comment by saudet** [comment]
I've added support for Windows in commit https://github.com/bytedeco/javacpp-presets/commit/d2f456545574cc2e44d7bba6f4e19f08e49667ab.
Please give it a try with the snapshots: http://bytedeco.org/builds/
Thanks for reporting!

**Comment by oneengineer** [comment]
Cool, works like a charm.

Close the bug.
