### ISSUE TITLE
What is the best correct way to use OpenCV in Java with GPU support?

### ISSUE THREAD

**Issue by Daniel-Alievsky** [bytedeco/javacpp-presets#984]
Hello! I need to use the latest stable version of JavaCPP + OpenCV platform in Java with full support of GPU functions (like Gaussian blur etc.). I use the following Maven dependency:
```
    <properties>
        <javacpp.version>1.5.4</javacpp.version>
        <opencv.version>4.4.0-1.5.4</opencv.version>
    </properties>
    <dependencies>
        <dependency>
            <groupId>org.bytedeco</groupId>
            <artifactId>javacpp-platform</artifactId>
            <version>${javacpp.version}</version>
        </dependency>
        <dependency>
            <groupId>org.bytedeco</groupId>
            <artifactId>opencv-platform</artifactId>
            <version>${opencv.version}</version>
        </dependency>
    <dependencies>
```
My 1st question: is it correct?

It seems that yes, and it automatically includes GPU support. But on the page http://bytedeco.org/download/ it is written:
```
 <!-- Additional dependencies required to use CUDA, cuDNN, NCCL, and TensorRT -->
    <dependency>
        <groupId>org.bytedeco</groupId>
        <artifactId>opencv-platform-gpu</artifactId>
        <version>${opencv.version}</version>
    </dependency>
```
My 2nd question: is it necessary to add the latter dependency manually, or it is absolutely enough to use dependency `<artifactId>opencv-platform</artifactId>` - it always includes also opencv-platform-gpu ?

**Comment by saudet** [comment]
All builds contain support for OpenCL, so GPUs can get used that way, but it's not going to work for code written in CUDA.

**Comment by Daniel-Alievsky** [comment]
Thank you. So, maybe it makes sense to remove "opencv-platform-gpu" from the section
`<!-- Additional dependencies required to use CUDA, cuDNN, NCCL, and TensorRT -->` 
in http://bytedeco.org/download/ page?
As I understand, it have no additional effect when the main "opencv-platform" dependency is specified.

**Comment by saudet** [comment]
It won't have any effect if you're not using any of the CUDA modules, no.

**Comment by Daniel-Alievsky** [comment]
So, why not to remove it from your documentation page http://bytedeco.org/download/ ? I've read that page and thought that it is necessary do add dependency from "opencv-platform-gpu", but it is not necessary.

**Comment by saudet** [comment]
If you're only using functions that use OpenCL, that's correct. If you're using functions that use CUDA, you'll need the -gpu ones.

**Comment by saudet** [comment]
In general, functions that accept GpuMat require the `-gpu` binaries compiled for CUDA, while the ones dealing with `UMat` do not.

**Comment by Daniel-Alievsky** [comment]
Thank you very much.
