### ISSUE TITLE
How to convert Windows C++ .dll to Java .jar?

### ISSUE THREAD

**Issue by Microkitty** [bytedeco/javacpp-presets#988]
I have a C++ library with .h and .dll on Windows platform, and I want to use this library with Java.  
But I do not want to use JNA or to write JNI, how can I use JavaCPP to do this work?  
I can only find cppbuild.sh, there is no .bat to run for Windows!  
I have use JavaCPP to convert .so OK on Linux, how can I do it on Windows?

**Comment by saudet** [comment]
Please read these pages and let me know if you have any questions after that:
https://github.com/bytedeco/javacpp-presets/wiki/Build-Environments
https://github.com/bytedeco/javacpp-presets/wiki/Create-New-Presets
