### ISSUE TITLE
jniavcodec.cpp file error, can't find #include <exception>

### ISSUE THREAD

**Issue by szitguy** [bytedeco/javacpp-presets#99]
javacpp-presets/ffmpeg/target/classes/org/bytedeco/javacpp/jniavcodec.cpp:46:21: fatal error: exception: No such file or directory  #include exception

**Comment by saudet** [comment]
Like I said, please install a C++ compiler. And please stop opening a new issue for every single question!! Please post all your questions related to the same topic in the same issue. Thank you.

**Comment by szitguy** [comment]
OK, thank you
