### ISSUE TITLE
How to retrieve value from a org.bytedeco.arrow.Scalar?

### ISSUE THREAD

**Issue by xuchen-plus** [bytedeco/javacpp-presets#998]
After calling an arrow::compute::ScalarAggregationFunction, it returns a Datum object which contains a Scalar object. However, there's no value() method in the generated java wrapper to retrieve the underlying value, e.g. long/int, etc.

My code:
```java
ArrowBuf buf; // this is an int64 ArrowBuf java object initialized in java

// Below are all javacpp calls

ArrowBuffer buffer = new ArrowBuffer(buf.nioBuffer(), capacity);
ExecContext context = new ExecContext();
DataType type = int64();
PrimitiveArray array = new PrimitiveArray(type, capacity, buffer);
Function func = context.func_registry().GetFunction("sum").ValueOrDie();
DatumVector vector = new DatumVector(new Datum(array));
Scalar s = func.Execute(vector, null, context).ValueOrDie().scalar();
// How can I retrieve the `long` value from the Scalar result object here?  Haven't found such methods from either Scalar or Int64Scalar classes.
```

Please help advice. Thanks very much.

**Comment by saudet** [comment]
`get()` should work for most use cases... Let me know if that's not enough though.

**Comment by saudet** [comment]
Ah, sorry about that, I was confusing this with OpenCV. So, it looks like we need to use the internal API to access the data. Something like this should work:
```java
long value = new LongPointer(new PrimitiveScalarBase(s).data()).get();
```

**Comment by xuchen-plus** [comment]
> Ah, sorry about that, I was confusing this with OpenCV. So, it looks like we need to use the internal API to access the data. Something like this should work:
> 
> ```java
> long value = new LongPointer(new PrimitiveScalarBase(s).data()).get();
> ```

Thanks, this works. And thank you for creating this great project!
